import {z} from 'zod';
import {uuid} from '@/modules/crm/domain';

export const documentStatuses={draft:'Rascunho',sent:'Enviado',accepted:'Aceito',refused:'Recusado'} as const;
export const documentTypes={budget:'Orçamento',contract:'Contrato',amendment:'Aditivo',receipt:'Comprovante',invoice:'Nota fiscal',client_document:'Documento do cliente',other:'Outro'} as const;
export type DocumentStatus=keyof typeof documentStatuses;
export const documentStatusSchema=z.enum(Object.keys(documentStatuses) as [DocumentStatus,...DocumentStatus[]]);
const text=(max:number)=>z.string().trim().max(max).default('');
const optionalUuid=z.union([uuid,z.literal(''),z.null()]).optional().transform(value=>value||null);
export const documentCreateSchema=z.object({customer_id:uuid,opportunity_id:optionalUuid,contract_id:optionalUuid,document_type:z.enum(Object.keys(documentTypes) as [keyof typeof documentTypes,...Array<keyof typeof documentTypes>]).default('budget'),name:z.string().trim().min(2).max(180),budget_value:z.coerce.number().min(0).max(99999999999.99),valid_until:z.iso.date(),notes:text(4000)}).strict().refine(value=>value.opportunity_id||value.contract_id,{message:'Vincule o documento a uma oportunidade ou contrato.'});
export const documentUpdateSchema=z.object({name:z.string().trim().min(2).max(180),document_type:z.enum(Object.keys(documentTypes) as [keyof typeof documentTypes,...Array<keyof typeof documentTypes>]).default('budget'),budget_value:z.coerce.number().min(0).max(99999999999.99),valid_until:z.iso.date(),notes:text(4000),version:z.coerce.number().int().positive()}).strict();
export const documentListSchema=z.object({customer_id:uuid.optional(),opportunity_id:uuid.optional(),contract_id:uuid.optional()}).strict().superRefine((value,context)=>{if(Number(!!value.customer_id)+Number(!!value.opportunity_id)+Number(!!value.contract_id)!==1)context.addIssue({code:'custom',message:'Informe um cliente, uma oportunidade ou um contrato.'});});
export const documentSignatureSchema=z.object({signature_status:z.enum(['unsigned','signed']),signed_at:z.union([z.iso.datetime({offset:true}),z.literal(''),z.null()]).optional(),signed_by:z.string().trim().max(180).default(''),signature_notes:text(2000),version:z.coerce.number().int().positive()}).strict().superRefine((value,ctx)=>{if(value.signature_status==='signed'&&(!value.signed_at||!value.signed_by))ctx.addIssue({code:'custom',message:'Informe quem assinou e quando.'});});
export const documentEmailSchema=z.object({recipient:z.string().trim().toLowerCase().email('Informe um e-mail válido.').max(254),subject:z.string().trim().min(1,'Informe o assunto.').max(180).refine(value=>!/[\r\n]/.test(value),'Assunto inválido.'),message:z.string().trim().min(1,'Informe a mensagem.').max(10000),client_request_id:uuid}).strict();
export type CrmDocument={id:string;customer_id:string;opportunity_id:string|null;contract_id:string|null;document_type:keyof typeof documentTypes;signature_status:'unsigned'|'signed';signed_at:string|null;signed_by:string;signature_notes:string;customer_name:string;customer_email:string;opportunity_title:string|null;contract_number:string|null;name:string;budget_value:number;valid_until:string;notes:string;status:DocumentStatus;original_filename:string;file_size:number;content_sha256:string;version:number;created_by:string;created_by_name:string;created_at:string;updated_at:string};
export type DocumentHistory={id:string;action:'created'|'updated'|'status_changed'|'signature_changed';snapshot:CrmDocument;actor_name:string;created_at:string};
export type DocumentEmail={id:string;document_id:string;customer_id:string;opportunity_id:string|null;recipient:string;subject:string;message:string;document_name:string;original_filename:string;provider_message_id:string;actor_name:string;status:'pending'|'sent'|'failed';safe_error:string;sent_at:string|null;created_at:string};
