import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {database,transaction} from '@/server/db';
import {AccessError,type Actor} from '@/modules/auth/policy';
import {getRecord,crmAccess} from '@/modules/crm/repository';
import {getOpportunity} from '@/modules/commercial/repository';
import {uuid} from '@/modules/crm/domain';
import {documentCreateSchema,documentListSchema,documentSignatureSchema,documentStatusSchema,documentUpdateSchema,type CrmDocument,type DocumentStatus} from './domain';
import {documentEmailSchema,type DocumentEmail} from './domain';
import {loadPdf,removePdf,storePdf,validatePdf} from './storage';
import type {DocumentMailProvider} from '@/integrations/mail';
import {appendContractHistory,getContract} from '@/modules/contracts/repository';
type Db=Pick<PoolClient,'query'>;
const select=`d.*,c.name customer_name,c.email customer_email,o.title opportunity_title,k.contract_number,u.name created_by_name,to_char(d.valid_until,'YYYY-MM-DD') valid_until`;
const joins=`FROM crm_documents d JOIN crm_records c ON c.organization_id=d.organization_id AND c.id=d.customer_id LEFT JOIN crm_opportunities o ON o.organization_id=d.organization_id AND o.id=d.opportunity_id LEFT JOIN contracts k ON k.organization_id=d.organization_id AND k.id=d.contract_id JOIN users u ON u.id=d.created_by`;
const normalize=(row:Record<string,unknown>):CrmDocument=>{const publicRow={...row};delete publicRow.storage_key;delete publicRow.customer_kind;return JSON.parse(JSON.stringify({...publicRow,budget_value:Number(row.budget_value),file_size:Number(row.file_size)}));};
async function parents(actor:Actor,customerId:string,opportunityId:string|null,contractId:string|null,db:Db){const customer=await getRecord(actor,customerId,db);if(customer.kind!=='customer')throw new AccessError(400,'O documento deve pertencer a um cliente.');const opportunity=opportunityId?await getOpportunity(actor,opportunityId,db):null;if(opportunity&&opportunity.customer_id!==customer.id)throw new AccessError(400,'A oportunidade deve estar vinculada ao cliente informado.');const contract=contractId?await getContract(actor,contractId,db):null;if(contract&&contract.client_id!==customer.id)throw new AccessError(400,'O contrato deve estar vinculado ao cliente informado.');if(contract&&opportunity&&contract.opportunity_id&&contract.opportunity_id!==opportunity.id)throw new AccessError(400,'O contrato não pertence à oportunidade informada.');return {customer,opportunity,contract};}
async function row(actor:Actor,id:string,db:Db=database(),lock=false){crmAccess(actor);uuid.parse(id);const result=await db.query(`SELECT ${select} ${joins} WHERE d.organization_id=$1 AND d.id=$2${lock?' FOR UPDATE OF d':''}`,[actor.organizationId,id]);if(!result.rows[0])throw new AccessError(404,'Documento não encontrado.');const document=normalize(result.rows[0]);await parents(actor,document.customer_id,document.opportunity_id,document.contract_id,db);return document;}
async function history(db:Db,actor:Actor,document:CrmDocument,action:'created'|'updated'|'status_changed'|'signature_changed'){await db.query('INSERT INTO crm_document_history(organization_id,document_id,actor_id,action,snapshot) VALUES ($1,$2,$3,$4,$5::jsonb)',[actor.organizationId,document.id,actor.userId,action,JSON.stringify(document)]);await db.query("INSERT INTO crm_activities(organization_id,record_id,actor_id,action,detail) VALUES ($1,$2,$3,'document.'||$4,$5)",[actor.organizationId,document.customer_id,actor.userId,action,document.name]);if(document.opportunity_id)await db.query('UPDATE crm_opportunities SET last_activity_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,document.opportunity_id]);if(document.contract_id)await appendContractHistory(db,actor,document.contract_id,`document_${action}`,document.name);}

export async function listDocuments(actor:Actor,input:unknown){crmAccess(actor);const filter=documentListSchema.parse(input);if(filter.customer_id){const customer=await getRecord(actor,filter.customer_id);if(customer.kind!=='customer')throw new AccessError(400,'Cliente inválido.');}else if(filter.opportunity_id)await getOpportunity(actor,filter.opportunity_id);else await getContract(actor,filter.contract_id!);const column=filter.customer_id?'customer_id':filter.opportunity_id?'opportunity_id':'contract_id',value=filter.customer_id??filter.opportunity_id??filter.contract_id;const result=await database().query(`SELECT ${select} ${joins} WHERE d.organization_id=$1 AND d.${column}=$2 ORDER BY d.created_at DESC,d.id DESC`,[actor.organizationId,value]);return result.rows.map(normalize);}
export async function getDocument(actor:Actor,id:string){const document=await row(actor,id);const [historyResult,emailResult]=await Promise.all([database().query('SELECT h.id,h.action,h.snapshot,u.name actor_name,h.created_at FROM crm_document_history h JOIN users u ON u.id=h.actor_id WHERE h.organization_id=$1 AND h.document_id=$2 ORDER BY h.created_at DESC,h.id DESC',[actor.organizationId,id]),database().query('SELECT e.*,u.name actor_name FROM crm_document_emails e JOIN users u ON u.id=e.actor_id WHERE e.organization_id=$1 AND e.document_id=$2 ORDER BY e.sent_at DESC,e.id DESC',[actor.organizationId,id])]);return {document,history:historyResult.rows,emails:emailResult.rows as DocumentEmail[]};}
export async function createDocument(actor:Actor,input:unknown,file:{name:string;type:string;bytes:Uint8Array}){crmAccess(actor);const data=documentCreateSchema.parse(input);await parents(actor,data.customer_id,data.opportunity_id,data.contract_id,database());const checked=validatePdf(file.name,file.type,file.bytes);const id=randomUUID(),storageKey=`${actor.organizationId}/${id}.pdf`;await storePdf(storageKey,file.bytes);try{return await transaction(async db=>{await parents(actor,data.customer_id,data.opportunity_id,data.contract_id,db);await db.query('INSERT INTO crm_documents(id,organization_id,customer_id,opportunity_id,contract_id,document_type,name,budget_value,valid_until,notes,original_filename,storage_key,file_size,content_sha256,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[id,actor.organizationId,data.customer_id,data.opportunity_id,data.contract_id,data.document_type,data.name,data.budget_value,data.valid_until,data.notes,checked.filename,storageKey,file.bytes.length,checked.sha256,actor.userId]);const document=await row(actor,id,db);await history(db,actor,document,'created');return document;});}catch(error){await removePdf(storageKey);throw error;}}
export async function updateDocument(actor:Actor,id:string,input:unknown){const data=documentUpdateSchema.parse(input);return transaction(async db=>{const before=await row(actor,id,db,true);if(before.version!==data.version)throw new AccessError(409,'Documento atualizado por outra pessoa. Recarregue.');await db.query('UPDATE crm_documents SET name=$3,document_type=$4,budget_value=$5,valid_until=$6,notes=$7,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,data.name,data.document_type,data.budget_value,data.valid_until,data.notes]);const document=await row(actor,id,db);await history(db,actor,document,'updated');return document;});}
export async function setDocumentSignature(actor:Actor,id:string,input:unknown){const data=documentSignatureSchema.parse(input);return transaction(async db=>{const before=await row(actor,id,db,true);if(before.version!==data.version)throw new AccessError(409,'Documento atualizado por outra pessoa. Recarregue.');await db.query("UPDATE crm_documents SET signature_status=$3,signed_at=CASE WHEN $3='signed' THEN $4::timestamptz ELSE NULL END,signed_by=CASE WHEN $3='signed' THEN $5 ELSE '' END,signature_notes=$6,signature_recorded_by=$7,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[actor.organizationId,id,data.signature_status,data.signed_at||null,data.signed_by,data.signature_notes,actor.userId]);const document=await row(actor,id,db);await history(db,actor,document,'signature_changed');return document;});}
export async function setDocumentStatus(actor:Actor,id:string,status:unknown,version:unknown){const next=documentStatusSchema.parse(status),parsedVersion=Number(version);if(!Number.isInteger(parsedVersion)||parsedVersion<1)throw new AccessError(400,'Versão inválida.');return transaction(async db=>{const before=await row(actor,id,db,true);if(before.version!==parsedVersion)throw new AccessError(409,'Documento atualizado por outra pessoa. Recarregue.');if(before.status===next)return before;await db.query('UPDATE crm_documents SET status=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,next]);const document=await row(actor,id,db);await history(db,actor,document,'status_changed');return document;});}
export async function getDocumentFile(actor:Actor,id:string){const document=await row(actor,id);return {document,bytes:await loadPdf((await database().query('SELECT storage_key FROM crm_documents WHERE organization_id=$1 AND id=$2',[actor.organizationId,id])).rows[0].storage_key,document.content_sha256)};}
export async function sendDocumentEmail(actor:Actor,id:string,input:unknown,mail:DocumentMailProvider){const data=documentEmailSchema.parse(input),{document,bytes}=await getDocumentFile(actor,id);let delivery:{messageId:string};try{delivery=await mail.sendDocument({to:data.recipient,subject:data.subject,message:data.message,filename:document.original_filename,content:bytes});}catch{throw new AccessError(502,'Não foi possível enviar o e-mail. Verifique a configuração SMTP e tente novamente.');}return transaction(async db=>{let current=await row(actor,id,db,true);const sent=await db.query(`INSERT INTO crm_document_emails(organization_id,document_id,customer_id,opportunity_id,actor_id,recipient,subject,message,document_name,original_filename,provider_message_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[actor.organizationId,id,current.customer_id,current.opportunity_id,actor.userId,data.recipient,data.subject,data.message,current.name,current.original_filename,delivery.messageId.slice(0,500)]);await db.query("INSERT INTO crm_activities(organization_id,record_id,actor_id,action,detail) VALUES ($1,$2,$3,'document.email_sent',$4)",[actor.organizationId,current.customer_id,actor.userId,`${current.name} enviado para ${data.recipient}`]);if(current.opportunity_id)await db.query('UPDATE crm_opportunities SET last_activity_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,current.opportunity_id]);if(current.contract_id)await appendContractHistory(db,actor,current.contract_id,'document_email_sent',`${current.name} enviado para ${data.recipient}`);if(current.status==='draft'){await db.query("UPDATE crm_documents SET status='sent',version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[actor.organizationId,id]);current=await row(actor,id,db);await history(db,actor,current,'status_changed');}return {document:current,email:{...sent.rows[0],actor_name:actor.name} as DocumentEmail};});}
export type {DocumentStatus};
