import type {PoolClient} from 'pg';
import {database,transaction} from '@/server/db';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {getRecord} from '@/modules/crm/repository';
import {getOpportunity} from '@/modules/commercial/repository';
import {uuid} from '@/modules/crm/domain';
import {calculateContract,contractAlertFiltersSchema,contractFiltersSchema,contractSchema,contractStatusSchema,paymentSchema,paymentUpdateSchema,type Contract,type ContractDetail,type ContractStatus} from './domain';
type Db=Pick<PoolClient,'query'>;
const json=<T>(value:unknown)=>JSON.parse(JSON.stringify(value)) as T;
const permitted=(actor:Actor,permission:string)=>actor.permissions.includes(permission);
function access(actor:Actor){if(!permitted(actor,'contracts.all')&&!permitted(actor,'contracts.own'))throw new AccessError(403,'Seu perfil não tem acesso a contratos.');}
const scope=(actor:Actor,alias='c')=>permitted(actor,'contracts.all')?`${alias}.organization_id=$1`:`${alias}.organization_id=$1 AND ${alias}.responsible_user_id=$2`;
const params=(actor:Actor):unknown[]=>permitted(actor,'contracts.all')?[actor.organizationId]:[actor.organizationId,actor.userId];
const select=`c.*,r.name client_name,r.email client_email,o.title opportunity_title,u.name responsible_name,to_char(c.first_due_date,'YYYY-MM-DD') first_due_date,to_char(c.start_date,'YYYY-MM-DD') start_date,to_char(c.end_date,'YYYY-MM-DD') end_date`;
const joins=`FROM contracts c JOIN crm_records r ON r.organization_id=c.organization_id AND r.id=c.client_id LEFT JOIN crm_opportunities o ON o.organization_id=c.organization_id AND o.id=c.opportunity_id JOIN users u ON u.id=c.responsible_user_id`;
const normalize=(row:Record<string,unknown>):Contract=>json({...row,...Object.fromEntries(['total_value','discount_value','item_discount_value','commercial_discount_value','net_value','down_payment_value','balance_value'].map(key=>[key,Number(row[key])]))});
async function ownerAllowed(actor:Actor,userId:string,db:Db){if(userId!==actor.userId&&!permitted(actor,'contracts.all'))throw new AccessError(403,'Você só pode atribuir contratos a si mesmo.');const found=await db.query("SELECT 1 FROM memberships m JOIN role_permissions rp ON rp.role_code=m.role_code WHERE m.organization_id=$1 AND m.user_id=$2 AND m.active AND rp.permission_code IN ('contracts.all','contracts.own')",[actor.organizationId,userId]);if(!found.rowCount)throw new AccessError(400,'O responsável não possui acesso a contratos.');}
async function parents(actor:Actor,clientId:string,opportunityId:string|null,db:Db){const client=await getRecord(actor,clientId,db);if(client.kind!=='customer'||client.status==='archived')throw new AccessError(400,'Selecione um cliente ativo.');let opportunity=null;if(opportunityId){opportunity=await getOpportunity(actor,opportunityId,db);if(opportunity.customer_id!==clientId)throw new AccessError(400,'A oportunidade não pertence ao cliente informado.');}return {client,opportunity};}
export async function getContract(actor:Actor,id:string,db:Db=database(),lock=false){access(actor);uuid.parse(id);const p=params(actor);p.push(id);const result=await db.query(`SELECT ${select} ${joins} WHERE ${scope(actor)} AND c.id=$${p.length}${lock?' FOR UPDATE OF c':''}`,p);if(!result.rows[0])throw new AccessError(404,'Contrato não encontrado.');return normalize(result.rows[0]);}
async function writeHistory(db:Db,actor:Actor,contract:Contract,action:string,detail:string){await db.query('INSERT INTO contract_history(organization_id,contract_id,actor_id,action,detail,snapshot) VALUES ($1,$2,$3,$4,$5,$6::jsonb)',[actor.organizationId,contract.id,actor.userId,action,detail,JSON.stringify(contract)]);await db.query("INSERT INTO crm_activities(organization_id,record_id,actor_id,action,detail) VALUES ($1,$2,$3,'contract.'||$4,$5)",[actor.organizationId,contract.client_id,actor.userId,action,`${contract.contract_number} · ${detail}`]);if(contract.opportunity_id)await db.query('UPDATE crm_opportunities SET last_activity_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,contract.opportunity_id]);}
function addMonths(date:string,index:number){const [year,month,day]=date.split('-').map(Number);const target=new Date(Date.UTC(year,month-1+index,1));const last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();return `${target.getUTCFullYear()}-${String(target.getUTCMonth()+1).padStart(2,'0')}-${String(Math.min(day,last)).padStart(2,'0')}`;}
async function makeInstallments(db:Db,actor:Actor,contractId:string,data:{down_payment_value:number;balance_value:number;installments_count:number;first_due_date:string|null}){let order=0;if(data.down_payment_value>0){await db.query("INSERT INTO contract_installments(organization_id,contract_id,installment_number,description,due_date,amount,remaining_amount,created_by,updated_by) VALUES ($1,$2,0,'Entrada',(now() AT TIME ZONE 'America/Sao_Paulo')::date,$3,$3,$4,$4)",[actor.organizationId,contractId,data.down_payment_value,actor.userId]);order++;}if(data.balance_value>0&&data.first_due_date){const total=Math.round(data.balance_value*100),base=Math.floor(total/data.installments_count);for(let i=0;i<data.installments_count;i++){const amount=(i===data.installments_count-1?total-base*i:base)/100;await db.query('INSERT INTO contract_installments(organization_id,contract_id,installment_number,description,due_date,amount,remaining_amount,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$6,$7,$7)',[actor.organizationId,contractId,i+1,`Parcela ${i+1}/${data.installments_count}`,addMonths(data.first_due_date,i),amount,actor.userId]);order++;}}return order;}
async function nextNumber(db:Db,actor:Actor){const year=new Date().getUTCFullYear();const result=await db.query('INSERT INTO contract_sequences(organization_id,year,last_value) VALUES ($1,$2,1) ON CONFLICT(organization_id,year) DO UPDATE SET last_value=contract_sequences.last_value+1 RETURNING last_value',[actor.organizationId,year]);return `PECLAT-${year}-${String(result.rows[0].last_value).padStart(6,'0')}`;}
export async function saveContract(actor:Actor,input:unknown,id?:string){requirePermission(actor,id?'contracts.edit':'contracts.create');const data=contractSchema.parse(input);let financial;try{financial=calculateContract(data.items,data.commercial_discount_value,data.down_payment_value);}catch(error){throw new AccessError(400,(error as Error).message);}return transaction(async db=>{
 const before=id?await getContract(actor,id,db,true):null;if(before&&before.version!==data.version)throw new AccessError(409,'Contrato atualizado por outra pessoa. Recarregue.');if(before?.status==='cancelled'||before?.status==='completed')throw new AccessError(409,'Contrato encerrado não pode ser editado.');
 const responsible=data.responsible_user_id??before?.responsible_user_id??actor.userId;await ownerAllowed(actor,responsible,db);const {client}=await parents(actor,data.client_id,data.opportunity_id,db);const payments=before?Number((await db.query('SELECT count(*) FROM contract_payments WHERE organization_id=$1 AND contract_id=$2',[actor.organizationId,id])).rows[0].count):0;if(payments)throw new AccessError(409,'Contrato com pagamentos registrados não permite alterar itens ou plano financeiro.');
 let saved=id;if(before){await db.query(`UPDATE contracts SET client_id=$3,opportunity_id=$4,responsible_user_id=$5,title=$6,total_value=$7,discount_value=$8,item_discount_value=$9,commercial_discount_value=$10,net_value=$11,down_payment_value=$12,balance_value=$13,payment_method=$14,installments_count=$15,first_due_date=$16,start_date=$17,end_date=$18,conditions=$19,notes=$20,is_demo=$21,updated_by=$22,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,data.client_id,data.opportunity_id,responsible,data.title,financial.totalValue,financial.discountValue,financial.itemDiscountValue,financial.commercialDiscountValue,financial.netValue,financial.downPaymentValue,financial.balanceValue,data.payment_method,data.installments_count,data.first_due_date,data.start_date,data.end_date,data.conditions,data.notes,client.is_demo,actor.userId]);await db.query('DELETE FROM contract_installments WHERE organization_id=$1 AND contract_id=$2',[actor.organizationId,id]);await db.query('DELETE FROM contract_items WHERE organization_id=$1 AND contract_id=$2',[actor.organizationId,id]);}
 else{const number=await nextNumber(db,actor);const result=await db.query(`INSERT INTO contracts(organization_id,client_id,opportunity_id,responsible_user_id,contract_number,title,total_value,discount_value,item_discount_value,commercial_discount_value,net_value,down_payment_value,balance_value,payment_method,installments_count,first_due_date,start_date,end_date,conditions,notes,is_demo,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$22) RETURNING id`,[actor.organizationId,data.client_id,data.opportunity_id,responsible,number,data.title,financial.totalValue,financial.discountValue,financial.itemDiscountValue,financial.commercialDiscountValue,financial.netValue,financial.downPaymentValue,financial.balanceValue,data.payment_method,data.installments_count,data.first_due_date,data.start_date,data.end_date,data.conditions,data.notes,client.is_demo,actor.userId]);saved=result.rows[0].id;}
 for(const item of financial.items)await db.query('INSERT INTO contract_items(organization_id,contract_id,description,category,equipment_id,kit_id,quantity,unit_value,discount_value,gross_value,total_value,display_order) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[actor.organizationId,saved,item.description,item.category,item.equipment_id,item.kit_id,item.quantity,item.unit_value,item.discount_value,item.gross_value,item.total_value,item.display_order]);await makeInstallments(db,actor,saved!,{down_payment_value:financial.downPaymentValue,balance_value:financial.balanceValue,installments_count:data.installments_count,first_due_date:data.first_due_date});const contract=await getContract(actor,saved!,db);await writeHistory(db,actor,contract,before?'updated':'created',before?'Dados e plano comercial atualizados.':'Contrato criado.');return contract;
 });}
export async function setContractStatus(actor:Actor,id:string,input:unknown){const data=contractStatusSchema.parse(input);if(data.status==='cancelled')requirePermission(actor,'contracts.cancel');else requirePermission(actor,'contracts.edit');return transaction(async db=>{const before=await getContract(actor,id,db,true);if(before.version!==data.version)throw new AccessError(409,'Contrato atualizado por outra pessoa. Recarregue.');if(before.status===data.status)return before;if(before.status==='cancelled'||before.status==='completed')throw new AccessError(409,'Contrato encerrado não pode mudar de status.');if(data.status==='completed'){const pending=await db.query("SELECT 1 FROM contract_installments WHERE organization_id=$1 AND contract_id=$2 AND remaining_amount>0 AND status!='cancelled' LIMIT 1",[actor.organizationId,id]);if(pending.rowCount)throw new AccessError(409,'Quite todas as parcelas antes de concluir o contrato.');}const signed=['signed','active','completed'].includes(data.status);await db.query("UPDATE contracts SET status=$3,signed_at=CASE WHEN $4 THEN COALESCE(signed_at,now()) ELSE signed_at END,updated_by=$5,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[actor.organizationId,id,data.status,signed,actor.userId]);if(data.status==='cancelled')await db.query("UPDATE contract_installments SET status='cancelled',version=version+1,updated_by=$3,updated_at=now() WHERE organization_id=$1 AND contract_id=$2 AND remaining_amount>0",[actor.organizationId,id,actor.userId]);const contract=await getContract(actor,id,db);const actions:Record<ContractStatus,string>={draft:'drafted',sent:'sent',negotiation:'negotiation_started',signed:'signed',active:'activated',completed:'completed',cancelled:'cancelled'};await writeHistory(db,actor,contract,actions[data.status],`Status alterado para ${data.status}.`);return contract;});}
export async function listContracts(actor:Actor,input:unknown){access(actor);const f=contractFiltersSchema.parse(input),p=params(actor),conditions=[scope(actor)];const add=(sql:string,value:unknown)=>{p.push(value);conditions.push(sql.replace('?',`$${p.length}`));};if(f.status!=='all')add('c.status=?',f.status);if(f.owner)add('c.responsible_user_id=?',f.owner);if(f.client_id)add('c.client_id=?',f.client_id);if(f.opportunity_id)add('c.opportunity_id=?',f.opportunity_id);if(f.from)add('c.created_at>=?::date',f.from);if(f.to)add("c.created_at<?::date+interval '1 day'",f.to);if(f.q)add("lower(concat_ws(' ',c.contract_number,c.title,r.name,r.document,o.title,u.name,c.status)) LIKE lower(?)",`%${f.q.replace(/[\\%_]/g,'\\$&')}%`);const where=conditions.join(' AND ');const result=await database().query(`SELECT ${select} ${joins} WHERE ${where} ORDER BY c.created_at DESC,c.id LIMIT $${p.length+1} OFFSET $${p.length+2}`,[...p,f.pageSize,(f.page-1)*f.pageSize]);const count=await database().query(`SELECT count(*)::int total ${joins} WHERE ${where}`,p);return {items:result.rows.map(normalize),total:count.rows[0].total,page:f.page,pageSize:f.pageSize};}
export async function getContractDetail(actor:Actor,id:string):Promise<ContractDetail>{const contract=await getContract(actor,id);const p=[actor.organizationId,id];const [items,installments,payments,history]=await Promise.all([
 database().query("SELECT i.*,COALESCE(e.name,k.name,'') source_name FROM contract_items i LEFT JOIN solar_equipment e ON e.organization_id=i.organization_id AND e.id=i.equipment_id LEFT JOIN solar_kits k ON k.organization_id=i.organization_id AND k.id=i.kit_id WHERE i.organization_id=$1 AND i.contract_id=$2 ORDER BY i.display_order",p),
 database().query("SELECT i.*,to_char(i.due_date,'YYYY-MM-DD') due_date,CASE WHEN i.status='pending' AND i.due_date<(now() AT TIME ZONE 'America/Sao_Paulo')::date THEN 'overdue' ELSE i.status END effective_status FROM contract_installments i WHERE i.organization_id=$1 AND i.contract_id=$2 ORDER BY i.installment_number",p),
 database().query('SELECT p.*,i.installment_number,u.name actor_name FROM contract_payments p JOIN contract_installments i ON i.organization_id=p.organization_id AND i.id=p.installment_id JOIN users u ON u.id=p.created_by WHERE p.organization_id=$1 AND p.contract_id=$2 ORDER BY p.paid_at DESC,p.id DESC',p),
 database().query('SELECT h.*,u.name actor_name FROM contract_history h JOIN users u ON u.id=h.actor_id WHERE h.organization_id=$1 AND h.contract_id=$2 ORDER BY h.created_at DESC,h.id DESC',p)
 ]);return {contract,items:json(items.rows.map(item=>({...item,quantity:Number(item.quantity),unit_value:Number(item.unit_value),discount_value:Number(item.discount_value),gross_value:Number(item.gross_value),total_value:Number(item.total_value)}))),installments:json(installments.rows.map(item=>({...item,amount:Number(item.amount),amount_paid:Number(item.amount_paid),remaining_amount:Number(item.remaining_amount),status:item.effective_status}))),payments:json(payments.rows.map(item=>({...item,amount:Number(item.amount)}))),history:json(history.rows)};}
async function refreshInstallment(db:Db,actor:Actor,installmentId:string){const paid=Number((await db.query('SELECT COALESCE(sum(amount),0)::float8 total FROM contract_payments WHERE organization_id=$1 AND installment_id=$2',[actor.organizationId,installmentId])).rows[0].total);const result=await db.query('SELECT amount FROM contract_installments WHERE organization_id=$1 AND id=$2',[actor.organizationId,installmentId]);const amount=Number(result.rows[0].amount);if(paid>amount+0.001)throw new AccessError(409,'O total pago não pode superar o valor da parcela.');const status=paid===0?'pending':paid>=amount?'paid':'partially_paid';await db.query("UPDATE contract_installments SET amount_paid=$3,remaining_amount=amount-$3,status=$4,paid_at=CASE WHEN $4='paid' THEN now() ELSE NULL END,version=version+1,updated_by=$5,updated_at=now() WHERE organization_id=$1 AND id=$2",[actor.organizationId,installmentId,paid,status,actor.userId]);}
export async function registerPayment(actor:Actor,contractId:string,input:unknown){requirePermission(actor,'contracts.payments.manage');const data=paymentSchema.parse(input);return transaction(async db=>{const contract=await getContract(actor,contractId,db,true);if(contract.status==='cancelled')throw new AccessError(409,'Não registre pagamentos em contrato cancelado.');const installment=await db.query("SELECT * FROM contract_installments WHERE organization_id=$1 AND id=$2 AND contract_id=$3 AND status!='cancelled' FOR UPDATE",[actor.organizationId,data.installment_id,contractId]);if(!installment.rowCount)throw new AccessError(404,'Parcela não encontrada.');const result=await db.query('INSERT INTO contract_payments(organization_id,contract_id,installment_id,amount,paid_at,payment_method,transaction_reference,notes,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING id',[actor.organizationId,contractId,data.installment_id,data.amount,data.paid_at,data.payment_method,data.transaction_reference,data.notes,actor.userId]);await refreshInstallment(db,actor,data.installment_id);await db.query('UPDATE contracts SET version=version+1,updated_by=$3,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,contractId,actor.userId]);const current=await getContract(actor,contractId,db);await writeHistory(db,actor,current,'payment_created',`Pagamento de R$ ${data.amount.toFixed(2)} registrado.`);return {id:result.rows[0].id,contract:current};});}
export async function updatePayment(actor:Actor,id:string,input:unknown){requirePermission(actor,'contracts.payments.manage');uuid.parse(id);const data=paymentUpdateSchema.parse(input);return transaction(async db=>{const result=await db.query('SELECT * FROM contract_payments WHERE organization_id=$1 AND id=$2 FOR UPDATE',[actor.organizationId,id]);if(!result.rowCount)throw new AccessError(404,'Pagamento não encontrado.');const before=result.rows[0];await getContract(actor,before.contract_id,db,true);if(before.version!==data.version)throw new AccessError(409,'Pagamento atualizado por outra pessoa. Recarregue.');await db.query('UPDATE contract_payments SET amount=$3,paid_at=$4,payment_method=$5,transaction_reference=$6,notes=$7,updated_by=$8,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,data.amount,data.paid_at,data.payment_method,data.transaction_reference,data.notes,actor.userId]);await refreshInstallment(db,actor,before.installment_id);await db.query('UPDATE contracts SET version=version+1,updated_by=$3,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,before.contract_id,actor.userId]);const contract=await getContract(actor,before.contract_id,db);await writeHistory(db,actor,contract,'payment_updated',`Pagamento de R$ ${data.amount.toFixed(2)} atualizado.`);return contract;});}
export async function contractDashboard(actor:Actor){access(actor);const p=params(actor),where=scope(actor);const result=await database().query(`WITH scoped_contracts AS (SELECT c.* FROM contracts c WHERE ${where}) SELECT (SELECT count(*)::int FROM scoped_contracts WHERE status NOT IN ('completed','cancelled')) active_contracts,(SELECT count(*)::int FROM scoped_contracts WHERE status IN ('signed','active','completed')) signed_contracts,(SELECT count(*)::int FROM scoped_contracts WHERE status='cancelled') cancelled_contracts,(SELECT COALESCE(sum(net_value),0)::float8 FROM scoped_contracts WHERE status!='cancelled') contracted_value,COALESCE(sum(i.amount_paid) FILTER(WHERE i.status!='cancelled'),0)::float8 received_value,COALESCE(sum(i.remaining_amount) FILTER(WHERE i.status!='cancelled'),0)::float8 receivable_value,COALESCE(sum(i.remaining_amount) FILTER(WHERE i.status IN ('pending','partially_paid','overdue') AND i.due_date<(now() AT TIME ZONE 'America/Sao_Paulo')::date),0)::float8 overdue_value,count(i.id) FILTER(WHERE i.status IN ('pending','partially_paid','overdue') AND i.due_date<(now() AT TIME ZONE 'America/Sao_Paulo')::date)::int overdue_count,count(i.id) FILTER(WHERE i.status IN ('pending','partially_paid') AND i.due_date BETWEEN (now() AT TIME ZONE 'America/Sao_Paulo')::date AND (now() AT TIME ZONE 'America/Sao_Paulo')::date+7)::int upcoming_payments FROM scoped_contracts c LEFT JOIN contract_installments i ON i.organization_id=c.organization_id AND i.contract_id=c.id`,p);return result.rows[0];}
export async function contractAlerts(actor:Actor,input:unknown={}){access(actor);const f=contractAlertFiltersSchema.parse(input),p=params(actor),conditions=[scope(actor),"i.status IN ('pending','partially_paid','overdue')","i.due_date<(now() AT TIME ZONE 'America/Sao_Paulo')::date"];const add=(sql:string,value:unknown)=>{p.push(value);conditions.push(sql.replace('?',`$${p.length}`));};if(f.owner)add('c.responsible_user_id=?',f.owner);if(f.client_id)add('c.client_id=?',f.client_id);if(f.status!=='all')add("CASE WHEN i.status='pending' AND i.due_date<(now() AT TIME ZONE 'America/Sao_Paulo')::date THEN 'overdue' ELSE i.status END=?",f.status);if(f.from)add('i.due_date>=?::date',f.from);if(f.to)add('i.due_date<=?::date',f.to);return (await database().query(`SELECT i.id installment_id,i.installment_number,to_char(i.due_date,'YYYY-MM-DD') due_date,((now() AT TIME ZONE 'America/Sao_Paulo')::date-i.due_date)::int overdue_days,i.remaining_amount::float8,c.id contract_id,c.contract_number,c.title,r.name client_name,u.name responsible_name ${joins} JOIN contract_installments i ON i.organization_id=c.organization_id AND i.contract_id=c.id WHERE ${conditions.join(' AND ')} ORDER BY i.due_date LIMIT 50`,p)).rows;}
export async function contractOptions(actor:Actor){access(actor);const [owners,equipment,kits]=await Promise.all([database().query("SELECT DISTINCT u.id,u.name FROM memberships m JOIN users u ON u.id=m.user_id JOIN role_permissions rp ON rp.role_code=m.role_code WHERE m.organization_id=$1 AND m.active AND u.active AND rp.permission_code IN ('contracts.all','contracts.own') ORDER BY u.name",[actor.organizationId]),database().query("SELECT id,name,nominal_power_w,category FROM solar_equipment WHERE organization_id=$1 AND status='active' ORDER BY name",[actor.organizationId]),database().query("SELECT id,name FROM solar_kits WHERE organization_id=$1 AND status='active' ORDER BY name",[actor.organizationId])]);return {owners:permitted(actor,'contracts.all')?owners.rows:owners.rows.filter(o=>o.id===actor.userId),equipment:equipment.rows,kits:kits.rows};}
export async function appendContractHistory(db:Db,actor:Actor,contractId:string,action:string,detail:string){const contract=await getContract(actor,contractId,db);await writeHistory(db,actor,contract,action,detail);}
export type {ContractStatus};
