import type { PoolClient } from 'pg';
import { z } from 'zod';
import { database,transaction } from '@/server/db';
import { AccessError,type Actor } from '@/modules/auth/policy';
import { crmAccess,getRecord } from '@/modules/crm/repository';
import { uuid } from '@/modules/crm/domain';
import { opportunitySchema,opportunityFilters,taskInput,taskFilters,opportunityStages,lossReasons,taskStatuses,stageSchema,type Opportunity,type CommercialTask } from './domain';
import { assertCommercialAssignee, commercialScope, commercialScopeParams } from './scope';
import {emitAutomationEvent} from '@/modules/automations/events';
type Db=Pick<PoolClient,'query'>;
const json=<T>(value:unknown):T=>JSON.parse(JSON.stringify(value));
function params(actor:Actor):unknown[]{crmAccess(actor);return commercialScopeParams(actor);}
function scoped(actor:Actor,alias:string){crmAccess(actor);return commercialScope(actor,alias);}
async function ownerAllowed(actor:Actor,id:string,db:Db){await assertCommercialAssignee(actor,id,db);}
function applyOwnerView(actor:Actor,view:'mine'|'team'|'all'|undefined,team:string|undefined,alias:string,p:unknown[],conditions:string[]){
 if(view==='all'&&actor.role!=='admin')throw new AccessError(403,'Visão total restrita ao administrador.');
 if((view==='team'||team)&&actor.role==='seller')throw new AccessError(403,'Visão de equipe indisponível.');
 if(view==='mine'){p.push(actor.userId);conditions.push(`${alias}.owner_id=$${p.length}`);}
 if(team){p.push(team);conditions.push(`EXISTS(SELECT 1 FROM commercial_team_members tm WHERE tm.organization_id=${alias}.organization_id AND tm.user_id=${alias}.owner_id AND tm.team_id=$${p.length})`);}
}
const joins=`FROM crm_opportunities o JOIN users u ON u.id=o.owner_id LEFT JOIN crm_records l ON l.organization_id=o.organization_id AND l.id=o.lead_id LEFT JOIN crm_records c ON c.organization_id=o.organization_id AND c.id=o.customer_id LEFT JOIN crm_records e ON e.organization_id=o.organization_id AND e.id=o.company_id LEFT JOIN crm_contacts ct ON ct.organization_id=o.organization_id AND ct.id=o.contact_id LEFT JOIN users cu ON cu.id=o.closed_owner_id`;
const select=`o.*,u.name owner_name,l.name lead_name,c.name customer_name,e.name company_name,ct.name contact_name,cu.name closed_owner_name,COALESCE(NULLIF(ct.whatsapp,''),NULLIF(ct.phone,''),NULLIF(c.whatsapp,''),NULLIF(c.phone,''),NULLIF(l.whatsapp,''),NULLIF(l.phone,''),NULLIF(e.whatsapp,''),NULLIF(e.phone,''),'') whatsapp_number,to_char(o.opened_on,'YYYY-MM-DD') opened_on,COALESCE(to_char(o.expected_close,'YYYY-MM-DD'),'') expected_close,COALESCE((SELECT json_agg(t) FROM (SELECT DISTINCT tg.id,tg.name,tg.color FROM crm_record_tags rt JOIN crm_tags tg ON tg.id=rt.tag_id AND tg.organization_id=rt.organization_id WHERE rt.organization_id=o.organization_id AND rt.record_id IN (o.lead_id,o.customer_id,o.company_id)) t),'[]') tags`;
function normalize(row:Record<string,unknown>){return json<Opportunity>({...row,estimated_value:Number(row.estimated_value),closed_value:row.closed_value===null?null:Number(row.closed_value)});}
export async function getOpportunity(actor:Actor,id:string,db:Db=database(),lock=false){uuid.parse(id);const p=params(actor);p.push(id);const r=await db.query(`SELECT ${select} ${joins} WHERE ${scoped(actor,'o')} AND o.id=$${p.length}${lock?' FOR UPDATE OF o':''}`,p);if(!r.rows[0])throw new AccessError(404,'Oportunidade não encontrada.');return normalize(r.rows[0]);}
async function event(db:Db,actor:Actor,relation:{record_id?:string|null;opportunity_id?:string|null},action:string,detail:string){await db.query('INSERT INTO crm_activities(organization_id,record_id,opportunity_id,actor_id,action,detail) VALUES ($1,$2,$3,$4,$5,$6)',[actor.organizationId,relation.record_id??null,relation.opportunity_id??null,actor.userId,action,detail]);if(relation.opportunity_id)await db.query('UPDATE crm_opportunities SET last_activity_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,relation.opportunity_id]);}
const keys=['title','lead_id','customer_id','company_id','contact_id','stage','estimated_value','probability','priority','source','opened_on','expected_close','loss_reason','observations'] as const;
export async function saveOpportunity(actor:Actor,input:unknown,id?:string){crmAccess(actor);const data=opportunitySchema.parse(input);return transaction(async db=>{
 const before=id?await getOpportunity(actor,id,db,true):null;if(before&&before.version!==data.version)throw new AccessError(409,'Oportunidade atualizada por outra pessoa. Recarregue.');
 if(before?.lead_id&&data.lead_id!==before.lead_id)throw new AccessError(400,'O lead de origem deve ser preservado.');
 const owner=data.owner_id??before?.owner_id??actor.userId;if(!before||before.owner_id!==owner)await ownerAllowed(actor,owner,db);
 for(const [key,kind] of [['lead_id','lead'],['customer_id','customer'],['company_id','company']] as const){if(data[key]&&(!before||data[key]!==before[key])){const record=await getRecord(actor,data[key]!,db);if(record.kind!==kind||record.status==='archived')throw new AccessError(400,'Vínculo incompatível ou arquivado.');}}
 if(data.contact_id){const contact=await db.query('SELECT 1 FROM crm_record_contacts WHERE organization_id=$1 AND contact_id=$2 AND record_id=ANY($3::uuid[])',[actor.organizationId,data.contact_id,[data.lead_id,data.customer_id,data.company_id].filter(Boolean)]);if(!contact.rowCount)throw new AccessError(400,'Contato deve pertencer a um cadastro vinculado.');}
 const demoRows=await db.query('SELECT DISTINCT is_demo FROM crm_records WHERE organization_id=$1 AND id=ANY($2::uuid[])',[actor.organizationId,[data.lead_id,data.customer_id,data.company_id].filter(Boolean)]);if(demoRows.rows.length>1)throw new AccessError(400,'Não misture cadastros DEMO e reais na mesma oportunidade.');const isDemo=demoRows.rows[0]?.is_demo??false;if(before&&before.is_demo!==isDemo)throw new AccessError(400,'Uma oportunidade não pode alternar entre DEMO e operação real.');
 if(data.stage==='won')data.probability=100;if(data.stage==='lost')data.probability=0;
 const status=data.stage==='won'?'won':data.stage==='lost'?'lost':'open';
 if(before?.status!=='open'&&before&&status===before.status&&before.estimated_value!==data.estimated_value)throw new AccessError(409,'Reabra a oportunidade antes de alterar o valor fechado.');
 const values=keys.map(key=>key==='expected_close'?(data[key]||null):data[key]);let saved=id;
 if(before){await db.query(`UPDATE crm_opportunities SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')},is_demo=$20,owner_id=$${values.length+1},status=$${values.length+2},closed_at=CASE WHEN $16='open' THEN NULL WHEN status!=$16 THEN now() ELSE closed_at END,closed_value=CASE WHEN $16='open' THEN NULL WHEN status!=$16 THEN $7::numeric ELSE closed_value END,closed_by=CASE WHEN $16='open' THEN NULL WHEN status!=$16 THEN $19::uuid ELSE closed_by END,closed_owner_id=CASE WHEN $16='open' THEN NULL WHEN status!=$16 THEN $15::uuid ELSE closed_owner_id END,version=version+1,updated_at=now(),stage_changed_at=CASE WHEN stage!=$6 THEN now() ELSE stage_changed_at END WHERE organization_id=$${values.length+3} AND id=$${values.length+4}`,[...values,owner,status,actor.organizationId,id,actor.userId,isDemo]);}
 else{const r=await db.query(`INSERT INTO crm_opportunities(${keys.join(',')},owner_id,status,organization_id,closed_at,closed_value,closed_by,closed_owner_id,is_demo) VALUES (${values.map((_,i)=>`$${i+1}`).join(',')},$15,$16,$17,CASE WHEN $16='open' THEN NULL ELSE now() END,CASE WHEN $16='open' THEN NULL ELSE $7::numeric END,CASE WHEN $16='open' THEN NULL ELSE $18::uuid END,CASE WHEN $16='open' THEN NULL ELSE $15::uuid END,$19) RETURNING id`,[...values,owner,status,actor.organizationId,actor.userId,isDemo]);saved=r.rows[0].id;}
 const relation={opportunity_id:saved};
 if(!before){await event(db,actor,relation,'opportunity.created',data.title);if(data.lead_id)await event(db,actor,{record_id:data.lead_id},'lead.opportunity',data.title);}
 else{await event(db,actor,relation,'opportunity.updated','Dados comerciais atualizados.');for(const [changed,action,label] of [['stage','stage','Etapa'],['owner_id','owner','Responsável'],['estimated_value','value','Valor estimado'],['priority','priority','Prioridade'],['expected_close','forecast','Previsão de fechamento']] as const){const next=changed==='owner_id'?owner:data[changed];if(before[changed]!==next)await event(db,actor,relation,`opportunity.${action}`,changed==='stage'?`${opportunityStages[before.stage]} -> ${opportunityStages[data.stage]}`:changed==='owner_id'?`${before.owner_id} -> ${owner}`:`${label} alterado.`);}if(before.owner_id!==owner)await db.query("INSERT INTO audit_logs(organization_id,actor_id,action) VALUES ($1,$2,'commercial.owner.changed')",[actor.organizationId,actor.userId]);}
 if(before&&before.stage!==data.stage)await emitAutomationEvent(db,{organizationId:actor.organizationId,type:'opportunity.stage_changed',eventId:`opportunity:${saved}:stage:${before.version+1}`,entityType:'opportunity',entityId:saved,opportunityId:saved,payload:{owner_id:owner,stage:data.stage,previous_stage:before.stage}});
 if(!before||before.status!==status){if(status==='won')await event(db,actor,relation,'opportunity.won',`Valor final: ${data.estimated_value}`);else if(status==='lost')await event(db,actor,relation,'opportunity.lost',lossReasons[data.loss_reason as keyof typeof lossReasons]);else if(before)await event(db,actor,relation,'opportunity.reopened','Oportunidade reaberta.');}
 return getOpportunity(actor,saved!,db);
});}
export async function moveOpportunity(actor:Actor,id:string,input:unknown){const data=z.object({stage:stageSchema,version:z.number().int().positive(),loss_reason:z.string().max(40).optional()}).strict().parse(input);const current=await getOpportunity(actor,id);const body=Object.fromEntries(keys.map(k=>[k,current[k]]));return saveOpportunity(actor,{...body,owner_id:current.owner_id,...data},id);}
function filtered(actor:Actor,input:unknown){const f=opportunityFilters.parse(input),p=params(actor),c=[scoped(actor,'o')];const add=(sql:string,value:unknown)=>{p.push(value);c.push(sql.replaceAll('?',`$${p.length}`));};applyOwnerView(actor,f.view,f.team,'o',p,c);for(const key of ['stage','priority','source'] as const)if(f[key])add(`o.${key}=?`,f[key]);if(f.status!=='all')add('o.status=?',f.status);if(!f.record_id&&f.demo!=='all')add('o.is_demo=?',f.demo==='demo');if(f.owner)add('o.owner_id=?',f.owner);if(f.record_id)add('(o.lead_id=? OR o.customer_id=? OR o.company_id=?)',f.record_id);if(f.from)add('o.opened_on>=?::date',f.from);if(f.to)add('o.opened_on<=?::date',f.to);if(f.q){const query=f.q.replace(/[\\%_]/g,'\\$&');add(`lower(concat_ws(' ',o.title,l.name,c.name,e.name,l.phone,l.whatsapp,l.email,c.phone,c.whatsapp,c.email,e.phone,e.whatsapp,e.email,ct.name,ct.phone,ct.whatsapp,ct.email)) LIKE lower(?) ESCAPE '\\'`,`%${query}%`);const n=f.q.replace(/\D/g,'');if(n.length>=4){const original=c.pop();p.push(`%${n}%`);c.push(`(${original} OR concat_ws(' ',l.phone,l.whatsapp,c.phone,c.whatsapp,e.phone,e.whatsapp,ct.phone,ct.whatsapp) LIKE $${p.length})`);}}return {f,p,where:c.join(' AND ')};}
export async function listOpportunities(actor:Actor,input:unknown){const {f,p,where}=filtered(actor,input);const r=await database().query(`SELECT ${select} ${joins} WHERE ${where} ORDER BY o.updated_at DESC,o.id LIMIT $${p.length+1} OFFSET $${p.length+2}`,[...p,f.pageSize,(f.page-1)*f.pageSize]);const stats=await database().query(`SELECT count(*)::int total,COALESCE(sum(o.estimated_value),0)::float8 value_total,COALESCE(sum(o.estimated_value) FILTER(WHERE o.status='open'),0)::float8 value_open,COALESCE(sum(o.closed_value) FILTER(WHERE o.status='won'),0)::float8 value_won ${joins} WHERE ${where}`,p);return {items:r.rows.map(normalize),...(stats.rows[0] as {total:number;value_total:number;value_open:number;value_won:number}),page:f.page,pageSize:f.pageSize};}
export async function pipeline(actor:Actor,input:unknown){const parsed=opportunityFilters.parse(input);const summary=await listOpportunities(actor,{...parsed,pageSize:1});const columns=[];for(const stage of Object.keys(opportunityStages)){if(parsed.stage&&parsed.stage!==stage)continue;const column=await listOpportunities(actor,{...parsed,stage,page:parsed.page,pageSize:20});columns.push({stage,...column});}return {columns,total:summary.total,value_total:summary.value_total,value_open:summary.value_open,value_won:summary.value_won};}
export async function settings(actor:Actor){crmAccess(actor);const r=await database().query('SELECT inactive_days FROM crm_commercial_settings WHERE organization_id=$1',[actor.organizationId]);return {inactive_days:r.rows[0]?.inactive_days??7,can_edit:actor.permissions.includes('crm.all')};}
export async function saveSettings(actor:Actor,input:unknown){crmAccess(actor);if(!actor.permissions.includes('crm.all'))throw new AccessError(403,'Somente a gestão pode configurar o acompanhamento.');const {inactive_days}=z.object({inactive_days:z.coerce.number().int().min(1).max(365)}).strict().parse(input);await transaction(async db=>{await db.query('INSERT INTO crm_commercial_settings(organization_id,inactive_days) VALUES ($1,$2) ON CONFLICT(organization_id) DO UPDATE SET inactive_days=$2,updated_at=now()',[actor.organizationId,inactive_days]);await db.query("INSERT INTO audit_logs(organization_id,actor_id,action) VALUES ($1,$2,'commercial.settings.updated')",[actor.organizationId,actor.userId]);});return settings(actor);}
export async function opportunityFeed(actor:Actor,id:string,type:'activities'|'notes',page=1){const o=await getOpportunity(actor,id);const ids=[o.lead_id,o.customer_id,o.company_id].filter(Boolean);if(o.customer_id){const original=await database().query('SELECT original_lead_id FROM crm_records WHERE organization_id=$1 AND id=$2',[actor.organizationId,o.customer_id]);if(original.rows[0]?.original_lead_id)ids.push(original.rows[0].original_lead_id);}
 const visible=params(actor);visible.push(ids);
 const allowed=await database().query(`SELECT r.id FROM crm_records r WHERE ${commercialScope(actor,'r',true)} AND r.id=ANY($${visible.length}::uuid[])`,visible);
 const table=type==='notes'?'crm_notes':'crm_activities';const p=[actor.organizationId,id,allowed.rows.map(r=>r.id)];const where='x.organization_id=$1 AND (x.opportunity_id=$2 OR x.record_id=ANY($3::uuid[]))';const r=await database().query(`SELECT x.*,u.name actor_name FROM ${table} x JOIN users u ON u.id=x.actor_id WHERE ${where} ORDER BY x.created_at DESC,x.id LIMIT 20 OFFSET $4`,[...p,(page-1)*20]);const count=await database().query(`SELECT count(*)::int total FROM ${table} x WHERE ${where}`,p);return {items:json(r.rows),total:count.rows[0].total,page};}
export async function addOpportunityNote(actor:Actor,input:unknown){const data=z.object({opportunity_id:uuid,body:z.string().trim().min(1).max(4000)}).strict().parse(input);return transaction(async db=>{await getOpportunity(actor,data.opportunity_id,db,true);const r=await db.query('INSERT INTO crm_notes(organization_id,opportunity_id,actor_id,body) VALUES ($1,$2,$3,$4) RETURNING id',[actor.organizationId,data.opportunity_id,actor.userId,data.body]);await event(db,actor,data,'note.created',data.body);return r.rows[0];});}
const taskSelect=`t.*,u.name owner_name,u.name actor_name,COALESCE(o.title,r.name,'Cadastro') related_name,COALESCE(r.kind,'opportunity') related_kind,to_char(t.due_date,'YYYY-MM-DD') due_date,COALESCE(to_char(t.due_time,'HH24:MI'),'') due_time`;
const taskJoins='FROM crm_tasks t JOIN users u ON u.id=t.owner_id LEFT JOIN crm_records r ON r.organization_id=t.organization_id AND r.id=t.record_id LEFT JOIN crm_opportunities o ON o.organization_id=t.organization_id AND o.id=t.opportunity_id';
export async function getTask(actor:Actor,id:string,db:Db=database(),lock=false){uuid.parse(id);const p=params(actor);p.push(id);const r=await db.query(`SELECT ${taskSelect} ${taskJoins} WHERE ${scoped(actor,'t')} AND t.id=$${p.length}${lock?' FOR UPDATE OF t':''}`,p);if(!r.rows[0])throw new AccessError(404,'Tarefa não encontrada.');return json<CommercialTask>(r.rows[0]);}
export async function saveTask(actor:Actor,input:unknown,id?:string){crmAccess(actor);const data=taskInput.parse(input);return transaction(async db=>{
 const before=id?await getTask(actor,id,db,true):null;if(before&&before.version!==data.version)throw new AccessError(409,'Tarefa atualizada por outra pessoa. Recarregue.');
 let defaultOwner=before?.owner_id??actor.userId;
 if(!before||before.record_id!==data.record_id||before.opportunity_id!==data.opportunity_id){const parent=data.opportunity_id?await getOpportunity(actor,data.opportunity_id,db):await getRecord(actor,data.record_id!,db);defaultOwner=parent.owner_id??actor.userId;}
 const owner=data.owner_id??defaultOwner;if(!before||before.owner_id!==owner)await ownerAllowed(actor,owner,db);
 let day=data.due_date,time=data.due_time;
 if(!day&&data.due_at){const d=new Date(data.due_at);day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);time=new Intl.DateTimeFormat('en-GB',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
 const values=[actor.organizationId,data.record_id,data.opportunity_id,owner,data.title,data.description,data.priority,data.status,day,time||null];let saved=id;
 if(before){await db.query(`UPDATE crm_tasks SET record_id=$2,opportunity_id=$3,owner_id=$4,title=$5,description=$6,priority=$7,status=$8,due_date=$9,due_time=$10,due_at=($9::date+COALESCE($10::time,'23:59:59'::time)) AT TIME ZONE 'America/Sao_Paulo',completed_at=CASE WHEN $8='completed' THEN COALESCE(completed_at,now()) ELSE NULL END,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$11`,[...values,id]);}
 else{const r=await db.query(`INSERT INTO crm_tasks(organization_id,record_id,opportunity_id,owner_id,title,description,priority,status,due_date,due_time,due_at,completed_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,($9::date+COALESCE($10::time,'23:59:59'::time)) AT TIME ZONE 'America/Sao_Paulo',CASE WHEN $8='completed' THEN now() ELSE NULL END) RETURNING id`,values);saved=r.rows[0].id;}
 await event(db,actor,data,before?'task.updated':'task.created',data.title);if(before?.status!==data.status&&data.status==='completed')await event(db,actor,data,'task.completed',data.title);else if(before&&before.status!==data.status)await event(db,actor,data,'task.status',`${data.title}: ${taskStatuses[data.status]}`);
 return getTask(actor,saved!,db);
});}
export async function updateTaskStatus(actor:Actor,id:string,input:unknown){const data=z.object({status:z.enum(['pending','in_progress','completed','cancelled']),version:z.number().int().positive().optional()}).strict().parse(input);const t=await getTask(actor,id);if(data.version!==undefined&&data.version!==t.version)throw new AccessError(409,'Tarefa atualizada. Recarregue.');return saveTask(actor,{title:t.title,description:t.description,priority:t.priority,status:data.status,record_id:t.record_id,opportunity_id:t.opportunity_id,owner_id:t.owner_id,due_date:t.due_date,due_time:t.due_time,version:t.version},id);}
export async function listTasks(actor:Actor,input:unknown){const f=taskFilters.parse(input),p=params(actor),c=[scoped(actor,'t')];const add=(sql:string,v:unknown)=>{p.push(v);c.push(sql.replaceAll('?',`$${p.length}`));};applyOwnerView(actor,f.view,f.team,'t',p,c);if(f.owner)add('t.owner_id=?',f.owner);if(f.opportunity_id){await getOpportunity(actor,f.opportunity_id);add('t.opportunity_id=?',f.opportunity_id);}if(f.record_id){const r=await getRecord(actor,f.record_id);add('t.record_id=ANY(?::uuid[])',[r.id,...(r.original_lead_id?[r.original_lead_id]:[])]);}if(f.status==='active')c.push("t.status IN ('pending','in_progress')");else if(f.status!=='all')add('t.status=?',f.status);if(f.from)add('t.due_date>=?::date',f.from);if(f.to)add('t.due_date<=?::date',f.to);const today="(now() AT TIME ZONE 'America/Sao_Paulo')::date";if(f.bucket==='overdue')c.push(`t.due_at<now() AND t.status IN ('pending','in_progress')`);if(f.bucket==='today')c.push(`t.due_date=${today}`);if(f.bucket==='upcoming')c.push(`t.due_date>${today}`);if(!f.record_id&&!f.opportunity_id&&f.demo!=='all')add('COALESCE(o.is_demo,r.is_demo,false)=?',f.demo==='demo');const where=c.join(' AND ');const r=await database().query(`SELECT ${taskSelect} ${taskJoins} WHERE ${where} ORDER BY t.due_date,t.due_time NULLS FIRST,t.id LIMIT $${p.length+1} OFFSET $${p.length+2}`,[...p,f.pageSize,(f.page-1)*f.pageSize]);const count=await database().query(`SELECT count(*)::int total ${taskJoins} WHERE ${where}`,p);return {items:json<CommercialTask[]>(r.rows),total:count.rows[0].total,page:f.page,pageSize:f.pageSize};}
export async function indicators(actor:Actor,input:unknown={}){const f=z.object({demo:z.enum(['real','demo']).default('real'),from:z.iso.date().optional(),to:z.iso.date().optional()}).parse(input);if(f.from&&f.to&&f.from>f.to)throw new AccessError(400,'Período inválido.');const {inactive_days}=await settings(actor);const p=params(actor);p.push(inactive_days);const days=`$${p.length}`;p.push(f.from??null,f.to??null);const period=`(closed_at AT TIME ZONE 'America/Sao_Paulo')::date>=COALESCE($${p.length-1}::date,date_trunc('month',now() AT TIME ZONE 'America/Sao_Paulo')::date) AND (closed_at AT TIME ZONE 'America/Sao_Paulo')::date<=COALESCE($${p.length}::date,(now() AT TIME ZONE 'America/Sao_Paulo')::date)`;
 const r=await database().query(`SELECT count(*) FILTER(WHERE status='open')::int open_count,COALESCE(sum(estimated_value) FILTER(WHERE status='open'),0)::float8 pipeline_value,count(*) FILTER(WHERE status='won' AND ${period})::int won_count,count(*) FILTER(WHERE status='lost' AND ${period})::int lost_count,COALESCE(sum(closed_value) FILTER(WHERE status='won' AND ${period}),0)::float8 won_value,count(*) FILTER(WHERE status='open' AND last_activity_at<now()-make_interval(days=>${days}::int))::int inactive_count FROM crm_opportunities o WHERE ${scoped(actor,'o')} AND o.is_demo=${f.demo==='demo'?'true':'false'}`,p);const pending=await database().query(`SELECT count(*)::int total ${taskJoins} WHERE ${scoped(actor,'t')} AND t.status IN ('pending','in_progress') AND COALESCE(o.is_demo,r.is_demo,false)=${f.demo==='demo'?'true':'false'}`,params(actor));const row=r.rows[0];return {...row,pending_tasks:pending.rows[0].total,conversion_rate:row.won_count+row.lost_count?Math.round(10000*row.won_count/(row.won_count+row.lost_count))/100:0,inactive_days,period_from:f.from??null,period_to:f.to??null};}
export async function followUp(actor:Actor,demo=false){const config=await settings(actor),p=params(actor);p.push(config.inactive_days);const threshold=`now()-make_interval(days=>$${p.length}::int)`;const groups:Record<string,Opportunity[]>={};for(const [key,condition] of [['inactive',`o.last_activity_at<${threshold}`],['stalled',`o.stage_changed_at<${threshold}`],['closing',`o.expected_close BETWEEN (now() AT TIME ZONE 'America/Sao_Paulo')::date AND (now() AT TIME ZONE 'America/Sao_Paulo')::date+7 AND $${p.length}::int>0`]]){const r=await database().query(`SELECT ${select} ${joins} WHERE ${scoped(actor,'o')} AND o.status='open' AND o.is_demo=${demo?'true':'false'} AND ${condition} ORDER BY o.expected_close NULLS LAST,o.updated_at LIMIT 20`,p);groups[key]=r.rows.map(normalize);}return {settings:config,inactive:groups.inactive,stalled:groups.stalled,closing:groups.closing,today:await listTasks(actor,{demo:demo?'demo':'real',bucket:'today',status:'active'}),overdue:await listTasks(actor,{demo:demo?'demo':'real',bucket:'overdue',status:'active'})};}
