'use client';
import { useEffect,useState } from 'react';
import { Archive,BarChart3,Boxes,Calculator,Edit,FileText,PackagePlus,Plus,RotateCcw,Zap } from 'lucide-react';
import { api,errorMessage } from '@/components/crm/api';
import { Modal } from '@/components/crm/modal';
import { supplyTypes,tariffFlags,type EnergyBill,type EnergyUnit,type MonthlyConsumption,type SolarSizing } from '@/modules/energy/domain';
import type { KitSelection,SolarKit } from '@/modules/solar-catalog/domain';

type Detail={unit:EnergyUnit;consumptions:MonthlyConsumption[];bills:EnergyBill[];sizings:SolarSizing[];summary:{months_count:number;last_12_months:number;average_kwh:number|null;total_kwh:number;ready_for_sizing:boolean}};
const monthLabel=(value:string)=>value?new Intl.DateTimeFormat('pt-BR',{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(value+'-01T00:00:00Z')):'-';
const number=(value:FormDataEntryValue|null)=>value===''||value===null?null:Number(value);
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});

export function EnergyWorkspace({customerId,customerName}:{customerId:string;customerName:string}){
 const [units,setUnits]=useState<EnergyUnit[]>([]);const [selected,setSelected]=useState('');const [detail,setDetail]=useState<Detail|null>(null);const [kits,setKits]=useState<SolarKit[]>([]);const [selections,setSelections]=useState<KitSelection[]>([]);const [modal,setModal]=useState<'unit'|'consumption'|'bill'|'sizing'|'kit'|null>(null);const [editing,setEditing]=useState<EnergyUnit|MonthlyConsumption|EnergyBill|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function loadUnits(preferred?:string){setLoading(true);try{const data=await api<EnergyUnit[]>(`/api/energy-units?customer_id=${customerId}`);setUnits(data);const next=preferred||selected||data.find(item=>item.status==='active')?.id||data[0]?.id||'';setSelected(next);if(!next)setDetail(null);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 async function loadDetail(id=selected){if(!id)return;setLoading(true);try{setDetail(await api<Detail>(`/api/energy-units/${id}`));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();api<EnergyUnit[]>(`/api/energy-units?customer_id=${customerId}`,'GET',undefined,controller.signal).then(data=>{setUnits(data);setSelected(data.find(item=>item.status==='active')?.id||data[0]?.id||'');if(!data.length)setDetail(null);setLoading(false);}).catch(e=>{if(!controller.signal.aborted){setError(errorMessage(e));setLoading(false);}});return()=>controller.abort();},[customerId]);
 useEffect(()=>{if(!selected)return;const controller=new AbortController();api<Detail>(`/api/energy-units/${selected}`,'GET',undefined,controller.signal).then(data=>{setDetail(data);setLoading(false);}).catch(e=>{if(!controller.signal.aborted){setError(errorMessage(e));setLoading(false);}});return()=>controller.abort();},[selected]);
 const latestSizingId=detail?.sizings[0]?.id??'';
 useEffect(()=>{if(!latestSizingId)return;const controller=new AbortController();Promise.all([api<SolarKit[]>('/api/solar-kits','GET',undefined,controller.signal),api<KitSelection[]>(`/api/solar-kit-selections?sizing_id=${latestSizingId}`,'GET',undefined,controller.signal)]).then(([available,history])=>{setKits(available);setSelections(history);}).catch(e=>{if(!controller.signal.aborted)setError(errorMessage(e));});return()=>controller.abort();},[latestSizingId]);
 function open(kind:'unit'|'consumption'|'bill'|'sizing'|'kit',item:EnergyUnit|MonthlyConsumption|EnergyBill|null=null){setEditing(item);setError('');setNotice('');setModal(kind);}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{
  if(modal==='unit'){
   const current=editing as EnergyUnit|null;const body={customer_id:customerId,label:String(form.get('label')),consumer_unit_number:String(form.get('consumer_unit_number')),installation_number:String(form.get('installation_number')),utility:String(form.get('utility')),holder_name:String(form.get('holder_name')),tariff_group:String(form.get('tariff_group')),supply_type:String(form.get('supply_type')),voltage:number(form.get('voltage')),service_address:String(form.get('service_address')),...(current?{version:current.version}:{})};
   const saved=await api<EnergyUnit>(`/api/energy-units${current?'/'+current.id:''}`,current?'PUT':'POST',body);await loadUnits(saved.id);setNotice(current?'Unidade consumidora atualizada.':'Unidade consumidora cadastrada.');
  }else if(modal==='consumption'){
   const current=editing as MonthlyConsumption|null;const body={consumer_unit_id:selected,reference_month:String(form.get('reference_month')),consumption_kwh:Number(form.get('consumption_kwh')),injected_energy_kwh:number(form.get('injected_energy_kwh')),peak_demand_kw:number(form.get('peak_demand_kw')),days_billed:number(form.get('days_billed')),source:String(form.get('source')),notes:String(form.get('notes')),...(current?{version:current.version}:{})};
   await api(`/api/energy-consumptions${current?'/'+current.id:''}`,current?'PUT':'POST',body);await loadDetail();await loadUnits(selected);setNotice(current?'Consumo mensal atualizado.':'Consumo mensal adicionado.');
  }else if(modal==='bill'){
   const current=editing as EnergyBill|null;const body={consumer_unit_id:selected,reference_month:String(form.get('reference_month')),invoice_number:String(form.get('invoice_number')),issue_date:String(form.get('issue_date')),due_date:String(form.get('due_date')),total_amount:Number(form.get('total_amount')),tariff_flag:String(form.get('tariff_flag')),previous_reading:number(form.get('previous_reading')),current_reading:number(form.get('current_reading')),notes:String(form.get('notes')),...(current?{version:current.version}:{})};
   await api(`/api/energy-bills${current?'/'+current.id:''}`,current?'PUT':'POST',body);await loadDetail();setNotice(current?'Fatura atualizada.':'Fatura adicionada.');
  }else if(modal==='sizing'){
   const body={consumer_unit_id:selected,solar_irradiation_daily:Number(form.get('solar_irradiation_daily')),performance_ratio_percent:Number(form.get('performance_ratio_percent')),module_power_w:Number(form.get('module_power_w')),safety_margin_percent:Number(form.get('safety_margin_percent')),notes:String(form.get('notes'))};
   await api('/api/solar-sizings','POST',body);await loadDetail();setNotice('Dimensionamento calculado e salvo no histórico do cliente.');
  }else if(modal==='kit'){
   const sizingId=detail?.sizings[0]?.id;if(!sizingId)throw new Error('Calcule um dimensionamento antes de vincular o kit.');const saved=await api<KitSelection>('/api/solar-kit-selections','POST',{sizing_id:sizingId,kit_id:String(form.get('kit_id'))});setSelections(current=>[saved,...current]);setNotice('Kit vinculado ao dimensionamento e salvo no histórico.');
  }
  setModal(null);setEditing(null);
 }catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function status(){if(!detail)return;setBusy(true);setError('');const action=detail.unit.status==='active'?'archive':'restore';try{await api(`/api/energy-units/${detail.unit.id}/${action}`,'POST',{version:detail.unit.version});await loadUnits(detail.unit.id);await loadDetail(detail.unit.id);setNotice(action==='archive'?'Unidade arquivada.':'Unidade reativada.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const consumptionByMonth=new Map(detail?.consumptions.map(item=>[item.reference_month,item])??[]);const billByMonth=new Map(detail?.bills.map(item=>[item.reference_month,item])??[]);const months=[...new Set([...(detail?.consumptions.map(item=>item.reference_month)??[]),...(detail?.bills.map(item=>item.reference_month)??[])])].sort().reverse();const chart=(detail?.consumptions.slice(0,12).reverse()??[]);const max=Math.max(1,...chart.map(item=>item.consumption_kwh));
 return <div className="energy-workspace">
  <div className="card-heading"><div><h2>Consumo e faturas</h2><p className="muted">Unidades consumidoras de {customerName}, com histórico mensal preparado para dimensionamento.</p></div><button className="button primary" onClick={()=>open('unit')}><Plus size={16}/>Nova unidade</button></div>
  {notice&&<p className="crm-notice" role="status">{notice}</p>}{error&&!modal&&<p className="error-box" role="alert">{error}</p>}{loading&&!detail&&<p className="crm-loading" role="status">Carregando dados de energia…</p>}
  {!loading&&units.length===0&&<div className="energy-empty"><Zap size={28}/><h3>Nenhuma unidade consumidora</h3><p>Cadastre a primeira unidade para registrar consumo e dados das faturas.</p><button className="button primary" onClick={()=>open('unit')}><Plus size={16}/>Cadastrar unidade</button></div>}
  {units.length>0&&<><div className="energy-unit-bar"><label><span>Unidade consumidora</span><select aria-label="Unidade consumidora" value={selected} onChange={e=>setSelected(e.target.value)}>{units.map(item=><option key={item.id} value={item.id}>{item.label}{item.status==='archived'?' (arquivada)':''}</option>)}</select></label>{detail&&<div className="energy-unit-actions"><button className="button secondary" onClick={()=>open('unit',detail.unit)}><Edit size={15}/>Editar unidade</button><button className="button secondary" disabled={busy} onClick={status}>{detail.unit.status==='active'?<Archive size={15}/>:<RotateCcw size={15}/>} {detail.unit.status==='active'?'Arquivar':'Reativar'}</button></div>}</div>
  {detail&&<><div className="energy-unit-profile"><div><span>Distribuidora</span><strong>{detail.unit.utility||'Não informada'}</strong></div><div><span>Número da UC</span><strong>{detail.unit.consumer_unit_number||'Não informado'}</strong></div><div><span>Ligação</span><strong>{supplyTypes[detail.unit.supply_type]}</strong></div><div><span>Grupo tarifário</span><strong>{detail.unit.tariff_group||'Não informado'}</strong></div></div>
  <div className="energy-summary"><article><span>Média mensal</span><strong>{detail.summary.average_kwh===null?'—':`${detail.summary.average_kwh.toLocaleString('pt-BR')} kWh`}</strong></article><article><span>Últimos 12 meses</span><strong>{detail.summary.total_kwh.toLocaleString('pt-BR')} kWh</strong></article><article><span>Histórico</span><strong>{detail.summary.months_count} {detail.summary.months_count===1?'mês':'meses'}</strong></article><article className={detail.summary.ready_for_sizing?'ready':''}><span>Base para dimensionamento</span><strong>{detail.summary.ready_for_sizing?'Completa':'Em formação'}</strong><small>{detail.summary.last_12_months}/12 meses recentes</small></article></div>
  <div className="energy-section-heading"><div><BarChart3 size={18}/><div><h3>Histórico mensal</h3><p>Consumo em kWh por mês de referência.</p></div></div>{detail.unit.status==='active'&&<button className="button primary" onClick={()=>open('consumption')}><Plus size={16}/>Adicionar consumo</button>}</div>
  {chart.length>0&&<div className="energy-chart" aria-label="Gráfico de consumo mensal">{chart.map(item=><div className="energy-bar-column" key={item.id}><span>{item.consumption_kwh.toLocaleString('pt-BR')}</span><div style={{height:`${Math.max(8,item.consumption_kwh/max*100)}%`}}/><small>{monthLabel(item.reference_month).replace(' de ','/')}</small></div>)}</div>}
  <div className="energy-section-heading"><div><FileText size={18}/><div><h3>Consumos e faturas</h3><p>Dados mensais informados manualmente, sem envio ou integração externa.</p></div></div>{detail.unit.status==='active'&&<button className="button secondary" onClick={()=>open('bill')}><Plus size={16}/>Adicionar fatura</button>}</div>
  {months.length===0?<div className="energy-empty compact"><p>Nenhum consumo ou fatura cadastrado nesta unidade.</p></div>:<div className="energy-table-wrap"><table className="energy-table"><thead><tr><th>Mês</th><th>Consumo</th><th>Injetada</th><th>Fatura</th><th>Vencimento</th><th>Ações</th></tr></thead><tbody>{months.map(month=>{const c=consumptionByMonth.get(month);const b=billByMonth.get(month);return <tr key={month}><td><strong>{monthLabel(month)}</strong></td><td>{c?`${c.consumption_kwh.toLocaleString('pt-BR')} kWh`:'—'}</td><td>{c?.injected_energy_kwh!=null?`${c.injected_energy_kwh.toLocaleString('pt-BR')} kWh`:'—'}</td><td>{b?money.format(b.total_amount):'—'}</td><td>{b?.due_date?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(b.due_date+'T00:00:00Z')):'—'}</td><td><div className="energy-row-actions">{c&&detail.unit.status==='active'&&<button aria-label={`Editar consumo de ${monthLabel(month)}`} onClick={()=>open('consumption',c)}>Consumo</button>}{b&&detail.unit.status==='active'?<button aria-label={`Editar fatura de ${monthLabel(month)}`} onClick={()=>open('bill',b)}>Fatura</button>:detail.unit.status==='active'&&<button onClick={()=>open('bill',{reference_month:month} as EnergyBill)}>Fatura</button>}</div></td></tr>;})}</tbody></table></div>}<SizingSection detail={detail} onCalculate={()=>open('sizing')}/><KitLinkSection sizing={detail.sizings[0]} kits={kits} selections={selections} active={detail.unit.status==='active'} onLink={()=>open('kit')}/></>}</>}
  {modal&&<Modal title={modal==='unit'?(editing?'Editar unidade consumidora':'Nova unidade consumidora'):modal==='consumption'?(editing?'Editar consumo mensal':'Adicionar consumo mensal'):modal==='bill'?(editing?.id?'Editar fatura':'Adicionar fatura'):modal==='sizing'?'Novo dimensionamento solar':'Vincular kit ao dimensionamento'} onClose={()=>{if(!busy)setModal(null);}}><form className="crm-form" onSubmit={submit}>
   {modal==='unit'?<UnitFields value={editing as EnergyUnit|null}/>:modal==='consumption'?<ConsumptionFields value={editing as MonthlyConsumption|null}/>:modal==='bill'?<BillFields value={editing as EnergyBill|null}/>:modal==='sizing'?<SizingFields months={detail?.summary.last_12_months??0}/>:<KitSelectionFields kits={kits}/>} {error&&<p className="error-box" role="alert">{error}</p>}<div className="crm-form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" disabled={busy}>{busy?'Calculando…':modal==='sizing'?'Calcular e salvar':modal==='kit'?'Vincular kit':'Salvar'}</button></div>
  </form></Modal>}
 </div>;
}

function SizingSection({detail,onCalculate}:{detail:Detail;onCalculate:()=>void}){
 const latest=detail.sizings[0];const format=(value:number,digits=2)=>value.toLocaleString('pt-BR',{minimumFractionDigits:digits,maximumFractionDigits:digits});
 return <section className="sizing-section"><div className="energy-section-heading"><div><Calculator size={18}/><div><h3>Dimensionamento solar</h3><p>Estimativa baseada no consumo da unidade e nos parâmetros informados.</p></div></div>{detail.unit.status==='active'&&detail.summary.average_kwh!==null&&<button className="button primary" onClick={onCalculate}><Calculator size={16}/>Calcular dimensionamento</button>}</div>
  {detail.summary.average_kwh===null?<div className="energy-empty compact"><p>Cadastre ao menos um mês de consumo maior que zero para iniciar o dimensionamento.</p></div>:!latest?<div className="sizing-callout"><strong>Base disponível para cálculo</strong><p>A média atual é de {format(detail.summary.average_kwh)} kWh/mês, calculada com {detail.summary.last_12_months} {detail.summary.last_12_months===1?'mês':'meses'}.</p></div>:<><article className="sizing-result"><header><div><span>Último dimensionamento</span><strong>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(latest.created_at))}</strong></div><small>Calculado por {latest.actor_name}</small></header><div className="sizing-result-grid"><div><span>Geração necessária</span><strong>{format(latest.required_generation_kwh)} kWh/mês</strong></div><div><span>Módulos estimados</span><strong>{latest.module_count}</strong><small>{latest.module_power_w} W por módulo</small></div><div><span>Potência do sistema</span><strong>{format(latest.system_power_kwp)} kWp</strong><small>Mínimo calculado: {format(latest.required_power_kwp)} kWp</small></div><div><span>Geração estimada</span><strong>{format(latest.estimated_monthly_generation_kwh)} kWh/mês</strong></div></div><footer>Média de {format(latest.average_consumption_kwh)} kWh · margem {format(latest.safety_margin_percent)}% · irradiação {format(latest.solar_irradiation_daily)} · desempenho {format(latest.performance_ratio_percent)}% · período {monthLabel(latest.consumption_period_start)} a {monthLabel(latest.consumption_period_end)}</footer></article>
  {detail.sizings.length>0&&<div className="sizing-history"><h4>Memória de cálculos</h4><div className="energy-table-wrap"><table className="energy-table"><thead><tr><th>Data</th><th>Consumo médio</th><th>Margem</th><th>Módulos</th><th>Potência</th><th>Geração estimada</th></tr></thead><tbody>{detail.sizings.map(item=><tr key={item.id}><td>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(item.created_at))}</td><td>{format(item.average_consumption_kwh)} kWh</td><td>{format(item.safety_margin_percent)}%</td><td>{item.module_count} × {item.module_power_w} W</td><td>{format(item.system_power_kwp)} kWp</td><td>{format(item.estimated_monthly_generation_kwh)} kWh</td></tr>)}</tbody></table></div></div>}</>}
 </section>;
}

function KitLinkSection({sizing,kits,selections,active,onLink}:{sizing:SolarSizing|undefined;kits:SolarKit[];selections:KitSelection[];active:boolean;onLink:()=>void}){
 if(!sizing)return null;const history=selections.filter(item=>item.sizing_id===sizing.id);const latest=history[0];return <section className="kit-link-section"><div className="energy-section-heading"><div><Boxes size={18}/><div><h3>Kit do dimensionamento</h3><p>Composição comercial associada ao cálculo mais recente.</p></div></div>{active&&kits.length>0&&<button className="button primary" onClick={onLink}><PackagePlus size={16}/>{latest?'Alterar kit':'Vincular kit'}</button>}</div>
  {kits.length===0?<div className="energy-empty compact"><p>Nenhum kit ativo está disponível. Cadastre a composição em Equipamentos e kits.</p></div>:!latest?<div className="sizing-callout"><strong>Nenhum kit vinculado</strong><p>Escolha um kit ativo; a quantidade será calculada para alcançar a potência dimensionada de {sizing.system_power_kwp.toLocaleString('pt-BR')} kWp.</p></div>:<><article className="linked-kit"><header><div><span>Kit selecionado</span><h4>{latest.kit_name}</h4></div><small>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(latest.created_at))}</small></header><div><p><strong>{latest.kit_quantity}</strong><span>{latest.kit_quantity===1?'kit':'kits'}</span></p><p><strong>{latest.module_count}</strong><span>módulos</span></p><p><strong>{latest.dc_power_kwp.toLocaleString('pt-BR')} kWp</strong><span>potência CC</span></p><p><strong>{latest.inverter_power_kw.toLocaleString('pt-BR')} kW</strong><span>inversores</span></p></div><footer>Vinculado por {latest.actor_name}. A composição técnica foi preservada como snapshot.</footer></article>{history.length>1&&<div className="kit-selection-history"><h4>Histórico de kits vinculados</h4>{history.map(item=><p key={item.id}><span>{item.kit_name} · {item.kit_quantity} × · {item.dc_power_kwp.toLocaleString('pt-BR')} kWp</span><time>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(item.created_at))}</time></p>)}</div>}</>}
 </section>;
}

function UnitFields({value}:{value:EnergyUnit|null}){return <><div className="crm-form-grid"><Field name="label" label="Nome da unidade" required defaultValue={value?.label}/><Field name="consumer_unit_number" label="Número da unidade consumidora" defaultValue={value?.consumer_unit_number}/><Field name="installation_number" label="Número da instalação" defaultValue={value?.installation_number}/><Field name="utility" label="Distribuidora" defaultValue={value?.utility}/><Field name="holder_name" label="Titular da fatura" defaultValue={value?.holder_name}/><Field name="tariff_group" label="Grupo tarifário" placeholder="Ex.: B1 residencial" defaultValue={value?.tariff_group}/><label className="crm-field"><span>Tipo de ligação</span><select name="supply_type" defaultValue={value?.supply_type??'unknown'}>{Object.entries(supplyTypes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><Field name="voltage" label="Tensão (V)" type="number" min="1" max="1000000" defaultValue={value?.voltage??''}/></div><label className="crm-field"><span>Endereço da unidade</span><textarea name="service_address" maxLength={500} rows={3} defaultValue={value?.service_address}/></label></>}
function ConsumptionFields({value}:{value:MonthlyConsumption|null}){return <><div className="crm-form-grid"><Field name="reference_month" label="Mês de referência" type="month" required defaultValue={value?.reference_month}/><Field name="consumption_kwh" label="Consumo (kWh)" type="number" min="0" max="100000000" step="0.001" required defaultValue={value?.consumption_kwh}/><Field name="injected_energy_kwh" label="Energia injetada (kWh)" type="number" min="0" step="0.001" defaultValue={value?.injected_energy_kwh??''}/><Field name="peak_demand_kw" label="Demanda máxima (kW)" type="number" min="0" step="0.001" defaultValue={value?.peak_demand_kw??''}/><Field name="days_billed" label="Dias faturados" type="number" min="1" max="62" defaultValue={value?.days_billed??''}/><label className="crm-field"><span>Origem do dado</span><select name="source" defaultValue={value?.source??'manual'}><option value="manual">Informado manualmente</option><option value="bill">Extraído da fatura</option></select></label></div><label className="crm-field"><span>Observações</span><textarea name="notes" maxLength={2000} rows={3} defaultValue={value?.notes}/></label></>}
function BillFields({value}:{value:EnergyBill|null}){return <><div className="crm-form-grid"><Field name="reference_month" label="Mês de referência" type="month" required defaultValue={value?.reference_month}/><Field name="total_amount" label="Valor total (R$)" type="number" min="0" max="1000000000" step="0.01" required defaultValue={value?.total_amount}/><Field name="invoice_number" label="Número da fatura" defaultValue={value?.invoice_number}/><Field name="issue_date" label="Data de emissão" type="date" defaultValue={value?.issue_date}/><Field name="due_date" label="Data de vencimento" type="date" defaultValue={value?.due_date}/><label className="crm-field"><span>Bandeira tarifária</span><select name="tariff_flag" defaultValue={value?.tariff_flag??'not_informed'}>{Object.entries(tariffFlags).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><Field name="previous_reading" label="Leitura anterior" type="number" min="0" step="0.001" defaultValue={value?.previous_reading??''}/><Field name="current_reading" label="Leitura atual" type="number" min="0" step="0.001" defaultValue={value?.current_reading??''}/></div><label className="crm-field"><span>Observações da fatura</span><textarea name="notes" maxLength={2000} rows={3} defaultValue={value?.notes}/></label></>}
function SizingFields({months}:{months:number}){return <><p className="sizing-explanation">O cálculo usará a média dos {months} {months===1?'mês cadastrado':'meses mais recentes cadastrados'}, limitado a 12. Cada execução será preservada no histórico.</p><div className="crm-form-grid"><Field name="solar_irradiation_daily" label="Irradiação solar média (kWh/m²/dia)" type="number" min="1" max="8" step="0.01" required defaultValue="5.00"/><Field name="performance_ratio_percent" label="Desempenho global (%)" type="number" min="50" max="100" step="0.01" required defaultValue="80"/><Field name="module_power_w" label="Potência do módulo (W)" type="number" min="100" max="1000" step="1" required defaultValue="550"/><Field name="safety_margin_percent" label="Margem de segurança (%)" type="number" min="0" max="50" step="0.01" required defaultValue="10"/></div><label className="crm-field"><span>Observações do cálculo</span><textarea name="notes" maxLength={2000} rows={3}/></label><p className="muted">Estimativa comercial baseada em 30 dias por mês. Deve ser validada tecnicamente antes de qualquer proposta ou instalação.</p></>}
function KitSelectionFields({kits}:{kits:SolarKit[]}){return <><p className="sizing-explanation">A quantidade de kits será arredondada para cima até alcançar a potência do dimensionamento. O vínculo salvará uma cópia da composição atual.</p><label className="crm-field"><span>Kit comercial</span><select name="kit_id" required defaultValue=""><option value="" disabled>Selecione um kit</option>{kits.map(kit=><option key={kit.id} value={kit.id}>{kit.name} · {kit.dc_power_kwp.toLocaleString('pt-BR')} kWp · {kit.module_count.toLocaleString('pt-BR')} módulos</option>)}</select></label></>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...input}=props;return <label className="crm-field"><span>{label}</span><input {...input} maxLength={input.type==='number'||input.type==='date'||input.type==='month'?undefined:180}/></label>}
