'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Edit,FileText} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
import {contractItemCategories} from '@/modules/contracts/domain';
import {installationStatuses,installationTransitions,type InstallationDetail as Detail,type InstallationStatus} from '@/modules/installations/domain';
import {InstallationWorkspace,type WorkspaceTab} from './installation-workspace';
import {RelatedPostSales} from '@/components/post-sales/related';

const date=(value:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`)):'A definir';
const datetime=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value));
const historyLabels:Record<string,string>={created:'Instalação criada',updated:'Dados atualizados',responsible_changed:'Responsável alterado',schedule_changed:'Datas alteradas',start_changed:'Início alterado',status_changed:'Status alterado',completed:'Instalação concluída',cancelled:'Instalação cancelada',checklist_changed:'Checklist alterado',photo_added:'Foto adicionada',photo_removed:'Foto removida',document_added:'Documento adicionado',document_removed:'Documento removido',issue_created:'Pendência criada',issue_updated:'Pendência atualizada',issue_resolved:'Pendência resolvida',delivery_recorded:'Entrega registrada',delivery_updated:'Entrega atualizada'};
type Tab='summary'|'history'|WorkspaceTab;
export function InstallationDetail({initial,canEdit,canManage,canReadPostSales,owners}:{initial:Detail;canEdit:boolean;canManage:boolean;canReadPostSales:boolean;owners:Array<{id:string;name:string}>}){
 const [detail,setDetail]=useState(initial),[tab,setTab]=useState<Tab>('summary'),[next,setNext]=useState<InstallationStatus|null>(null),[statusDate,setStatusDate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setDetail(await api<Detail>(`/api/installations/${item.id}`));}
 const item=detail.installation;
 const available=installationTransitions[item.status].filter(status=>!['completed','cancelled'].includes(status)||canManage);
 async function changeStatus(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();if(!next)return;setBusy(true);setError('');
  const form=new FormData(e.currentTarget);
  try{await api(`/api/installations/${item.id}/status`,'POST',{status:next,version:item.version,scheduled_on:next==='scheduled'?statusDate:'',started_on:next==='in_progress'?statusDate:'',completed_on:next==='completed'?statusDate:'',final_notes:String(form.get('final_notes')??''),confirm_open_issues:form.get('confirm_open_issues')==='on'});setDetail(await api<Detail>(`/api/installations/${item.id}`));setNext(null);setStatusDate('');}
  catch(e){setError(errorMessage(e));}finally{setBusy(false);}
 }
 return <><div className="page-heading"><div><span className="eyebrow green">{item.installation_number}</span><h1>Instalação de {item.client_name}</h1><p>Contrato <Link href={`/contratos/${item.contract_id}`}>{item.contract_number}</Link>{item.opportunity_id&&<> · <Link href={`/oportunidades/${item.opportunity_id}`}>Oportunidade</Link></>}</p></div>{canEdit&&!['completed','cancelled'].includes(item.status)&&<Link className="button secondary" href={`/instalacoes/${item.id}/editar`}><Edit size={15}/>Editar instalação</Link>}</div>
  {error&&<p className="error-box" role="alert">{error}</p>}
  <div className="crm-tabs installation-tabs" aria-label="Seções da instalação">{([['summary','Resumo'],['checklist','Checklist'],['photos','Fotos'],['documents','Documentos'],['issues','Pendências'],['delivery','Entrega'],['history','Histórico']] as const).map(([key,label])=><button key={key} className={tab===key?'selected':''} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
  {tab==='summary'&&<><div className="installation-summary"><div><span>Status</span><strong>{installationStatuses[item.status]}</strong></div><div><span>Responsável</span><strong>{item.responsible_name}</strong></div><div><span>Agendada</span><strong>{date(item.scheduled_on)}</strong></div><div><span>Checklist</span><strong>{detail.checklist.filter(entry=>entry.checked).length} de {detail.checklist.length} · {detail.checklist.length?Math.round(detail.checklist.filter(entry=>entry.checked).length/detail.checklist.length*100):0}%</strong></div><div><span>Fotos e documentos</span><strong>{detail.files.filter(file=>file.kind==='photo').length} / {detail.files.filter(file=>file.kind==='document').length}</strong></div><div><span>Pendências abertas</span><strong>{detail.issues.filter(issue=>['open','in_progress'].includes(issue.status)).length}</strong></div></div>
  {(canEdit||canManage)&&available.length>0&&<section className="card installation-status-form"><div><h2>Atualizar andamento</h2><p>As mudanças ficam registradas no histórico do cliente e da instalação.</p></div><form onSubmit={changeStatus}><label className="crm-field"><span>Novo status</span><select aria-label="Novo status da instalação" value={next??''} onChange={e=>{setNext((e.target.value||null) as InstallationStatus|null);setStatusDate('');}}><option value="">Selecione</option>{available.map(status=><option key={status} value={status}>{installationStatuses[status]}</option>)}</select></label>{next&&['scheduled','in_progress','completed'].includes(next)&&<label className="crm-field"><span>{next==='scheduled'?'Data agendada':next==='in_progress'?'Data de início':'Data de conclusão'}</span><input aria-label="Data da mudança de status" type="date" value={statusDate} onChange={e=>setStatusDate(e.target.value)} required={next==='scheduled'&&!item.scheduled_on}/></label>}{next==='completed'&&<><label className="crm-field"><span>Observações finais</span><textarea name="final_notes" maxLength={4000} rows={3}/></label>{detail.checklist.some(entry=>!entry.checked)&&<p className="crm-notice">Checklist incompleto. O progresso atual será registrado na conclusão.</p>}{detail.issues.some(issue=>['open','in_progress'].includes(issue.status))&&<label className="crm-checks"><input type="checkbox" name="confirm_open_issues" required/>Confirmo a conclusão com pendências abertas.</label>}</>}<button className="button primary" disabled={busy||!next}>{busy?'Atualizando…':'Atualizar status'}</button></form></section>}
  <section className="card"><div className="card-heading"><div><span className="eyebrow blue">PLANEJAMENTO</span><h2>Dados da instalação</h2></div></div><dl className="crm-info-grid"><div><dt>Cliente</dt><dd><Link href={`/clientes/${item.client_id}`}>{item.client_name}</Link></dd></div><div><dt>Contrato</dt><dd><Link href={`/contratos/${item.contract_id}`}>{item.contract_number} · {item.contract_title}</Link></dd></div><div><dt>Endereço da instalação</dt><dd>{item.installation_address}</dd></div><div><dt>Equipe</dt><dd>{item.team_name||'Não informada'}</dd></div><div><dt>Data prevista</dt><dd>{date(item.planned_on)}</dd></div><div><dt>Data agendada</dt><dd>{date(item.scheduled_on)}</dd></div><div><dt>Início</dt><dd>{date(item.started_on)}</dd></div><div><dt>Conclusão</dt><dd>{date(item.completed_on)}</dd></div><div><dt>Criado por</dt><dd>{item.created_by_name}</dd></div><div><dt>Criado em</dt><dd>{datetime(item.created_at)}</dd></div><div><dt>Atualizado em</dt><dd>{datetime(item.updated_at)}</dd></div></dl>{item.notes&&<p className="installation-notes">{item.notes}</p>}</section>
  <section className="card"><div className="card-heading"><div><span className="eyebrow blue">CONTRATO</span><h2>Itens vendidos</h2><p className="muted">Composição consultada diretamente no contrato vinculado.</p></div></div><div className="table-scroll"><table><thead><tr><th>Item</th><th>Categoria</th><th>Quantidade</th></tr></thead><tbody>{detail.items.map(row=><tr key={row.id}><td>{row.description}{row.source_name&&<small> · {row.source_name}</small>}</td><td>{contractItemCategories[row.category as keyof typeof contractItemCategories]??row.category}</td><td>{row.quantity.toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div></section>
  {detail.completion&&<section className="card"><h2>Conclusão</h2><p>Concluída em {datetime(detail.completion.completed_at)} por {detail.completion.completed_by_name}. {detail.completion.had_open_issues?'Com pendências registradas.':'Sem pendências abertas.'}</p>{detail.completion.final_notes&&<p>{detail.completion.final_notes}</p>}</section>}{canReadPostSales&&<RelatedPostSales installationId={item.id}/>}</>}
  {tab==='history'&&<section className="card"><div className="card-heading"><div><span className="eyebrow blue">AUDITORIA</span><h2>Histórico da instalação</h2></div></div><div className="contract-history">{detail.history.map(entry=><article key={entry.id}><FileText size={15}/><div><strong>{historyLabels[entry.action]??entry.action}</strong><p>{entry.detail}</p></div><span>{entry.actor_name}</span><time>{datetime(entry.created_at)}</time></article>)}</div></section>}
  {tab!=='summary'&&tab!=='history'&&<InstallationWorkspace tab={tab} detail={detail} refresh={refresh} canEdit={canEdit} canManage={canManage} owners={owners}/>}
 </>;
}
