'use client';
import {useState} from 'react';
import Image from 'next/image';
import {Download,Trash2} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
import {Modal} from '@/components/crm/modal';
import {issuePriorities,issueStatuses,type InstallationDetail,type InstallationFile,type InstallationIssue} from '@/modules/installations/domain';

const datetime=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value));
const photoCategories={before:'Antes da instalação',equipment:'Equipamentos',roof:'Estrutura/telhado',during:'Durante a instalação',electrical:'Elétrica',modules:'Módulos',inverter:'Inversor',completed:'Instalação concluída',issue:'Pendência',other:'Outros'};
const documentCategories={installation:'Instalação',delivery:'Entrega/aceite',other:'Outros'};
export type WorkspaceTab='checklist'|'photos'|'documents'|'issues'|'delivery';
export function InstallationWorkspace({tab,detail,refresh,canEdit,canManage,owners}:{tab:WorkspaceTab;detail:InstallationDetail;refresh:()=>Promise<void>;canEdit:boolean;canManage:boolean;owners:Array<{id:string;name:string}>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState<InstallationFile|null>(null),[removing,setRemoving]=useState<InstallationFile|null>(null),[issueForm,setIssueForm]=useState<InstallationIssue|'new'|null>(null);
 const installation=detail.installation,finished=['completed','cancelled'].includes(installation.status),canUpload=canEdit&&installation.status!=='cancelled';
 const photos=detail.files.filter(file=>file.kind==='photo'),documents=detail.files.filter(file=>file.kind==='document');
 const completed=detail.checklist.filter(entry=>entry.checked).length,total=detail.checklist.length,percent=total?Math.round(completed/total*100):0;
 const open=detail.issues.filter(issue=>['open','in_progress'].includes(issue.status)),resolved=detail.issues.filter(issue=>issue.status==='resolved');
 const overdue=open.filter(issue=>issue.due_on&&issue.due_on<new Date().toISOString().slice(0,10));
 async function run(work:()=>Promise<void>,message:string){setBusy(true);setError('');setNotice('');try{await work();await refresh();setNotice(message);}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function checklist(event:React.FormEvent<HTMLFormElement>,id:string,version:number){event.preventDefault();const form=new FormData(event.currentTarget);await run(async()=>{await api(`/api/installation-checklist/${id}`,'PUT',{checked:form.get('checked')==='on',notes:String(form.get('notes')??''),version});},'Checklist atualizado.');}
 async function upload(event:React.FormEvent<HTMLFormElement>,kind:'photo'|'document'){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);form.set('installation_id',installation.id);form.set('kind',kind);await run(async()=>{const response=await fetch('/api/installation-files',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.error??'Não foi possível enviar o arquivo.');formElement.reset();},kind==='photo'?'Foto adicionada.':'Documento adicionado.');}
 async function remove(file:InstallationFile){await run(async()=>{await api(`/api/installation-files/${file.id}`,'DELETE',{version:file.version});setRemoving(null);},'Arquivo removido.');}
 async function issue(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),current=issueForm==='new'?null:issueForm;await run(async()=>{await api(`/api/installation-issues${current?'/'+current.id:''}`,current?'PUT':'POST',{installation_id:installation.id,title:String(form.get('title')??''),description:String(form.get('description')??''),status:String(form.get('status')??'open'),priority:String(form.get('priority')??'medium'),responsible_user_id:String(form.get('responsible_user_id')??installation.responsible_user_id),due_on:String(form.get('due_on')??''),resolution_notes:String(form.get('resolution_notes')??''),...(current?{version:current.version}:{})});setIssueForm(null);},'Pendência registrada.');}
 async function delivery(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(async()=>{await api(`/api/installations/${installation.id}/delivery`,'POST',{delivered_at:new Date(String(form.get('delivered_at'))).toISOString(),delivered_by:String(form.get('delivered_by')),recipient_name:String(form.get('recipient_name')),notes:String(form.get('notes')??''),confirmed:form.get('confirmed')==='on',version:detail.delivery?.version});},'Entrega confirmada.');}
 return <>{error&&<p className="error-box" role="alert">{error}</p>}{notice&&<p className="crm-notice" role="status">{notice}</p>}
 {tab==='checklist'&&<section className="card"><div className="card-heading"><div><h2>Checklist</h2><p>{completed} de {total} concluídos · {percent}%</p></div></div><progress className="installation-progress" value={completed} max={total} aria-label="Progresso do checklist"/><div className="installation-checklist">{detail.checklist.map(entry=><form key={entry.id+'-'+entry.version} onSubmit={event=>checklist(event,entry.id,entry.version)}><label className="crm-checks"><input name="checked" type="checkbox" defaultChecked={entry.checked} disabled={!canEdit||finished}/><strong>{entry.label}</strong></label><label className="crm-field"><span>Observação</span><input name="notes" defaultValue={entry.notes} maxLength={2000} disabled={!canEdit||finished}/></label><small>{entry.checked&&entry.checked_at?`Marcado por ${entry.checked_by_name} em ${datetime(entry.checked_at)}`:'Ainda não concluído'}</small>{canEdit&&!finished&&<button className="button secondary" disabled={busy}>Salvar item</button>}</form>)}</div></section>}
 {tab==='photos'&&<section className="card"><h2>Fotos da instalação</h2><p className="muted">Arquivos privados, até 10 MB cada.</p>{canUpload&&<FileUpload kind="photo" categories={photoCategories} busy={busy} submit={upload}/>}<div className="installation-gallery">{photos.map(file=><article key={file.id}><button type="button" onClick={()=>setPreview(file)} aria-label={`Ampliar ${file.name}`}><Image src={`/api/installation-files/${file.id}/file`} alt={file.description||file.name} width={320} height={220} unoptimized/></button><div><strong>{file.name}</strong><small>{photoCategories[file.category as keyof typeof photoCategories]??file.category} · {file.created_by_name} · {datetime(file.created_at)}</small>{file.description&&<p>{file.description}</p>}<div className="installation-file-actions"><a className="button secondary" href={`/api/installation-files/${file.id}/file?download=1`} download><Download size={15}/>Baixar</a>{canManage&&<button className="button danger" onClick={()=>setRemoving(file)}><Trash2 size={15}/>Excluir</button>}</div></div></article>)}</div>{photos.length===0&&<p className="muted">Nenhuma foto registrada.</p>}</section>}
 {tab==='documents'&&<section className="card"><h2>Documentos da instalação</h2><p className="muted">Arquivos privados, até 10 MB cada.</p>{canUpload&&<FileUpload kind="document" categories={documentCategories} busy={busy} submit={upload}/>}<div className="installation-documents">{documents.map(file=><article key={file.id}><div><strong>{file.name}</strong><small>{file.original_filename} · {Math.ceil(file.file_size/1024)} KB · {file.created_by_name} · {datetime(file.created_at)}</small>{file.description&&<p>{file.description}</p>}</div><a className="button secondary" href={`/api/installation-files/${file.id}/file`} download><Download size={15}/>Baixar</a>{canManage&&<button className="button danger" onClick={()=>setRemoving(file)}><Trash2 size={15}/>Excluir</button>}</article>)}</div>{documents.length===0&&<p className="muted">Nenhum documento anexado.</p>}</section>}
 {tab==='issues'&&<section className="card"><div className="card-heading"><div><h2>Pendências</h2><p>{open.length} abertas · {resolved.length} resolvidas · {overdue.length} vencidas</p></div>{canEdit&&!finished&&<button className="button primary" onClick={()=>setIssueForm('new')}>Nova pendência</button>}</div><div className="installation-issues">{detail.issues.map(entry=><article key={entry.id}><div><span className={`document-status ${entry.status}`}>{issueStatuses[entry.status]}</span><span className="document-status">{issuePriorities[entry.priority]}</span><h3>{entry.title}</h3><p>{entry.description}</p><small>Responsável: {entry.responsible_name} · Criado por {entry.created_by_name} em {datetime(entry.created_at)}{entry.due_on?` · Prazo ${entry.due_on}`:''}</small>{entry.resolution_notes&&<p>Resolução: {entry.resolution_notes}</p>}</div>{canEdit&&installation.status!=='cancelled'&&<button className="button secondary" onClick={()=>setIssueForm(entry)}>Editar</button>}</article>)}</div>{detail.issues.length===0&&<p className="muted">Nenhuma pendência registrada.</p>}</section>}
 {tab==='delivery'&&<section className="card"><h2>Entrega e aceite</h2>{detail.delivery&&<p>Entregue em {datetime(detail.delivery.delivered_at)} por {detail.delivery.delivered_by_name} a {detail.delivery.recipient_name}. {detail.delivery.notes}</p>}{installation.status!=='completed'&&<p className="muted">Conclua a instalação antes de registrar a entrega.</p>}{canManage&&installation.status==='completed'&&<form className="crm-form installation-delivery-form" onSubmit={delivery}><div className="contract-form-grid"><label className="crm-field"><span>Data e hora da entrega</span><input name="delivered_at" type="datetime-local" required defaultValue={detail.delivery?.delivered_at?new Date(detail.delivery.delivered_at).toISOString().slice(0,16):''}/></label><label className="crm-field"><span>Responsável pela entrega</span><select name="delivered_by" defaultValue={detail.delivery?.delivered_by??installation.responsible_user_id}>{owners.map(owner=><option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label><label className="crm-field"><span>Quem recebeu</span><input name="recipient_name" required minLength={2} maxLength={180} defaultValue={detail.delivery?.recipient_name??''}/></label></div><label className="crm-field"><span>Observações</span><textarea name="notes" maxLength={2000} defaultValue={detail.delivery?.notes??''}/></label><label className="crm-checks"><input name="confirmed" type="checkbox" required defaultChecked={detail.delivery?.confirmed??false}/>Confirmo que a entrega foi realizada e recebida.</label><button className="button primary" disabled={busy}>{detail.delivery?'Atualizar entrega':'Registrar entrega'}</button></form>}</section>}
 {preview&&<Modal title={preview.name} onClose={()=>setPreview(null)}><Image className="installation-preview" src={`/api/installation-files/${preview.id}/file`} alt={preview.description||preview.name} width={900} height={700} unoptimized/><p>{preview.description}</p><a className="button secondary" href={`/api/installation-files/${preview.id}/file?download=1`} download>Baixar foto</a></Modal>}
 {removing&&<Modal title="Excluir arquivo?" onClose={()=>setRemoving(null)}><p>O arquivo {removing.name} será removido do armazenamento privado. O evento ficará no histórico.</p><div className="crm-form-actions"><button className="button secondary" onClick={()=>setRemoving(null)}>Cancelar</button><button className="button danger" disabled={busy} onClick={()=>remove(removing)}>Excluir arquivo</button></div></Modal>}
 {issueForm&&<Modal title={issueForm==='new'?'Nova pendência':'Editar pendência'} onClose={()=>setIssueForm(null)}><form className="crm-form" onSubmit={issue}><label className="crm-field"><span>Título</span><input name="title" required minLength={2} maxLength={180} defaultValue={issueForm==='new'?'':issueForm.title}/></label><label className="crm-field"><span>Descrição</span><textarea name="description" maxLength={4000} defaultValue={issueForm==='new'?'':issueForm.description}/></label><div className="contract-form-grid"><label className="crm-field"><span>Status</span><select name="status" defaultValue={issueForm==='new'?'open':issueForm.status} disabled={issueForm==='new'}>{Object.entries(issueStatuses).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label className="crm-field"><span>Prioridade</span><select name="priority" defaultValue={issueForm==='new'?'medium':issueForm.priority}>{Object.entries(issuePriorities).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label className="crm-field"><span>Responsável</span><select name="responsible_user_id" defaultValue={issueForm==='new'?installation.responsible_user_id:issueForm.responsible_user_id}>{owners.map(owner=><option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label><label className="crm-field"><span>Prazo</span><input type="date" name="due_on" defaultValue={issueForm==='new'?'':issueForm.due_on??''}/></label></div><label className="crm-field"><span>Observação da resolução</span><textarea name="resolution_notes" maxLength={2000} defaultValue={issueForm==='new'?'':issueForm.resolution_notes}/></label><div className="crm-form-actions"><button type="button" className="button secondary" onClick={()=>setIssueForm(null)}>Cancelar</button><button className="button primary" disabled={busy}>Salvar pendência</button></div></form></Modal>}
 </>;
}
function FileUpload({kind,categories,busy,submit}:{kind:'photo'|'document';categories:Record<string,string>;busy:boolean;submit:(event:React.FormEvent<HTMLFormElement>,kind:'photo'|'document')=>Promise<void>}){
 return <form className="installation-upload crm-form" onSubmit={event=>submit(event,kind)}><div className="contract-form-grid"><label className="crm-field"><span>Nome</span><input name="name" required minLength={2} maxLength={180}/></label><label className="crm-field"><span>Categoria</span><select name="category">{Object.entries(categories).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label className="crm-field"><span>Arquivo</span><input type="file" name="file" required accept={kind==='photo'?'.png,.jpg,.jpeg,.webp':'.pdf,.png,.jpg,.jpeg,.webp,.xlsx,.xls,.csv,.docx,.doc,.txt'}/></label></div><label className="crm-field"><span>Legenda ou descrição</span><input name="description" maxLength={2000}/></label><button className="button primary" disabled={busy}>{busy?'Enviando…':kind==='photo'?'Adicionar foto':'Adicionar documento'}</button></form>;
}
