import {test,expect,type Page} from '@playwright/test';

const password='Peclat teste seguro 2026';
async function login(page:Page,email:string,secret=password){await page.goto('/login');await page.getByLabel('E-mail profissional').fill(email);await page.getByLabel('Senha',{exact:true}).fill(secret);await page.getByRole('button',{name:'Entrar na plataforma'}).click();await expect(page).toHaveURL(/\/$/);}
async function createUser(page:Page,name:string,email:string,role:string){await page.getByRole('button',{name:'Novo usuário'}).click();const dialog=page.getByRole('dialog',{name:'Novo usuário'});await dialog.getByLabel('Nome').fill(name);await dialog.getByLabel('E-mail').fill(email);await dialog.getByLabel('Função').selectOption(role);await dialog.getByRole('button',{name:'Salvar usuário'}).click();const credential=page.getByLabel('Credencial temporária');await expect(credential).toContainText(name);const secret=(await credential.locator('code').textContent())!;await credential.getByRole('button',{name:'Fechar'}).click();return secret;}

test('admin cria acessos internos, integra equipe e bloqueia gestão por gerente',async({page,browser})=>{
 test.setTimeout(90000);await page.setViewportSize({width:1440,height:900});await login(page,'contracts@e2e.local');
 await page.goto('/configuracoes');await page.getByRole('link',{name:/Usuários e acessos/}).click();await expect(page.getByRole('heading',{name:'Usuários e acessos'})).toBeVisible();
 const sellerPassword=await createUser(page,'Vendedora interna E2E','internal-seller@e2e.local','seller');
 const managerPassword=await createUser(page,'Gerente interno E2E','internal-manager@e2e.local','manager');
 await page.goto('/equipe');await page.getByRole('button',{name:'Criar equipe'}).click();const teamDialog=page.getByRole('dialog',{name:'Criar equipe'});await teamDialog.getByLabel('Nome da equipe').fill('Equipe usuários internos E2E');await teamDialog.getByLabel('Gerente comercial').selectOption({label:'Gerente interno E2E'});await teamDialog.getByRole('button',{name:'Salvar equipe'}).click();await page.getByLabel('Adicionar vendedor à Equipe usuários internos E2E').selectOption({label:'Vendedora interna E2E'});await expect(page.getByText('Vendedor adicionado.')).toBeVisible();
 await page.goto('/configuracoes/usuarios');const row=page.locator('.user-row').filter({hasText:'internal-seller@e2e.local'});await row.getByRole('button',{name:'Editar'}).click();const edit=page.getByRole('dialog',{name:'Editar usuário'});await edit.getByLabel('Status').selectOption('false');await edit.getByRole('button',{name:'Salvar usuário'}).click();await expect(row).toContainText('Inativo');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 const inactive=await browser.newPage();const manager=await browser.newPage();try{await inactive.goto('/login');await inactive.getByLabel('E-mail profissional').fill('internal-seller@e2e.local');await inactive.getByLabel('Senha',{exact:true}).fill(sellerPassword);await inactive.getByRole('button',{name:'Entrar na plataforma'}).click();await expect(inactive.locator('.error-box')).toContainText('Organização, e-mail ou senha inválidos.');await login(manager,'internal-manager@e2e.local',managerPassword);await manager.goto('/configuracoes/usuarios');await expect(manager.getByRole('heading',{name:'Acesso restrito'})).toBeVisible();}finally{await inactive.close();await manager.close();}
});
