import {test,expect,type APIRequestContext,type Page} from '@playwright/test';
const origin='http://localhost:3100',password='Peclat teste seguro 2026';
type Person={id:string;name:string;email:string};
async function login(page:Page,name:string){const response=await page.request.post('/api/auth/login',{headers:{origin},data:{organization:'peclat-solar',email:`${name}@e2e.local`,password}});expect(response.status()).toBe(200);await page.goto('/');}
async function post<T>(request:APIRequestContext,path:string,data:Record<string,unknown>){const response=await request.post(path,{headers:{origin},data});expect(response.ok(),`${path}: ${await response.text()}`).toBeTruthy();return response.json() as Promise<T>;}
async function fits(page:Page){for(const viewport of [{width:1440,height:900},{width:390,height:844}]){await page.setViewportSize(viewport);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}}

test('metas e desempenho respeitam administrador, equipe do gerente e vendedor',async({page,browser})=>{
 test.setTimeout(120000);await login(page,'goals-admin');
 const overview=await (await page.request.get('/api/commercial-teams')).json() as {members:Person[]};const person=(name:string)=>overview.members.find(item=>item.email===`${name}@e2e.local`)!;
 const manager=person('goals-manager'),a=person('goals-a'),b=person('goals-b'),outside=person('goals-outside');expect(manager).toBeTruthy();expect(a).toBeTruthy();expect(b).toBeTruthy();expect(outside).toBeTruthy();
 const team=await post<{id:string}>(page.request,'/api/commercial-teams',{name:'Equipe metas E2E',manager_user_id:manager.id});for(const seller of [a,b])await post(page.request,`/api/commercial-teams/${team.id}/members`,{user_id:seller.id,action:'add'});
 for(const [name,owner] of [['Cliente meta A',a],['Cliente meta B',b],['Cliente meta externo',outside]] as const)await post(page.request,'/api/customers',{name,owner_id:owner.id,person_type:'PF'});
 const lead=await post<{id:string}>(page.request,'/api/leads',{name:'Lead oportunidade meta',owner_id:a.id,person_type:'PF'});const opportunity=await post<{id:string;version:number}>(page.request,'/api/opportunities',{title:'Oportunidade meta ganha',lead_id:lead.id,owner_id:a.id,estimated_value:12000});await post(page.request,`/api/opportunities/${opportunity.id}/win`,{version:opportunity.version});
 await post(page.request,'/api/commercial-goals',{target_kind:'seller',seller_user_id:a.id,team_id:null,metric:'opportunities_won',period:'monthly',starts_on:'2026-09-01',ends_on:'2026-09-30',target_value:1});
 await post(page.request,'/api/commercial-goals',{target_kind:'team',seller_user_id:null,team_id:team.id,metric:'new_customers',period:'monthly',starts_on:'2026-09-01',ends_on:'2026-09-30',target_value:2});
 await page.goto('/desempenho');await expect(page.getByRole('heading',{name:'Metas e desempenho'})).toBeVisible();await expect(page.getByRole('heading',{name:'Oportunidades ganhas',exact:true})).toBeVisible();await expect(page.locator('.goal-card').filter({hasText:'Oportunidades ganhas'}).getByText('100% atingido',{exact:false})).toBeVisible();await expect(page.getByRole('cell').filter({hasText:a.name})).toBeVisible();await expect(page.getByRole('cell').filter({hasText:outside.name})).toBeVisible();await fits(page);
 const managerPage=await browser.newPage(),sellerPage=await browser.newPage(),outsidePage=await browser.newPage();try{
  await login(managerPage,'goals-manager');await managerPage.goto('/desempenho');await expect(managerPage.locator('.goal-card').filter({hasText:'Equipe metas E2E'})).toBeVisible();await expect(managerPage.getByRole('cell').filter({hasText:a.name})).toBeVisible();await expect(managerPage.getByRole('cell').filter({hasText:b.name})).toBeVisible();await expect(managerPage.getByRole('cell').filter({hasText:outside.name})).toHaveCount(0);await expect(managerPage.getByRole('button',{name:'Criar meta'})).toBeVisible();await fits(managerPage);
  await login(sellerPage,'goals-a');await sellerPage.goto('/desempenho');await expect(sellerPage.getByRole('cell').filter({hasText:a.name})).toBeVisible();await expect(sellerPage.getByRole('cell').filter({hasText:b.name})).toHaveCount(0);await expect(sellerPage.locator('.goal-card')).toHaveCount(1);await expect(sellerPage.getByRole('button',{name:'Criar meta'})).toHaveCount(0);await fits(sellerPage);
  await login(outsidePage,'goals-outside');await outsidePage.goto('/desempenho');await expect(outsidePage.getByText('Nenhuma meta visível cadastrada.')).toBeVisible();await expect(outsidePage.getByRole('cell').filter({hasText:outside.name})).toBeVisible();await expect(outsidePage.getByRole('cell').filter({hasText:a.name})).toHaveCount(0);
 }finally{await managerPage.close();await sellerPage.close();await outsidePage.close();}
});
