import {test,expect,type Page} from '@playwright/test';
const password='Peclat teste seguro 2026';
async function login(page:Page){await page.goto('/login');await page.getByLabel('E-mail profissional').fill('contracts@e2e.local');await page.getByLabel('Senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar na plataforma'}).click();await expect(page.getByRole('heading',{name:'Sua operação, conectada.'})).toBeVisible();}
test('contrato percorre venda, parcela, pagamento e documento assinado',async({page})=>{
 await login(page);await page.goto('/clientes/novo');await page.getByLabel('Nome *',{exact:true}).fill('Cliente Contrato E2E');await page.getByLabel('E-mail',{exact:true}).fill('contrato.e2e@example.com');await page.getByRole('button',{name:'Criar cadastro'}).click();await expect(page.getByRole('heading',{name:'Cliente Contrato E2E',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Criar oportunidade',exact:true}).click();await page.getByLabel('Título da oportunidade').fill('Venda Solar Contrato E2E');await page.getByLabel('Valor estimado (R$)').fill('25500');await page.getByRole('button',{name:'Criar oportunidade',exact:true}).click();await expect(page.getByRole('heading',{name:'Venda Solar Contrato E2E',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Contratos',exact:true}).click();await page.getByRole('link',{name:'Novo contrato'}).click();await page.getByLabel('Título do contrato').fill('Contrato fotovoltaico E2E');await page.getByLabel('Descrição').fill('Sistema solar completo');await page.getByLabel('Valor unitário').fill('25500');await page.getByLabel('Entrada').fill('500');await page.getByLabel('Primeiro vencimento').fill('2026-10-20');await page.getByRole('button',{name:'Criar contrato'}).click();
 await expect(page.getByRole('heading',{name:'Contrato fotovoltaico E2E'})).toBeVisible();await expect(page.getByText(/PECLAT-\d{4}-000001/).first()).toBeVisible();await page.getByRole('button',{name:'Registrar pagamento'}).nth(1).click();const payment=page.getByRole('dialog',{name:'Registrar pagamento'});await payment.getByLabel('Valor recebido').fill('5000');await payment.getByLabel('Data e hora').fill('2026-09-15T14:30');await payment.getByLabel('Referência').fill('PIX-E2E-001');await payment.getByRole('button',{name:'Registrar',exact:true}).click();await expect(page.getByText('R$ 20.000,00',{exact:true})).toBeVisible();await page.getByLabel('Status do contrato').selectOption('sent');await expect(page.getByLabel('Status do contrato')).toHaveValue('sent');await expect(page.getByText('Contrato enviado',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Anexar PDF'}).click();const upload=page.getByRole('dialog',{name:'Anexar documento em PDF'});await upload.getByLabel('Nome do documento').fill('Contrato comercial assinado');await upload.getByLabel('Valor (R$)').fill('25500');await upload.getByLabel('Validade').fill('2026-12-31');await upload.getByLabel('Arquivo PDF').setInputFiles({name:'contrato-e2e.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\ncontract e2e\n%%EOF')});await upload.getByRole('button',{name:'Anexar PDF'}).click();await expect(page.getByRole('status').filter({hasText:'PDF anexado'})).toBeVisible();
 const card=page.locator('.document-card').filter({hasText:'Contrato comercial assinado'});await card.getByRole('button',{name:'Assinatura'}).click();const signature=page.getByRole('dialog',{name:'Registrar assinatura'});await signature.getByLabel('Situação').selectOption('signed');await signature.getByLabel('Assinado por').fill('Cliente Contrato E2E');await signature.getByLabel('Data e hora da assinatura').fill('2026-09-15T15:00');await signature.getByRole('button',{name:'Salvar registro'}).click();await expect(card.getByText('Assinado',{exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await expect(page.getByRole('heading',{name:'Contrato fotovoltaico E2E'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
