import {test,expect,type Page} from '@playwright/test';
const password='Peclat teste seguro 2026';
async function login(page:Page){await page.goto('/login');await page.getByLabel('E-mail profissional').fill('documents@e2e.local');await page.getByLabel('Senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar na plataforma'}).click();await expect(page.getByRole('heading',{name:'Sua operação, conectada.'})).toBeVisible();}

test('orçamento PDF é anexado, enviado por e-mail e acompanhado no cliente e na oportunidade',async({page})=>{
 await login(page);await page.goto('/clientes/novo');await page.getByLabel('Nome *',{exact:true}).fill('Cliente Documento E2E');await page.getByLabel('E-mail',{exact:true}).fill('cliente.documento@example.com');await page.getByRole('button',{name:'Criar cadastro'}).click();await expect(page.getByRole('heading',{name:'Cliente Documento E2E',exact:true})).toBeVisible();const customerUrl=page.url();
 await page.getByRole('link',{name:'Criar oportunidade',exact:true}).click();await page.getByLabel('Título da oportunidade').fill('Projeto Documento E2E');await page.getByLabel('Valor estimado (R$)').fill('28750');await page.getByRole('button',{name:'Criar oportunidade',exact:true}).click();await expect(page.getByRole('heading',{name:'Projeto Documento E2E',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Documentos',exact:true}).click();await page.getByRole('button',{name:'Anexar PDF'}).click();const upload=page.getByRole('dialog',{name:'Anexar orçamento em PDF'});await upload.getByLabel('Nome do documento').fill('Orçamento Solar E2E');await upload.getByLabel('Valor do orçamento (R$)').fill('28750');await upload.getByLabel('Validade').fill('2026-10-31');await upload.getByLabel('Observação').fill('Orçamento preparado manualmente.');await upload.getByLabel('Arquivo PDF').setInputFiles({name:'orcamento-solar-e2e.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF')});await upload.getByRole('button',{name:'Anexar PDF'}).click();
 await expect(page.getByRole('status').filter({hasText:'PDF anexado'})).toBeVisible();const card=page.locator('.document-card').filter({hasText:'Orçamento Solar E2E'});await expect(card.getByText('R$ 28.750,00',{exact:true})).toBeVisible();
 await card.getByRole('button',{name:'Enviar por e-mail'}).click();const email=page.getByRole('dialog',{name:'Enviar orçamento por e-mail'});await expect(email.getByLabel('E-mail do cliente')).toHaveValue('cliente.documento@example.com');await email.getByLabel('Assunto').fill('Orçamento personalizado Peclat');await email.getByLabel('Mensagem').fill('Olá, segue o orçamento preparado para seu projeto.');await email.getByRole('button',{name:'Enviar orçamento'}).click();await expect(page.getByRole('status').filter({hasText:'Orçamento enviado por e-mail'})).toBeVisible();await expect(card.locator('.document-status')).toHaveText('Enviado');
 const download=page.waitForEvent('download');await card.getByRole('link',{name:'Baixar PDF'}).click();const saved=await download;expect(saved.suggestedFilename()).toBe('orcamento-solar-e2e.pdf');
 await card.getByRole('button',{name:'Editar dados'}).click();const edit=page.getByRole('dialog',{name:'Editar dados do documento'});await edit.getByLabel('Valor do orçamento (R$)').fill('27990');await edit.getByLabel('Observação').fill('Condição revisada manualmente.');await edit.getByRole('button',{name:'Salvar alterações'}).click();await expect(page.getByText('R$ 27.990,00',{exact:true})).toBeVisible();
 await card.getByRole('button',{name:'Histórico'}).click();const history=page.getByRole('dialog',{name:/Histórico · Orçamento Solar E2E/});await expect(history.getByText('cliente.documento@example.com',{exact:false})).toBeVisible();await expect(history.getByText('Orçamento personalizado Peclat',{exact:false})).toBeVisible();await expect(history.getByText('Documento criado')).toBeVisible();await expect(history.getByText('Status alterado')).toBeVisible();await expect(history.getByText('Dados atualizados')).toBeVisible();await history.getByRole('button',{name:'Fechar janela'}).click();
 await page.getByRole('button',{name:'Histórico e atividades'}).click();await expect(page.getByText('Orçamento enviado por e-mail',{exact:false})).toBeVisible();await page.goto(customerUrl+'?tab=documents');await expect(page.locator('.document-card').filter({hasText:'Projeto Documento E2E'})).toBeVisible();await page.getByRole('button',{name:'Atividades',exact:true}).click();await expect(page.getByText('Orçamento enviado por e-mail',{exact:true})).toBeVisible();
 await page.goto(customerUrl+'?tab=documents');await page.setViewportSize({width:390,height:844});await expect(page.locator('.document-card').filter({hasText:'Orçamento Solar E2E'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/document-email-mobile.png',fullPage:true});
});
