import {test,expect,type Page} from '@playwright/test';
const password='Peclat teste seguro 2026';
async function login(page:Page){await page.goto('/login');await page.getByLabel('E-mail profissional').fill('admin@e2e.local');await page.getByLabel('Senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar na plataforma'}).click();await expect(page.getByRole('heading',{name:'Sua operação, conectada.'})).toBeVisible();}

test('cliente recebe unidade, histórico de consumo e fatura pelo navegador',async({page})=>{
 await login(page);await page.getByRole('link',{name:'Equipamentos e kits',exact:true}).click();await expect(page.getByRole('heading',{name:'Equipamentos e kits solares.'})).toBeVisible();
 await page.getByRole('button',{name:'Novo equipamento'}).click();let equipment=page.getByRole('dialog',{name:'Novo equipamento'});await equipment.getByLabel('Nome').fill('Módulo E2E 550 W');await equipment.getByLabel('Fabricante').fill('Peclat Teste');await equipment.getByLabel('Código interno').fill('MOD-E2E-550');await equipment.getByLabel('Potência nominal (W)').fill('550');await equipment.getByRole('button',{name:'Salvar'}).click();await expect(page.getByText('Módulo E2E 550 W',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Novo equipamento'}).click();equipment=page.getByRole('dialog',{name:'Novo equipamento'});await equipment.getByLabel('Categoria').selectOption('inverter');await equipment.getByLabel('Nome').fill('Inversor E2E 6 kW');await equipment.getByLabel('Código interno').fill('INV-E2E-6000');await equipment.getByLabel('Potência nominal (W)').fill('6000');await equipment.getByLabel('Número de fases').fill('2');await equipment.getByRole('button',{name:'Salvar'}).click();
 await page.getByRole('button',{name:'Kits comerciais',exact:true}).click();await page.getByRole('button',{name:'Novo kit'}).click();const kit=page.getByRole('dialog',{name:'Novo kit comercial'});await kit.getByLabel('Nome do kit').fill('Kit E2E 6,05 kWp');await kit.getByLabel('Código interno').fill('KIT-E2E-605');await kit.getByLabel('Quantidade de Módulo E2E 550 W').fill('11');await kit.getByLabel('Quantidade de Inversor E2E 6 kW').fill('1');await kit.getByRole('button',{name:'Salvar'}).click();await expect(page.getByText('6,05 kWp CC',{exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/solar-catalog-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});
 await page.goto('/clientes/novo');await page.getByLabel('Nome *',{exact:true}).fill('Cliente Energia E2E');await page.getByRole('button',{name:'Criar cadastro'}).click();await expect(page.getByRole('heading',{name:'Cliente Energia E2E',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Consumo e faturas',exact:true}).click();await expect(page.getByRole('heading',{name:'Nenhuma unidade consumidora'})).toBeVisible();await page.getByRole('button',{name:'Cadastrar unidade'}).click();
 const unit=page.getByRole('dialog',{name:'Nova unidade consumidora'});await unit.getByLabel('Nome da unidade').fill('Casa principal');await unit.getByLabel('Número da unidade consumidora').fill('UC-E2E-400');await unit.getByLabel('Distribuidora').fill('Cemig');await unit.getByLabel('Titular da fatura').fill('Cliente Energia E2E');await unit.getByLabel('Tipo de ligação').selectOption('two_phase');await unit.getByRole('button',{name:'Salvar'}).click();await expect(page.getByRole('status').filter({hasText:'Unidade consumidora cadastrada'})).toBeVisible();
 await page.getByRole('button',{name:'Adicionar consumo'}).click();const consumption=page.getByRole('dialog',{name:'Adicionar consumo mensal'});await consumption.getByLabel('Mês de referência').fill('2026-08');await consumption.getByLabel('Consumo (kWh)').fill('640');await consumption.getByLabel('Energia injetada (kWh)').fill('32');await consumption.getByLabel('Dias faturados').fill('30');await consumption.getByRole('button',{name:'Salvar'}).click();await expect(page.getByRole('cell',{name:'640 kWh',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Adicionar fatura'}).click();const bill=page.getByRole('dialog',{name:'Adicionar fatura'});await bill.getByLabel('Mês de referência').fill('2026-08');await bill.getByLabel('Valor total (R$)').fill('712.45');await bill.getByLabel('Data de emissão').fill('2026-08-03');await bill.getByLabel('Data de vencimento').fill('2026-08-15');await bill.getByLabel('Bandeira tarifária').selectOption('green');await bill.getByRole('button',{name:'Salvar'}).click();await expect(page.getByText('R$ 712,45',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Calcular dimensionamento'}).click();const sizing=page.getByRole('dialog',{name:'Novo dimensionamento solar'});await expect(sizing.getByText(/mês cadastrado/)).toBeVisible();await sizing.getByLabel('Irradiação solar média (kWh/m²/dia)').fill('5');await sizing.getByLabel('Desempenho global (%)').fill('80');await sizing.getByLabel('Potência do módulo (W)').fill('550');await sizing.getByLabel('Margem de segurança (%)').fill('10');await sizing.getByRole('button',{name:'Calcular e salvar'}).click();const result=page.locator('.sizing-result');await expect(result.getByText('11',{exact:true})).toBeVisible();await expect(result.getByText('6,05 kWp',{exact:true})).toBeVisible();await expect(page.getByRole('status').filter({hasText:'salvo no histórico'})).toBeVisible();
 await page.getByRole('button',{name:'Vincular kit'}).click();const selection=page.getByRole('dialog',{name:'Vincular kit ao dimensionamento'});await selection.getByLabel('Kit comercial').selectOption({index:1});await selection.getByRole('button',{name:'Vincular kit'}).click();await expect(page.locator('.linked-kit').getByRole('heading',{name:'Kit E2E 6,05 kWp'})).toBeVisible();await expect(page.locator('.linked-kit').getByText('1',{exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await expect(page.getByText('Em formação',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/energy-customer-mobile.png',fullPage:true});
});
