import {test,expect,type Page} from '@playwright/test';
const origin='http://localhost:3100',password='Peclat teste seguro 2026';
async function login(page:Page,email='seller@e2e.local'){await page.goto('/login');await page.getByLabel('E-mail profissional').fill(email);await page.getByLabel('Senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar na plataforma'}).click();await expect(page.getByRole('heading',{name:'Sua operação, conectada.'})).toBeVisible();}
test('lead vira oportunidade, recebe nota e tarefa e avança no pipeline até ganha',async({page})=>{
 await login(page);await page.goto('/leads/novo');await page.getByLabel('Nome *',{exact:true}).fill('Lead Operação E2E');await page.getByRole('button',{name:'Criar cadastro'}).click();await page.getByRole('link',{name:'Criar oportunidade',exact:true}).click();await expect(page.getByRole('heading',{name:'Nova oportunidade',exact:true})).toBeVisible();
 await page.getByLabel('Título da oportunidade').fill('Solar Operação E2E');await page.getByLabel('Valor estimado (R$)').fill('42000');await page.getByLabel('Probabilidade (%)').fill('30');await page.getByLabel('Previsão de fechamento').fill('2026-12-15');await page.getByRole('button',{name:'Criar oportunidade',exact:true}).click();await expect(page.getByRole('heading',{name:'Solar Operação E2E',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Notas',exact:true}).click();await page.getByLabel('Nova nota interna').fill('Proposta em avaliação pelo cliente.');await page.getByRole('button',{name:'Adicionar nota',exact:true}).click();await expect(page.getByText('Proposta em avaliação pelo cliente.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Tarefas',exact:true}).click();await page.getByRole('button',{name:'Nova tarefa',exact:true}).click();await page.getByLabel('Título da tarefa').fill('Retornar negociação E2E');await page.getByLabel('Data de vencimento').fill('2026-09-14');await page.getByLabel('Horário opcional (Brasília)').fill('15:00');await page.getByRole('button',{name:'Salvar tarefa'}).click();await expect(page.getByRole('heading',{name:'Retornar negociação E2E'})).toBeVisible();
 await page.getByRole('link',{name:'Pipeline',exact:true}).click();await page.locator('.opportunity-card').filter({hasText:'Solar Operação E2E'}).dragTo(page.locator('.stage-qualification'));await page.getByRole('button',{name:'Confirmar etapa'}).click();await expect(page.getByRole('dialog',{name:'Alterar etapa da oportunidade'})).toBeHidden({timeout:15000});await expect(page.locator('.stage-qualification').getByRole('link',{name:'Solar Operação E2E'})).toBeVisible();await page.getByRole('combobox',{name:'Mover Solar Operação E2E',exact:true}).selectOption('proposal_sent');await page.getByRole('button',{name:'Confirmar etapa'}).click();await expect(page.getByRole('dialog',{name:'Alterar etapa da oportunidade'})).toBeHidden({timeout:15000});await expect(page.locator('.stage-proposal_sent').getByRole('link',{name:'Solar Operação E2E'})).toBeVisible();
 await page.getByRole('combobox',{name:'Mover Solar Operação E2E',exact:true}).selectOption('won');await page.getByRole('button',{name:'Confirmar etapa'}).click();await expect(page.getByRole('dialog',{name:'Alterar etapa da oportunidade'})).toBeHidden({timeout:15000});await expect(page.locator('.stage-won').getByRole('link',{name:'Solar Operação E2E'})).toBeVisible();
 await page.getByRole('link',{name:'Solar Operação E2E',exact:true}).click();await page.getByRole('button',{name:'Histórico e atividades'}).click();await expect(page.getByText('Oportunidade ganha',{exact:true})).toBeVisible();
});
test('agenda permite editar e concluir tarefa; follow-up e pipeline funcionam no celular',async({page})=>{
 await login(page);await page.getByRole('link',{name:'Agenda',exact:true}).click();await page.getByLabel('Data da agenda').fill('2026-09-14');await page.getByRole('combobox',{name:'Visualização',exact:true}).selectOption('day');const card=page.locator('.task-card').filter({hasText:'Retornar negociação E2E'});await expect(card).toBeVisible();await card.getByRole('button',{name:'Editar tarefa'}).click();await page.getByLabel('Descrição',{exact:true}).fill('Confirmar o retorno comercial.');await page.getByRole('combobox',{name:'Status da tarefa',exact:true}).selectOption('in_progress');await page.getByRole('button',{name:'Salvar tarefa'}).click();await expect(card.getByText('Em andamento',{exact:true})).toBeVisible();await card.getByRole('button',{name:'Concluir',exact:true}).click();await expect(card.getByText('Concluída',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Follow-up',exact:true}).click();await expect(page.getByRole('heading',{name:'Follow-up comercial'})).toBeVisible();
 for(const [path,ready] of [['/pipeline','.opportunity-card'],['/agenda','.agenda-column'],['/follow-up','.follow-grid'],['/oportunidades','.opportunity-card']]){await page.goto(path);await page.setViewportSize({width:390,height:844});await expect(page.locator(ready).first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
});
test('API comercial protege oportunidades, tarefas, fechamento e configurações',async({playwright})=>{
 const admin=await playwright.request.newContext({baseURL:origin}),seller=await playwright.request.newContext({baseURL:origin});for(const [client,email] of [[admin,'admin@e2e.local'],[seller,'seller@e2e.local']] as const){expect((await client.post('/api/auth/login',{headers:{origin},data:{organization:'peclat-solar',email,password}})).ok()).toBeTruthy();}
 const record=await (await admin.post('/api/leads',{headers:{origin},data:{name:'Privado Operação API'}})).json();const create=await admin.post('/api/opportunities',{headers:{origin},data:{title:'Oportunidade privada API',lead_id:record.id,estimated_value:18000}});expect(create.status()).toBe(201);let o=await create.json();
 expect((await seller.get('/api/opportunities/'+o.id)).status()).toBe(404);expect((await seller.post('/api/opportunities/'+o.id+'/notes',{headers:{origin},data:{body:'Bloqueado'}})).status()).toBe(404);
 expect((await admin.post('/api/opportunities/'+o.id+'/lose',{headers:{origin},data:{version:o.version}})).status()).toBe(400);const lost=await admin.post('/api/opportunities/'+o.id+'/lose',{headers:{origin},data:{version:o.version,loss_reason:'competitor'}});expect(lost.status()).toBe(200);o=await lost.json();expect(o.status).toBe('lost');
 const taskResponse=await admin.post('/api/tasks',{headers:{origin},data:{title:'Tarefa privada API',opportunity_id:o.id,due_date:'2026-09-20'}});expect(taskResponse.status()).toBe(201);const task=await taskResponse.json();expect((await seller.get('/api/tasks/'+task.id)).status()).toBe(404);
 expect((await seller.put('/api/commercial-settings',{headers:{origin},data:{inactive_days:5}})).status()).toBe(403);
 expect(JSON.stringify(await (await seller.get('/api/search?q=privada')).json())).not.toContain('Oportunidade privada API');expect((await admin.get('/api/search?q=privada')).status()).toBe(200);expect((await admin.get('/api/commercial-indicators')).status()).toBe(200);
 await admin.dispose();await seller.dispose();
});
