'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRemote} from '@/components/crm/use-remote';
import {api,errorMessage} from '@/components/crm/api';
import {money,opportunityStages,type Opportunity,type CommercialTask} from '@/modules/commercial/domain';
type Data={settings:{inactive_days:number;can_edit:boolean};inactive:Opportunity[];stalled:Opportunity[];closing:Opportunity[];today:{items:CommercialTask[];total:number};overdue:{items:CommercialTask[];total:number}};
export function FollowUp(){const [demo,setDemo]=useState('real');const [revision,setRevision]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState('');const {data,loading,error:loadError}=useRemote<Data>('/api/follow-up?demo='+demo,revision);async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{await api('/api/commercial-settings','PUT',{inactive_days:Number(new FormData(e.currentTarget).get('inactive_days'))});setRevision(n=>n+1);setNotice('Critério de acompanhamento atualizado.');setError('');}catch(e){setError(errorMessage(e));}}
 return <><label className="crm-field"><span>Base de dados</span><select value={demo} onChange={e=>setDemo(e.target.value)}><option value="real">Operação real</option><option value="demo">Demonstração DEMO</option></select></label>{loading&&<p role="status">Carregando acompanhamento…</p>}{(error||loadError)&&<p role="alert" className="error-box">{error||loadError}</p>}{notice&&<p role="status" className="crm-notice">{notice}</p>}{data&&<>{data.settings.can_edit?<form className="follow-settings card" onSubmit={save}><label className="crm-field"><span>Dias sem atividade / na mesma etapa</span><input name="inactive_days" type="number" min={1} max={365} defaultValue={data.settings.inactive_days} required/></label><button className="button secondary">Salvar critério</button></form>:<p className="muted">Critério da equipe: {data.settings.inactive_days} dias sem atividade ou na mesma etapa.</p>}<div className="follow-grid">{(['today','overdue'] as const).map(key=><section className="card" key={key}><h2>{key==='today'?'Contatos e tarefas para hoje':'Tarefas atrasadas'} <span className="badge">{data[key].total}</span></h2><p className="muted">{key==='today'?'Atendimentos com tarefa agendada para hoje.':'Priorize os retornos que passaram do prazo.'}</p>{data[key].items.map(t=><Link className="follow-item" key={t.id} href={'/tarefas?bucket='+key}><strong>{t.title}</strong><span>{t.related_name}</span><small>{t.owner_name} · {t.due_date.split('-').reverse().join('/')} {t.due_time}</small></Link>)}{!data[key].total&&<p className="empty-state">Nenhuma tarefa neste grupo.</p>}<Link className="text-link" href={'/tarefas?bucket='+key}>Ver tarefas →</Link></section>)}{(['inactive','closing','stalled'] as const).map(key=><section className="card" key={key}><h2>{key==='inactive'?'Sem atividade recente':key==='closing'?'Fechamento nos próximos 7 dias':'Paradas na mesma etapa'}</h2><p className="muted">Até 20 oportunidades por grupo.</p>{data[key].map(o=><Link className="follow-item" href={'/oportunidades/'+o.id} key={o.id}><strong>{o.title}</strong><span>{o.customer_name??o.lead_name??o.company_name}</span><small>{opportunityStages[o.stage]} · {money(o.estimated_value)}</small></Link>)}{!data[key].length&&<p className="empty-state">Nenhuma oportunidade neste grupo.</p>}</section>)}</div></>}</>;
}
