'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {api,errorMessage} from '@/components/crm/api';
import {useRemote} from '@/components/crm/use-remote';
import {EntityPicker} from './entity-picker';
import {opportunityStages,lossReasons,today,type Opportunity} from '@/modules/commercial/domain';
import {priorities,sources,type CommercialRecord} from '@/modules/crm/domain';
export type Owners={id:string;name:string}[];
export function OpportunityForm({initial,record,owners,userId,onSaved}:{initial?:Opportunity;record?:CommercialRecord;owners:Owners;userId:string;onSaved?:(o:Opportunity)=>void}){
 const router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const related=(kind:'lead'|'customer'|'company')=>initial?.[`${kind}_id`]?{id:initial[`${kind}_id`]!,name:initial[`${kind}_name`]??''}:record?.kind===kind?{id:record.id,name:record.name}:null;
 const [lead,setLead]=useState(related('lead')),[customer,setCustomer]=useState(related('customer')),[company,setCompany]=useState(related('company'));
 const [stage,setStage]=useState(initial?.stage??'new');
 const leadContacts=useRemote<{items:{id:string;name:string}[]}>(lead?`/api/contacts?record_id=${lead.id}`:null);
 const customerContacts=useRemote<{items:{id:string;name:string}[]}>(customer?`/api/contacts?record_id=${customer.id}`:null);
 const companyContacts=useRemote<{items:{id:string;name:string}[]}>(company?`/api/contacts?record_id=${company.id}`:null);
 const contacts=[...new Map([...(leadContacts.data?.items??[]),...(customerContacts.data?.items??[]),...(companyContacts.data?.items??[])].map(c=>[c.id,c])).values()];
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const saved=await api<Opportunity>(`/api/opportunities${initial?'/'+initial.id:''}`,initial?'PUT':'POST',{...Object.fromEntries(f),lead_id:lead?.id??null,customer_id:customer?.id??null,company_id:company?.id??null,contact_id:f.get('contact_id')||null,...(initial?{version:initial.version}:{})});if(onSaved)onSaved(saved);else router.push('/oportunidades/'+saved.id);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const field=(name:string,label:string,type='text',value:string|number='',required=false)=><label className="crm-field"><span>{label}</span><input name={name} type={type} defaultValue={value} required={required} maxLength={180} min={type==='number'?0:undefined} step={name==='estimated_value'?'0.01':undefined} max={name==='probability'?100:undefined}/></label>;
 return <form className="crm-form" onSubmit={submit}><fieldset disabled={busy}><legend>Relacionamentos</legend><p className="muted">Selecione ao menos um cadastro existente. Nenhum cliente será criado automaticamente.</p><div className="crm-form-grid"><EntityPicker kind="lead" label="Lead relacionado" value={lead} onChange={setLead}/><EntityPicker kind="customer" label="Cliente relacionado" value={customer} onChange={setCustomer}/><EntityPicker kind="company" label="Empresa relacionada" value={company} onChange={setCompany}/></div><label className="crm-field"><span>Contato relacionado</span><select name="contact_id" defaultValue={initial?.contact_id??''}><option value="">Sem contato específico</option>{initial?.contact_id&&!contacts.some(c=>c.id===initial.contact_id)&&<option value={initial.contact_id}>{initial.contact_name}</option>}{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></fieldset>
 <fieldset disabled={busy}><legend>Oportunidade comercial</legend><div className="crm-form-grid">{field('title','Título da oportunidade','text',initial?.title??(record?'Projeto solar · '+record.name:''),true)}<label className="crm-field"><span>Responsável</span><select name="owner_id" defaultValue={initial?.owner_id??record?.owner_id??userId}>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="crm-field"><span>Etapa</span><select name="stage" value={stage} onChange={e=>setStage(e.target.value as keyof typeof opportunityStages)}>{Object.entries(opportunityStages).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{field('estimated_value','Valor estimado (R$)','number',initial?.estimated_value??record?.potential_value??0)}{field('probability','Probabilidade (%)','number',initial?.probability??0)}<label className="crm-field"><span>Prioridade</span><select name="priority" defaultValue={initial?.priority??record?.priority??'normal'}>{Object.entries(priorities).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="crm-field"><span>Origem</span><select name="source" defaultValue={initial?.source??record?.source??'Manual'}>{[...new Set([...sources,initial?.source??record?.source??'Manual'])].map(v=><option key={v}>{v}</option>)}</select></label>{field('opened_on','Data de abertura','date',initial?.opened_on??today(),true)}{field('expected_close','Previsão de fechamento','date',initial?.expected_close??'')}<label className="crm-field"><span>Motivo de perda</span><select name="loss_reason" required={stage==='lost'} defaultValue={initial?.loss_reason??''}><option value="">Selecione se perdida</option>{Object.entries(lossReasons).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></fieldset><label className="crm-field"><span>Observações internas</span><textarea name="observations" maxLength={4000} rows={4} defaultValue={initial?.observations}/></label>{error&&<p className="error-box" role="alert">{error}</p>}<div className="crm-form-actions">{onSaved&&initial?<button type="button" className="button secondary" onClick={()=>onSaved(initial)}>Cancelar</button>:<Link className="button secondary" href="/oportunidades">Cancelar</Link>}<button className="button primary" disabled={busy}>{busy?'Salvando…':initial?'Salvar oportunidade':'Criar oportunidade'}</button></div></form>;
}
