'use client';
import {useState,type FormEvent} from 'react';
import {Check,Copy,KeyRound,Plus,UserCog} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
import {Modal} from '@/components/crm/modal';
import type {ManagedUser} from '@/modules/users/domain';
import type {userAdministration} from '@/modules/users/repository';

type Overview=Awaited<ReturnType<typeof userAdministration>>;
type History={id:string;action:string;detail:string;created_at:string;actor_name:string;subject_name:string};
const actions:Record<string,string>={'users.created':'Usuário criado','users.name_changed':'Nome alterado','users.role_changed':'Função alterada','users.activated':'Acesso ativado','users.deactivated':'Acesso desativado','users.access_reset':'Acesso redefinido'};
const date=(value:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value)):'Nunca';

export function UserWorkspace({initial}:{initial:Overview}){
 const [data,setData]=useState(initial),[editing,setEditing]=useState<ManagedUser|Record<string,never>|null>(null),[resetting,setResetting]=useState<ManagedUser|null>(null);
 const [credential,setCredential]=useState<{name:string;email:string;password:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[copied,setCopied]=useState(false);
 const refresh=async()=>setData(await api<Overview>('/api/admin-users'));
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget),current=editing&&'id' in editing?editing as ManagedUser:null;const body={name:String(form.get('name')),email:String(form.get('email')),role_code:String(form.get('role_code')),active:form.get('active')==='true',...(current?{version:current.version}:{})};try{if(current){await api(`/api/admin-users/${current.id}`,'PUT',{name:body.name,role_code:body.role_code,active:body.active,version:body.version});setNotice('Usuário atualizado.');}else{const result=await api<{temporary_password:string}>('/api/admin-users','POST',body);setCredential({name:body.name,email:body.email,password:result.temporary_password});setNotice('Usuário criado. Entregue a credencial temporária por um canal seguro.');}await refresh();setEditing(null);}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function reset(){if(!resetting)return;setBusy(true);setError('');try{const result=await api<{temporary_password:string}>(`/api/admin-users/${resetting.id}/reset-access`,'POST',{});setCredential({name:resetting.name,email:resetting.email,password:result.temporary_password});setResetting(null);setNotice('Acesso redefinido e sessões anteriores encerradas.');await refresh();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function copyCredential(){if(!credential)return;await navigator.clipboard.writeText(`Peclat Solar CRM\nE-mail: ${credential.email}\nSenha temporária: ${credential.password}`);setCopied(true);}
 return <div className="user-workspace"><div className="page-heading"><div><span className="eyebrow blue">CONFIGURAÇÕES</span><h1>Usuários e acessos</h1><p>Controle quem acessa a organização e quais responsabilidades cada pessoa possui.</p></div><button className="button primary" onClick={()=>{setError('');setEditing({});}}><Plus size={17}/>Novo usuário</button></div>
  {notice&&<p role="status" className="crm-notice">{notice}</p>}{error&&!editing&&!resetting&&<p role="alert" className="error-box">{error}</p>}
  {credential&&<section className="user-credential" aria-label="Credencial temporária"><div><KeyRound size={20}/><div><strong>Credencial temporária de {credential.name}</strong><p>Esta senha aparece somente agora. Envie por um canal seguro e oriente a pessoa a usar a recuperação de senha quando o e-mail estiver configurado.</p></div></div><dl><div><dt>E-mail</dt><dd>{credential.email}</dd></div><div><dt>Senha temporária</dt><dd><code>{credential.password}</code></dd></div></dl><div className="crm-form-actions"><button className="button secondary" onClick={copyCredential}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copiado':'Copiar acesso'}</button><button className="button secondary" onClick={()=>{setCredential(null);setCopied(false);}}>Fechar</button></div></section>}
  <section className="card"><div className="card-heading"><h2>Membros da organização</h2><span className="badge">{data.users.length} usuário(s)</span></div>{!data.users.length&&<p className="empty-state">Nenhum usuário cadastrado.</p>}<div className="user-list">{data.users.map(user=><article className="user-row" key={user.id}><div className="user-identity"><span className="avatar"><UserCog size={16}/></span><div><strong>{user.name}</strong><small>{user.email}</small></div></div><dl><div><dt>Função</dt><dd>{user.role_name}</dd></div><div><dt>Equipe</dt><dd>{user.team_name??'Não definida'}</dd></div><div><dt>Último acesso</dt><dd>{date(user.last_access)}</dd></div><div><dt>Criado em</dt><dd>{date(user.created_at)}</dd></div></dl><span className={`document-status ${user.active?'active':'cancelled'}`}>{user.active?'Ativo':'Inativo'}</span><div className="user-actions"><button className="button secondary" onClick={()=>{setError('');setEditing(user);}}>Editar</button>{user.id!==data.current_user_id&&<button className="button secondary" onClick={()=>{setError('');setResetting(user);}}>Redefinir acesso</button>}</div></article>)}</div></section>
  {(data.history as History[]).length>0&&<section className="card user-history"><h2>Histórico recente</h2>{(data.history as History[]).map(item=><p key={item.id}><strong>{actions[item.action]??item.action}</strong><span>{item.subject_name} · {item.detail} · por {item.actor_name}</span><time>{date(item.created_at)}</time></p>)}</section>}
  {editing&&<Modal title={'id' in editing?'Editar usuário':'Novo usuário'} onClose={()=>!busy&&setEditing(null)}><form className="crm-form" onSubmit={save}><label className="crm-field"><span>Nome</span><input name="name" required minLength={2} maxLength={180} defaultValue={'name' in editing?String(editing.name):''}/></label><label className="crm-field"><span>E-mail</span><input name="email" type="email" required maxLength={320} disabled={'id' in editing} defaultValue={'email' in editing?String(editing.email):''}/></label><label className="crm-field"><span>Função</span><select name="role_code" required defaultValue={'role_code' in editing?String(editing.role_code):'seller'}>{data.roles.map(role=><option key={role.code} value={role.code}>{role.name}</option>)}</select></label><label className="crm-field"><span>Status</span><select name="active" defaultValue={'active' in editing&&editing.active===false?'false':'true'}><option value="true">Ativo</option><option value="false">Inativo</option></select></label>{'id' in editing&&editing.id===data.current_user_id&&<p className="info-strip">Seu próprio papel e status não podem ser alterados por esta tela.</p>}{error&&<p role="alert" className="error-box">{error}</p>}<div className="crm-form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancelar</button><button className="button primary" disabled={busy}>{busy?'Salvando…':'Salvar usuário'}</button></div></form></Modal>}
  {resetting&&<Modal title="Redefinir acesso?" onClose={()=>!busy&&setResetting(null)}><p>Uma nova senha temporária será criada para <strong>{resetting.name}</strong>. Todas as sessões e recuperações anteriores serão encerradas.</p>{error&&<p role="alert" className="error-box">{error}</p>}<div className="crm-form-actions"><button className="button secondary" disabled={busy} onClick={()=>setResetting(null)}>Cancelar</button><button className="button primary" disabled={busy} onClick={reset}>{busy?'Redefinindo…':'Gerar novo acesso'}</button></div></Modal>}
 </div>;
}
