import {database,transaction} from '@/server/db';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {assertCommercialAssignee,assertManagedTeam} from '@/modules/commercial/scope';
import {dashboardFilters,goalInput,type CommercialGoal,type SellerPerformance} from './domain';
import {uuid} from '@/modules/crm/domain';

type Db=Pick<ReturnType<typeof database>,'query'>;
const admin=(actor:Actor)=>actor.role==='admin';
const visibleGoal=(actor:Actor,alias='g')=>admin(actor)?`${alias}.organization_id=$1`:`${alias}.organization_id=$1 AND (${alias}.seller_user_id=$2${actor.role==='manager'?` OR EXISTS(SELECT 1 FROM commercial_teams mt WHERE mt.organization_id=${alias}.organization_id AND mt.id=${alias}.team_id AND mt.manager_user_id=$2 AND mt.active) OR EXISTS(SELECT 1 FROM commercial_team_members mm JOIN commercial_teams mt ON mt.organization_id=mm.organization_id AND mt.id=mm.team_id WHERE mm.organization_id=${alias}.organization_id AND mm.user_id=${alias}.seller_user_id AND mt.manager_user_id=$2 AND mt.active)`:''})`;
const params=(actor:Actor)=>admin(actor)?[actor.organizationId]:[actor.organizationId,actor.userId];

async function validateTarget(actor:Actor,data:{target_kind:'seller'|'team';seller_user_id?:string|null;team_id?:string|null},db:Db){
 if(data.target_kind==='seller')await assertCommercialAssignee(actor,data.seller_user_id!,db,true);
 else await assertManagedTeam(actor,data.team_id!,db,true);
}
export async function saveGoal(actor:Actor,input:unknown,id?:string){
 requirePermission(actor,'commercial_goals.manage');if(id)uuid.parse(id);const data=goalInput.parse(input);
 return transaction(async db=>{await validateTarget(actor,data,db);let before:{target_value:number;version:number}|undefined;
  if(id){const row=await db.query<{target_value:number;version:number}>(`SELECT target_value::float8 target_value,version FROM commercial_goals g WHERE ${visibleGoal(actor)} AND g.id=$${params(actor).length+1} FOR UPDATE`,[...params(actor),id]);before=row.rows[0];if(!before)throw new AccessError(404,'Meta não encontrada.');if(before.version!==data.version)throw new AccessError(409,'Meta atualizada por outra pessoa. Recarregue.');}
  try{const values=[actor.organizationId,data.target_kind,data.seller_user_id??null,data.team_id??null,data.metric,data.period,data.starts_on,data.ends_on,data.target_value,actor.userId];
   const row=id?await db.query<{id:string}>(`UPDATE commercial_goals SET target_kind=$2,seller_user_id=$3,team_id=$4,metric=$5,period=$6,starts_on=$7,ends_on=$8,target_value=$9,updated_by=$10,updated_at=now(),version=version+1 WHERE organization_id=$1 AND id=$11 RETURNING id`,[...values,id])
    :await db.query<{id:string}>(`INSERT INTO commercial_goals(organization_id,target_kind,seller_user_id,team_id,metric,period,starts_on,ends_on,target_value,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10) RETURNING id`,values);
   const goalId=row.rows[0].id,snapshot=JSON.stringify({...data,id:goalId});await db.query('INSERT INTO commercial_goal_history(organization_id,goal_id,actor_id,action,previous_value,new_value,snapshot) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb)',[actor.organizationId,goalId,actor.userId,id?'updated':'created',before?.target_value??null,data.target_value,snapshot]);await db.query('INSERT INTO audit_logs(organization_id,actor_id,action) VALUES ($1,$2,$3)',[actor.organizationId,actor.userId,id?'commercial_goal.updated':'commercial_goal.created']);return goalId;
  }catch(error){if((error as {code?:string}).code==='23505')throw new AccessError(409,'Já existe uma meta igual para esse período.');throw error;}
 });
}

export async function performanceDashboard(actor:Actor,input:unknown){
 requirePermission(actor,'commercial_goals.read');const filter=dashboardFilters.parse(input);const p:unknown[]=[actor.organizationId,filter.from,filter.to];const conditions=['m.organization_id=$1',"m.role_code='seller'",'m.active','u.active'];
 if(actor.role==='seller'){p.push(actor.userId);conditions.push(`m.user_id=$${p.length}`);}else if(actor.role==='manager'){p.push(actor.userId);conditions.push(`EXISTS(SELECT 1 FROM commercial_team_members sm JOIN commercial_teams st ON st.organization_id=sm.organization_id AND st.id=sm.team_id WHERE sm.organization_id=m.organization_id AND sm.user_id=m.user_id AND st.manager_user_id=$${p.length} AND st.active)`);}
 if(filter.team_id){await assertManagedTeam(actor,filter.team_id,database());p.push(filter.team_id);conditions.push(`tm.team_id=$${p.length}`);}if(filter.seller_user_id){await assertCommercialAssignee(actor,filter.seller_user_id,database(),true);p.push(filter.seller_user_id);conditions.push(`m.user_id=$${p.length}`);}
 const rows=await database().query<SellerPerformance>(`WITH subjects AS (SELECT m.user_id,u.name,tm.team_id,t.name team_name FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN commercial_team_members tm ON tm.organization_id=m.organization_id AND tm.user_id=m.user_id LEFT JOIN commercial_teams t ON t.organization_id=tm.organization_id AND t.id=tm.team_id WHERE ${conditions.join(' AND ')}),
 rec AS (SELECT owner_id,count(*) FILTER(WHERE kind='lead')::int leads_received,count(*) FILTER(WHERE kind='customer')::int customers FROM crm_records WHERE organization_id=$1 AND deleted_at IS NULL AND created_at>=$2::date AND created_at<$3::date+1 GROUP BY owner_id),
 worked AS (SELECT r.owner_id,count(DISTINCT r.id)::int leads_worked FROM crm_records r JOIN crm_activities a ON a.organization_id=r.organization_id AND a.record_id=r.id WHERE r.organization_id=$1 AND r.kind='lead' AND a.created_at>=$2::date AND a.created_at<$3::date+1 GROUP BY r.owner_id),
 opp AS (SELECT COALESCE(closed_owner_id,owner_id) owner_id,count(*) FILTER(WHERE status='won')::int opportunities_won,count(*) FILTER(WHERE status='lost')::int opportunities_lost FROM crm_opportunities WHERE organization_id=$1 AND closed_at>=$2::date AND closed_at<$3::date+1 GROUP BY COALESCE(closed_owner_id,owner_id)),
 openopp AS (SELECT owner_id,count(*)::int opportunities_open FROM crm_opportunities WHERE organization_id=$1 AND status='open' GROUP BY owner_id),
 sales AS (SELECT responsible_user_id owner_id,count(*)::int contracts,COALESCE(sum(net_value),0)::float8 sales_value FROM contracts WHERE organization_id=$1 AND status IN ('signed','active','completed') AND signed_at>=$2::date AND signed_at<$3::date+1 GROUP BY responsible_user_id),
 task AS (SELECT owner_id,count(*) FILTER(WHERE status IN ('pending','in_progress'))::int tasks_open,count(*) FILTER(WHERE status='completed' AND completed_at>=$2::date AND completed_at<$3::date+1)::int tasks_completed FROM crm_tasks WHERE organization_id=$1 GROUP BY owner_id)
 SELECT s.user_id,s.name,s.team_id,s.team_name,COALESCE(r.leads_received,0)::int leads_received,COALESCE(w.leads_worked,0)::int leads_worked,COALESCE(r.customers,0)::int customers,COALESCE(oop.opportunities_open,0)::int opportunities_open,COALESCE(o.opportunities_won,0)::int opportunities_won,COALESCE(o.opportunities_lost,0)::int opportunities_lost,COALESCE(sa.contracts,0)::int contracts,COALESCE(sa.sales_value,0)::float8 sales_value,CASE WHEN COALESCE(sa.contracts,0)>0 THEN round((sa.sales_value/sa.contracts)::numeric,2)::float8 ELSE 0 END average_ticket,COALESCE(ta.tasks_open,0)::int tasks_open,COALESCE(ta.tasks_completed,0)::int tasks_completed,CASE WHEN COALESCE(o.opportunities_won,0)+COALESCE(o.opportunities_lost,0)>0 THEN round(100.0*o.opportunities_won/(o.opportunities_won+o.opportunities_lost),2)::float8 ELSE 0 END conversion_rate FROM subjects s LEFT JOIN rec r ON r.owner_id=s.user_id LEFT JOIN worked w ON w.owner_id=s.user_id LEFT JOIN opp o ON o.owner_id=s.user_id LEFT JOIN openopp oop ON oop.owner_id=s.user_id LEFT JOIN sales sa ON sa.owner_id=s.user_id LEFT JOIN task ta ON ta.owner_id=s.user_id ORDER BY s.name,s.user_id`,p);
 const goals=await listGoals(actor);const history=actor.permissions.includes('commercial_goals.manage')?await goalHistory(actor):[];return {from:filter.from,to:filter.to,people:rows.rows,goals,history,can_manage:actor.permissions.includes('commercial_goals.manage')};
}

export async function listGoals(actor:Actor){requirePermission(actor,'commercial_goals.read');const p=params(actor);const result=await database().query<CommercialGoal>(`SELECT g.id,g.target_kind,g.seller_user_id,g.team_id,COALESCE(u.name,t.name) target_name,g.metric,g.period,g.starts_on,g.ends_on,g.target_value::float8 target_value,g.version,g.created_at,g.updated_at,
 CASE g.metric WHEN 'sales_value' THEN COALESCE((SELECT sum(c.net_value) FROM contracts c WHERE c.organization_id=g.organization_id AND c.status IN ('signed','active','completed') AND c.signed_at>=g.starts_on AND c.signed_at<g.ends_on+1 AND (c.responsible_user_id=g.seller_user_id OR EXISTS(SELECT 1 FROM commercial_team_members x WHERE x.organization_id=g.organization_id AND x.team_id=g.team_id AND x.user_id=c.responsible_user_id))),0)
 WHEN 'contracts_closed' THEN (SELECT count(*) FROM contracts c WHERE c.organization_id=g.organization_id AND c.status IN ('signed','active','completed') AND c.signed_at>=g.starts_on AND c.signed_at<g.ends_on+1 AND (c.responsible_user_id=g.seller_user_id OR EXISTS(SELECT 1 FROM commercial_team_members x WHERE x.organization_id=g.organization_id AND x.team_id=g.team_id AND x.user_id=c.responsible_user_id)))
 WHEN 'opportunities_won' THEN (SELECT count(*) FROM crm_opportunities o WHERE o.organization_id=g.organization_id AND o.status='won' AND o.closed_at>=g.starts_on AND o.closed_at<g.ends_on+1 AND (o.closed_owner_id=g.seller_user_id OR EXISTS(SELECT 1 FROM commercial_team_members x WHERE x.organization_id=g.organization_id AND x.team_id=g.team_id AND x.user_id=o.closed_owner_id)))
 ELSE (SELECT count(*) FROM crm_records r WHERE r.organization_id=g.organization_id AND r.kind='customer' AND r.deleted_at IS NULL AND r.created_at>=g.starts_on AND r.created_at<g.ends_on+1 AND (r.owner_id=g.seller_user_id OR EXISTS(SELECT 1 FROM commercial_team_members x WHERE x.organization_id=g.organization_id AND x.team_id=g.team_id AND x.user_id=r.owner_id))) END::float8 actual_value
 FROM commercial_goals g LEFT JOIN users u ON u.id=g.seller_user_id LEFT JOIN commercial_teams t ON t.organization_id=g.organization_id AND t.id=g.team_id WHERE ${visibleGoal(actor)} ORDER BY g.starts_on DESC,g.created_at DESC`,p);const date=(value:unknown)=>value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);return result.rows.map(row=>({...row,starts_on:date(row.starts_on),ends_on:date(row.ends_on),target_value:Number(row.target_value),actual_value:Number(row.actual_value),progress:Math.round(10000*Number(row.actual_value)/Number(row.target_value))/100}));}
async function goalHistory(actor:Actor){const p=params(actor);const result=await database().query(`SELECT h.id,h.goal_id,h.action,h.previous_value::float8 previous_value,h.new_value::float8 new_value,h.created_at,u.name actor_name FROM commercial_goal_history h JOIN commercial_goals g ON g.organization_id=h.organization_id AND g.id=h.goal_id JOIN users u ON u.id=h.actor_id WHERE ${visibleGoal(actor,'g')} ORDER BY h.created_at DESC,h.id DESC LIMIT 50`,p);return result.rows;}
export async function goalOptions(actor:Actor){requirePermission(actor,'commercial_goals.read');const overview=await database().query<{id:string;name:string;kind:string}>(`SELECT m.user_id id,u.name,'seller' kind FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND m.role_code='seller' AND m.active AND u.active AND ($2::boolean OR m.user_id=$3 OR EXISTS(SELECT 1 FROM commercial_team_members x JOIN commercial_teams t ON t.organization_id=x.organization_id AND t.id=x.team_id WHERE x.organization_id=m.organization_id AND x.user_id=m.user_id AND t.manager_user_id=$3 AND t.active)) UNION ALL SELECT t.id,t.name,'team' FROM commercial_teams t WHERE t.organization_id=$1 AND t.active AND ($2::boolean OR t.manager_user_id=$3) ORDER BY kind,name`,[actor.organizationId,admin(actor),actor.userId]);return overview.rows;}
