import {randomBytes} from 'node:crypto';
import {database,transaction} from '@/server/db';
import {hashPassword} from '@/modules/auth/crypto';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {userCreateInput,userId,userUpdateInput,type ManagedUser} from './domain';

const temporaryPassword=()=>`Pec-${randomBytes(12).toString('base64url')}!9`;
function access(actor:Actor,permission:'users.read'|'users.manage'){requirePermission(actor,permission);if(actor.role!=='admin')throw new AccessError(403,'Somente administradores podem gerenciar usuários.');}
export async function userAdministration(actor:Actor){access(actor,'users.read');const [users,roles,history]=await Promise.all([
 database().query<ManagedUser>(`SELECT u.id,u.name,u.email,m.role_code,r.name role_name,(u.active AND m.active) active,t.name team_name,
  (SELECT max(a.created_at) FROM audit_logs a WHERE a.organization_id=m.organization_id AND a.actor_id=u.id AND a.action='auth.login') last_access,
  u.created_at,m.version
  FROM memberships m JOIN users u ON u.id=m.user_id JOIN roles r ON r.code=m.role_code
  LEFT JOIN commercial_team_members tm ON tm.organization_id=m.organization_id AND tm.user_id=m.user_id
  LEFT JOIN commercial_teams t ON t.organization_id=tm.organization_id AND t.id=tm.team_id
  WHERE m.organization_id=$1 ORDER BY (u.active AND m.active) DESC,u.name,u.id`,[actor.organizationId]),
 database().query<{code:string;name:string}>("SELECT code,name FROM roles WHERE code=ANY($1::text[]) ORDER BY CASE code WHEN 'admin' THEN 1 WHEN 'manager' THEN 2 WHEN 'seller' THEN 3 WHEN 'technician' THEN 4 WHEN 'support' THEN 5 ELSE 6 END",[['admin','manager','seller','technician','support','postsales']]),
 database().query(`SELECT a.id,a.action,a.detail,a.created_at,actor.name actor_name,subject.name subject_name FROM audit_logs a JOIN users actor ON actor.id=a.actor_id JOIN users subject ON subject.id=a.subject_user_id WHERE a.organization_id=$1 AND a.subject_user_id IS NOT NULL AND a.action LIKE 'users.%' ORDER BY a.created_at DESC,a.id DESC LIMIT 100`,[actor.organizationId]),
 ]);return {users:users.rows.map(row=>({...row,version:Number(row.version)})),roles:roles.rows,history:history.rows,current_user_id:actor.userId};}
async function exclusiveMembership(db:Pick<ReturnType<typeof database>,'query'>,organizationId:string,id:string){const result=await db.query<{total:number}>('SELECT count(*)::int total FROM memberships WHERE user_id=$1',[id]);if(result.rows[0]?.total!==1)throw new AccessError(409,'Esta conta pertence a mais de uma organização e não pode ter credenciais globais alteradas aqui.');const found=await db.query('SELECT 1 FROM memberships WHERE organization_id=$1 AND user_id=$2',[organizationId,id]);if(!found.rowCount)throw new AccessError(404,'Usuário não encontrado.');}
async function audit(db:Pick<ReturnType<typeof database>,'query'>,actor:Actor,subject:string,action:string,detail:string){await db.query('INSERT INTO audit_logs(organization_id,actor_id,subject_user_id,action,detail) VALUES ($1,$2,$3,$4,$5)',[actor.organizationId,actor.userId,subject,action,detail]);}
export async function createManagedUser(actor:Actor,input:unknown){access(actor,'users.manage');const data=userCreateInput.parse(input),password=temporaryPassword(),hash=await hashPassword(password);const id=await transaction(async db=>{const duplicate=await db.query('SELECT 1 FROM users WHERE email=$1',[data.email]);if(duplicate.rowCount)throw new AccessError(409,'Não foi possível usar este e-mail.');const created=await db.query<{id:string}>('INSERT INTO users(email,name,password_hash) VALUES ($1,$2,$3) RETURNING id',[data.email,data.name,hash]);const id=created.rows[0].id;await db.query('INSERT INTO memberships(organization_id,user_id,role_code,active) VALUES ($1,$2,$3,$4)',[actor.organizationId,id,data.role_code,data.active]);await audit(db,actor,id,'users.created',`Função: ${data.role_code}; status: ${data.active?'ativo':'inativo'}.`);return id;});return {id,temporary_password:password};}
export async function updateManagedUser(actor:Actor,id:string,input:unknown){access(actor,'users.manage');userId.parse(id);const data=userUpdateInput.parse(input);return transaction(async db=>{const current=await db.query<{name:string;role_code:string;membership_active:boolean;user_active:boolean;version:number}>(`SELECT u.name,m.role_code,m.active membership_active,u.active user_active,m.version FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND m.user_id=$2 FOR UPDATE OF m,u`,[actor.organizationId,id]);if(!current.rowCount)throw new AccessError(404,'Usuário não encontrado.');const before=current.rows[0],wasActive=before.user_active&&before.membership_active;if(Number(before.version)!==data.version)throw new AccessError(409,'Usuário atualizado. Recarregue a página.');if(id===actor.userId&&(before.role_code!==data.role_code||wasActive!==data.active))throw new AccessError(409,'Você não pode alterar sua própria função ou desativar seu acesso.');if(before.role_code!==data.role_code){if(before.role_code==='manager'){const teams=await db.query('SELECT 1 FROM commercial_teams WHERE organization_id=$1 AND manager_user_id=$2 LIMIT 1',[actor.organizationId,id]);if(teams.rowCount)throw new AccessError(409,'Reatribua as equipes gerenciadas antes de alterar esta função.');}if(before.role_code==='seller'){const teams=await db.query('SELECT 1 FROM commercial_team_members WHERE organization_id=$1 AND user_id=$2 LIMIT 1',[actor.organizationId,id]);if(teams.rowCount)throw new AccessError(409,'Remova o vendedor da equipe antes de alterar esta função.');}}if(before.name!==data.name){await exclusiveMembership(db,actor.organizationId,id);await db.query('UPDATE users SET name=$1 WHERE id=$2',[data.name,id]);await audit(db,actor,id,'users.name_changed',`${before.name} → ${data.name}`);}if(data.active&&!before.user_active){await exclusiveMembership(db,actor.organizationId,id);await db.query('UPDATE users SET active=true WHERE id=$1',[id]);}await db.query('UPDATE memberships SET role_code=$3,active=$4,version=version+1 WHERE organization_id=$1 AND user_id=$2',[actor.organizationId,id,data.role_code,data.active]);if(before.role_code!==data.role_code){await db.query('DELETE FROM sessions WHERE organization_id=$1 AND user_id=$2',[actor.organizationId,id]);await audit(db,actor,id,'users.role_changed',`${before.role_code} → ${data.role_code}`);}if(wasActive!==data.active){if(!data.active)await db.query('DELETE FROM sessions WHERE organization_id=$1 AND user_id=$2',[actor.organizationId,id]);await audit(db,actor,id,data.active?'users.activated':'users.deactivated',data.active?'Acesso ativado.':'Acesso desativado.');}return {ok:true};});}
export async function resetManagedUserAccess(actor:Actor,id:string){access(actor,'users.manage');userId.parse(id);if(id===actor.userId)throw new AccessError(409,'Use a recuperação de senha para alterar seu próprio acesso.');const password=temporaryPassword(),hash=await hashPassword(password);await transaction(async db=>{await exclusiveMembership(db,actor.organizationId,id);await db.query('UPDATE users SET password_hash=$1 WHERE id=$2',[hash,id]);await db.query('DELETE FROM sessions WHERE user_id=$1',[id]);await db.query('DELETE FROM password_resets WHERE user_id=$1',[id]);await audit(db,actor,id,'users.access_reset','Credencial temporária gerada; sessões anteriores encerradas.');});return {temporary_password:password};}
