'use client';
import {useEffect,useState} from 'react';
import {Pause,Play,RotateCcw,XCircle} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
import {recoveryConsentStatuses,recoveryStatuses} from '@/modules/lead-recovery/domain';

type Preference={whatsapp_consent_status:keyof typeof recoveryConsentStatuses;consent_source:string;version:number|null};
type Enrollment={id:string;status:keyof typeof recoveryStatuses;next_attempt_at:string|null;attempt_count:number;version:number;state_reason:string}|null;
type Attempt={id:string;step_position:number;day_offset:number|null;inactivity_anchor:string;eligible_at:string|null;scheduled_for:string;sent_at:string|null;status:string;template_name:string|null;safe_error:string;failure_code:string|null;state_reason:string};
const date=(v:string|null)=>v?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
const attemptStatuses:Record<string,string>={pending:'Pendente',processing:'Processando',sent:'Enviada',failed:'Falhou',cancelled:'Cancelada',uncertain:'Resultado incerto',skipped:'Ignorada'};
export function LeadRecoveryPanel({recordId,canOperate}:{recordId:string;canOperate:boolean}){
 const [data,setData]=useState<{preference:Preference;enrollment:Enrollment;history:Attempt[]}|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(){try{setData(await api(`/api/lead-recovery/records/${recordId}`));}catch(e){setError(errorMessage(e));}}
 useEffect(()=>{let active=true;api<{preference:Preference;enrollment:Enrollment;history:Attempt[]}>(`/api/lead-recovery/records/${recordId}`).then(result=>{if(active)setData(result);}).catch(error=>{if(active)setError(errorMessage(error));});return()=>{active=false;};},[recordId]);
 async function optOut(){if(!data)return;setBusy('consent');setError('');try{await api(`/api/lead-recovery/records/${recordId}/consent`,'PUT',{whatsapp_consent_status:'opted_out',version:data.preference.version});await load();}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 async function operate(action:'pause'|'resume'|'cancel'|'reschedule',scheduledFor?:string){if(!data?.enrollment)return;setBusy(action);setError('');try{const body=action==='reschedule'?{action,version:data.enrollment.version,scheduled_for:scheduledFor}:{action,version:data.enrollment.version};await api(`/api/lead-recovery/enrollments/${data.enrollment.id}`,'POST',body);await load();}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 if(!data&&!error)return <section className="lead-recovery-panel"><p className="muted">Carregando acompanhamento…</p></section>;
 return <section className="lead-recovery-panel"><div className="card-heading"><div><h2>Recuperação de Leads</h2><p className="muted">A autorização é registrada automaticamente quando há confirmação explícita no WhatsApp. Descadastramentos continuam bloqueando os envios.</p></div>{data?.enrollment&&<span className={'document-status '+data.enrollment.status}>{recoveryStatuses[data.enrollment.status]}</span>}</div>{error&&<p className="error-box" role="alert">{error}</p>}{data&&<><dl className="crm-info-grid"><div><dt>Consentimento</dt><dd>{recoveryConsentStatuses[data.preference.whatsapp_consent_status]}</dd></div><div><dt>Origem</dt><dd>{data.preference.consent_source||'Não informada'}</dd></div><div><dt>Próxima mensagem</dt><dd>{data.enrollment?.next_attempt_at?new Date(data.enrollment.next_attempt_at).toLocaleString('pt-BR'):'Não agendada'}</dd></div><div><dt>Tentativas concluídas</dt><dd>{data.enrollment?.attempt_count??0}</dd></div></dl>{canOperate&&<div className="table-actions"><button className="button secondary" disabled={Boolean(busy)} onClick={optOut}>Descadastrar</button>{data.enrollment?.status==='scheduled'&&<><button className="button secondary" disabled={Boolean(busy)} onClick={()=>operate('pause')}><Pause size={15}/>Pausar</button><button className="button secondary" disabled={Boolean(busy)} onClick={()=>operate('reschedule',new Date(Date.now()+86400000).toISOString())}><RotateCcw size={15}/>Reagendar</button><button className="button danger" disabled={Boolean(busy)} onClick={()=>operate('cancel')}><XCircle size={15}/>Cancelar</button></>}{data.enrollment?.status==='paused'&&<button className="button secondary" disabled={Boolean(busy)} onClick={()=>operate('resume')}><Play size={15}/>Retomar</button>}</div>}{Boolean(data.history?.length)&&<details><summary>Histórico das tentativas</summary><p className="muted">Horários em America/Sao_Paulo. Cada ciclo mantém sua base original.</p><div className="table-scroll"><table><thead><tr><th>Etapa</th><th>Modelo</th><th>Base / prazo</th><th>Agendada / enviada</th><th>Situação</th></tr></thead><tbody>{data.history.map(a=><tr key={a.id}><td>{a.step_position} · D+{a.day_offset??"—"}</td><td>{a.template_name??"Modelo anterior"}</td><td>{date(a.inactivity_anchor)}<small>{date(a.eligible_at)}</small></td><td>{date(a.scheduled_for)}<small>{date(a.sent_at)}</small></td><td>{attemptStatuses[a.status]??a.status}<small>{a.safe_error||a.failure_code||a.state_reason}</small></td></tr>)}</tbody></table></div></details>}</>}</section>;
}
