'use client';
import {useMemo,useState} from 'react';
import {CheckCircle2,Clock3,Edit3,FilePlus2,RefreshCw,Send,ShieldAlert} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
import {Modal} from '@/components/crm/modal';
import {bodyVariableCount,renderTemplatePreview} from '@/modules/whatsapp/template-manager-domain';

type Draft={id:string;name:string;category:'MARKETING'|'UTILITY';language:string;body_text:string;example_values:string[];submission_status:string;meta_template_id:string|null;rejection_reason:string;safe_error:string;outcome_uncertain:boolean;submitted_at:string|null;synced_at:string|null;version:number;created_by_name:string;updated_by_name:string;updated_at:string};
type Overview={items:Draft[];supported:{categories:string[];languages:{code:string;label:string}[];components:string[]}};
type Form={name:string;category:'MARKETING'|'UTILITY';language:string;body_text:string;example_values:string[];version?:number};
const empty:Form={name:'',category:'MARKETING',language:'pt_BR',body_text:'',example_values:[]};
const statusLabels:Record<string,string>={DRAFT:'Rascunho',SUBMITTING:'Enviando',PENDING:'Em análise',APPROVED:'Aprovado',REJECTED:'Rejeitado',PAUSED:'Pausado',DISABLED:'Desativado',IN_APPEAL:'Em recurso',PENDING_DELETION:'Exclusão pendente',DELETED:'Excluído',LIMIT_EXCEEDED:'Limite excedido',UNKNOWN:'Estado não confirmado',UNCERTAIN:'Resultado incerto'};
const date=(value:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value)):'—';
const badge=(status:string)=>status==='APPROVED'?'completed':status==='PENDING'||status==='SUBMITTING'?'scheduled':status==='DRAFT'?'draft':status==='REJECTED'||status==='DISABLED'||status==='DELETED'?'cancelled':'pending_issue';

export function WhatsAppTemplateManager({initial}:{initial:Overview}){const [data,setData]=useState(initial),[editing,setEditing]=useState<Draft|null|undefined>(undefined),[confirming,setConfirming]=useState<Draft|null>(null),[form,setForm]=useState<Form>(empty),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');const variableCount=bodyVariableCount(form.body_text),preview=useMemo(()=>renderTemplatePreview(form.body_text,form.example_values),[form.body_text,form.example_values]);
 function open(draft?:Draft){setEditing(draft??null);setForm(draft?{name:draft.name,category:draft.category,language:draft.language,body_text:draft.body_text,example_values:[...draft.example_values],version:draft.version}:empty);setError('');setNotice('');}
 function body(value:string){const count=Math.max(0,bodyVariableCount(value));setForm(current=>({...current,body_text:value,example_values:Array.from({length:count},(_,index)=>current.example_values[index]??'')}));}
 async function refresh(){setBusy('sync');setError('');try{setData(await api<Overview>('/api/whatsapp/template-manager/sync','POST',{}));setNotice('Estados sincronizados com a Meta. Nenhuma mensagem foi enviada.');}catch(cause){setError(errorMessage(cause));}finally{setBusy('');}}
 async function save(){setBusy('save');setError('');try{const payload={name:form.name,category:form.category,language:form.language,body_text:form.body_text,example_values:form.example_values,...(editing?{version:form.version}: {})};if(editing)await api(`/api/whatsapp/template-manager/${editing.id}`,'PUT',payload);else await api('/api/whatsapp/template-manager','POST',payload);setData(await api<Overview>('/api/whatsapp/template-manager'));setEditing(undefined);setNotice('Rascunho salvo localmente. Nada foi submetido à Meta.');}catch(cause){setError(errorMessage(cause));}finally{setBusy('');}}
 async function submit(){if(!confirming)return;setBusy('submit');setError('');try{await api(`/api/whatsapp/template-manager/${confirming.id}/submit`,'POST',{version:confirming.version,confirmation:true});setData(await api<Overview>('/api/whatsapp/template-manager'));setConfirming(null);setNotice('Modelo submetido à Meta. Aguarde a aprovação antes de utilizá-lo.');}catch(cause){setError(errorMessage(cause));setConfirming(null);setData(await api<Overview>('/api/whatsapp/template-manager').catch(()=>data));}finally{setBusy('');}}
 return <div className="template-manager"><div className="page-heading"><div><span className="eyebrow green">WHATSAPP OFICIAL</span><h1>Modelos de Mensagens</h1><p>Crie rascunhos seguros, submeta individualmente à Meta e acompanhe a aprovação.</p></div><div className="heading-actions"><button className="button secondary" onClick={refresh} disabled={Boolean(busy)}><RefreshCw size={16}/>{busy==='sync'?'Sincronizando…':'Sincronizar Meta'}</button><button className="button primary" onClick={()=>open()} disabled={Boolean(busy)}><FilePlus2 size={16}/>Novo rascunho</button></div></div>{notice&&<p className="success-box" role="status">{notice}</p>}{error&&<p className="error-box" role="alert">{error}</p>}<section className="info-strip"><ShieldAlert size={18}/><span>Somente modelos aprovados ficam disponíveis para envio e automações. Tokens e credenciais permanecem exclusivamente no servidor.</span></section><div className="template-list">{data.items.map(item=><article className="card template-card" key={item.id}><header><div><span className="eyebrow">{item.category} · {item.language}</span><h2>{item.name}</h2></div><span className={`document-status ${badge(item.submission_status)}`}>{statusLabels[item.submission_status]??item.submission_status}</span></header><p className="template-body">{item.body_text}</p><div className="template-preview"><strong>Prévia com exemplos</strong><p>{renderTemplatePreview(item.body_text,item.example_values)}</p></div><dl><div><dt>Variáveis</dt><dd>{item.example_values.length?item.example_values.map((value,index)=>`{{${index+1}}} = ${value}`).join(' · '):'Nenhuma'}</dd></div><div><dt>Atualização</dt><dd>{date(item.updated_at)} · {item.updated_by_name}</dd></div><div><dt>ID Meta</dt><dd>{item.meta_template_id?'Registrado':'Ainda não submetido'}</dd></div></dl>{(item.rejection_reason||item.safe_error)&&<p className="error-box">{item.rejection_reason||item.safe_error}</p>}{item.outcome_uncertain&&<p className="info-box">Sincronize o catálogo antes de qualquer nova tentativa. O resultado anterior não foi confirmado.</p>}<footer>{['DRAFT','REJECTED'].includes(item.submission_status)&&!item.meta_template_id&&<button className="button secondary" onClick={()=>open(item)} disabled={Boolean(busy)}><Edit3 size={15}/>Editar</button>}{['DRAFT','REJECTED'].includes(item.submission_status)&&!item.meta_template_id&&!item.outcome_uncertain&&<button className="button primary" onClick={()=>setConfirming(item)} disabled={Boolean(busy)}><Send size={15}/>Revisar e submeter</button>}{item.submission_status==='APPROVED'&&<span className="template-ready"><CheckCircle2 size={16}/>Disponível para automações</span>}{item.submission_status==='PENDING'&&<span className="template-waiting"><Clock3 size={16}/>Aguardando análise da Meta</span>}</footer></article>)}{!data.items.length&&<section className="card empty-state"><FilePlus2 size={28}/><h2>Nenhum modelo cadastrado</h2><p>Crie um rascunho para iniciar.</p></section>}</div>
 {editing!==undefined&&<Modal title={editing?'Editar rascunho':'Novo modelo'} onClose={()=>setEditing(undefined)}><div className="crm-form template-form"><div className="crm-form-grid"><label className="crm-field"><span>Nome técnico</span><input value={form.name} onChange={event=>setForm(current=>({...current,name:event.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'_')}))} maxLength={128} placeholder="nome_do_modelo"/></label><label className="crm-field"><span>Categoria</span><select value={form.category} onChange={event=>setForm(current=>({...current,category:event.target.value as Form['category']}))}><option value="MARKETING">Marketing</option><option value="UTILITY">Utilidade</option></select></label><label className="crm-field"><span>Idioma</span><select value={form.language} onChange={event=>setForm(current=>({...current,language:event.target.value}))}>{data.supported.languages.map(language=><option key={language.code} value={language.code}>{language.label}</option>)}</select></label></div><label className="crm-field"><span>Corpo da mensagem</span><textarea rows={8} value={form.body_text} onChange={event=>body(event.target.value)} maxLength={1024} placeholder="Olá, {{1}}! ..."/><small>Variáveis posicionais sequenciais: {'{{1}}'}, {'{{2}}'}…</small></label>{variableCount>0&&<div className="template-examples"><strong>Exemplos exigidos pela Meta</strong>{form.example_values.map((value,index)=><label className="crm-field" key={index}><span>{`{{${index+1}}}`}</span><input value={value} onChange={event=>setForm(current=>({...current,example_values:current.example_values.map((item,i)=>i===index?event.target.value:item)}))} maxLength={120} placeholder={index===0?'Maria':'Exemplo'}/></label>)}</div>}<div className="template-preview"><strong>Prévia</strong><p>{preview||'Digite o conteúdo para visualizar.'}</p></div>{error&&<p className="error-box" role="alert">{error}</p>}<div className="form-actions"><button className="button secondary" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="button primary" onClick={save} disabled={busy==='save'||!form.name||!form.body_text||variableCount<0}>{busy==='save'?'Salvando…':'Salvar rascunho'}</button></div></div></Modal>}
 {confirming&&<Modal title="Confirmar submissão à Meta" onClose={()=>setConfirming(null)}><div className="template-confirm"><p>Revise o conteúdo. Após a submissão, o modelo ficará bloqueado para edição local e só poderá ser usado quando a Meta marcar como aprovado.</p><dl><dt>Nome</dt><dd>{confirming.name}</dd><dt>Categoria e idioma</dt><dd>{confirming.category} · {confirming.language}</dd></dl><div className="template-preview"><strong>Mensagem submetida</strong><p>{renderTemplatePreview(confirming.body_text,confirming.example_values)}</p></div><div className="form-actions"><button className="button secondary" onClick={()=>setConfirming(null)}>Voltar</button><button className="button primary" onClick={submit} disabled={busy==='submit'}>{busy==='submit'?'Submetendo…':'Confirmar submissão'}</button></div></div></Modal>}</div>;
}
