'use client';
import {useState,type FormEvent} from 'react';
import {api,errorMessage} from '@/components/crm/api';
import {Modal} from '@/components/crm/modal';
import {goalMetrics,goalPeriods,type CommercialGoal,type SellerPerformance} from '@/modules/commercial-goals/domain';
import type {performanceDashboard} from '@/modules/commercial-goals/repository';

type Dashboard=Awaited<ReturnType<typeof performanceDashboard>>;type Option={id:string;name:string;kind:string};
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const number=(value:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(value);
function periodDates(period:string,date:string){const start=new Date(`${date}T12:00:00Z`);if(period==='monthly')start.setUTCDate(1);if(period==='quarterly'){start.setUTCDate(1);start.setUTCMonth(Math.floor(start.getUTCMonth()/3)*3);}if(period==='annual'){start.setUTCMonth(0,1);}const end=new Date(start);if(period==='monthly')end.setUTCMonth(end.getUTCMonth()+1);if(period==='quarterly')end.setUTCMonth(end.getUTCMonth()+3);if(period==='annual')end.setUTCFullYear(end.getUTCFullYear()+1);end.setUTCDate(end.getUTCDate()-1);return {starts_on:start.toISOString().slice(0,10),ends_on:end.toISOString().slice(0,10)};}
function total(rows:SellerPerformance[]){const sum=(key:keyof SellerPerformance)=>rows.reduce((value,row)=>value+Number(row[key]??0),0),won=sum('opportunities_won'),lost=sum('opportunities_lost'),contracts=sum('contracts'),sales=sum('sales_value');return {sales,contracts,won,customers:sum('customers'),conversion:won+lost?Math.round(10000*won/(won+lost))/100:0,ticket:contracts?sales/contracts:0};}
export function CommercialPerformance({initial,options}:{initial:Dashboard;options:Option[]}){
 const [data,setData]=useState(initial),[filters,setFilters]=useState({from:initial.from,to:initial.to,team_id:'',seller_user_id:''}),[editing,setEditing]=useState<CommercialGoal|Record<string,never>|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const summary=total(data.people),teams=options.filter(item=>item.kind==='team'),sellers=options.filter(item=>item.kind==='seller');
 async function refresh(next=filters){setBusy(true);setError('');try{const query=new URLSearchParams(Object.entries(next).filter(([,value])=>value));setData(await api<Dashboard>(`/api/commercial-goals?${query}`));setFilters(next);}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget),current=editing&&'id' in editing?editing as CommercialGoal:null,target_kind=String(form.get('target_kind')),period=String(form.get('period')),dates=periodDates(period,String(form.get('starts_on')));try{await api('/api/commercial-goals'+(current?`/${current.id}`:''),current?'PUT':'POST',{target_kind,seller_user_id:target_kind==='seller'?String(form.get('target_id')):null,team_id:target_kind==='team'?String(form.get('target_id')):null,metric:String(form.get('metric')),period,...dates,target_value:Number(form.get('target_value')),...(current?{version:current.version}:{})});await refresh();setEditing(null);setNotice(current?'Meta atualizada.':'Meta criada.');}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}
 return <div className="performance-workspace"><div className="page-heading"><div><span className="eyebrow blue">GESTÃO COMERCIAL</span><h1>Metas e desempenho</h1><p>Resultados calculados com contratos, oportunidades e clientes reais do CRM.</p></div>{data.can_manage&&<button className="button primary" onClick={()=>setEditing({})}>Criar meta</button>}</div>
 {notice&&<p role="status" className="crm-notice">{notice}</p>}{error&&!editing&&<p role="alert" className="error-box">{error}</p>}
 <form className="performance-filters card" onSubmit={event=>{event.preventDefault();void refresh();}}><label className="crm-field"><span>De</span><input type="date" value={filters.from} onChange={event=>setFilters({...filters,from:event.target.value})}/></label><label className="crm-field"><span>Até</span><input type="date" value={filters.to} onChange={event=>setFilters({...filters,to:event.target.value})}/></label>{teams.length>0&&<label className="crm-field"><span>Equipe</span><select value={filters.team_id} onChange={event=>setFilters({...filters,team_id:event.target.value,seller_user_id:''})}><option value="">Todas visíveis</option>{teams.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label className="crm-field"><span>Vendedor</span><select value={filters.seller_user_id} onChange={event=>setFilters({...filters,seller_user_id:event.target.value})}><option value="">Todos visíveis</option>{sellers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button secondary" disabled={busy}>{busy?'Atualizando…':'Aplicar filtros'}</button></form>
 <section className="performance-summary" aria-label="Resumo do período"><div className="card"><small>Valor vendido</small><strong>{money(summary.sales)}</strong></div><div className="card"><small>Contratos</small><strong>{summary.contracts}</strong></div><div className="card"><small>Oportunidades ganhas</small><strong>{summary.won}</strong></div><div className="card"><small>Conversão</small><strong>{number(summary.conversion)}%</strong></div><div className="card"><small>Ticket médio</small><strong>{money(summary.ticket)}</strong></div></section>
 <section className="card performance-section"><div className="card-heading"><div><h2>Metas</h2><p className="muted">Resultados atualizados a partir da operação registrada.</p></div><span className="badge">{data.goals.length}</span></div><div className="goal-grid">{data.goals.map(goal=><article className="goal-card" key={goal.id}><div><span className="badge">{goalPeriods[goal.period]}</span><small>{goal.target_name}</small></div><h3>{goalMetrics[goal.metric]}</h3><div className="goal-values"><strong>{goal.metric==='sales_value'?money(goal.actual_value):number(goal.actual_value)}</strong><span>de {goal.metric==='sales_value'?money(goal.target_value):number(goal.target_value)}</span></div><progress max={Math.max(goal.target_value,goal.actual_value,1)} value={goal.actual_value}/><p>{number(goal.progress)}% atingido · {new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(goal.starts_on+'T12:00:00Z'))} a {new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(goal.ends_on+'T12:00:00Z'))}</p>{data.can_manage&&<button className="button secondary" onClick={()=>setEditing(goal)}>Editar meta</button>}</article>)}{!data.goals.length&&<p className="empty-state">Nenhuma meta visível cadastrada.</p>}</div></section>
 <section className="card performance-section"><div className="card-heading"><div><h2>Desempenho por vendedor</h2><p className="muted">Período de {filters.from.split('-').reverse().join('/')} a {filters.to.split('-').reverse().join('/')}.</p></div></div><div className="performance-table-wrap"><table className="performance-table"><thead><tr><th>Vendedor</th><th>Leads recebidos</th><th>Trabalhados</th><th>Clientes</th><th>Oportunidades</th><th>Ganhos / perdas</th><th>Contratos</th><th>Valor</th><th>Ticket médio</th><th>Tarefas</th><th>Conversão</th></tr></thead><tbody>{data.people.map(row=><tr key={row.user_id}><td><strong>{row.name}</strong><small>{row.team_name??'Sem equipe'}</small></td><td>{row.leads_received}</td><td>{row.leads_worked}</td><td>{row.customers}</td><td>{row.opportunities_open}</td><td>{row.opportunities_won} / {row.opportunities_lost}</td><td>{row.contracts}</td><td>{money(row.sales_value)}</td><td>{money(row.average_ticket)}</td><td>{row.tasks_open} abertas<br/>{row.tasks_completed} concluídas</td><td>{number(row.conversion_rate)}%</td></tr>)}</tbody></table>{!data.people.length&&<p className="empty-state">Nenhum vendedor encontrado para os filtros.</p>}</div></section>
 {data.can_manage&&data.history.length>0&&<section className="card performance-section"><h2>Histórico de metas</h2><div className="commercial-team-history">{data.history.map((item:{id:string;action:string;previous_value:number|null;new_value:number;actor_name:string;created_at:string})=><p key={item.id}><strong>{item.action==='created'?'Meta criada':'Meta atualizada'}</strong><span>{item.previous_value===null?'Valor inicial':number(item.previous_value)} → {number(item.new_value)} · {item.actor_name}</span><time>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(item.created_at))}</time></p>)}</div></section>}
 {editing&&<Modal title={'id' in editing?'Editar meta':'Criar meta'} onClose={()=>!busy&&setEditing(null)}><GoalForm editing={editing} sellers={sellers} teams={teams} busy={busy} error={error} save={save} close={()=>setEditing(null)}/></Modal>}</div>;
}
function GoalForm({editing,sellers,teams,busy,error,save,close}:{editing:CommercialGoal|Record<string,never>;sellers:Option[];teams:Option[];busy:boolean;error:string;save:(event:FormEvent<HTMLFormElement>)=>void;close:()=>void}){const current='id' in editing?editing as CommercialGoal:null,[kind,setKind]=useState<'seller'|'team'>(current?.target_kind??'seller');return <form className="crm-form" onSubmit={save}><label className="crm-field"><span>Meta para</span><select name="target_kind" value={kind} onChange={event=>setKind(event.target.value as 'seller'|'team')}><option value="seller">Vendedor</option><option value="team">Equipe</option></select></label><label className="crm-field"><span>{kind==='seller'?'Vendedor':'Equipe'}</span><select name="target_id" required defaultValue={current?.seller_user_id??current?.team_id??''}><option value="">Selecione</option>{(kind==='seller'?sellers:teams).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="crm-field"><span>Indicador</span><select name="metric" defaultValue={current?.metric??'sales_value'}>{Object.entries(goalMetrics).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="crm-field"><span>Período</span><select name="period" defaultValue={current?.period??'monthly'}>{Object.entries(goalPeriods).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="crm-field"><span>Data de referência</span><input name="starts_on" type="date" required defaultValue={current?.starts_on??new Date().toISOString().slice(0,10)}/></label><label className="crm-field"><span>Valor ou quantidade alvo</span><input name="target_value" type="number" min="0.01" max="999999999999.99" step="0.01" required defaultValue={current?.target_value??''}/></label>{error&&<p role="alert" className="error-box">{error}</p>}<div className="crm-form-actions"><button type="button" className="button secondary" disabled={busy} onClick={close}>Cancelar</button><button className="button primary" disabled={busy}>{busy?'Salvando…':'Salvar meta'}</button></div></form>;}
