import type { PoolClient } from 'pg';
import { database,transaction } from '@/server/db';
import { AccessError,type Actor } from '@/modules/auth/policy';
import { getRecord } from '@/modules/crm/repository';
import { uuid } from '@/modules/crm/domain';
import { billSchema,consumptionSchema,sizingSchema,unitSchema,type EnergyBill,type EnergyUnit,type MonthlyConsumption,type SolarSizing } from './domain';
type Db=Pick<PoolClient,'query'>;

const numberOrNull=(value:unknown)=>value===null?null:Number(value);
const monthSql=(column:string)=>`to_char(${column},'YYYY-MM')`;
function normalizeUnit(row:Record<string,unknown>):EnergyUnit{return JSON.parse(JSON.stringify({...row,voltage:numberOrNull(row.voltage),months_count:Number(row.months_count??0),average_kwh:numberOrNull(row.average_kwh),last_month:row.last_month??''}));}
function normalizeConsumption(row:Record<string,unknown>):MonthlyConsumption{return JSON.parse(JSON.stringify({...row,consumption_kwh:Number(row.consumption_kwh),injected_energy_kwh:numberOrNull(row.injected_energy_kwh),peak_demand_kw:numberOrNull(row.peak_demand_kw),days_billed:numberOrNull(row.days_billed)}));}
function normalizeBill(row:Record<string,unknown>):EnergyBill{return JSON.parse(JSON.stringify({...row,total_amount:Number(row.total_amount),previous_reading:numberOrNull(row.previous_reading),current_reading:numberOrNull(row.current_reading)}));}
function normalizeSizing(row:Record<string,unknown>):SolarSizing{return JSON.parse(JSON.stringify({...row,consumption_months:Number(row.consumption_months),average_consumption_kwh:Number(row.average_consumption_kwh),safety_margin_percent:Number(row.safety_margin_percent),required_generation_kwh:Number(row.required_generation_kwh),solar_irradiation_daily:Number(row.solar_irradiation_daily),performance_ratio_percent:Number(row.performance_ratio_percent),module_power_w:Number(row.module_power_w),required_power_kwp:Number(row.required_power_kwp),module_count:Number(row.module_count),system_power_kwp:Number(row.system_power_kwp),estimated_monthly_generation_kwh:Number(row.estimated_monthly_generation_kwh)}));}
async function customer(actor:Actor,id:string,db:Db,lock=false){const record=await getRecord(actor,id,db,lock);if(record.kind!=='customer')throw new AccessError(404,'Cliente não encontrado.');return record;}
async function unit(actor:Actor,id:string,db:Db=database(),lock=false){uuid.parse(id);const result=await db.query(`SELECT u.* FROM energy_consumer_units u WHERE u.organization_id=$1 AND u.id=$2${lock?' FOR UPDATE':''}`,[actor.organizationId,id]);if(!result.rows[0])throw new AccessError(404,'Unidade consumidora não encontrada.');await customer(actor,result.rows[0].customer_id,db,lock);return result.rows[0] as Record<string,unknown>;}
async function activity(db:Db,actor:Actor,customerId:string,action:string,detail:string){await db.query('INSERT INTO crm_activities(organization_id,record_id,actor_id,action,detail) VALUES ($1,$2,$3,$4,$5)',[actor.organizationId,customerId,actor.userId,action,detail]);}
function conflict(error:unknown,message:string):never{if((error as {code?:string}).code==='23505')throw new AccessError(409,message);throw error;}

export async function listEnergyUnits(actor:Actor,customerId:string){
 await customer(actor,uuid.parse(customerId),database());
 const {rows}=await database().query(`SELECT u.*,
  (SELECT count(*)::int FROM energy_monthly_consumption c WHERE c.organization_id=u.organization_id AND c.consumer_unit_id=u.id) months_count,
  (SELECT round(avg(x.consumption_kwh),2) FROM (SELECT consumption_kwh FROM energy_monthly_consumption c WHERE c.organization_id=u.organization_id AND c.consumer_unit_id=u.id ORDER BY reference_month DESC LIMIT 12) x) average_kwh,
  COALESCE((SELECT ${monthSql('max(c.reference_month)')} FROM energy_monthly_consumption c WHERE c.organization_id=u.organization_id AND c.consumer_unit_id=u.id),'') last_month
  FROM energy_consumer_units u WHERE u.organization_id=$1 AND u.customer_id=$2 ORDER BY u.status,u.created_at,u.id`,[actor.organizationId,customerId]);
 return rows.map(normalizeUnit);
}

export async function getEnergyUnit(actor:Actor,id:string){
 const found=await unit(actor,id);const history=await database().query(`SELECT c.*,${monthSql('c.reference_month')} reference_month FROM energy_monthly_consumption c WHERE c.organization_id=$1 AND c.consumer_unit_id=$2 ORDER BY c.reference_month DESC LIMIT 120`,[actor.organizationId,id]);
 const bills=await database().query(`SELECT b.*,${monthSql('b.reference_month')} reference_month,COALESCE(to_char(b.issue_date,'YYYY-MM-DD'),'') issue_date,COALESCE(to_char(b.due_date,'YYYY-MM-DD'),'') due_date FROM energy_bills b WHERE b.organization_id=$1 AND b.consumer_unit_id=$2 ORDER BY b.reference_month DESC LIMIT 120`,[actor.organizationId,id]);
 const sizings=await database().query(`SELECT s.*,u.name actor_name,to_char(s.consumption_period_start,'YYYY-MM') consumption_period_start,to_char(s.consumption_period_end,'YYYY-MM') consumption_period_end FROM solar_sizings s JOIN users u ON u.id=s.actor_id WHERE s.organization_id=$1 AND s.consumer_unit_id=$2 ORDER BY s.created_at DESC,s.id DESC LIMIT 100`,[actor.organizationId,id]);
 const months=history.rows.map(normalizeConsumption);const last12=months.slice(0,12);const average=last12.length?last12.reduce((sum,item)=>sum+item.consumption_kwh,0)/last12.length:null;
 return {unit:normalizeUnit({...found,months_count:months.length,average_kwh:average,last_month:months[0]?.reference_month??''}),consumptions:months,bills:bills.rows.map(normalizeBill),sizings:sizings.rows.map(normalizeSizing),summary:{months_count:months.length,last_12_months:last12.length,average_kwh:average===null?null:Math.round(average*100)/100,total_kwh:last12.reduce((sum,item)=>sum+item.consumption_kwh,0),ready_for_sizing:last12.length>=12}};
}

export async function listSolarSizings(actor:Actor,unitId:string){await unit(actor,unitId);const {rows}=await database().query(`SELECT s.*,u.name actor_name,to_char(s.consumption_period_start,'YYYY-MM') consumption_period_start,to_char(s.consumption_period_end,'YYYY-MM') consumption_period_end FROM solar_sizings s JOIN users u ON u.id=s.actor_id WHERE s.organization_id=$1 AND s.consumer_unit_id=$2 ORDER BY s.created_at DESC,s.id DESC LIMIT 100`,[actor.organizationId,unitId]);return rows.map(normalizeSizing);}

export async function createSolarSizing(actor:Actor,input:unknown){const data=sizingSchema.parse(input);return transaction(async db=>{const parent=await unit(actor,data.consumer_unit_id,db,true);if(parent.status!=='active')throw new AccessError(409,'Reative a unidade antes de dimensionar o sistema.');const history=await db.query('SELECT reference_month,consumption_kwh FROM energy_monthly_consumption WHERE organization_id=$1 AND consumer_unit_id=$2 ORDER BY reference_month DESC LIMIT 12',[actor.organizationId,data.consumer_unit_id]);if(!history.rowCount)throw new AccessError(422,'Cadastre ao menos um mês de consumo antes de dimensionar.');const total=history.rows.reduce((sum,row)=>sum+Number(row.consumption_kwh),0);const average=total/history.rows.length;if(average<=0)throw new AccessError(422,'O consumo médio precisa ser maior que zero para dimensionar.');
 const requiredGeneration=average*(1+data.safety_margin_percent/100);const requiredPower=requiredGeneration/(data.solar_irradiation_daily*30*(data.performance_ratio_percent/100));const moduleCount=Math.ceil(requiredPower*1000/data.module_power_w);const systemPower=moduleCount*data.module_power_w/1000;const estimatedGeneration=systemPower*data.solar_irradiation_daily*30*(data.performance_ratio_percent/100);const start=history.rows.at(-1).reference_month;const end=history.rows[0].reference_month;
 const result=await db.query(`INSERT INTO solar_sizings(organization_id,consumer_unit_id,customer_id,actor_id,consumption_months,consumption_period_start,consumption_period_end,average_consumption_kwh,safety_margin_percent,required_generation_kwh,solar_irradiation_daily,performance_ratio_percent,module_power_w,required_power_kwp,module_count,system_power_kwp,estimated_monthly_generation_kwh,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING *,''::text actor_name,to_char(consumption_period_start,'YYYY-MM') consumption_period_start,to_char(consumption_period_end,'YYYY-MM') consumption_period_end`,[actor.organizationId,data.consumer_unit_id,parent.customer_id,actor.userId,history.rows.length,start,end,average,data.safety_margin_percent,requiredGeneration,data.solar_irradiation_daily,data.performance_ratio_percent,data.module_power_w,requiredPower,moduleCount,systemPower,estimatedGeneration,data.notes]);await activity(db,actor,String(parent.customer_id),'solar.sizing.created',`${systemPower.toFixed(2)} kWp; ${moduleCount} módulos`);return normalizeSizing({...result.rows[0],actor_name:actor.name});});}

export async function saveEnergyUnit(actor:Actor,input:unknown,id?:string){const data=unitSchema.parse(input);return transaction(async db=>{try{
 const current=id?await unit(actor,id,db,true):null;const owner=await customer(actor,current?String(current.customer_id):data.customer_id,db,true);
 if(current&&data.customer_id!==current.customer_id)throw new AccessError(400,'A unidade não pode ser transferida para outro cliente.');
 if(current&&data.version!==current.version)throw new AccessError(409,'Esta unidade foi atualizada por outra pessoa. Recarregue antes de salvar.');
 const values=[data.label,data.consumer_unit_number,data.installation_number,data.utility,data.holder_name,data.tariff_group,data.supply_type,data.voltage,data.service_address];
 let savedId=id;
 if(current)await db.query('UPDATE energy_consumer_units SET label=$3,consumer_unit_number=$4,installation_number=$5,utility=$6,holder_name=$7,tariff_group=$8,supply_type=$9,voltage=$10,service_address=$11,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,...values]);
 else savedId=(await db.query('INSERT INTO energy_consumer_units(organization_id,customer_id,label,consumer_unit_number,installation_number,utility,holder_name,tariff_group,supply_type,voltage,service_address,is_demo) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id',[actor.organizationId,data.customer_id,...values,owner.is_demo])).rows[0].id;
 await activity(db,actor,String(owner.id),current?'energy.unit.updated':'energy.unit.created',data.label);return (await getEnergyUnitWithDb(actor,savedId!,db));
 }catch(error){conflict(error,'Já existe uma unidade com este número para a distribuidora informada.');}});}
async function getEnergyUnitWithDb(actor:Actor,id:string,db:Db){const found=await unit(actor,id,db);return normalizeUnit({...found,months_count:0,average_kwh:null,last_month:''});}
export async function setEnergyUnitStatus(actor:Actor,id:string,status:'active'|'archived',version:number){return transaction(async db=>{const current=await unit(actor,id,db,true);if(current.version!==version)throw new AccessError(409,'Esta unidade foi atualizada. Recarregue antes de continuar.');await db.query('UPDATE energy_consumer_units SET status=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,status]);await activity(db,actor,String(current.customer_id),status==='archived'?'energy.unit.archived':'energy.unit.restored',String(current.label));return getEnergyUnitWithDb(actor,id,db);});}

export async function saveConsumption(actor:Actor,input:unknown,id?:string){const data=consumptionSchema.parse(input);return transaction(async db=>{try{const parent=await unit(actor,data.consumer_unit_id,db,true);if(parent.status!=='active')throw new AccessError(409,'Reative a unidade antes de alterar o histórico.');let current:Record<string,unknown>|null=null;if(id){uuid.parse(id);current=(await db.query('SELECT * FROM energy_monthly_consumption WHERE organization_id=$1 AND id=$2 FOR UPDATE',[actor.organizationId,id])).rows[0]??null;if(!current||current.consumer_unit_id!==data.consumer_unit_id)throw new AccessError(404,'Consumo mensal não encontrado.');if(current.version!==data.version)throw new AccessError(409,'Este consumo foi atualizado por outra pessoa. Recarregue antes de salvar.');}
 const values=[data.reference_month+'-01',data.consumption_kwh,data.injected_energy_kwh,data.peak_demand_kw,data.days_billed,data.source,data.notes];let savedId=id;
 if(current)await db.query('UPDATE energy_monthly_consumption SET reference_month=$3,consumption_kwh=$4,injected_energy_kwh=$5,peak_demand_kw=$6,days_billed=$7,source=$8,notes=$9,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,...values]);
 else savedId=(await db.query('INSERT INTO energy_monthly_consumption(organization_id,consumer_unit_id,reference_month,consumption_kwh,injected_energy_kwh,peak_demand_kw,days_billed,source,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[actor.organizationId,data.consumer_unit_id,...values])).rows[0].id;
 await activity(db,actor,String(parent.customer_id),current?'energy.consumption.updated':'energy.consumption.created',data.reference_month);const row=(await db.query(`SELECT c.*,${monthSql('c.reference_month')} reference_month FROM energy_monthly_consumption c WHERE c.organization_id=$1 AND c.id=$2`,[actor.organizationId,savedId])).rows[0];return normalizeConsumption(row);
 }catch(error){conflict(error,'Já existe consumo cadastrado para este mês.');}});}

export async function saveBill(actor:Actor,input:unknown,id?:string){const data=billSchema.parse(input);return transaction(async db=>{try{const parent=await unit(actor,data.consumer_unit_id,db,true);if(parent.status!=='active')throw new AccessError(409,'Reative a unidade antes de alterar as faturas.');let current:Record<string,unknown>|null=null;if(id){uuid.parse(id);current=(await db.query('SELECT * FROM energy_bills WHERE organization_id=$1 AND id=$2 FOR UPDATE',[actor.organizationId,id])).rows[0]??null;if(!current||current.consumer_unit_id!==data.consumer_unit_id)throw new AccessError(404,'Fatura não encontrada.');if(current.version!==data.version)throw new AccessError(409,'Esta fatura foi atualizada por outra pessoa. Recarregue antes de salvar.');}
 const values=[data.reference_month+'-01',data.invoice_number,data.issue_date||null,data.due_date||null,data.total_amount,data.tariff_flag,data.previous_reading,data.current_reading,data.notes];let savedId=id;
 if(current)await db.query('UPDATE energy_bills SET reference_month=$3,invoice_number=$4,issue_date=$5,due_date=$6,total_amount=$7,tariff_flag=$8,previous_reading=$9,current_reading=$10,notes=$11,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,...values]);
 else savedId=(await db.query('INSERT INTO energy_bills(organization_id,consumer_unit_id,reference_month,invoice_number,issue_date,due_date,total_amount,tariff_flag,previous_reading,current_reading,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id',[actor.organizationId,data.consumer_unit_id,...values])).rows[0].id;
 await activity(db,actor,String(parent.customer_id),current?'energy.bill.updated':'energy.bill.created',data.reference_month);const row=(await db.query(`SELECT b.*,${monthSql('b.reference_month')} reference_month,COALESCE(to_char(b.issue_date,'YYYY-MM-DD'),'') issue_date,COALESCE(to_char(b.due_date,'YYYY-MM-DD'),'') due_date FROM energy_bills b WHERE b.organization_id=$1 AND b.id=$2`,[actor.organizationId,savedId])).rows[0];return normalizeBill(row);
 }catch(error){conflict(error,'Já existe uma fatura cadastrada para este mês.');}});}
