'use client';
import { useEffect,useState } from 'react';
import { Archive,Boxes,Edit,History,PackagePlus,Plus,RotateCcw } from 'lucide-react';
import { api,errorMessage } from '@/components/crm/api';
import { Modal } from '@/components/crm/modal';
import { equipmentCategories,equipmentUnits,type SolarEquipment,type SolarKit } from '@/modules/solar-catalog/domain';

type HistoryEntry={id:string;action:string;actor_name:string;created_at:string};
type Detail=(SolarEquipment|SolarKit)&{history:HistoryEntry[]};
const num=(value:FormDataEntryValue|null)=>value===''||value===null?null:Number(value);
const actions:Record<string,string>={created:'Criado',updated:'Atualizado',archived:'Arquivado',restored:'Reativado'};
export function CatalogWorkspace({canManage}:{canManage:boolean}){
 const [equipment,setEquipment]=useState<SolarEquipment[]>([]);const [kits,setKits]=useState<SolarKit[]>([]);const [tab,setTab]=useState<'equipment'|'kits'>('equipment');const [modal,setModal]=useState<'equipment'|'kit'|'history'|null>(null);const [editing,setEditing]=useState<SolarEquipment|SolarKit|null>(null);const [detail,setDetail]=useState<Detail|null>(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function load(){setLoading(true);try{const [items,commercialKits]=await Promise.all([api<SolarEquipment[]>('/api/solar-equipment?status=all'),api<SolarKit[]>('/api/solar-kits?status=all')]);setEquipment(items);setKits(commercialKits);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();Promise.all([api<SolarEquipment[]>('/api/solar-equipment?status=all','GET',undefined,controller.signal),api<SolarKit[]>('/api/solar-kits?status=all','GET',undefined,controller.signal)]).then(([items,commercialKits])=>{setEquipment(items);setKits(commercialKits);setLoading(false);}).catch(e=>{if(!controller.signal.aborted){setError(errorMessage(e));setLoading(false);}});return()=>controller.abort();},[]);
 function open(kind:'equipment'|'kit',item:SolarEquipment|SolarKit|null=null){setEditing(item);setError('');setNotice('');setModal(kind);}
 async function showHistory(kind:'equipment'|'kit',id:string){setBusy(true);setError('');try{setDetail(await api<Detail>(`/api/solar-${kind==='equipment'?'equipment':'kits'}/${id}`));setModal('history');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{if(modal==='equipment'){const current=editing as SolarEquipment|null;const body={category:String(form.get('category')),name:String(form.get('name')),manufacturer:String(form.get('manufacturer')),model:String(form.get('model')),sku:String(form.get('sku')),nominal_power_w:num(form.get('nominal_power_w')),efficiency_percent:num(form.get('efficiency_percent')),phases:num(form.get('phases')),mppt_count:num(form.get('mppt_count')),unit:String(form.get('unit')),technical_notes:String(form.get('technical_notes')),...(current?{version:current.version}:{})};await api(`/api/solar-equipment${current?'/'+current.id:''}`,current?'PUT':'POST',body);setNotice(current?'Equipamento atualizado.':'Equipamento cadastrado.');}else{const current=editing as SolarKit|null;const items=equipment.map(item=>({equipment_id:item.id,quantity:Number(form.get('item_'+item.id)||0)})).filter(item=>item.quantity>0);const body={name:String(form.get('name')),code:String(form.get('code')),description:String(form.get('description')),items,...(current?{version:current.version}:{})};await api(`/api/solar-kits${current?'/'+current.id:''}`,current?'PUT':'POST',body);setNotice(current?'Kit comercial atualizado.':'Kit comercial cadastrado.');}setModal(null);setEditing(null);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function status(kind:'equipment'|'kit',item:SolarEquipment|SolarKit){setBusy(true);setError('');try{const action=item.status==='active'?'archive':'restore';await api(`/api/solar-${kind==='equipment'?'equipment':'kits'}/${item.id}/${action}`,'POST',{version:item.version});setNotice(action==='archive'?'Item arquivado.':'Item reativado.');await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <><div className="page-heading"><div><span className="eyebrow green">ENERGIA SOLAR</span><h1>Equipamentos e kits solares.</h1><p>Catálogo técnico e composições comerciais disponíveis para os dimensionamentos.</p></div>{canManage&&<button className="button primary" onClick={()=>open(tab==='equipment'?'equipment':'kit')}>{tab==='equipment'?<Plus size={16}/>:<PackagePlus size={16}/>} {tab==='equipment'?'Novo equipamento':'Novo kit'}</button>}</div>
  {notice&&<p className="crm-notice" role="status">{notice}</p>}{error&&!modal&&<p className="error-box" role="alert">{error}</p>}
  <div className="crm-tabs" aria-label="Seções do catálogo"><button className={tab==='equipment'?'selected':''} aria-pressed={tab==='equipment'} onClick={()=>setTab('equipment')}>Equipamentos</button><button className={tab==='kits'?'selected':''} aria-pressed={tab==='kits'} onClick={()=>setTab('kits')}>Kits comerciais</button></div>
  {loading?<p className="crm-loading" role="status">Carregando catálogo…</p>:tab==='equipment'?<EquipmentList items={equipment} canManage={canManage} edit={item=>open('equipment',item)} history={id=>showHistory('equipment',id)} status={item=>status('equipment',item)} busy={busy}/>:<KitList items={kits} canManage={canManage} edit={item=>open('kit',item)} history={id=>showHistory('kit',id)} status={item=>status('kit',item)} busy={busy}/>} 
  {modal&&<Modal title={modal==='equipment'?(editing?'Editar equipamento':'Novo equipamento'):modal==='kit'?(editing?'Editar kit comercial':'Novo kit comercial'):`Histórico · ${detail?.name??''}`} onClose={()=>{if(!busy)setModal(null);}}>{modal==='history'?<HistoryView detail={detail}/>:<form className="crm-form" onSubmit={submit}>{modal==='equipment'?<EquipmentFields value={editing as SolarEquipment|null}/>:<KitFields value={editing as SolarKit|null} equipment={equipment.filter(item=>item.status==='active')}/>} {error&&<p className="error-box" role="alert">{error}</p>}<div className="crm-form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" disabled={busy}>{busy?'Salvando…':'Salvar'}</button></div></form>}</Modal>}
 </>;
}
function EquipmentList({items,canManage,edit,history,status,busy}:{items:SolarEquipment[];canManage:boolean;edit:(item:SolarEquipment)=>void;history:(id:string)=>void;status:(item:SolarEquipment)=>void;busy:boolean}){return items.length===0?<div className="card energy-empty"><Boxes size={28}/><h3>Catálogo vazio</h3><p>Cadastre módulos, inversores, estruturas e componentes.</p></div>:<div className="catalog-grid">{items.map(item=><article className={`card catalog-card ${item.status==='archived'?'archived':''}`} key={item.id}><header><span className="badge">{equipmentCategories[item.category]}</span><span className="badge">{item.status==='active'?'Ativo':'Arquivado'}</span></header><h2>{item.name}</h2><p>{[item.manufacturer,item.model].filter(Boolean).join(' · ')||'Fabricante e modelo não informados'}</p><dl><div><dt>Potência nominal</dt><dd>{item.nominal_power_w?`${item.nominal_power_w.toLocaleString('pt-BR')} W`:'Não aplicável'}</dd></div><div><dt>Código</dt><dd>{item.sku||'Não informado'}</dd></div></dl><footer><button className="button secondary" disabled={busy} onClick={()=>history(item.id)}><History size={15}/>Histórico</button>{canManage&&<><button className="button secondary" onClick={()=>edit(item)}><Edit size={15}/>Editar</button><button className="icon-button" aria-label={`${item.status==='active'?'Arquivar':'Reativar'} ${item.name}`} disabled={busy} onClick={()=>status(item)}>{item.status==='active'?<Archive size={17}/>:<RotateCcw size={17}/>}</button></>}</footer></article>)}</div>}
function KitList({items,canManage,edit,history,status,busy}:{items:SolarKit[];canManage:boolean;edit:(item:SolarKit)=>void;history:(id:string)=>void;status:(item:SolarKit)=>void;busy:boolean}){return items.length===0?<div className="card energy-empty"><PackagePlus size={28}/><h3>Nenhum kit comercial</h3><p>Monte um kit usando os equipamentos ativos do catálogo.</p></div>:<div className="catalog-grid kits">{items.map(item=><article className={`card catalog-card ${item.status==='archived'?'archived':''}`} key={item.id}><header><span className="badge">Kit comercial</span><span className="badge">{item.status==='active'?'Ativo':'Arquivado'}</span></header><h2>{item.name}</h2><p>{item.description||'Sem descrição.'}</p><div className="kit-metrics"><strong>{item.module_count.toLocaleString('pt-BR')} módulos</strong><strong>{item.dc_power_kwp.toLocaleString('pt-BR')} kWp CC</strong><span>{item.inverter_power_kw.toLocaleString('pt-BR')} kW inversores</span></div><ul>{item.items.map(entry=><li key={entry.equipment_id}><span>{entry.name}</span><strong>{entry.quantity.toLocaleString('pt-BR')} {equipmentUnits[entry.unit]}</strong></li>)}</ul><footer><button className="button secondary" disabled={busy} onClick={()=>history(item.id)}><History size={15}/>Histórico</button>{canManage&&<><button className="button secondary" onClick={()=>edit(item)}><Edit size={15}/>Editar</button><button className="icon-button" aria-label={`${item.status==='active'?'Arquivar':'Reativar'} ${item.name}`} disabled={busy} onClick={()=>status(item)}>{item.status==='active'?<Archive size={17}/>:<RotateCcw size={17}/>}</button></>}</footer></article>)}</div>}
function EquipmentFields({value}:{value:SolarEquipment|null}){return <><div className="crm-form-grid"><label className="crm-field"><span>Categoria</span><select name="category" defaultValue={value?.category??'module'}>{Object.entries(equipmentCategories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><Field label="Nome" name="name" required defaultValue={value?.name}/><Field label="Fabricante" name="manufacturer" defaultValue={value?.manufacturer}/><Field label="Modelo" name="model" defaultValue={value?.model}/><Field label="Código interno" name="sku" defaultValue={value?.sku}/><Field label="Potência nominal (W)" name="nominal_power_w" type="number" min="0.01" step="0.01" defaultValue={value?.nominal_power_w??''}/><Field label="Eficiência (%)" name="efficiency_percent" type="number" min="0.01" max="100" step="0.01" defaultValue={value?.efficiency_percent??''}/><Field label="Número de fases" name="phases" type="number" min="1" max="3" step="1" defaultValue={value?.phases??''}/><Field label="Quantidade de MPPT" name="mppt_count" type="number" min="1" max="100" step="1" defaultValue={value?.mppt_count??''}/><label className="crm-field"><span>Unidade de medida</span><select name="unit" defaultValue={value?.unit??'unit'}>{Object.entries(equipmentUnits).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><label className="crm-field"><span>Características técnicas</span><textarea name="technical_notes" rows={4} maxLength={4000} defaultValue={value?.technical_notes}/></label></>}
function KitFields({value,equipment}:{value:SolarKit|null;equipment:SolarEquipment[]}){const selected=new Map(value?.items.map(item=>[item.equipment_id,item.quantity])??[]);return <><div className="crm-form-grid"><Field label="Nome do kit" name="name" required defaultValue={value?.name}/><Field label="Código interno" name="code" defaultValue={value?.code}/></div><label className="crm-field"><span>Descrição comercial</span><textarea name="description" rows={3} maxLength={4000} defaultValue={value?.description}/></label><fieldset className="kit-composer"><legend>Composição e quantidade</legend>{equipment.length===0?<p className="muted">Cadastre equipamentos ativos antes de montar o kit.</p>:equipment.map(item=><label key={item.id}><span><strong>{item.name}</strong><small>{equipmentCategories[item.category]}{item.nominal_power_w?` · ${item.nominal_power_w} W`:''}</small></span><input aria-label={`Quantidade de ${item.name}`} name={'item_'+item.id} type="number" min="0" max="1000000" step="0.001" defaultValue={selected.get(item.id)??''} placeholder="0"/></label>)}</fieldset></>}
function HistoryView({detail}:{detail:Detail|null}){return !detail?<p>Carregando…</p>:<div className="catalog-history">{detail.history.map(entry=><article key={entry.id}><strong>{actions[entry.action]??entry.action}</strong><span>{entry.actor_name}</span><time>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(entry.created_at))}</time></article>)}</div>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...input}=props;return <label className="crm-field"><span>{label}</span><input {...input} maxLength={input.type==='number'?undefined:180}/></label>}
