import {NextResponse} from 'next/server';
import {z} from 'zod';
import {apiActor} from '@/server/session';
import {failure,readMutation} from '@/server/http';
import {AccessError} from '@/modules/auth/policy';
import {createLeadFromWhatsApp,getWhatsAppConversation,linkWhatsAppConversation,listWhatsAppConversations,markWhatsAppConversationRead,searchWhatsAppLinkOptions,WhatsAppLeadDuplicateError} from '@/modules/whatsapp/inbox';
import {sendWhatsAppTemplate,sendWhatsAppText} from '@/modules/whatsapp/outbound';
import {automationConversationInput} from '@/modules/automations/domain';
import {updateConversationAutomation} from '@/modules/automations/repository';
type Context={params:Promise<{segments?:string[]}>};
async function handle(request:Request,context:Context){try{const actor=await apiActor(),url=new URL(request.url),query=Object.fromEntries(url.searchParams),[id,action,...rest]=(await context.params).segments??[],respond=(value:unknown,status=200)=>NextResponse.json(value,{status,headers:{'Cache-Control':'no-store'}});if(rest.length)throw new AccessError(404,'Recurso não encontrado.');if(request.method==='GET'&&!id)return respond(await listWhatsAppConversations(actor,query));if(request.method==='GET'&&id==='records'&&!action)return respond(await searchWhatsAppLinkOptions(actor,z.string().max(120).parse(query.q??'')));if(request.method==='GET'&&id&&!action)return respond(await getWhatsAppConversation(actor,id,z.coerce.number().int().min(1).max(100000).parse(query.page??1)));if(request.method==='POST'&&id&&action==='read')return respond(await markWhatsAppConversationRead(actor,id,await readMutation(request)));if(request.method==='POST'&&id&&action==='create-lead')return respond(await createLeadFromWhatsApp(actor,id,await readMutation(request)),201);if(request.method==='POST'&&id&&action==='messages')return respond(await sendWhatsAppText(actor,id,await readMutation(request)));if(request.method==='POST'&&id&&action==='template')return respond(await sendWhatsAppTemplate(actor,id,await readMutation(request)));if(request.method==='PUT'&&id&&action==='link')return respond(await linkWhatsAppConversation(actor,id,await readMutation(request)));if(request.method==='PUT'&&id&&action==='automation')return respond(await updateConversationAutomation(actor,id,automationConversationInput.parse(await readMutation(request))));throw new AccessError(404,'Recurso não encontrado.');}catch(error){if(error instanceof WhatsAppLeadDuplicateError)return NextResponse.json({error:error.message,matches:error.matches,multiple:error.multiple},{status:409,headers:{'Cache-Control':'no-store'}});return failure(error);}}
export const GET=handle;export const POST=handle;export const PUT=handle;
