import { CommercialMetrics } from '@/components/commercial/metrics';
import { DashboardSummary } from '@/components/crm/dashboard-summary';
import Link from 'next/link';
import { ArrowUpRight, Check, ShieldCheck, Users, Sun, Zap, CircleDashed, ArrowRight, MessageCircle, FileText, Wrench, Sprout } from 'lucide-react';
import { pageActor } from '@/server/session';
import { recentAudit } from '@/modules/core/repository';
import { requirePermission } from '@/modules/auth/policy';
const actionNames: Record<string,string>={'auth.login':'Acesso à plataforma','auth.logout':'Sessão encerrada','auth.password_reset':'Senha redefinida'};
export default async function Dashboard() {
  const actor=await pageActor(); requirePermission(actor,'dashboard.read');
  const events=actor.permissions.includes('audit.read')?await recentAudit(actor):[];
  const date=new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'long',year:'numeric',timeZone:'America/Sao_Paulo'}).format(new Date());
  return <><div className="page-heading"><div><span className="eyebrow blue">VISÃO GERAL</span><h1>Sua operação, conectada.</h1><p>Olá, {actor.name.split(' ')[0]}. Este é o ponto de partida da sua jornada solar.</p></div><span className="date-label"><CalendarIcon/>{date}</span></div>
    <section className="welcome-banner"><div><span className="badge light"><span className="status-dot"/> WORKSPACE INICIADO</span><h2>Uma base sólida para<br/>crescer com energia.</h2><p>Organize leads, conheça seus clientes e acompanhe<br className="desktop-break"/> cada conversa com um histórico conectado.</p><a className="banner-link" href="#jornada">Conheça a jornada comercial <ArrowRight size={17}/></a></div><div className="banner-art" aria-hidden="true"><div className="sun-circle"><Sun size={55} strokeWidth={1.3}/></div><span className="orbit o1"/><span className="orbit o2"/><span className="power-chip"><Zap size={20}/> PECLAT SOLAR</span></div></section>
    <DashboardSummary actor={actor}/>{actor.permissions.some(p=>p==='crm.all'||p==='crm.own')&&<CommercialMetrics/>}
    <div className="dashboard-columns"><section className="card journey-card" id="jornada"><div className="card-heading"><div><span className="eyebrow blue">DO CONTATO À CONQUISTA</span><h2>A jornada do seu cliente</h2></div><Sprout size={25} className="green"/></div><p className="muted">Uma visão integrada de cada etapa do projeto solar.</p><div className="journey">{[[Users,'Conectar','Leads e atendimento'],[FileText,'Propor','Análise e negociação'],[Wrench,'Instalar','Projeto e homologação'],[Sun,'Acompanhar','Pós-venda e indicações']].map(([Icon,title,subtitle],index)=>{const I=Icon as typeof Users;return <div className="journey-step" key={String(title)}><span className="step-icon"><I size={21}/></span><small>0{index+1}</small><h3>{String(title)}</h3><p>{String(subtitle)}</p></div>;})}</div><div className="info-strip"><ShieldCheck size={18}/><span>Dados e acessos separados por organização desde o início.</span></div></section>
    <section className="card setup-card"><div className="card-heading"><h2>Seu workspace</h2><span className="badge green-badge">BASE INICIADA</span></div><div className="setup-row"><span className="check-icon"><Check size={16}/></span><div><strong>Organização cadastrada</strong><small>{actor.organizationName}</small></div></div><div className="setup-row"><span className="check-icon"><Check size={16}/></span><div><strong>Acesso protegido</strong><small>{actor.roleName} · sessão ativa</small></div></div><div className="setup-row"><span className="pending-icon"><MessageCircle size={17}/></span><div><strong>WhatsApp Business</strong><small>Fundação segura preparada na fase 8.1</small></div></div>{actor.permissions.includes('settings.read')&&<Link className="text-link" href="/configuracoes">Ver configurações <ArrowUpRight size={17}/></Link>}</section></div>
    <section className="card activity-card"><div className="card-heading"><div><h2>Atividade recente</h2><p className="muted">{actor.permissions.includes('audit.read')?'Registros reais de acesso da sua organização.':'O histórico comercial estará disponível com os próximos módulos.'}</p></div><span className="badge">SEGURANÇA</span></div>{events.length?<div className="activity-list">{events.map(event=><div className="activity-row" key={event.id}><span className="activity-symbol"><ShieldCheck size={16}/></span><div><strong>{actionNames[event.action]??'Atividade de segurança'}</strong><small>{event.name??'Sistema'}</small></div><time dateTime={event.created_at.toISOString()}>{new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'America/Sao_Paulo'}).format(event.created_at)}</time></div>)}</div>:<div className="empty-state"><CircleDashed size={30}/><h3>Tudo pronto para começar</h3><p>As atividades aparecerão aqui conforme sua operação evoluir.</p></div>}</section>
  </>;
}
function CalendarIcon(){return <span aria-hidden="true">◷</span>;}
