import {z} from 'zod';
import {uuid} from '@/modules/crm/domain';

const text=(max:number)=>z.string().trim().max(max).default('');
const optionalUuid=z.union([uuid,z.literal(''),z.null()]).optional().transform(value=>value||null);
const optionalDate=z.union([z.iso.date(),z.literal(''),z.null()]).optional().transform(value=>value||null);
const version=z.coerce.number().int().positive().optional();
export const warrantyCategories={module:'Módulos',inverter:'Inversor',microinverter:'Microinversor',structure:'Estrutura',labor:'Instalação e mão de obra',auxiliary:'Equipamento auxiliar',other:'Outro'} as const;
export const warrantyLifecycle={normal:'Vigente',claimed:'Acionada',closed:'Encerrada',cancelled:'Cancelada'} as const;
export const warrantyStatuses={active:'Ativa',expiring:'Próxima do vencimento',expired:'Vencida',claimed:'Acionada',closed:'Encerrada',cancelled:'Cancelada'} as const;
export const ticketCategories={question:'Dúvida',installation:'Instalação',generation:'Geração',equipment:'Equipamento',inverter:'Inversor',module:'Módulo',electrical:'Elétrica',structure:'Estrutura',warranty:'Garantia',maintenance:'Manutenção',financial:'Financeiro',documentation:'Documentação',other:'Outro'} as const;
export const ticketPriorities={low:'Baixa',medium:'Média',high:'Alta',critical:'Crítica'} as const;
export const ticketStatuses={open:'Aberto',analysis:'Em análise',waiting_customer:'Aguardando cliente',waiting_supplier:'Aguardando fornecedor',waiting_part:'Aguardando peça',scheduled:'Agendado',in_service:'Em atendimento',resolved:'Resolvido',closed:'Encerrado',cancelled:'Cancelado'} as const;
export const claimStatuses={awaiting_send:'Aguardando envio',sent:'Enviado ao fornecedor',analysis:'Em análise',approved:'Aprovado',rejected:'Recusado',replacement:'Substituição',repair:'Reparo',closed:'Encerrado'} as const;
export const maintenanceTypes={preventive:'Preventiva',corrective:'Corretiva',inspection:'Vistoria',cleaning:'Limpeza',replacement:'Substituição',adjustment:'Ajuste',diagnostic:'Diagnóstico',other:'Outro'} as const;
export const maintenanceStatuses={requested:'Solicitada',scheduled:'Agendada',in_progress:'Em execução',completed:'Concluída',cancelled:'Cancelada'} as const;

export const warrantySchema=z.object({installation_id:uuid,contract_item_id:optionalUuid,category:z.enum(Object.keys(warrantyCategories) as [keyof typeof warrantyCategories,...(keyof typeof warrantyCategories)[]]),description:z.string().trim().min(2).max(500),manufacturer:text(180),serial_number:text(180),supplier:text(180),start_on:z.iso.date(),duration_months:z.coerce.number().int().min(1).max(600),notes:text(4000),lifecycle:z.enum(Object.keys(warrantyLifecycle) as [keyof typeof warrantyLifecycle,...(keyof typeof warrantyLifecycle)[]]).default('normal'),responsible_user_id:uuid,version}).strict();
export const ticketSchema=z.object({client_id:uuid,contract_id:optionalUuid,installation_id:optionalUuid,warranty_id:optionalUuid,contract_item_id:optionalUuid,title:z.string().trim().min(2).max(180),description:text(4000),category:z.enum(Object.keys(ticketCategories) as [keyof typeof ticketCategories,...(keyof typeof ticketCategories)[]]),priority:z.enum(Object.keys(ticketPriorities) as [keyof typeof ticketPriorities,...(keyof typeof ticketPriorities)[]]).default('medium'),status:z.enum(Object.keys(ticketStatuses) as [keyof typeof ticketStatuses,...(keyof typeof ticketStatuses)[]]).default('open'),responsible_user_id:uuid,due_on:optionalDate,resolution:text(4000),version}).strict();
export const claimSchema=z.object({warranty_id:uuid,ticket_id:uuid,reason:z.string().trim().min(2).max(4000),supplier:text(180),protocol:text(180),notes:text(4000),status:z.enum(Object.keys(claimStatuses) as [keyof typeof claimStatuses,...(keyof typeof claimStatuses)[]]).default('awaiting_send'),result:text(4000),responsible_user_id:uuid,version}).strict();
export const maintenanceSchema=z.object({installation_id:uuid,ticket_id:optionalUuid,warranty_id:optionalUuid,type:z.enum(Object.keys(maintenanceTypes) as [keyof typeof maintenanceTypes,...(keyof typeof maintenanceTypes)[]]),reason:z.string().trim().min(2).max(500),description:text(4000),responsible_user_id:uuid,planned_on:optionalDate,scheduled_on:optionalDate,executed_on:optionalDate,status:z.enum(Object.keys(maintenanceStatuses) as [keyof typeof maintenanceStatuses,...(keyof typeof maintenanceStatuses)[]]).default('requested'),notes:text(4000),resolution:text(4000),internal_cost:z.coerce.number().min(0).max(99999999999.99).default(0),charged_amount:z.coerce.number().min(0).max(99999999999.99).default(0),no_charge:z.boolean().default(false),financial_notes:text(2000),version}).strict().superRefine((value,ctx)=>{if(value.no_charge&&value.charged_amount)ctx.addIssue({code:'custom',path:['charged_amount'],message:'Serviço gratuito não pode ter valor cobrado.'});if(value.status==='scheduled'&&!value.scheduled_on)ctx.addIssue({code:'custom',path:['scheduled_on'],message:'Informe a data agendada.'});if(value.status==='completed'&&(!value.executed_on||!value.resolution))ctx.addIssue({code:'custom',path:['resolution'],message:'Informe data executada e serviço realizado.'});});
export const maintenanceItemSchema=z.object({maintenance_id:uuid,description:z.string().trim().min(2).max(500),quantity:z.coerce.number().positive().max(1000000),equipment_id:optionalUuid,notes:text(2000)}).strict();
export const fileSchema=z.object({parent_type:z.enum(['warranty','ticket','maintenance']),parent_id:uuid,name:z.string().trim().min(2).max(180),description:text(2000),category:z.string().trim().min(2).max(80)}).strict();
export const taskLinkSchema=z.object({parent_type:z.enum(['ticket','maintenance']),parent_id:uuid,task_id:uuid}).strict();
export const ticketFilters=z.object({q:text(120),client_id:optionalUuid,contract_id:optionalUuid,installation_id:optionalUuid,owner:optionalUuid,status:z.union([z.enum(Object.keys(ticketStatuses) as [keyof typeof ticketStatuses,...(keyof typeof ticketStatuses)[]]),z.literal('all')]).default('all'),priority:z.union([z.enum(Object.keys(ticketPriorities) as [keyof typeof ticketPriorities,...(keyof typeof ticketPriorities)[]]),z.literal('all')]).default('all'),category:z.union([z.enum(Object.keys(ticketCategories) as [keyof typeof ticketCategories,...(keyof typeof ticketCategories)[]]),z.literal('all')]).default('all'),from:optionalDate,to:optionalDate,page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(30)}).strict();
export const relationFilters=z.object({client_id:optionalUuid,installation_id:optionalUuid,contract_id:optionalUuid,status:text(40),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(30)}).strict();

export type Warranty=z.output<typeof warrantySchema>&{id:string;contract_id:string;contract_number:string;client_id:string;client_name:string;installation_number:string;end_on:string;effective_status:keyof typeof warrantyStatuses;responsible_name:string;created_at:string;updated_at:string;version:number};
export type Ticket=z.output<typeof ticketSchema>&{id:string;ticket_number:string;client_name:string;client_document:string;contract_number:string|null;installation_number:string|null;warranty_description:string|null;responsible_name:string;opened_at:string;attended_at:string|null;resolved_at:string|null;created_at:string;updated_at:string;version:number};
export type Claim=z.output<typeof claimSchema>&{id:string;created_at:string;updated_at:string;closed_at:string|null;responsible_name:string;version:number};
export type Maintenance=z.output<typeof maintenanceSchema>&{id:string;contract_id:string;client_id:string;client_name:string;installation_number:string;ticket_number:string|null;responsible_name:string;created_at:string;updated_at:string;version:number};
export type PostSalesFile={id:string;warranty_id:string|null;ticket_id:string|null;maintenance_id:string|null;name:string;description:string;category:string;original_filename:string;mime_type:string;file_size:number;created_by_name:string;created_at:string;version:number};
export type TicketHistory={id:string;action:string;detail:string;actor_name:string;created_at:string};
export type MaintenanceItem={id:string;description:string;quantity:number;equipment_id:string|null;equipment_name:string|null;notes:string;created_at:string};
export type PostSalesOptions={clients:Array<{id:string;name:string}>;contracts:Array<{id:string;contract_number:string;client_id:string}>;installations:Array<{id:string;installation_number:string;client_id:string;contract_id:string}>;owners:Array<{id:string;name:string}>;contractItems:Array<{id:string;contract_id:string;description:string;equipment_id:string|null}>;equipment:Array<{id:string;name:string}>;warranties:Array<{id:string;description:string;installation_id:string}>;tickets:Array<{id:string;ticket_number:string;installation_id:string|null;client_id:string}>};
