'use client';
import {useState,type FormEvent} from 'react';
import {Sparkles} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
type Provider='gemini'|'openai';
type Settings={enabled:boolean;provider:Provider;model:string;context_message_limit:number;max_requests_per_hour:number;version:number|null;updated_at:string|null;configured:boolean;configured_providers:Record<Provider,boolean>;can_manage:boolean};
const defaults:Record<Provider,string>={gemini:'gemini-3.5-flash-lite',openai:'gpt-5-mini'};
const labels:Record<Provider,string>={gemini:'Gemini',openai:'OpenAI'};
export function AiAssistantSettings({initial}:{initial:Settings}){const [value,setValue]=useState(initial),[provider,setProvider]=useState<Provider>(initial.provider),[model,setModel]=useState(initial.model),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setNotice('');try{const form=new FormData(event.currentTarget);const next=await api<Settings>('/api/ai/commercial-assistant','PUT',{enabled:form.get('enabled')==='on',provider,model,context_message_limit:Number(form.get('context_message_limit')),max_requests_per_hour:Number(form.get('max_requests_per_hour')),version:value.version});setValue(next);setProvider(next.provider);setModel(next.model);setNotice('Configuração do assistente atualizada.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 function changeProvider(next:Provider){setProvider(next);setModel(defaults[next]);setNotice('');setError('');}
 const configured=value.configured_providers[provider];
 return <div className="settings-page"><div className="page-heading"><div><span className="eyebrow blue">INTEGRAÇÃO SEGURA</span><h1>Assistente Comercial com IA</h1><p>A IA cria sugestões sob demanda. Nenhuma resposta é enviada sem revisão e clique do usuário.</p></div></div><form className="card crm-form" onSubmit={save}><div className="integration-heading"><Sparkles size={22}/><div><h2>Configuração por organização</h2><span className="badge">{configured?`${labels[provider]} configurado`:`${labels[provider]} ainda não configurado`}</span></div></div><label className="check-row"><input name="enabled" type="checkbox" defaultChecked={value.enabled}/><span><strong>Ativar assistente nesta organização</strong><small>Os usuários ainda precisam da permissão e devem clicar em cada ação.</small></span></label><label className="crm-field"><span>Provedor</span><select name="provider" value={provider} onChange={event=>changeProvider(event.target.value as Provider)}><option value="gemini">Google Gemini</option><option value="openai">OpenAI</option></select></label><label className="crm-field"><span>Modelo</span>{provider==='gemini'?<select name="model" value={model} onChange={event=>setModel(event.target.value)} required>{model==='gemini-2.5-flash'&&<option value="gemini-2.5-flash" disabled>gemini-2.5-flash (legado)</option>}<option value="gemini-3.5-flash-lite">gemini-3.5-flash-lite</option><option value="gemini-3.8-flash">gemini-3.8-flash</option></select>:<input name="model" value={model} onChange={event=>setModel(event.target.value)} minLength={1} maxLength={100} required/>}</label><label className="crm-field"><span>Mensagens recentes usadas como contexto</span><input name="context_message_limit" type="number" min={10} max={50} defaultValue={value.context_message_limit} required/></label><label className="crm-field"><span>Máximo de solicitações por usuário a cada hora</span><input name="max_requests_per_hour" type="number" min={1} max={500} defaultValue={value.max_requests_per_hour} required/></label><p className="muted">A chave do provedor permanece somente no secret do runtime. Prompts e respostas completas não são gravados na telemetria.</p>{notice&&<p className="crm-notice" role="status">{notice}</p>}{error&&<p className="error-box" role="alert">{error}</p>}<div className="crm-form-actions"><button className="button primary" disabled={busy}>{busy?'Salvando…':'Salvar configuração'}</button></div></form></div>}
