'use client';
import {useState,type FormEvent} from 'react';
import {BookOpen,CheckCircle2,FlaskConical,Plus} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';

type Entry={id:string;category:string;question:string;answer:string;keywords:string[];status:string;version:number;updated_at:string;reviewed_at:string|null};
type Guidance={tone:'profissional'|'acolhedor'|'direto';formality:'formal'|'equilibrada'|'informal';response_length:'curta'|'media'|'detalhada';emoji_policy:'nenhum'|'moderado';seller_introduction:string;commercial_rules:string;version:number|null;updated_at:string|null};
type Overview={entries:Entry[];guidance:Guidance};
type Preview={answer:string;sources:{id:string;category:string;question:string}[];gaps:string[]};
const empty={category:'Geral',question:'',answer:'',keywords:''};
const statusLabel:Record<string,string>={draft:'Aguardando revisão',active:'Ativa',inactive:'Inativa',rejected:'Rejeitada'};
export function KnowledgeWorkspace({initial}:{initial:Overview}){
 const [data,setData]=useState(initial),[selected,setSelected]=useState<Entry|null>(null),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[question,setQuestion]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[filter,setFilter]=useState('');
 async function reload(){setData(await api<Overview>('/api/ai/knowledge'));}
 function edit(entry:Entry){setSelected(entry);setForm({category:entry.category,question:entry.question,answer:entry.answer,keywords:entry.keywords.join(', ')});setError('');}
 function clear(){setSelected(null);setForm(empty);}
 async function saveEntry(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setNotice('');try{const body={category:form.category.trim(),question:form.question.trim(),answer:form.answer.trim(),keywords:form.keywords.split(',').map(value=>value.trim()).filter(Boolean)};if(selected)await api(`/api/ai/knowledge/${selected.id}`,'PUT',{...body,version:selected.version});else await api('/api/ai/knowledge','POST',body);await reload();clear();setNotice('Item salvo como rascunho. Aprove para usá-lo nas sugestões.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function change(entry:Entry,status:'active'|'inactive'|'rejected'|'deleted'){if(status==='deleted'&&!window.confirm('Excluir este item da base? O registro de auditoria será preservado.'))return;setBusy(true);setError('');try{await api(`/api/ai/knowledge/${entry.id}`,'PATCH',{version:entry.version,status});await reload();if(selected?.id===entry.id)clear();setNotice(status==='active'?'Resposta aprovada e disponível para o assistente.':'Estado atualizado.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function saveGuidance(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const form=new FormData(event.currentTarget),value={tone:form.get('tone'),formality:form.get('formality'),response_length:form.get('response_length'),emoji_policy:form.get('emoji_policy'),seller_introduction:String(form.get('seller_introduction')??''),commercial_rules:String(form.get('commercial_rules')??''),version:data.guidance.version};setData(await api<Overview>('/api/ai/knowledge','PUT',value));setNotice('Orientações de estilo atualizadas.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function test(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setPreview(null);try{setPreview(await api<Preview>('/api/ai/knowledge/test','POST',{question}));}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 const visible=data.entries.filter(entry=>`${entry.category} ${entry.question} ${entry.answer}`.toLocaleLowerCase('pt-BR').includes(filter.toLocaleLowerCase('pt-BR')));
 return <div className="knowledge-page"><div className="page-heading"><div><span className="eyebrow blue">ASSISTENTE COMERCIAL</span><h1>Base de Conhecimento da IA</h1><p>Respostas oficiais entram no assistente somente depois da aprovação. Nenhuma mensagem é enviada ao cliente por esta página.</p></div></div>
  {notice&&<p className="crm-notice" role="status">{notice}</p>}{error&&<p className="error-box" role="alert">{error}</p>}
  <div className="knowledge-grid"><section className="card"><div className="card-heading"><h2><BookOpen size={18}/> Perguntas e respostas</h2><span className="badge">{data.entries.length} itens</span></div><label className="crm-field"><span>Buscar nesta base</span><input value={filter} onChange={event=>setFilter(event.target.value)} placeholder="Categoria ou pergunta"/></label><div className="knowledge-list">{visible.map(entry=><article className="knowledge-entry" key={entry.id}><div><strong>{entry.question}</strong><span className="badge">{statusLabel[entry.status]??entry.status}</span></div><small>{entry.category} · Atualizada em {new Date(entry.updated_at).toLocaleDateString('pt-BR')}</small><p>{entry.answer}</p>{entry.keywords.length>0&&<small>Palavras-chave: {entry.keywords.join(', ')}</small>}<div className="knowledge-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>edit(entry)}>Editar</button>{entry.status!=='active'&&<button type="button" className="button primary" disabled={busy} onClick={()=>void change(entry,'active')}>Aprovar e ativar</button>}{entry.status==='active'&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void change(entry,'inactive')}>Desativar</button>}{entry.status==='draft'&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void change(entry,'rejected')}>Rejeitar</button>}<button type="button" className="button secondary" disabled={busy} onClick={()=>void change(entry,'deleted')}>Excluir</button></div></article>)}{visible.length===0&&<p className="muted">Nenhum item encontrado.</p>}</div></section>
  <section className="card"><div className="card-heading"><h2><Plus size={18}/> {selected?'Editar resposta':'Nova resposta'}</h2>{selected&&<button type="button" className="button secondary" onClick={clear}>Cancelar</button>}</div><p className="muted">Edite fatos com cuidado. Uma alteração volta para revisão antes de aparecer ao assistente.</p><form className="crm-form" onSubmit={saveEntry}><label className="crm-field"><span>Categoria</span><input value={form.category} onChange={event=>setForm({...form,category:event.target.value})} maxLength={80} required/></label><label className="crm-field"><span>Pergunta frequente</span><textarea value={form.question} onChange={event=>setForm({...form,question:event.target.value})} minLength={5} maxLength={500} required/></label><label className="crm-field"><span>Resposta oficial proposta</span><textarea value={form.answer} onChange={event=>setForm({...form,answer:event.target.value})} maxLength={3000} required rows={6}/></label><label className="crm-field"><span>Palavras-chave opcionais, separadas por vírgula</span><input value={form.keywords} onChange={event=>setForm({...form,keywords:event.target.value})} placeholder="visita técnica, orçamento"/></label><div className="crm-form-actions"><button className="button primary" disabled={busy}>{busy?'Salvando…':'Salvar para revisão'}</button></div></form></section></div>
  <div className="knowledge-grid"><section className="card"><h2>Orientações comerciais</h2><p className="muted">Ajustam o estilo das sugestões. Não podem substituir as regras de segurança nem autorizar promessas sem dados.</p><form className="crm-form" onSubmit={saveGuidance} key={data.guidance.version??0}><div className="knowledge-options"><label className="crm-field"><span>Tom</span><select name="tone" defaultValue={data.guidance.tone}><option value="profissional">Profissional</option><option value="acolhedor">Acolhedor</option><option value="direto">Direto</option></select></label><label className="crm-field"><span>Formalidade</span><select name="formality" defaultValue={data.guidance.formality}><option value="equilibrada">Equilibrada</option><option value="formal">Formal</option><option value="informal">Informal</option></select></label><label className="crm-field"><span>Tamanho</span><select name="response_length" defaultValue={data.guidance.response_length}><option value="curta">Curto</option><option value="media">Médio</option><option value="detalhada">Detalhado</option></select></label><label className="crm-field"><span>Emojis</span><select name="emoji_policy" defaultValue={data.guidance.emoji_policy}><option value="moderado">Moderados</option><option value="nenhum">Nenhum</option></select></label></div><label className="crm-field"><span>Apresentação do vendedor</span><input name="seller_introduction" defaultValue={data.guidance.seller_introduction} maxLength={300} placeholder="Sou da equipe Peclat Solar..."/></label><label className="crm-field"><span>Regras comerciais e limites de comunicação</span><textarea name="commercial_rules" defaultValue={data.guidance.commercial_rules} maxLength={3000} rows={5} placeholder="Confirme valores e condições antes de apresentar ao cliente."/></label><div className="crm-form-actions"><button className="button primary" disabled={busy}>Salvar orientações</button></div></form></section>
  <section className="card"><h2><FlaskConical size={18}/> Testar pergunta</h2><p className="muted">Prévia privada, sem envio ao WhatsApp. Só respostas ativas relevantes entram no contexto.</p><form className="crm-form" onSubmit={test}><label className="crm-field"><span>Pergunta de teste</span><textarea value={question} onChange={event=>setQuestion(event.target.value)} minLength={5} maxLength={500} required placeholder="A Peclat faz visita técnica?"/></label><div className="crm-form-actions"><button className="button secondary" disabled={busy}>{busy?'Testando…':'Gerar prévia'}</button></div></form>{preview&&<div className="knowledge-preview" role="status"><h3>Resposta sugerida</h3><p>{preview.answer||'Informação não disponível. Confirme antes de responder.'}</p><h3>Informações utilizadas</h3>{preview.sources.length?<ul>{preview.sources.map(source=><li key={source.id}>{source.category}: {source.question}</li>)}</ul>:<p>Nenhuma resposta aprovada localizada.</p>}{preview.gaps.length>0&&<><h3>Lacunas</h3><ul>{preview.gaps.map(gap=><li key={gap}>{gap}</li>)}</ul></>}</div>}</section></div>
  <p className="info-strip"><CheckCircle2 size={17}/> Conteúdo de clientes e rascunhos não são aprendidos automaticamente. Toda proposta precisa de revisão administrativa.</p>
 </div>;
}
