import type { PoolClient } from 'pg';
import { database,transaction } from '@/server/db';
import { AccessError,requirePermission,type Actor } from '@/modules/auth/policy';
import { crmAccess,getRecord } from '@/modules/crm/repository';
import { uuid } from '@/modules/crm/domain';
import { equipmentSchema,kitSchema,kitSelectionSchema,type KitSelection,type SolarEquipment,type SolarKit,type SolarKitItem } from './domain';
type Db=Pick<PoolClient,'query'>;
const numberOrNull=(value:unknown)=>value===null?null:Number(value);
const normalizeEquipment=(row:Record<string,unknown>):SolarEquipment=>JSON.parse(JSON.stringify({...row,nominal_power_w:numberOrNull(row.nominal_power_w),efficiency_percent:numberOrNull(row.efficiency_percent),phases:numberOrNull(row.phases),mppt_count:numberOrNull(row.mppt_count)}));
function normalizeKit(row:Record<string,unknown>):SolarKit{const items=(typeof row.items==='string'?JSON.parse(row.items):row.items??[]) as SolarKitItem[];return JSON.parse(JSON.stringify({...row,items:items.map(item=>({...item,quantity:Number(item.quantity),nominal_power_w:numberOrNull(item.nominal_power_w)})),module_count:Number(row.module_count??0),dc_power_kwp:Number(row.dc_power_kwp??0),inverter_power_kw:Number(row.inverter_power_kw??0)}));}
const kitSelect=`k.*,COALESCE((SELECT json_agg(json_build_object('equipment_id',e.id,'quantity',i.quantity,'name',e.name,'category',e.category,'manufacturer',e.manufacturer,'model',e.model,'nominal_power_w',e.nominal_power_w,'unit',e.unit) ORDER BY e.category,e.name,e.id) FROM solar_kit_items i JOIN solar_equipment e ON e.organization_id=i.organization_id AND e.id=i.equipment_id WHERE i.organization_id=k.organization_id AND i.kit_id=k.id),'[]') items,COALESCE((SELECT sum(i.quantity) FROM solar_kit_items i JOIN solar_equipment e ON e.organization_id=i.organization_id AND e.id=i.equipment_id WHERE i.organization_id=k.organization_id AND i.kit_id=k.id AND e.category='module'),0) module_count,COALESCE((SELECT sum(i.quantity*e.nominal_power_w)/1000 FROM solar_kit_items i JOIN solar_equipment e ON e.organization_id=i.organization_id AND e.id=i.equipment_id WHERE i.organization_id=k.organization_id AND i.kit_id=k.id AND e.category='module'),0) dc_power_kwp,COALESCE((SELECT sum(i.quantity*e.nominal_power_w)/1000 FROM solar_kit_items i JOIN solar_equipment e ON e.organization_id=i.organization_id AND e.id=i.equipment_id WHERE i.organization_id=k.organization_id AND i.kit_id=k.id AND e.category='inverter'),0) inverter_power_kw`;
function manage(actor:Actor){crmAccess(actor);requirePermission(actor,'solar.catalog.manage');}
async function equipment(actor:Actor,id:string,db:Db=database(),lock=false){crmAccess(actor);uuid.parse(id);const {rows}=await db.query(`SELECT * FROM solar_equipment WHERE organization_id=$1 AND id=$2${lock?' FOR UPDATE':''}`,[actor.organizationId,id]);if(!rows[0])throw new AccessError(404,'Equipamento não encontrado.');return normalizeEquipment(rows[0]);}
async function kit(actor:Actor,id:string,db:Db=database(),lock=false){crmAccess(actor);uuid.parse(id);const {rows}=await db.query(`SELECT ${kitSelect} FROM solar_kits k WHERE k.organization_id=$1 AND k.id=$2${lock?' FOR UPDATE OF k':''}`,[actor.organizationId,id]);if(!rows[0])throw new AccessError(404,'Kit não encontrado.');return normalizeKit(rows[0]);}
async function history(db:Db,actor:Actor,type:'equipment'|'kit',id:string,action:string,snapshot:unknown){const table=type==='equipment'?'solar_equipment_history':'solar_kit_history';const column=type==='equipment'?'equipment_id':'kit_id';await db.query(`INSERT INTO ${table}(organization_id,${column},actor_id,action,snapshot) VALUES ($1,$2,$3,$4,$5)`,[actor.organizationId,id,actor.userId,action,snapshot]);}
function conflict(error:unknown,message:string):never{if((error as {code?:string}).code==='23505')throw new AccessError(409,message);throw error;}
export async function listEquipment(actor:Actor,input:unknown={}){crmAccess(actor);const parsed=(input??{}) as Record<string,unknown>;const category=typeof parsed.category==='string'&&['module','inverter','structure','component'].includes(parsed.category)?parsed.category:'';const status=parsed.status==='all'?'all':'active';const {rows}=await database().query(`SELECT * FROM solar_equipment WHERE organization_id=$1 AND ($2='' OR category=$2) AND ($3='all' OR status=$3) ORDER BY status,category,name,id LIMIT 500`,[actor.organizationId,category,status]);return rows.map(normalizeEquipment);}
export async function getEquipment(actor:Actor,id:string){const item=await equipment(actor,id);const {rows}=await database().query('SELECT h.id,h.action,h.snapshot,h.created_at,u.name actor_name FROM solar_equipment_history h JOIN users u ON u.id=h.actor_id WHERE h.organization_id=$1 AND h.equipment_id=$2 ORDER BY h.created_at DESC LIMIT 100',[actor.organizationId,id]);return {...item,history:rows};}
export async function saveEquipment(actor:Actor,input:unknown,id?:string){manage(actor);const data=equipmentSchema.parse(input);return transaction(async db=>{try{const current=id?await equipment(actor,id,db,true):null;if(current&&current.version!==data.version)throw new AccessError(409,'Este equipamento foi atualizado. Recarregue antes de salvar.');const values=[data.category,data.name,data.manufacturer,data.model,data.sku,data.nominal_power_w,data.efficiency_percent,data.phases,data.mppt_count,data.unit,data.technical_notes];let savedId=id;if(current)await db.query('UPDATE solar_equipment SET category=$3,name=$4,manufacturer=$5,model=$6,sku=$7,nominal_power_w=$8,efficiency_percent=$9,phases=$10,mppt_count=$11,unit=$12,technical_notes=$13,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,...values]);else savedId=(await db.query('INSERT INTO solar_equipment(organization_id,category,name,manufacturer,model,sku,nominal_power_w,efficiency_percent,phases,mppt_count,unit,technical_notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id',[actor.organizationId,...values])).rows[0].id;const saved=await equipment(actor,savedId!,db);await history(db,actor,'equipment',saved.id,current?'updated':'created',saved);return saved;}catch(error){conflict(error,'Já existe um equipamento com este código interno.');}});}
export async function setEquipmentStatus(actor:Actor,id:string,status:'active'|'archived',version:number){manage(actor);return transaction(async db=>{const current=await equipment(actor,id,db,true);if(current.version!==version)throw new AccessError(409,'Este equipamento foi atualizado.');if(status==='archived'){const used=await db.query("SELECT 1 FROM solar_kit_items i JOIN solar_kits k ON k.organization_id=i.organization_id AND k.id=i.kit_id WHERE i.organization_id=$1 AND i.equipment_id=$2 AND k.status='active' LIMIT 1",[actor.organizationId,id]);if(used.rowCount)throw new AccessError(409,'Arquive ou atualize os kits ativos que usam este equipamento.');}await db.query('UPDATE solar_equipment SET status=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,status]);const saved=await equipment(actor,id,db);await history(db,actor,'equipment',id,status==='active'?'restored':'archived',saved);return saved;});}
export async function listKits(actor:Actor,input:unknown={}){crmAccess(actor);const status=(input as Record<string,unknown>)?.status==='all'?'all':'active';const {rows}=await database().query(`SELECT ${kitSelect} FROM solar_kits k WHERE k.organization_id=$1 AND ($2='all' OR k.status=$2) ORDER BY k.status,k.name,k.id LIMIT 500`,[actor.organizationId,status]);return rows.map(normalizeKit);}
export async function getKit(actor:Actor,id:string){const item=await kit(actor,id);const {rows}=await database().query('SELECT h.id,h.action,h.snapshot,h.created_at,u.name actor_name FROM solar_kit_history h JOIN users u ON u.id=h.actor_id WHERE h.organization_id=$1 AND h.kit_id=$2 ORDER BY h.created_at DESC LIMIT 100',[actor.organizationId,id]);return {...item,history:rows};}
export async function saveKit(actor:Actor,input:unknown,id?:string){manage(actor);const data=kitSchema.parse(input);if(new Set(data.items.map(item=>item.equipment_id)).size!==data.items.length)throw new AccessError(400,'Cada equipamento deve aparecer apenas uma vez no kit.');return transaction(async db=>{try{const current=id?await kit(actor,id,db,true):null;if(current&&current.version!==data.version)throw new AccessError(409,'Este kit foi atualizado. Recarregue antes de salvar.');const ids=data.items.map(item=>item.equipment_id);const valid=await db.query("SELECT id FROM solar_equipment WHERE organization_id=$1 AND id=ANY($2::uuid[]) AND status='active'",[actor.organizationId,ids]);if(valid.rowCount!==ids.length)throw new AccessError(400,'Um dos equipamentos não está ativo neste catálogo.');let savedId=id;if(current)await db.query('UPDATE solar_kits SET name=$3,code=$4,description=$5,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,data.name,data.code,data.description]);else savedId=(await db.query('INSERT INTO solar_kits(organization_id,name,code,description) VALUES ($1,$2,$3,$4) RETURNING id',[actor.organizationId,data.name,data.code,data.description])).rows[0].id;await db.query('DELETE FROM solar_kit_items WHERE organization_id=$1 AND kit_id=$2',[actor.organizationId,savedId]);for(const item of data.items)await db.query('INSERT INTO solar_kit_items(organization_id,kit_id,equipment_id,quantity) VALUES ($1,$2,$3,$4)',[actor.organizationId,savedId,item.equipment_id,item.quantity]);const saved=await kit(actor,savedId!,db);if(saved.dc_power_kwp<=0||saved.module_count<1)throw new AccessError(400,'O kit precisa conter ao menos um módulo com potência cadastrada.');await history(db,actor,'kit',saved.id,current?'updated':'created',saved);return saved;}catch(error){conflict(error,'Já existe um kit com este código interno.');}});}
export async function setKitStatus(actor:Actor,id:string,status:'active'|'archived',version:number){manage(actor);return transaction(async db=>{const current=await kit(actor,id,db,true);if(current.version!==version)throw new AccessError(409,'Este kit foi atualizado.');await db.query('UPDATE solar_kits SET status=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,status]);const saved=await kit(actor,id,db);await history(db,actor,'kit',id,status==='active'?'restored':'archived',saved);return saved;});}
async function sizingAccess(actor:Actor,id:string,db:Db){uuid.parse(id);const {rows}=await db.query('SELECT s.*,u.customer_id,u.id consumer_unit_id,u.status unit_status FROM solar_sizings s JOIN energy_consumer_units u ON u.organization_id=s.organization_id AND u.id=s.consumer_unit_id WHERE s.organization_id=$1 AND s.id=$2',[actor.organizationId,id]);if(!rows[0])throw new AccessError(404,'Dimensionamento não encontrado.');await getRecord(actor,rows[0].customer_id,db);return rows[0] as Record<string,unknown>;}
const normalizeSelection=(row:Record<string,unknown>):KitSelection=>JSON.parse(JSON.stringify({...row,kit_quantity:Number(row.kit_quantity),module_count:Number(row.module_count),dc_power_kwp:Number(row.dc_power_kwp),inverter_power_kw:Number(row.inverter_power_kw),kit_snapshot:typeof row.kit_snapshot==='string'?JSON.parse(row.kit_snapshot):row.kit_snapshot}));
export async function listKitSelections(actor:Actor,sizingId:string){await sizingAccess(actor,sizingId,database());const {rows}=await database().query('SELECT x.*,k.name kit_name,u.name actor_name FROM solar_sizing_kit_selections x JOIN solar_kits k ON k.organization_id=x.organization_id AND k.id=x.kit_id JOIN users u ON u.id=x.actor_id WHERE x.organization_id=$1 AND x.sizing_id=$2 ORDER BY x.created_at DESC,x.id DESC LIMIT 100',[actor.organizationId,sizingId]);return rows.map(normalizeSelection);}
export async function selectKitForSizing(actor:Actor,input:unknown){crmAccess(actor);const data=kitSelectionSchema.parse(input);return transaction(async db=>{const sizing=await sizingAccess(actor,data.sizing_id,db);if(sizing.unit_status!=='active')throw new AccessError(409,'Reative a unidade antes de vincular um kit.');const selected=await kit(actor,data.kit_id,db,true);if(selected.status!=='active')throw new AccessError(409,'Selecione um kit ativo.');if(selected.dc_power_kwp<=0)throw new AccessError(422,'O kit não possui potência de módulos.');const kitQuantity=Math.ceil(Number(sizing.system_power_kwp)/selected.dc_power_kwp);const moduleCount=Math.ceil(selected.module_count*kitQuantity);const dcPower=selected.dc_power_kwp*kitQuantity;const inverterPower=selected.inverter_power_kw*kitQuantity;const {rows}=await db.query('INSERT INTO solar_sizing_kit_selections(organization_id,sizing_id,kit_id,customer_id,consumer_unit_id,actor_id,kit_quantity,module_count,dc_power_kwp,inverter_power_kw,kit_snapshot) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[actor.organizationId,data.sizing_id,data.kit_id,sizing.customer_id,sizing.consumer_unit_id,actor.userId,kitQuantity,moduleCount,dcPower,inverterPower,selected]);await db.query('INSERT INTO crm_activities(organization_id,record_id,actor_id,action,detail) VALUES ($1,$2,$3,$4,$5)',[actor.organizationId,sizing.customer_id,actor.userId,'solar.kit.selected',`${selected.name}; ${kitQuantity} kit(s); ${dcPower.toFixed(2)} kWp`]);return normalizeSelection({...rows[0],kit_name:selected.name,actor_name:actor.name});});}
