import {NextResponse} from 'next/server';
import {z} from 'zod';
import {apiActor} from '@/server/session';
import {failure,readMutation} from '@/server/http';
import {AccessError} from '@/modules/auth/policy';
import {automationOptions,automationSettings,getAutomationRule,listAutomationRules,listAutomationRuns,saveAutomationRule,saveAutomationSettings,setAutomationRuleActive,simulateAutomationRule} from '@/modules/automations/repository';
type Context={params:Promise<{segments?:string[]}>};
async function handle(request:Request,context:Context){try{const actor=await apiActor(),url=new URL(request.url),[first,second,...rest]=(await context.params).segments??[],respond=(value:unknown,status=200)=>NextResponse.json(value,{status,headers:{'Cache-Control':'no-store'}});if(rest.length)throw new AccessError(404,'Recurso não encontrado.');if(request.method==='GET'&&!first)return respond({rules:await listAutomationRules(actor),settings:await automationSettings(actor),options:await automationOptions(actor)});if(request.method==='GET'&&first==='runs'&&!second)return respond(await listAutomationRuns(actor,z.coerce.number().int().min(1).max(100000).parse(url.searchParams.get('page')??1)));if(request.method==='GET'&&first&&second===undefined)return respond(await getAutomationRule(actor,first));if(request.method==='POST'&&!first)return respond(await saveAutomationRule(actor,await readMutation(request)),201);if(request.method==='PUT'&&first==='settings'&&!second)return respond(await saveAutomationSettings(actor,await readMutation(request)));if(request.method==='PUT'&&first&&!second)return respond(await saveAutomationRule(actor,await readMutation(request),first));if(request.method==='POST'&&first&&second==='active'){const body=z.object({active:z.boolean(),version:z.number().int().positive()}).strict().parse(await readMutation(request));return respond(await setAutomationRuleActive(actor,first,body.active,body.version));}if(request.method==='POST'&&first&&second==='simulate')return respond(await simulateAutomationRule(actor,first,await readMutation(request)));throw new AccessError(404,'Recurso não encontrado.');}catch(error){return failure(error);}}
export const GET=handle;export const POST=handle;export const PUT=handle;
