'use client';
import {useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowLeft,Download,Edit,Plus,Trash2} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
import {useRemote} from '@/components/crm/use-remote';
import {Modal} from '@/components/crm/modal';
import {claimStatuses,maintenanceStatuses,maintenanceTypes,ticketCategories,ticketPriorities,ticketStatuses,warrantyCategories,warrantyStatuses,type Claim,type Maintenance,type MaintenanceItem,type PostSalesFile,type PostSalesOptions,type Ticket,type TicketHistory,type Warranty} from '@/modules/post-sales/domain';
import {ClaimForm,MaintenanceForm,TicketForm,WarrantyForm} from './forms';

type Kind='chamados'|'garantias'|'manutencoes';
type Parent='ticket'|'warranty'|'maintenance';
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`)):'A definir';
const datetime=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value));
const historyLabels:Record<string,string>={opened:'Chamado aberto',updated:'Dados atualizados',status_changed:'Status alterado',owner_changed:'Responsável alterado',priority_changed:'Prioridade alterada',comment:'Atualização interna',resolved:'Chamado resolvido',reopened:'Chamado reaberto',closed:'Chamado encerrado',claim_created:'Garantia acionada',claim_updated:'Acionamento atualizado',maintenance_linked:'Manutenção vinculada',maintenance_updated:'Manutenção atualizada',maintenance_item:'Serviço registrado',file_added:'Anexo adicionado',file_removed:'Anexo removido'};
function SafeLink({enabled,href,children}:{enabled:boolean;href:string;children:React.ReactNode}){return enabled?<Link href={href}>{children}</Link>:<>{children}</>;}
export function PostSalesDetail({kind,initial,options,userId,canEdit,canManage,canUseTasks,canNavigateCommercial,canNavigateContracts,canNavigateInstallations}:{kind:Kind;initial:Ticket|Warranty|Maintenance;options:PostSalesOptions;userId:string;canEdit:boolean;canManage:boolean;canUseTasks:boolean;canNavigateCommercial:boolean;canNavigateContracts:boolean;canNavigateInstallations:boolean}){
 const [item,setItem]=useState(initial),[editing,setEditing]=useState(false),[revision,setRevision]=useState(0),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const parentType:Parent=kind==='chamados'?'ticket':kind==='garantias'?'warranty':'maintenance';
 async function refresh(){setItem(await api<Ticket|Warranty|Maintenance>(`/api/post-sales-${kind==='chamados'?'tickets':kind==='garantias'?'warranties':'maintenances'}/${item.id}`));setRevision(value=>value+1);}
 async function saved(){await refresh();setEditing(false);setNotice('Registro atualizado.');}
 const ticket=kind==='chamados'?item as Ticket:null,warranty=kind==='garantias'?item as Warranty:null,maintenance=kind==='manutencoes'?item as Maintenance:null;
 const clientId=ticket?.client_id??warranty?.client_id??maintenance?.client_id??'';
 const installationId=ticket?.installation_id??warranty?.installation_id??maintenance?.installation_id;
 return <><div className="page-heading"><div><Link className="back-link" href="/pos-venda"><ArrowLeft size={15}/>Pós-venda</Link><span className="eyebrow green">{ticket?.ticket_number??warranty?.installation_number??maintenance?.installation_number}</span><h1>{ticket?.title??warranty?.description??maintenance?.reason}</h1><p>{ticket?.client_name??warranty?.client_name??maintenance?.client_name} · {ticket?.responsible_name??warranty?.responsible_name??maintenance?.responsible_name}</p></div>{canEdit&&<button className="button secondary" onClick={()=>setEditing(true)}><Edit size={15}/>Editar</button>}</div>
 {error&&<p role="alert" className="error-box">{error}</p>}{notice&&<p role="status" className="crm-notice">{notice}</p>}
 <div className="installation-summary post-sales-metrics">{ticket&&<><div><span>Status</span><strong>{ticketStatuses[ticket.status]}</strong></div><div><span>Prioridade</span><strong>{ticketPriorities[ticket.priority]}</strong></div><div><span>Categoria</span><strong>{ticketCategories[ticket.category]}</strong></div><div><span>Aberto em</span><strong>{datetime(ticket.opened_at)}</strong></div><div><span>Prazo</span><strong>{date(ticket.due_on)}</strong></div></>}{warranty&&<><div><span>Situação</span><strong>{warrantyStatuses[warranty.effective_status]}</strong></div><div><span>Categoria</span><strong>{warrantyCategories[warranty.category]}</strong></div><div><span>Início</span><strong>{date(warranty.start_on)}</strong></div><div><span>Validade</span><strong>{date(warranty.end_on)}</strong></div><div><span>Prazo</span><strong>{warranty.duration_months} meses</strong></div></>}{maintenance&&<><div><span>Status</span><strong>{maintenanceStatuses[maintenance.status]}</strong></div><div><span>Tipo</span><strong>{maintenanceTypes[maintenance.type]}</strong></div><div><span>Agendada</span><strong>{date(maintenance.scheduled_on)}</strong></div><div><span>Executada</span><strong>{date(maintenance.executed_on)}</strong></div><div><span>Gratuito / garantia</span><strong>{maintenance.no_charge?'Sim':'Não'}</strong></div></>}</div>
 <div className="post-sales-detail-grid"><section className="card"><h2>Vínculos e informações</h2><dl className="crm-info-grid"><div><dt>Cliente</dt><dd><SafeLink enabled={canNavigateCommercial} href={`/clientes/${clientId}`}>{ticket?.client_name??warranty?.client_name??maintenance?.client_name}</SafeLink></dd></div>{(ticket?.contract_id||warranty?.contract_id||maintenance?.contract_id)&&<div><dt>Contrato</dt><dd><SafeLink enabled={canNavigateContracts} href={`/contratos/${ticket?.contract_id??warranty?.contract_id??maintenance?.contract_id}`}>{ticket?.contract_number??warranty?.contract_number??maintenance?.contract_id}</SafeLink></dd></div>}{installationId&&<div><dt>Instalação</dt><dd><SafeLink enabled={canNavigateInstallations} href={`/instalacoes/${installationId}`}>{ticket?.installation_number??warranty?.installation_number??maintenance?.installation_number}</SafeLink></dd></div>}{ticket?.warranty_id&&<div><dt>Garantia</dt><dd><Link href={`/pos-venda/garantias/${ticket.warranty_id}`}>{ticket.warranty_description??'Abrir garantia'}</Link></dd></div>}{maintenance?.ticket_id&&<div><dt>Chamado</dt><dd><Link href={`/pos-venda/chamados/${maintenance.ticket_id}`}>{maintenance.ticket_number}</Link></dd></div>}{maintenance?.warranty_id&&<div><dt>Garantia</dt><dd><Link href={`/pos-venda/garantias/${maintenance.warranty_id}`}>Abrir garantia</Link></dd></div>}{warranty&&<><div><dt>Fabricante</dt><dd>{warranty.manufacturer||'Não informado'}</dd></div><div><dt>Série</dt><dd>{warranty.serial_number||'Não informada'}</dd></div><div><dt>Fornecedor</dt><dd>{warranty.supplier||'Não informado'}</dd></div></>}{maintenance&&<><div><dt>Custo interno</dt><dd>{maintenance.internal_cost.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</dd></div><div><dt>Valor cobrado</dt><dd>{maintenance.charged_amount.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</dd></div></>}</dl>{ticket?.description&&<p className="preserve-text">{ticket.description}</p>}{ticket?.resolution&&<p className="preserve-text"><strong>Resolução:</strong> {ticket.resolution}</p>}{warranty?.notes&&<p className="preserve-text">{warranty.notes}</p>}{maintenance?.description&&<p className="preserve-text">{maintenance.description}</p>}{maintenance?.resolution&&<p className="preserve-text"><strong>Serviço realizado:</strong> {maintenance.resolution}</p>}{maintenance?.financial_notes&&<p className="preserve-text"><strong>Observação financeira:</strong> {maintenance.financial_notes}</p>}</section>
 {ticket&&<TicketUpdates ticket={ticket} revision={revision} canEdit={canEdit} canManage={canManage} refresh={refresh} setError={setError} options={options} userId={userId}/>}
 {warranty&&<WarrantyClaims warranty={warranty} revision={revision} options={options} userId={userId} canEdit={canEdit} canManage={canManage} refresh={refresh}/>}
 {maintenance&&<MaintenanceItems maintenance={maintenance} options={options} revision={revision} canEdit={canEdit} refresh={refresh}/>}
 <FilesPanel type={parentType} parentId={item.id} canEdit={canEdit} canManage={canManage}/>
 {(ticket||maintenance)&&<LinkedTasks type={parentType as 'ticket'|'maintenance'} parentId={item.id} clientId={clientId} canEdit={canEdit&&canUseTasks} refreshKey={revision}/>}
 </div>
 {editing&&<Modal title="Editar pós-venda" onClose={()=>setEditing(false)}>{ticket?<TicketForm options={options} userId={userId} initial={ticket} onSaved={saved} canManage={canManage}/>:warranty?<WarrantyForm options={options} userId={userId} initial={warranty} onSaved={saved} canManage={canManage}/>:maintenance&&<MaintenanceForm options={options} userId={userId} initial={maintenance} onSaved={saved} canManage={canManage}/>}</Modal>}
 </>;
}
function TicketUpdates({ticket,revision,canEdit,canManage,refresh,setError,options,userId}:{ticket:Ticket;revision:number;canEdit:boolean;canManage:boolean;refresh:()=>Promise<void>;setError:(value:string)=>void;options:PostSalesOptions;userId:string}){
 const [comment,setComment]=useState(''),[busy,setBusy]=useState(false),[claimForm,setClaimForm]=useState<Claim|'new'|null>(null);
 const history=useRemote<TicketHistory[]>(`/api/post-sales-tickets/${ticket.id}/history`,revision);
 const claims=useRemote<Claim[]>(`/api/post-sales-claims?ticket_id=${ticket.id}`,revision);
 async function addComment(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await api(`/api/post-sales-tickets/${ticket.id}/comments`,'POST',{body:comment});setComment('');await refresh();}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 return <><section className="card"><div className="card-heading"><div><h2>Histórico do chamado</h2><p>Atualizações internas e decisões, em ordem cronológica.</p></div></div>{canEdit&&<form className="crm-form" onSubmit={addComment}><label className="crm-field"><span>Nova atualização interna</span><textarea value={comment} onChange={event=>setComment(event.target.value)} required maxLength={4000}/></label><button className="button primary" disabled={busy}>Registrar atualização</button></form>}{history.error&&<p role="alert" className="error-box">{history.error}</p>}<div className="contract-history">{history.data?.map(event=><article key={event.id}><div><strong>{historyLabels[event.action]??event.action}</strong><p className="preserve-text">{event.detail}</p></div><span>{event.actor_name}</span><time>{datetime(event.created_at)}</time></article>)}</div></section>
 {ticket.warranty_id&&<section className="card"><div className="card-heading"><div><h2>Acionamento da garantia</h2><p>Vínculo com fornecedor, protocolo e resultado.</p></div>{canEdit&&<button className="button secondary" onClick={()=>setClaimForm('new')}><Plus size={15}/>Acionar</button>}</div>{claims.data?.map(claim=><article className="post-sales-claim" key={claim.id}><strong>{claimStatuses[claim.status]}</strong><p>{claim.reason}</p><small>{claim.supplier||'Fornecedor não informado'} · {claim.protocol||'Sem protocolo'} · {datetime(claim.created_at)}</small>{claim.result&&<p>Resultado: {claim.result}</p>}{canEdit&&(canManage||claim.status!=='closed')&&<button className="button secondary" onClick={()=>setClaimForm(claim)}>Atualizar acionamento</button>}</article>)}{claims.data?.length===0&&<p className="muted">Nenhum acionamento registrado.</p>}{claimForm&&<Modal title={claimForm==='new'?'Acionar garantia':'Atualizar acionamento'} onClose={()=>setClaimForm(null)}><ClaimForm warrantyId={ticket.warranty_id} ticketId={ticket.id} options={options} userId={userId} canManage={canManage} initial={claimForm==='new'?undefined:claimForm} onSaved={async()=>{setClaimForm(null);await refresh();}}/></Modal>}</section>}</>;
}
function WarrantyClaims({warranty,revision,options,userId,canEdit,canManage,refresh}:{warranty:Warranty;revision:number;options:PostSalesOptions;userId:string;canEdit:boolean;canManage:boolean;refresh:()=>Promise<void>}){
 const [ticketId,setTicketId]=useState(''),[show,setShow]=useState(false);
 const claims=useRemote<Claim[]>(`/api/post-sales-claims?warranty_id=${warranty.id}`,revision);
 const tickets=options.tickets.filter(row=>row.installation_id===warranty.installation_id);
 return <section className="card"><h2>Chamados e acionamentos</h2><div className="post-sales-related">{tickets.map(row=><Link key={row.id} href={`/pos-venda/chamados/${row.id}`}>{row.ticket_number}</Link>)}</div>{claims.data?.map(row=><article className="post-sales-claim" key={row.id}><strong>{claimStatuses[row.status]}</strong><p>{row.reason}</p><small>{row.protocol||'Sem protocolo'} · {datetime(row.created_at)}</small></article>)}{canEdit&&tickets.length>0&&<div className="crm-form-actions"><label className="crm-field"><span>Chamado para acionamento</span><select value={ticketId} onChange={event=>setTicketId(event.target.value)}><option value="">Selecione</option>{tickets.map(row=><option key={row.id} value={row.id}>{row.ticket_number}</option>)}</select></label><button className="button secondary" disabled={!ticketId} onClick={()=>setShow(true)}>Acionar garantia</button></div>}{show&&<Modal title="Acionar garantia" onClose={()=>setShow(false)}><ClaimForm warrantyId={warranty.id} ticketId={ticketId} options={options} userId={userId} canManage={canManage} onSaved={async()=>{setShow(false);await refresh();}}/></Modal>}</section>;
}
function MaintenanceItems({maintenance,options,revision,canEdit,refresh}:{maintenance:Maintenance;options:PostSalesOptions;revision:number;canEdit:boolean;refresh:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const items=useRemote<MaintenanceItem[]>(`/api/post-sales-maintenances/${maintenance.id}/items`,revision);
 async function add(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);setBusy(true);setError('');try{await api(`/api/post-sales-maintenances/${maintenance.id}/items`,'POST',{description:String(form.get('description')),quantity:Number(form.get('quantity')),equipment_id:String(form.get('equipment_id')??''),notes:String(form.get('notes')??'')});formElement.reset();await refresh();}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 return <section className="card"><h2>Serviços e itens executados</h2>{items.data?.map(row=><article className="post-sales-claim" key={row.id}><strong>{row.description}</strong><p>{row.quantity} {row.equipment_name?`· ${row.equipment_name}`:''} {row.notes}</p></article>)}{canEdit&&!['completed','cancelled'].includes(maintenance.status)&&<form className="crm-form" onSubmit={add}><div className="contract-form-grid"><label className="crm-field"><span>Descrição do serviço</span><input name="description" required minLength={2} maxLength={500}/></label><label className="crm-field"><span>Quantidade</span><input name="quantity" type="number" min={0.001} step={0.001} required defaultValue={1}/></label><label className="crm-field"><span>Equipamento</span><select name="equipment_id"><option value="">Sem equipamento</option>{options.equipment.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div><label className="crm-field"><span>Observação</span><input name="notes" maxLength={2000}/></label>{error&&<p role="alert" className="error-box">{error}</p>}<button className="button primary" disabled={busy}>Adicionar item</button></form>}</section>;
}
function FilesPanel({type,parentId,canEdit,canManage}:{type:Parent;parentId:string;canEdit:boolean;canManage:boolean}){
 const [revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<PostSalesFile|null>(null);
 const files=useRemote<PostSalesFile[]>(`/api/post-sales-files?parent_type=${type}&parent_id=${parentId}`,revision);
 async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);form.set('parent_type',type);form.set('parent_id',parentId);setBusy(true);setError('');try{const response=await fetch('/api/post-sales-files',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.error??'Não foi possível enviar o arquivo.');formElement.reset();setRevision(value=>value+1);}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function remove(file:PostSalesFile){setBusy(true);setError('');try{await api(`/api/post-sales-files/${file.id}`,'DELETE',{version:file.version});setRevision(value=>value+1);}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 return <section className="card"><h2>Fotos e documentos</h2><p className="muted">Arquivos privados, até 10 MB cada. Download apenas com sessão autorizada.</p>{canEdit&&<form className="crm-form" onSubmit={upload}><div className="contract-form-grid"><label className="crm-field"><span>Nome</span><input name="name" required minLength={2} maxLength={180}/></label><label className="crm-field"><span>Tipo</span><select name="category"><option value="photo">Foto</option><option value="invoice">Nota fiscal</option><option value="certificate">Certificado</option><option value="manual">Manual</option><option value="proof">Comprovante</option><option value="report">Relatório</option><option value="other">Outro</option></select></label><label className="crm-field"><span>Arquivo</span><input type="file" name="file" required accept=".pdf,.png,.jpg,.jpeg,.webp,.xlsx,.xls,.csv,.docx,.doc,.txt"/></label></div><label className="crm-field"><span>Descrição</span><input name="description" maxLength={2000}/></label><button className="button primary" disabled={busy}>Adicionar arquivo</button></form>}{error&&<p role="alert" className="error-box">{error}</p>}<div className="installation-documents">{files.data?.map(file=><article key={file.id}><div>{file.mime_type.startsWith('image/')&&<button className="post-sales-thumbnail" aria-label={`Ampliar ${file.name}`} onClick={()=>setPreview(file)}><Image src={`/api/post-sales-files/${file.id}/file`} alt={file.description||file.name} width={120} height={90} unoptimized/></button>}<strong>{file.name}</strong><small>{file.original_filename} · {Math.ceil(file.file_size/1024)} KB · {file.created_by_name} · {datetime(file.created_at)}</small>{file.description&&<p>{file.description}</p>}</div><a className="button secondary" href={`/api/post-sales-files/${file.id}/file?download=1`} download><Download size={15}/>Baixar</a>{canManage&&<button className="button danger" disabled={busy} onClick={()=>remove(file)}><Trash2 size={15}/>Excluir</button>}</article>)}</div>{files.data?.length===0&&<p className="muted">Nenhum anexo.</p>}{preview&&<Modal title={preview.name} onClose={()=>setPreview(null)}><Image className="installation-preview" src={`/api/post-sales-files/${preview.id}/file`} alt={preview.description||preview.name} width={900} height={700} unoptimized/></Modal>}</section>;
}
function LinkedTasks({type,parentId,clientId,canEdit,refreshKey}:{type:'ticket'|'maintenance';parentId:string;clientId:string;canEdit:boolean;refreshKey:number}){
 const [revision,setRevision]=useState(0),[selected,setSelected]=useState(''),[error,setError]=useState('');
 const url=type==='ticket'?`/api/post-sales-tickets/${parentId}/tasks`:`/api/post-sales-maintenances/${parentId}/tasks`;
 const linked=useRemote<Array<{id:string;title:string;status:string;due_date:string;owner_name:string}>>(url,revision+refreshKey);
 const existing=useRemote<{items:Array<{id:string;title:string;due_date:string}>}>(canEdit?`/api/tasks?record_id=${clientId}&pageSize=100`:null);
 async function add(){setError('');try{await api('/api/post-sales-task-links','POST',{parent_type:type,parent_id:parentId,task_id:selected});setSelected('');setRevision(value=>value+1);}catch(reason){setError(errorMessage(reason));}}
 return <section className="card"><h2>Tarefas e agenda</h2><p className="muted">Tarefas existentes do cliente aparecem também na agenda do CRM.</p>{linked.data?.map(row=><article className="post-sales-claim" key={row.id}><strong>{row.title}</strong><p>{date(row.due_date)} · {row.owner_name} · {row.status}</p></article>)}{canEdit&&<div className="crm-form-actions"><label className="crm-field"><span>Vincular tarefa existente</span><select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Selecione</option>{existing.data?.items.map(row=><option key={row.id} value={row.id}>{row.title} · {date(row.due_date)}</option>)}</select></label><button className="button secondary" disabled={!selected} onClick={add}>Vincular</button></div>}{error&&<p role="alert" className="error-box">{error}</p>}</section>;
}
