'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {HeartHandshake,Plus,Search} from 'lucide-react';
import {useRemote} from '@/components/crm/use-remote';
import {Modal} from '@/components/crm/modal';
import {maintenanceStatuses,maintenanceTypes,ticketCategories,ticketPriorities,ticketStatuses,warrantyCategories,warrantyStatuses,type Maintenance,type PostSalesOptions,type Ticket,type Warranty} from '@/modules/post-sales/domain';
import {MaintenanceForm,TicketForm,WarrantyForm} from './forms';

type Tab='dashboard'|'tickets'|'warranties'|'maintenances';
type Create='ticket'|'warranty'|'maintenance';
const paths={ticket:'chamados',warranty:'garantias',maintenance:'manutencoes'} as const;
const date=(value:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`)):'A definir';
export function PostSalesWorkspace({options,userId,canCreate,canManage}:{options:PostSalesOptions;userId:string;canCreate:boolean;canManage:boolean}){
 const router=useRouter();const [tab,setTab]=useState<Tab>('dashboard'),[create,setCreate]=useState<Create|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[priority,setPriority]=useState('all'),[category,setCategory]=useState('all'),[client,setClient]=useState(''),[owner,setOwner]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1);
 const ticketQuery=new URLSearchParams({q,status,priority,category,client_id:client,owner,from,to,page:String(page),pageSize:'20'});
 const relatedQuery=new URLSearchParams({client_id:client,status:status==='all'?'':status,page:String(page),pageSize:'20'});
 const dashboard=useRemote<Record<string,number>>('/api/post-sales-dashboard');
 const tickets=useRemote<{items:Ticket[];total:number;pageSize:number}>(tab==='tickets'?`/api/post-sales-tickets?${ticketQuery}`:null);
 const warranties=useRemote<{items:Warranty[];total:number;pageSize:number}>(tab==='warranties'?`/api/post-sales-warranties?${relatedQuery}`:null);
 const maintenances=useRemote<{items:Maintenance[];total:number;pageSize:number}>(tab==='maintenances'?`/api/post-sales-maintenances?${relatedQuery}`:null);
 const list=tab==='tickets'?tickets:tab==='warranties'?warranties:maintenances;
 function switchTab(value:Tab){setTab(value);setStatus('all');setPage(1);}
 function saved(value:{id:string}){const kind=create!;setCreate(null);router.push(`/pos-venda/${paths[kind]}/${value.id}`);router.refresh();}
 return <><div className="page-heading"><div><span className="eyebrow green">CUIDADO CONTÍNUO</span><h1>Pós-venda</h1><p>Chamados, garantias e manutenção da operação solar em um só lugar.</p></div>{canCreate&&<div className="crm-form-actions"><button className="button primary" onClick={()=>setCreate('ticket')}><Plus size={16}/>Novo chamado</button><button className="button secondary" onClick={()=>setCreate('warranty')}>Nova garantia</button><button className="button secondary" onClick={()=>setCreate('maintenance')}>Nova manutenção</button></div>}</div>
 <div className="crm-tabs post-sales-tabs" aria-label="Seções do pós-venda">{([['dashboard','Visão geral'],['tickets','Chamados'],['warranties','Garantias'],['maintenances','Manutenções']] as const).map(([key,label])=><button key={key} className={tab===key?'selected':''} aria-pressed={tab===key} onClick={()=>switchTab(key)}>{label}</button>)}</div>
 {tab==='dashboard'&&<><div className="installation-summary post-sales-metrics">{[['Chamados abertos','open_tickets'],['Críticos','critical_tickets'],['Em atendimento','in_service'],['Aguardando cliente','waiting_customer'],['Aguardando fornecedor','waiting_supplier'],['Resolvidos no período','resolved_period'],['Manutenções agendadas','scheduled_maintenances'],['Manutenções realizadas','completed_maintenances'],['Garantias acionadas','claimed_warranties'],['Garantias próximas do vencimento','expiring_warranties']] .map(([label,key])=><div key={key}><span>{label}</span><strong>{dashboard.data?.[key]??'—'}</strong></div>)}</div>{dashboard.error&&<p role="alert" className="error-box">{dashboard.error}</p>}<div className="card"><h2>Atendimento em andamento</h2><p className="muted">Use as abas para pesquisar clientes, acompanhar prazos e abrir cada registro.</p><button className="button secondary" onClick={()=>switchTab('tickets')}>Ver chamados</button></div></>}
 {tab!=='dashboard'&&<><div className="crm-toolbar card post-sales-toolbar">{tab==='tickets'&&<label className="crm-search"><Search size={16}/><input aria-label="Pesquisar chamados" value={q} onChange={event=>{setQ(event.target.value);setPage(1);}} maxLength={120} placeholder="Número, cliente, CPF/CNPJ, contrato ou instalação"/></label>}<label className="crm-field"><span>Cliente</span><select aria-label="Filtrar cliente" value={client} onChange={event=>{setClient(event.target.value);setPage(1);}}><option value="">Todos</option>{options.clients.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="crm-field"><span>Status</span><select aria-label="Filtrar status" value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}><option value="all">Todos</option>{Object.entries(tab==='tickets'?ticketStatuses:tab==='warranties'?warrantyStatuses:maintenanceStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{tab==='tickets'&&<><label className="crm-field"><span>Prioridade</span><select aria-label="Filtrar prioridade" value={priority} onChange={event=>{setPriority(event.target.value);setPage(1);}}><option value="all">Todas</option>{Object.entries(ticketPriorities).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="crm-field"><span>Categoria</span><select aria-label="Filtrar categoria" value={category} onChange={event=>{setCategory(event.target.value);setPage(1);}}><option value="all">Todas</option>{Object.entries(ticketCategories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="crm-field"><span>Responsável</span><select aria-label="Filtrar responsável" value={owner} onChange={event=>{setOwner(event.target.value);setPage(1);}}><option value="">Todos</option>{options.owners.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="crm-field"><span>De</span><input aria-label="Período inicial" type="date" value={from} onChange={event=>{setFrom(event.target.value);setPage(1);}}/></label><label className="crm-field"><span>Até</span><input aria-label="Período final" type="date" value={to} onChange={event=>{setTo(event.target.value);setPage(1);}}/></label></>}</div>
 {list.loading&&<p className="crm-loading" role="status">Carregando pós-venda…</p>}{list.error&&<p role="alert" className="error-box">{list.error}</p>}
 {tab==='tickets'&&<div className="installation-list">{tickets.data?.items.map(row=><Link className="card installation-row" href={`/pos-venda/chamados/${row.id}`} key={row.id}><div><span className={`document-status ${row.status}`}>{ticketStatuses[row.status]}</span><h2>{row.ticket_number} · {row.title}</h2><p>{row.client_name} · {row.contract_number??'Sem contrato'}</p><small>{ticketCategories[row.category]} · {ticketPriorities[row.priority]} · {row.responsible_name}</small></div><dl><div><dt>Prazo</dt><dd>{date(row.due_on)}</dd></div></dl></Link>)}</div>}
 {tab==='warranties'&&<div className="installation-list">{warranties.data?.items.map(row=><Link className="card installation-row" href={`/pos-venda/garantias/${row.id}`} key={row.id}><div><span className={`document-status ${row.effective_status}`}>{warrantyStatuses[row.effective_status]}</span><h2>{row.description}</h2><p>{row.client_name} · {row.installation_number}</p><small>{warrantyCategories[row.category]} · {row.manufacturer||'Fabricante não informado'}</small></div><dl><div><dt>Validade</dt><dd>{date(row.end_on)}</dd></div></dl></Link>)}</div>}
 {tab==='maintenances'&&<div className="installation-list">{maintenances.data?.items.map(row=><Link className="card installation-row" href={`/pos-venda/manutencoes/${row.id}`} key={row.id}><div><span className={`document-status ${row.status}`}>{maintenanceStatuses[row.status]}</span><h2>{row.reason}</h2><p>{row.client_name} · {row.installation_number}</p><small>{maintenanceTypes[row.type]} · {row.responsible_name}</small></div><dl><div><dt>Agendada</dt><dd>{date(row.scheduled_on)}</dd></div></dl></Link>)}</div>}
 {!list.loading&&((tab==='tickets'&&tickets.data?.items.length===0)||(tab==='warranties'&&warranties.data?.items.length===0)||(tab==='maintenances'&&maintenances.data?.items.length===0))&&<div className="card document-empty"><HeartHandshake size={28}/><h2>Nenhum registro encontrado</h2><p>Crie um registro ou ajuste os filtros.</p></div>}
 {list.data&&list.data.total>20&&<div className="crm-pagination"><span>{list.data.total} registros · Página {page}</span><div><button className="button secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><button className="button secondary" disabled={page*20>=list.data.total} onClick={()=>setPage(page+1)}>Próxima</button></div></div>}</>}
 {create&&<Modal title={create==='ticket'?'Novo chamado':create==='warranty'?'Nova garantia':'Nova manutenção'} onClose={()=>setCreate(null)}>{create==='ticket'?<TicketForm options={options} userId={userId} onSaved={saved} canManage={canManage}/>:create==='warranty'?<WarrantyForm options={options} userId={userId} onSaved={saved} canManage={canManage}/>:<MaintenanceForm options={options} userId={userId} onSaved={saved} canManage={canManage}/>}</Modal>}
 </>;
}
