import type {PoolClient} from 'pg';
import {database,transaction} from '@/server/db';
import type {Actor} from '@/modules/auth/policy';
import {isBusinessOpen,type BusinessHours} from '@/modules/automations/domain';
import {sendWhatsAppRecoveryTemplate} from '@/modules/whatsapp/outbound';
import type {MetaFetcher} from '@/modules/whatsapp/meta';
import {assessLead,loadLeadFacts,loadRecoveryConfig,type LeadFact,type RecoveryStep} from './eligibility';

type Db=Pick<PoolClient,'query'>;
type Attempt={id:string;organization_id:string;enrollment_id:string;step_position:number;template_id:string;client_request_id:string;attempts:number};
const parse=<T>(value:unknown):T=>typeof value==='string'?JSON.parse(value) as T:value as T;
const terminalReasons=new Set(['record_inactive','opted_out','consent_required','stage_excluded','seller_excluded','owner_inactive','invalid_phone','follow_up_scheduled','negotiation_concluded','proposal_accepted','conversation_paused','contact_blocked','awaiting_seller','uncontacted_disabled','missing_template','conversation_conflict','record_unavailable','not_scheduled','disabled','template_unavailable']);

async function actorFor(db:Db,organizationId:string,userId:string):Promise<Actor>{const result=await db.query(`SELECT u.id user_id,u.name,u.email,o.name organization_name,o.slug organization_slug,m.role_code role,r.name role_name,COALESCE(array_agg(rp.permission_code) FILTER(WHERE rp.permission_code IS NOT NULL),'{}') permissions FROM memberships m JOIN users u ON u.id=m.user_id JOIN organizations o ON o.id=m.organization_id JOIN roles r ON r.code=m.role_code LEFT JOIN role_permissions rp ON rp.role_code=m.role_code WHERE m.organization_id=$1 AND m.user_id=$2 AND m.active AND u.active GROUP BY u.id,u.name,u.email,o.name,o.slug,m.role_code,r.name`,[organizationId,userId]);const row=result.rows[0];if(!row)throw new Error('lead_recovery_actor_unavailable');return {userId:row.user_id,organizationId,name:row.name,email:row.email,organizationName:row.organization_name,organizationSlug:row.organization_slug,role:row.role,roleName:row.role_name,permissions:row.permissions};}
function cleanFact(fact:LeadFact):LeadFact{return {...fact,enrollment_id:null,enrollment_status:null,enrollment_version:null,attempt_count:null,next_attempt_at:null,state_reason:null};}

async function createEnrollment(db:Db,organizationId:string,fact:LeadFact,assessment:ReturnType<typeof assessLead>,updatedBy:string,first:RecoveryStep){
 if(!assessment.classification||!assessment.inactivity_anchor||!assessment.scheduled_for)return;
 const inserted=await db.query<{id:string}>(`INSERT INTO lead_recovery_enrollments(organization_id,record_id,conversation_id,owner_id,classification,inactivity_anchor,next_attempt_at,created_by,updated_by)
  VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8) ON CONFLICT(organization_id,record_id) WHERE status IN ('scheduled','paused') DO NOTHING RETURNING id`,[organizationId,fact.id,fact.conversation_id,fact.owner_id,assessment.classification,assessment.inactivity_anchor,assessment.scheduled_for,updatedBy]);
 if(inserted.rows[0])await db.query(`INSERT INTO lead_recovery_attempts(organization_id,enrollment_id,step_position,template_id,scheduled_for,client_request_id) VALUES ($1,$2,1,$3,$4,gen_random_uuid())`,[organizationId,inserted.rows[0].id,first.template_id,assessment.scheduled_for]);
}

export async function refreshLeadRecoveryEnrollments(){
 const organizations=await database().query<{organization_id:string}>("SELECT organization_id FROM organization_lead_recovery_settings WHERE enabled");let created=0,cancelled=0;
 for(const organization of organizations.rows){const loaded=await loadRecoveryConfig(database(),organization.organization_id);if(!loaded?.settings.enabled||!loaded.steps.length)continue;const facts=await loadLeadFacts(database(),organization.organization_id,undefined,2000);
  for(const fact of facts){const assessment=assessLead(cleanFact(fact),loaded.settings,loaded.steps);if(fact.enrollment_id&&['scheduled','paused'].includes(fact.enrollment_status??'')){if(!assessment.eligible&&terminalReasons.has(assessment.reason)){await transaction(async db=>{await db.query("UPDATE lead_recovery_enrollments SET status='cancelled',state_reason=$3,version=version+1,updated_by=$4,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status IN ('scheduled','paused')",[organization.organization_id,fact.enrollment_id,assessment.reason,loaded.settings.updated_by]);await db.query("UPDATE lead_recovery_attempts SET status='cancelled',safe_error=$3,completed_at=now(),updated_at=now() WHERE organization_id=$1 AND enrollment_id=$2 AND status='pending'",[organization.organization_id,fact.enrollment_id,assessment.reason]);});cancelled++;}continue;}if(assessment.eligible){await transaction(db=>createEnrollment(db,organization.organization_id,fact,assessment,loaded.settings.updated_by,loaded.steps[0]));created++;}}
 }
 return {organizations:organizations.rowCount,created,cancelled};
}

async function ensureConversation(db:Db,attempt:Attempt,fact:LeadFact,phone:string){
 const digits=phone.replace(/^\+/,'');const existing=await db.query<{id:string;record_id:string|null}>(`SELECT id,record_id FROM whatsapp_conversations WHERE organization_id=$1 AND external_wa_id=$2 FOR UPDATE`,[attempt.organization_id,digits]);
 if(existing.rows[0]){if(existing.rows[0].record_id&&existing.rows[0].record_id!==fact.id)throw new Error('lead_recovery_conversation_conflict');if(!existing.rows[0].record_id)await db.query("UPDATE whatsapp_conversations SET record_id=$3,link_status='identified',link_source='automatic',version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[attempt.organization_id,existing.rows[0].id,fact.id]);return existing.rows[0].id;}
 const inserted=await db.query<{id:string}>(`INSERT INTO whatsapp_conversations(organization_id,external_wa_id,phone_e164,profile_name,record_id,link_status,link_source,automation_owner_id) VALUES ($1,$2,$3,$4,$5,'identified','automatic',$6) RETURNING id`,[attempt.organization_id,digits,phone,fact.name,fact.id,fact.owner_id]);return inserted.rows[0].id;
}
export function leadFirstName(value:string){const first=value.trim().split(/\s+/u)[0]?.replace(/[^\p{L}\p{M}'’-]/gu,'').slice(0,80);return first||'Cliente';}
function render(value:string,fact:LeadFact,actor:Actor){return value.replaceAll('{{lead_first_name}}',leadFirstName(fact.name)).replaceAll('{{lead_name}}',fact.name).replaceAll('{{seller_name}}',fact.owner_name).replaceAll('{{organization_name}}',actor.organizationName);}

async function prepareAttempt(attempt:Attempt){return transaction(async db=>{
 const enrollment=await db.query<{record_id:string;status:string;owner_id:string}>(`SELECT record_id,status,owner_id FROM lead_recovery_enrollments WHERE organization_id=$1 AND id=$2 FOR UPDATE`,[attempt.organization_id,attempt.enrollment_id]);if(!enrollment.rows[0]||enrollment.rows[0].status!=='scheduled')throw new Error('lead_recovery_not_scheduled');
 const loaded=await loadRecoveryConfig(db,attempt.organization_id);if(!loaded?.settings.enabled)throw new Error('lead_recovery_disabled');const facts=await loadLeadFacts(db,attempt.organization_id,undefined,2000),fact=facts.find(row=>row.id===enrollment.rows[0].record_id);if(!fact)throw new Error('lead_recovery_record_unavailable');const assessment=assessLead(cleanFact(fact),loaded.settings,loaded.steps);if(!assessment.eligible||!assessment.normalized_phone)throw new Error(`lead_recovery_${assessment.reason}`);
 if(!isBusinessOpen(parse<BusinessHours>(loaded.settings.business_hours),loaded.settings.timezone,new Date())){await db.query("UPDATE lead_recovery_attempts SET status='pending',locked_at=NULL,scheduled_for=now()+interval '15 minutes',safe_error='outside_business_hours',updated_at=now() WHERE organization_id=$1 AND id=$2",[attempt.organization_id,attempt.id]);return null;}
 const step=loaded.steps.find(item=>item.position===attempt.step_position);if(!step||step.template_status!=='APPROVED'||!step.supported)throw new Error('lead_recovery_template_unavailable');const actor=await actorFor(db,attempt.organization_id,loaded.settings.updated_by),conversationId=await ensureConversation(db,attempt,fact,assessment.normalized_phone);await db.query('UPDATE lead_recovery_enrollments SET conversation_id=$3,updated_at=now() WHERE organization_id=$1 AND id=$2',[attempt.organization_id,attempt.enrollment_id,conversationId]);return {actor,conversationId,fact,step,steps:loaded.steps};
 });}

async function finishSent(attempt:Attempt,messageId:string,steps:RecoveryStep[]){await transaction(async db=>{await db.query("UPDATE lead_recovery_attempts SET status='sent',message_id=$3,sent_at=now(),completed_at=now(),locked_at=NULL,safe_error='',updated_at=now() WHERE organization_id=$1 AND id=$2",[attempt.organization_id,attempt.id,messageId]);const next=steps.find(step=>step.position===attempt.step_position+1);if(next){const scheduled=new Date(Date.now()+next.delay_days*86400000);await db.query('UPDATE lead_recovery_enrollments SET attempt_count=$3,last_attempt_at=now(),next_attempt_at=$4,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[attempt.organization_id,attempt.enrollment_id,attempt.step_position,scheduled]);await db.query('INSERT INTO lead_recovery_attempts(organization_id,enrollment_id,step_position,template_id,scheduled_for,client_request_id) VALUES ($1,$2,$3,$4,$5,gen_random_uuid()) ON CONFLICT(organization_id,enrollment_id,step_position) DO NOTHING',[attempt.organization_id,attempt.enrollment_id,next.position,next.template_id,scheduled]);}else await db.query("UPDATE lead_recovery_enrollments SET status='completed',attempt_count=$3,last_attempt_at=now(),next_attempt_at=NULL,state_reason='sequence_completed',version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[attempt.organization_id,attempt.enrollment_id,attempt.step_position]);});}
async function failAttempt(attempt:Attempt,error:unknown){const code=error instanceof Error?error.message.slice(0,180):'lead_recovery_unknown';const message=await database().query<{id:string;outcome_uncertain:boolean;delivery_status:string}>(`SELECT id,outcome_uncertain,delivery_status FROM whatsapp_messages WHERE organization_id=$1 AND lead_recovery_attempt_id=$2`,[attempt.organization_id,attempt.id]);const current=message.rows[0],uncertain=Boolean(current?.outcome_uncertain)||(Boolean(current)&&current.delivery_status!=='failed'),terminal=uncertain||terminalReasons.has(code.replace('lead_recovery_',''))||attempt.attempts>=3;if(!terminal){await database().query("UPDATE lead_recovery_attempts SET status='pending',locked_at=NULL,scheduled_for=now()+make_interval(mins=>attempts*5),safe_error=$3,updated_at=now() WHERE organization_id=$1 AND id=$2",[attempt.organization_id,attempt.id,code]);return;}await transaction(async db=>{await db.query('UPDATE lead_recovery_attempts SET status=$3,locked_at=NULL,safe_error=$4,completed_at=now(),updated_at=now() WHERE organization_id=$1 AND id=$2',[attempt.organization_id,attempt.id,uncertain?'uncertain':'failed',code]);await db.query("UPDATE lead_recovery_enrollments SET status='error',state_reason=$3,next_attempt_at=NULL,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[attempt.organization_id,attempt.enrollment_id,code]);});}

export async function processLeadRecoveryAttempts(limit=20,fetcher?:MetaFetcher){
 await database().query(`UPDATE lead_recovery_attempts a SET status=CASE WHEN a.attempts>=3 OR EXISTS(SELECT 1 FROM whatsapp_messages m WHERE m.organization_id=a.organization_id AND m.lead_recovery_attempt_id=a.id AND (m.outcome_uncertain OR m.delivery_status<>'failed')) THEN 'uncertain' ELSE 'pending' END,locked_at=NULL,scheduled_for=now()+interval '5 minutes',safe_error='lead_recovery_stale',updated_at=now() WHERE a.status='processing' AND a.locked_at<now()-interval '10 minutes'`);
 const jobs=await transaction(async db=>{const result=await db.query<Attempt>(`SELECT a.* FROM lead_recovery_attempts a JOIN lead_recovery_enrollments e ON e.organization_id=a.organization_id AND e.id=a.enrollment_id JOIN organization_lead_recovery_settings s ON s.organization_id=a.organization_id WHERE a.status='pending' AND a.scheduled_for<=now() AND e.status='scheduled' AND s.enabled ORDER BY a.scheduled_for,a.id FOR UPDATE OF a SKIP LOCKED LIMIT $1`,[limit]);if(result.rowCount)await db.query("UPDATE lead_recovery_attempts SET status='processing',attempts=attempts+1,locked_at=now(),updated_at=now() WHERE id=ANY($1::uuid[])",[result.rows.map(row=>row.id)]);return result.rows.map(row=>({...row,attempts:Number(row.attempts)+1}));});
 let sent=0;for(const attempt of jobs){try{const prepared=await prepareAttempt(attempt);if(!prepared)continue;const parameters={header:parse<string[]>(prepared.step.header_parameters).map(value=>render(value,prepared.fact,prepared.actor)),body:parse<string[]>(prepared.step.body_parameters).map(value=>render(value,prepared.fact,prepared.actor))};const message=await sendWhatsAppRecoveryTemplate(prepared.actor,prepared.conversationId,{client_request_id:attempt.client_request_id,template_id:attempt.template_id,parameters},{attemptId:attempt.id},fetcher);await finishSent(attempt,message.id,prepared.steps);sent++;}catch(error){await failAttempt(attempt,error);}}
 return {processed:jobs.length,sent};
}
export async function runLeadRecoveryScheduler(){await refreshLeadRecoveryEnrollments();return processLeadRecoveryAttempts();}

export async function handleLeadRecoveryInbound(db:Db,input:{organizationId:string;conversationId:string;recordId:string|null;timestamp:Date;text:string}){
 const enrollment=await db.query<{id:string;record_id:string;owner_id:string;status:string}>(`SELECT e.id,e.record_id,e.owner_id,e.status FROM lead_recovery_enrollments e WHERE e.organization_id=$1 AND (e.conversation_id=$2 OR ($3::uuid IS NOT NULL AND e.record_id=$3)) AND e.status IN ('scheduled','paused') ORDER BY e.created_at DESC LIMIT 1 FOR UPDATE`,[input.organizationId,input.conversationId,input.recordId]);if(!enrollment.rows[0])return {interrupted:false};const row=enrollment.rows[0],optOut=['sair','parar','cancelar','não quero receber','nao quero receber'].includes(input.text.trim().toLocaleLowerCase('pt-BR')),status=optOut?'cancelled':'responded',reason=optOut?'contact_opt_out':'client_replied';
 await db.query('UPDATE lead_recovery_enrollments SET status=$3,response_at=$4,next_attempt_at=NULL,state_reason=$5,version=version+1,updated_by=$6,updated_at=now() WHERE organization_id=$1 AND id=$2',[input.organizationId,row.id,status,input.timestamp,reason,row.owner_id]);await db.query("UPDATE lead_recovery_attempts SET status='cancelled',safe_error=$3,completed_at=now(),updated_at=now() WHERE organization_id=$1 AND enrollment_id=$2 AND status='pending'",[input.organizationId,row.id,reason]);
 if(optOut){await db.query(`INSERT INTO crm_contact_preferences(organization_id,record_id,whatsapp_consent_status,consent_source,opted_out_at,updated_by) VALUES ($1,$2,'opted_out','Solicitação recebida pelo WhatsApp',now(),$3) ON CONFLICT(organization_id,record_id) DO UPDATE SET whatsapp_consent_status='opted_out',consent_source=EXCLUDED.consent_source,consented_at=NULL,opted_out_at=now(),updated_by=EXCLUDED.updated_by,version=crm_contact_preferences.version+1,updated_at=now()`,[input.organizationId,row.record_id,row.owner_id]);await db.query('UPDATE whatsapp_conversations SET automation_blocked=true,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[input.organizationId,input.conversationId]);}
 await db.query(`INSERT INTO user_notifications(organization_id,user_id,notification_type,title,detail,entity_type,entity_id) VALUES ($1,$2,$3,$4,$5,'lead',$6)`,[input.organizationId,row.owner_id,optOut?'lead_recovery.opt_out':'lead_recovery.response',optOut?'Cliente solicitou descadastramento':'Lead respondeu à recuperação',optOut?'O contato foi bloqueado e as próximas tentativas foram canceladas.':'As próximas tentativas foram canceladas. Abra o atendimento para continuar.',row.record_id]);await db.query("INSERT INTO crm_activities(organization_id,record_id,actor_id,action,detail) VALUES ($1,$2,$3,$4,$5)",[input.organizationId,row.record_id,row.owner_id,optOut?'lead_recovery.opted_out':'lead_recovery.responded',optOut?'Descadastramento solicitado pelo WhatsApp.':'Cliente respondeu; sequência automática interrompida.']);return {interrupted:true,optOut};
}
