'use client';
import {useState} from 'react';
import {Activity,AlertTriangle,Bot,CheckCircle2,Database,HardDrive,Mail,MessageCircle,RefreshCw} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';

type Alert={id:string;code:string;severity:'warning'|'critical';status:'open'|'acknowledged'|'resolved';title:string;detail:string;occurrence_count:number;first_detected_at:string;last_detected_at:string;acknowledged_at:string|null;resolved_at:string|null};
type NotificationSettings={email_enabled:boolean;recipients:string[];minimum_severity:'warning'|'critical';notify_recovery:boolean;critical_escalation_minutes:number;version:number;updated_at:string|null};
type Delivery={id:string;alert_id:string;notification_kind:'opened'|'escalated'|'resolved';status:'pending'|'processing'|'sent'|'failed'|'uncertain';attempts:number;safe_error:string;created_at:string;sent_at:string|null;title:string;severity:'warning'|'critical'};
type Data={monitor:{status:'healthy'|'degraded';open_alerts:number;last_checked_at:string;last_healthy_at:string|null;check_duration_ms:number}|null;alerts:Alert[];queues:Record<string,number>;notification_settings:NotificationSettings;deliveries:Delivery[];integrations:{database:boolean;storage:boolean;whatsapp:boolean;smtp:boolean;ai:boolean;ai_provider:string|null}};

const date=(value:string|null)=>value?new Date(value).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
const names:Record<string,string>={database:'Banco de dados',storage:'Storage privado',whatsapp:'WhatsApp Business',smtp:'E-mail SMTP',ai:'Assistente de IA'};
const icons={database:Database,storage:HardDrive,whatsapp:MessageCircle,smtp:Mail,ai:Bot};
const queueGroups=[
 {name:'Webhooks do WhatsApp',failed:'webhook_failed',overdue:'webhook_overdue'},
 {name:'Exclusões do Storage',failed:'storage_failed',overdue:'storage_overdue'},
 {name:'Automações',failed:'automation_failed',overdue:'automation_overdue'},
 {name:'E-mails de documentos',failed:'email_failed',overdue:'email_overdue'},
] as const;
const deliveryStatus:Record<Delivery['status'],string>={pending:'Pendente',processing:'Processando',sent:'Enviado',failed:'Falhou',uncertain:'Confirmação incerta'};
const deliveryKind:Record<Delivery['notification_kind'],string>={opened:'Abertura',escalated:'Escalada',resolved:'Recuperação'};

export function OperationalMonitoring({initial}:{initial:Data}){
 const [data,setData]=useState(initial),[busy,setBusy]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const [settings,setSettings]=useState(initial.notification_settings),[recipients,setRecipients]=useState(initial.notification_settings.recipients.join('\n'));
 async function refresh(){setBusy('refresh');setError('');try{const next=await api<Data>('/api/operations/monitoring');setData(next);setSettings(next.notification_settings);setRecipients(next.notification_settings.recipients.join('\n'));}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 async function acknowledge(id:string){setBusy(id);setError('');try{await api('/api/operations/monitoring','POST',{alert_id:id});await refresh();}catch(e){setError(errorMessage(e));setBusy('');}}
 async function saveNotifications(){setBusy('settings');setError('');setSaved('');try{const list=recipients.split(/[\n,;]+/).map(value=>value.trim()).filter(Boolean);const next=await api<NotificationSettings>('/api/operations/monitoring','POST',{action:'save_notifications',email_enabled:settings.email_enabled,recipients:list,minimum_severity:settings.minimum_severity,notify_recovery:settings.notify_recovery,critical_escalation_minutes:settings.critical_escalation_minutes,version:settings.version});setSettings(next);setRecipients(next.recipients.join('\n'));setSaved('Configuração salva.');await refresh();}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 const active=data.alerts.filter(item=>item.status!=='resolved'),history=data.alerts.filter(item=>item.status==='resolved');
 return <div className="operations-monitoring">
  <div className="page-heading"><div><span className="eyebrow blue">OPERAÇÃO E CONFIABILIDADE</span><h1>Monitoramento do CRM</h1><p>Saúde das integrações, filas persistentes e incidentes seguros da organização.</p></div><button className="button secondary" onClick={refresh} disabled={Boolean(busy)}><RefreshCw size={16}/>{busy==='refresh'?'Atualizando…':'Atualizar'}</button></div>
  {error&&<p className="error-box" role="alert">{error}</p>}{saved&&<p className="success-box" role="status">{saved}</p>}
  <section className={'card operations-health '+(data.monitor?.status==='healthy'?'healthy':'degraded')}><div>{data.monitor?.status==='healthy'?<CheckCircle2 size={24}/>:<AlertTriangle size={24}/>}<span><strong>{data.monitor?.status==='healthy'?'Operação saudável':data.monitor?'Atenção necessária':'Aguardando primeira verificação'}</strong><small>Última verificação: {date(data.monitor?.last_checked_at??null)} · duração {data.monitor?.check_duration_ms??0} ms</small></span></div><b>{active.length} alerta(s) ativo(s)</b></section>
  <section><div className="section-heading"><h2>Integrações</h2><span className="muted">Nenhuma chave ou segredo é exibido.</span></div><div className="operations-integrations">{Object.entries(data.integrations).filter(([key])=>key!=='ai_provider').map(([key,configured])=>{const Icon=icons[key as keyof typeof icons]??Activity;return <article className="card" key={key}><Icon size={20}/><div><strong>{names[key]}</strong>{key==='ai'&&data.integrations.ai_provider?<small>Provedor: {data.integrations.ai_provider}</small>:null}</div><span className={'document-status '+(configured?'completed':'pending_issue')}>{configured?'Disponível':'Não configurado'}</span></article>;})}</div></section>
  <section><div className="section-heading"><h2>Filas operacionais</h2><span className="muted">Falhas recentes e trabalhos acima do tempo esperado.</span></div><div className="operations-queues">{queueGroups.map(queue=>{const failed=data.queues[queue.failed]??0,overdue=data.queues[queue.overdue]??0;return <article className="card" key={queue.name}><Activity size={20}/><div><strong>{queue.name}</strong><small>{failed} falha(s) · {overdue} atrasado(s)</small></div><span className={'document-status '+(failed||overdue?'pending_issue':'completed')}>{failed||overdue?'Atenção':'Normal'}</span></article>;})}<article className="card"><MessageCircle size={20}/><div><strong>Entrega WhatsApp</strong><small>{data.queues.whatsapp_uncertain??0} incerto(s) · {data.queues.whatsapp_failed??0} falha(s)</small></div><span className={'document-status '+((data.queues.whatsapp_uncertain??0)||(data.queues.whatsapp_failed??0)>=3?'pending_issue':'completed')}>{(data.queues.whatsapp_uncertain??0)||(data.queues.whatsapp_failed??0)>=3?'Atenção':'Normal'}</span></article><article className="card"><Bot size={20}/><div><strong>Assistente de IA</strong><small>{data.queues.ai_failed??0} falha(s) em {data.queues.ai_total??0} uso(s)</small></div><span className={'document-status '+((data.queues.ai_failed??0)>=3?'pending_issue':'completed')}>{(data.queues.ai_failed??0)>=3?'Atenção':'Normal'}</span></article></div></section>
  <section className="card operations-notification-settings"><div className="section-heading"><div><h2>Alertas externos por e-mail</h2><p className="muted">Avisos deduplicados para incidentes novos, escalados e recuperados.</p></div><span className={'document-status '+(settings.email_enabled?'completed':'scheduled')}>{settings.email_enabled?'Ativos':'Pausados'}</span></div>{!data.integrations.smtp&&<p className="info-box">Configure SMTP no ambiente para ativar o envio. Nenhuma credencial é armazenada nesta tela.</p>}<div className="form-grid"><label className="checkbox-row"><input type="checkbox" checked={settings.email_enabled} disabled={!data.integrations.smtp} onChange={event=>setSettings(current=>({...current,email_enabled:event.target.checked}))}/> Ativar alertas por e-mail</label><label>Severidade mínima<select value={settings.minimum_severity} onChange={event=>setSettings(current=>({...current,minimum_severity:event.target.value as NotificationSettings['minimum_severity']}))}><option value="critical">Somente críticos</option><option value="warning">Atenção e críticos</option></select></label><label>Escalar crítico após<input type="number" min={15} max={1440} value={settings.critical_escalation_minutes} onChange={event=>setSettings(current=>({...current,critical_escalation_minutes:Number(event.target.value)}))}/><small>Minutos sem reconhecimento; uma única escalada por incidente.</small></label><label className="field-span">Destinatários<textarea aria-label="Destinatários dos alertas" rows={3} value={recipients} onChange={event=>setRecipients(event.target.value)} placeholder={'gestao@empresa.com\nsuporte@empresa.com'}/><small>Um por linha, vírgula ou ponto e vírgula. Máximo de cinco.</small></label><label className="checkbox-row field-span"><input type="checkbox" checked={settings.notify_recovery} onChange={event=>setSettings(current=>({...current,notify_recovery:event.target.checked}))}/> Avisar quando a operação se recuperar</label></div><div className="form-actions"><button className="button primary" disabled={Boolean(busy)} onClick={saveNotifications}>{busy==='settings'?'Salvando…':'Salvar alertas externos'}</button></div></section>
  <section><div className="section-heading"><h2>Alertas ativos</h2><span className="muted">Alertas reconhecidos continuam acompanhados até a recuperação.</span></div>{active.length?<div className="operations-alerts">{active.map(alert=><article className={'card operations-alert '+alert.severity} key={alert.id}><AlertTriangle size={19}/><div><header><strong>{alert.title}</strong><span className={'document-status '+(alert.status==='acknowledged'?'scheduled':'pending_issue')}>{alert.status==='acknowledged'?'Reconhecido':alert.severity==='critical'?'Crítico':'Atenção'}</span></header><p>{alert.detail}</p><small>Detectado: {date(alert.first_detected_at)} · última ocorrência: {date(alert.last_detected_at)}</small></div>{alert.status==='open'&&<button className="button secondary" disabled={Boolean(busy)} onClick={()=>acknowledge(alert.id)}>{busy===alert.id?'Salvando…':'Reconhecer'}</button>}</article>)}</div>:<div className="card empty-state"><CheckCircle2 size={28}/><h3>Nenhum incidente ativo</h3><p>As verificações automáticas não encontraram filas paradas ou falhas recorrentes.</p></div>}</section>
  {data.deliveries.length>0&&<details className="card operations-history"><summary>Entregas de alertas por e-mail ({data.deliveries.length})</summary>{data.deliveries.map(delivery=><div key={delivery.id}><span><strong>{deliveryKind[delivery.notification_kind]} · {delivery.title}</strong><small>{date(delivery.sent_at??delivery.created_at)} · {deliveryStatus[delivery.status]}</small></span><span className={'document-status '+(delivery.status==='sent'?'completed':delivery.status==='failed'||delivery.status==='uncertain'?'pending_issue':'scheduled')}>{deliveryStatus[delivery.status]}</span></div>)}</details>}
  {history.length>0&&<details className="card operations-history"><summary>Incidentes resolvidos recentemente ({history.length})</summary>{history.map(alert=><div key={alert.id}><strong>{alert.title}</strong><small>Resolvido em {date(alert.resolved_at)}</small></div>)}</details>}
 </div>;
}
