'use client';
import {useState} from 'react';
import {Activity,AlertTriangle,Bot,CheckCircle2,Database,HardDrive,Mail,MessageCircle,RefreshCw} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
type Alert={id:string;code:string;severity:'warning'|'critical';status:'open'|'acknowledged'|'resolved';title:string;detail:string;occurrence_count:number;first_detected_at:string;last_detected_at:string;acknowledged_at:string|null;resolved_at:string|null};
type Data={monitor:{status:'healthy'|'degraded';open_alerts:number;last_checked_at:string;last_healthy_at:string|null;check_duration_ms:number}|null;alerts:Alert[];queues:Record<string,number>;integrations:{database:boolean;storage:boolean;whatsapp:boolean;smtp:boolean;ai:boolean;ai_provider:string|null}};
const date=(value:string|null)=>value?new Date(value).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
const names:Record<string,string>={database:'Banco de dados',storage:'Storage privado',whatsapp:'WhatsApp Business',smtp:'E-mail SMTP',ai:'Assistente de IA'};
const icons={database:Database,storage:HardDrive,whatsapp:MessageCircle,smtp:Mail,ai:Bot};
const queueGroups=[
 {name:'Webhooks do WhatsApp',failed:'webhook_failed',overdue:'webhook_overdue'},
 {name:'Exclusões do Storage',failed:'storage_failed',overdue:'storage_overdue'},
 {name:'Automações',failed:'automation_failed',overdue:'automation_overdue'},
 {name:'E-mails de documentos',failed:'email_failed',overdue:'email_overdue'},
] as const;
export function OperationalMonitoring({initial}:{initial:Data}){const [data,setData]=useState(initial),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function refresh(){setBusy('refresh');setError('');try{setData(await api<Data>('/api/operations/monitoring'));}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 async function acknowledge(id:string){setBusy(id);setError('');try{await api('/api/operations/monitoring','POST',{alert_id:id});await refresh();}catch(e){setError(errorMessage(e));setBusy('');}}
 const active=data.alerts.filter(item=>item.status!=='resolved'),history=data.alerts.filter(item=>item.status==='resolved');
 return <div className="operations-monitoring"><div className="page-heading"><div><span className="eyebrow blue">OPERAÇÃO E CONFIABILIDADE</span><h1>Monitoramento do CRM</h1><p>Saúde das integrações, filas persistentes e incidentes seguros da organização.</p></div><button className="button secondary" onClick={refresh} disabled={Boolean(busy)}><RefreshCw size={16}/>{busy==='refresh'?'Atualizando…':'Atualizar'}</button></div>{error&&<p className="error-box" role="alert">{error}</p>}
 <section className={`card operations-health ${data.monitor?.status==='healthy'?'healthy':'degraded'}`}><div>{data.monitor?.status==='healthy'?<CheckCircle2 size={24}/>:<AlertTriangle size={24}/>}<span><strong>{data.monitor?.status==='healthy'?'Operação saudável':data.monitor?'Atenção necessária':'Aguardando primeira verificação'}</strong><small>Última verificação: {date(data.monitor?.last_checked_at??null)} · duração {data.monitor?.check_duration_ms??0} ms</small></span></div><b>{active.length} alerta(s) ativo(s)</b></section>
 <section><div className="section-heading"><h2>Integrações</h2><span className="muted">Nenhuma chave ou segredo é exibido.</span></div><div className="operations-integrations">{Object.entries(data.integrations).filter(([key])=>key!=='ai_provider').map(([key,configured])=>{const Icon=icons[key as keyof typeof icons]??Activity;return <article className="card" key={key}><Icon size={20}/><div><strong>{names[key]}</strong>{key==='ai'&&data.integrations.ai_provider?<small>Provedor: {data.integrations.ai_provider}</small>:null}</div><span className={`document-status ${configured?'completed':'pending_issue'}`}>{configured?'Disponível':'Não configurado'}</span></article>;})}</div></section>
 <section><div className="section-heading"><h2>Filas operacionais</h2><span className="muted">Falhas recentes e trabalhos acima do tempo esperado.</span></div><div className="operations-queues">{queueGroups.map(queue=>{const failed=data.queues[queue.failed]??0,overdue=data.queues[queue.overdue]??0;return <article className="card" key={queue.name}><Activity size={20}/><div><strong>{queue.name}</strong><small>{failed} falha(s) · {overdue} atrasado(s)</small></div><span className={`document-status ${failed||overdue?'pending_issue':'completed'}`}>{failed||overdue?'Atenção':'Normal'}</span></article>;})}<article className="card"><MessageCircle size={20}/><div><strong>Entrega WhatsApp</strong><small>{data.queues.whatsapp_uncertain??0} incerto(s) · {data.queues.whatsapp_failed??0} falha(s)</small></div><span className={`document-status ${(data.queues.whatsapp_uncertain??0)||(data.queues.whatsapp_failed??0)>=3?'pending_issue':'completed'}`}>{(data.queues.whatsapp_uncertain??0)||(data.queues.whatsapp_failed??0)>=3?'Atenção':'Normal'}</span></article><article className="card"><Bot size={20}/><div><strong>Assistente de IA</strong><small>{data.queues.ai_failed??0} falha(s) em {data.queues.ai_total??0} uso(s)</small></div><span className={`document-status ${(data.queues.ai_failed??0)>=3?'pending_issue':'completed'}`}>{(data.queues.ai_failed??0)>=3?'Atenção':'Normal'}</span></article></div></section>
 <section><div className="section-heading"><h2>Alertas ativos</h2><span className="muted">Alertas reconhecidos continuam acompanhados até a recuperação.</span></div>{active.length?<div className="operations-alerts">{active.map(alert=><article className={`card operations-alert ${alert.severity}`} key={alert.id}><AlertTriangle size={19}/><div><header><strong>{alert.title}</strong><span className={`document-status ${alert.status==='acknowledged'?'scheduled':'pending_issue'}`}>{alert.status==='acknowledged'?'Reconhecido':alert.severity==='critical'?'Crítico':'Atenção'}</span></header><p>{alert.detail}</p><small>Detectado: {date(alert.first_detected_at)} · última ocorrência: {date(alert.last_detected_at)}</small></div>{alert.status==='open'&&<button className="button secondary" disabled={Boolean(busy)} onClick={()=>acknowledge(alert.id)}>{busy===alert.id?'Salvando…':'Reconhecer'}</button>}</article>)}</div>:<div className="card empty-state"><CheckCircle2 size={28}/><h3>Nenhum incidente ativo</h3><p>As verificações automáticas não encontraram filas paradas ou falhas recorrentes.</p></div>}</section>
 {history.length>0&&<details className="card operations-history"><summary>Incidentes resolvidos recentemente ({history.length})</summary>{history.map(alert=><div key={alert.id}><strong>{alert.title}</strong><small>Resolvido em {date(alert.resolved_at)}</small></div>)}</details>}</div>}
