import type {PoolClient} from 'pg';
import {database,transaction} from '@/server/db';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {assertCommercialAssignee,assertManagedTeam} from '@/modules/commercial/scope';
import {automationRuleInput,automationSettingsInput,automationSimulationInput,isBusinessOpen,type AutomationAction,type BusinessHours} from './domain';
import {assertWhatsAppConversation} from '@/modules/whatsapp/inbox';

type Db=Pick<PoolClient,'query'>;
const defaults={timezone:'America/Sao_Paulo',business_hours:{'1':{enabled:true,start:'08:00',end:'18:00'},'2':{enabled:true,start:'08:00',end:'18:00'},'3':{enabled:true,start:'08:00',end:'18:00'},'4':{enabled:true,start:'08:00',end:'18:00'},'5':{enabled:true,start:'08:00',end:'18:00'},'6':{enabled:true,start:'08:00',end:'12:00'},'7':{enabled:false,start:'08:00',end:'18:00'}} as BusinessHours,max_outbound_per_conversation_24h:3,max_outbound_per_rule_24h:100};
function read(actor:Actor){requirePermission(actor,'automations.read');}
function manage(actor:Actor){requirePermission(actor,'automations.manage');}
const parse=<T>(value:unknown)=>typeof value==='string'?JSON.parse(value) as T:value as T;
async function readAutomationRule(db:Db,actor:Actor,id:string){const result=await db.query('SELECT * FROM automation_rules WHERE organization_id=$1 AND id=$2 AND ($3::boolean OR created_by=$4)',[actor.organizationId,id,actor.role==='admin',actor.userId]);if(!result.rowCount)throw new AccessError(404,'Automação não encontrada.');return {...result.rows[0],conditions:parse(result.rows[0].conditions),actions:parse(result.rows[0].actions)};}

export async function automationSettings(actor:Actor){read(actor);const result=await database().query('SELECT * FROM organization_automation_settings WHERE organization_id=$1',[actor.organizationId]);const row=result.rows[0];return row?{...row,business_hours:parse<BusinessHours>(row.business_hours)}:{organization_id:actor.organizationId,whatsapp_outbound_enabled:false,...defaults,version:1,created_at:null,updated_at:null};}
export async function saveAutomationSettings(actor:Actor,input:unknown){manage(actor);if(actor.role!=='admin')throw new AccessError(403,'Somente administradores podem alterar o controle global de envio.');const data=automationSettingsInput.parse(input);return transaction(async db=>{const current=await db.query('SELECT version,whatsapp_outbound_enabled FROM organization_automation_settings WHERE organization_id=$1 FOR UPDATE',[actor.organizationId]);if(current.rowCount&&Number(current.rows[0].version)!==data.version)throw new AccessError(409,'As configurações foram atualizadas. Recarregue a página.');if(!current.rowCount&&data.version!==1)throw new AccessError(409,'As configurações foram atualizadas. Recarregue a página.');await db.query(`INSERT INTO organization_automation_settings(organization_id,whatsapp_outbound_enabled,timezone,business_hours,max_outbound_per_conversation_24h,max_outbound_per_rule_24h,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(organization_id) DO UPDATE SET whatsapp_outbound_enabled=EXCLUDED.whatsapp_outbound_enabled,timezone=EXCLUDED.timezone,business_hours=EXCLUDED.business_hours,max_outbound_per_conversation_24h=EXCLUDED.max_outbound_per_conversation_24h,max_outbound_per_rule_24h=EXCLUDED.max_outbound_per_rule_24h,updated_by=EXCLUDED.updated_by,version=organization_automation_settings.version+1,updated_at=now()`,[actor.organizationId,data.whatsapp_outbound_enabled,data.timezone,JSON.stringify(data.business_hours),data.max_outbound_per_conversation_24h,data.max_outbound_per_rule_24h,actor.userId]);await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,'automation.settings.updated',`Envio externo automático: ${data.whatsapp_outbound_enabled?'ativo':'pausado'}.`]);return (await db.query('SELECT * FROM organization_automation_settings WHERE organization_id=$1',[actor.organizationId])).rows[0];});}

async function validateReferences(actor:Actor,actions:AutomationAction[],db:Db){for(const action of actions){if('tag_id' in action){const tag=await db.query('SELECT 1 FROM crm_tags WHERE organization_id=$1 AND id=$2',[actor.organizationId,action.tag_id]);if(!tag.rowCount)throw new AccessError(400,'Tag não encontrada nesta organização.');}if('template_id' in action){const template=await db.query("SELECT 1 FROM whatsapp_templates WHERE organization_id=$1 AND id=$2 AND status='APPROVED' AND supported",[actor.organizationId,action.template_id]);if(!template.rowCount)throw new AccessError(400,'Modelo aprovado não encontrado nesta organização.');}if('owner_id' in action&&action.owner_id)await assertCommercialAssignee(actor,action.owner_id,db);if('team_id' in action&&action.team_id)await assertManagedTeam(actor,action.team_id,db);}}
export async function listAutomationRules(actor:Actor){read(actor);const result=await database().query('SELECT * FROM automation_rules WHERE organization_id=$1 AND ($2::boolean OR created_by=$3) ORDER BY active DESC,priority,name,id',[actor.organizationId,actor.role==='admin',actor.userId]);return result.rows.map(row=>({...row,conditions:parse(row.conditions),actions:parse(row.actions)}));}
export async function getAutomationRule(actor:Actor,id:string){read(actor);const result=await database().query('SELECT * FROM automation_rules WHERE organization_id=$1 AND id=$2 AND ($3::boolean OR created_by=$4)',[actor.organizationId,id,actor.role==='admin',actor.userId]);if(!result.rowCount)throw new AccessError(404,'Automação não encontrada.');return {...result.rows[0],conditions:parse(result.rows[0].conditions),actions:parse(result.rows[0].actions)};}
export async function saveAutomationRule(actor:Actor,input:unknown,id?:string){manage(actor);const data=automationRuleInput.parse(input);return transaction(async db=>{await validateReferences(actor,data.actions,db);const current=id?await db.query('SELECT * FROM automation_rules WHERE organization_id=$1 AND id=$2 AND ($3::boolean OR created_by=$4) FOR UPDATE',[actor.organizationId,id,actor.role==='admin',actor.userId]):null;if(id&&!current?.rowCount)throw new AccessError(404,'Automação não encontrada.');if(current?.rowCount&&Number(current.rows[0].version)!==data.version)throw new AccessError(409,'A automação foi atualizada. Recarregue a página.');if(!id&&data.version!==null)throw new AccessError(409,'A automação foi atualizada. Recarregue a página.');let saved=id;try{if(id)await db.query(`UPDATE automation_rules SET name=$3,description=$4,active=$5,trigger_type=$6,conditions=$7,actions=$8,priority=$9,cooldown_minutes=$10,updated_by=$11,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,data.name,data.description,data.active,data.trigger_type,JSON.stringify(data.conditions),JSON.stringify(data.actions),data.priority,data.cooldown_minutes,actor.userId]);else saved=(await db.query(`INSERT INTO automation_rules(organization_id,name,description,active,trigger_type,conditions,actions,priority,cooldown_minutes,created_by,updated_by) VALUES ($1,$2,$3,false,$4,$5,$6,$7,$8,$9,$9) RETURNING id`,[actor.organizationId,data.name,data.description,data.trigger_type,JSON.stringify(data.conditions),JSON.stringify(data.actions),data.priority,data.cooldown_minutes,actor.userId])).rows[0].id;}catch(error){if((error as {code?:string}).code==='23505')throw new AccessError(409,'Já existe uma automação com este nome.');throw error;}await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,id?'automation.rule.updated':'automation.rule.created',`Automação ${saved}; ${id?`ativa=${data.active}`:'criada desativada'}.`]);return readAutomationRule(db,actor,saved!);});}
export async function setAutomationRuleActive(actor:Actor,id:string,active:boolean,version:number){manage(actor);return transaction(async db=>{const result=await db.query('UPDATE automation_rules SET active=$3,updated_by=$4,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2 AND version=$5 AND ($6::boolean OR created_by=$7) RETURNING id',[actor.organizationId,id,active,actor.userId,version,actor.role==='admin',actor.userId]);if(!result.rowCount){const exists=await db.query('SELECT 1 FROM automation_rules WHERE organization_id=$1 AND id=$2 AND ($3::boolean OR created_by=$4)',[actor.organizationId,id,actor.role==='admin',actor.userId]);if(!exists.rowCount)throw new AccessError(404,'Automação não encontrada.');throw new AccessError(409,'A automação foi atualizada. Recarregue a página.');}await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,active?'automation.rule.activated':'automation.rule.deactivated',`Automação ${id}.`]);return readAutomationRule(db,actor,id);});}
export async function listAutomationRuns(actor:Actor,page=1){read(actor);const limit=30,offset=(page-1)*limit;const [items,total]=await Promise.all([database().query(`SELECT r.*,a.name rule_name,(SELECT json_agg(x ORDER BY x.action_index) FROM automation_run_actions x WHERE x.organization_id=r.organization_id AND x.run_id=r.id) actions FROM automation_runs r JOIN automation_rules a ON a.organization_id=r.organization_id AND a.id=r.rule_id WHERE r.organization_id=$1 AND ($4::boolean OR a.created_by=$5) ORDER BY r.created_at DESC,r.id DESC LIMIT $2 OFFSET $3`,[actor.organizationId,limit,offset,actor.role==='admin',actor.userId]),database().query('SELECT count(*)::int total FROM automation_runs r JOIN automation_rules a ON a.organization_id=r.organization_id AND a.id=r.rule_id WHERE r.organization_id=$1 AND ($2::boolean OR a.created_by=$3)',[actor.organizationId,actor.role==='admin',actor.userId])]);return {items:items.rows,total:Number(total.rows[0].total),page,pageSize:limit};}
export async function automationOptions(actor:Actor){read(actor);const [tags,owners,teams,templates]=await Promise.all([database().query('SELECT id,name,color FROM crm_tags WHERE organization_id=$1 ORDER BY name',[actor.organizationId]),database().query(`SELECT m.user_id id,u.name FROM memberships m JOIN users u ON u.id=m.user_id JOIN roles r ON r.code=m.role_code WHERE m.organization_id=$1 AND m.active AND r.code IN ('admin','manager','seller') AND ($2::boolean OR m.user_id=$3 OR EXISTS(SELECT 1 FROM commercial_team_members tm JOIN commercial_teams t ON t.organization_id=tm.organization_id AND t.id=tm.team_id WHERE tm.organization_id=m.organization_id AND tm.user_id=m.user_id AND t.manager_user_id=$3 AND t.active)) ORDER BY u.name`,[actor.organizationId,actor.role==='admin',actor.userId]),database().query('SELECT id,name FROM commercial_teams WHERE organization_id=$1 AND ($2::boolean OR manager_user_id=$3) ORDER BY name',[actor.organizationId,actor.role==='admin',actor.userId]),database().query("SELECT id,name,language FROM whatsapp_templates WHERE organization_id=$1 AND status='APPROVED' AND supported ORDER BY name,language",[actor.organizationId])]);return {tags:tags.rows,owners:owners.rows,teams:teams.rows,templates:templates.rows};}
export async function simulateAutomationRule(actor:Actor,id:string,input:unknown){const rule=await getAutomationRule(actor,id),sample=automationSimulationInput.parse(input),settings=await automationSettings(actor),checks=(rule.conditions.all as {type:string;value?:string}[]).map(condition=>({condition,matched:condition.type==='outside_business_hours'?sample.outside_business_hours:condition.type==='inside_business_hours'?!sample.outside_business_hours:condition.type==='conversation_unassigned'?sample.conversation_unassigned:condition.type==='new_whatsapp_conversation'?sample.new_whatsapp_conversation:condition.type==='record_kind'?sample.record_kind===condition.value:condition.type==='stage_equals'?sample.stage===condition.value:condition.type==='elapsed_minutes'?sample.elapsed_minutes>=Number(condition.value):false}));return {simulation:true,trigger_compatible:rule.trigger_type===sample.trigger_type,conditions:checks,matched:rule.trigger_type===sample.trigger_type&&checks.every(check=>check.matched),business_open:isBusinessOpen(settings.business_hours,settings.timezone),actions:(rule.actions as AutomationAction[]).map(action=>({type:action.type,would_execute:true})),external_actions_executed:false};}

export async function updateConversationAutomation(actor:Actor,conversationId:string,input:{automations_paused?:boolean;automation_blocked?:boolean;version:number}){requirePermission(actor,'whatsapp.use');return transaction(async db=>{const current=await assertWhatsAppConversation(actor,conversationId,db,true);if(Number(current.version)!==input.version)throw new AccessError(409,'Conversa atualizada. Recarregue a página.');const paused=input.automations_paused??current.automations_paused,blocked=input.automation_blocked??current.automation_blocked;await db.query('UPDATE whatsapp_conversations SET automations_paused=$3,automation_blocked=$4,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,conversationId,paused,blocked]);await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,input.automation_blocked!==undefined?'automation.conversation.blocked_changed':'automation.conversation.paused_changed',`Conversa ${conversationId}; pausada=${paused}; bloqueada=${blocked}.`]);return {ok:true};});}
