'use client';
import {useState} from 'react';
import {Download,FileClock,FilePlus2,History,Mail,PenLine} from 'lucide-react';
import {api,errorMessage} from '@/components/crm/api';
import {Modal} from '@/components/crm/modal';
import {useRemote} from '@/components/crm/use-remote';
import {documentStatuses,documentTypes,type CrmDocument,type DocumentEmail,type DocumentHistory,type DocumentStatus} from '@/modules/documents/domain';

type OpportunityOption={id:string;title:string;status:string};
type ListResponse={items:OpportunityOption[]};
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const date=(value:string,withTime=false)=>new Intl.DateTimeFormat('pt-BR',withTime?{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}:{timeZone:'UTC'}).format(new Date(withTime?value:value+'T12:00:00Z'));
const size=(bytes:number)=>bytes<1024*1024?`${Math.ceil(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(1).replace('.',',')} MB`;

export function DocumentWorkspace({customerId,opportunityId,opportunityTitle,contractId}:{customerId:string|null;opportunityId?:string;opportunityTitle?:string;contractId?:string}){
 const [revision,setRevision]=useState(0),[modal,setModal]=useState<'upload'|'edit'|'email'|'history'|'signature'|null>(null),[selected,setSelected]=useState<CrmDocument|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const listUrl=customerId?`/api/documents?${contractId?'contract_id='+contractId:opportunityId?'opportunity_id='+opportunityId:'customer_id='+customerId}`:null;
 const documents=useRemote<CrmDocument[]>(listUrl,revision);
 const opportunities=useRemote<ListResponse>(customerId&&!opportunityId?`/api/opportunities?record_id=${customerId}&status=all&demo=all&pageSize=100`:null);
 const detail=useRemote<{document:CrmDocument;history:DocumentHistory[];emails:DocumentEmail[]}>(modal==='history'&&selected?`/api/documents/${selected.id}`:null,revision);
 const options=opportunityId?[{id:opportunityId,title:opportunityTitle??selected?.opportunity_title??'Oportunidade atual',status:'open'}]:(opportunities.data?.items??[]);
 function open(kind:'upload'|'edit'|'email'|'history'|'signature',document:CrmDocument|null=null){setError('');setSelected(document);setModal(kind);}
 async function submitUpload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/documents',{method:'POST',body:new FormData(event.currentTarget)});const result=await response.json();if(!response.ok)throw new Error(result.error??'Não foi possível anexar o PDF.');setModal(null);setRevision(value=>value+1);setNotice('PDF anexado e registrado no histórico.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function submitEdit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);setError('');const form=new FormData(event.currentTarget);try{await api(`/api/documents/${selected.id}`,'PUT',{name:form.get('name'),document_type:form.get('document_type'),budget_value:form.get('budget_value'),valid_until:form.get('valid_until'),notes:form.get('notes'),version:selected.version});setModal(null);setRevision(value=>value+1);setNotice('Dados do documento atualizados.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function submitSignature(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);setError('');const form=new FormData(event.currentTarget),signed=form.get('signature_status')==='signed';try{await api(`/api/documents/${selected.id}/signature`,'POST',{signature_status:signed?'signed':'unsigned',signed_at:signed?new Date(String(form.get('signed_at'))).toISOString():null,signed_by:signed?String(form.get('signed_by')):'',signature_notes:String(form.get('signature_notes')),version:selected.version});setModal(null);setRevision(value=>value+1);setNotice('Situação da assinatura registrada.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function status(document:CrmDocument,next:DocumentStatus){setBusy(true);setError('');try{await api(`/api/documents/${document.id}/status`,'POST',{status:next,version:document.version});setRevision(value=>value+1);setNotice(`Status alterado para ${documentStatuses[next].toLowerCase()}.`);}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function sendEmail(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);setError('');const form=new FormData(event.currentTarget);try{await api(`/api/documents/${selected.id}/email`,'POST',{recipient:form.get('recipient'),subject:form.get('subject'),message:form.get('message')});setModal(null);setRevision(value=>value+1);setNotice('Orçamento enviado por e-mail e registrado no histórico.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 if(!customerId)return <div className="document-empty"><FileClock size={28}/><h2>Vincule um cliente à oportunidade</h2><p>O PDF do orçamento precisa permanecer ligado ao cliente e à oportunidade. Edite esta oportunidade e selecione um cliente antes de anexar.</p></div>;
 return <div className="document-workspace"><div className="card-heading"><div><h2>Documentos comerciais em PDF</h2><p className="muted">Arquivos privados vinculados ao cliente{contractId?', ao contrato': ' e à oportunidade'}.</p></div><button className="button primary" disabled={!contractId&&!opportunityId&&!options.length} onClick={()=>open('upload')}><FilePlus2 size={17}/>Anexar PDF</button></div>
 {!opportunityId&&!opportunities.loading&&!options.length&&<p className="crm-notice">Crie uma oportunidade vinculada a este cliente antes de anexar um orçamento.</p>}{notice&&<p role="status" className="crm-notice">{notice}</p>}{error&&!modal&&<p role="alert" className="error-box">{error}</p>}{documents.loading&&<p role="status" className="crm-loading">Carregando documentos…</p>}{documents.error&&<p role="alert" className="error-box">{documents.error}</p>}
 <div className="document-list">{documents.data?.map(document=><article className="document-card" key={document.id}><div className="document-icon"><FileClock size={22}/></div><div className="document-main"><div className="document-title"><div><span className={`document-status ${document.status}`}>{documentStatuses[document.status]}</span><span className="document-status">{documentTypes[document.document_type]}</span><span className={`document-status ${document.signature_status==='signed'?'accepted':''}`}>{document.signature_status==='signed'?'Assinado':'Sem assinatura'}</span><h3>{document.name}</h3></div><strong>{money(document.budget_value)}</strong></div><p>{document.contract_number??document.opportunity_title??document.customer_name} · validade até {date(document.valid_until)}</p><small>{document.original_filename} · {size(document.file_size)} · criado em {date(document.created_at,true)} por {document.created_by_name}</small>{document.notes&&<p className="document-notes">{document.notes}</p>}<div className="document-actions"><button className="button primary" onClick={()=>open('email',document)}><Mail size={16}/>Enviar por e-mail</button><a className="button secondary" href={`/api/documents/${document.id}/file`} download><Download size={16}/>Baixar PDF</a><button className="button secondary" onClick={()=>open('signature',document)}><PenLine size={16}/>Assinatura</button><button className="button secondary" onClick={()=>open('edit',document)}><PenLine size={16}/>Editar dados</button><button className="button secondary" onClick={()=>open('history',document)}><History size={16}/>Histórico</button><label><span>Status</span><select aria-label={`Status de ${document.name}`} value={document.status} disabled={busy} onChange={event=>status(document,event.target.value as DocumentStatus)}>{Object.entries(documentStatuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div></div></article>)}</div>{documents.data?.length===0&&<div className="document-empty"><FileClock size={28}/><h3>Nenhum PDF anexado</h3><p>O arquivo será armazenado de forma privada e só poderá ser baixado por usuários autorizados.</p></div>}
 {modal==='upload'&&<Modal title="Anexar documento em PDF" onClose={()=>!busy&&setModal(null)}><form className="crm-form" onSubmit={submitUpload}><input type="hidden" name="customer_id" value={customerId}/><input type="hidden" name="contract_id" value={contractId??''}/>{!contractId&&<label className="crm-field"><span>Oportunidade</span><select name="opportunity_id" required defaultValue={opportunityId??''}>{!opportunityId&&<option value="">Selecione</option>}{options.map(option=><option value={option.id} key={option.id}>{option.title}</option>)}</select></label>}<div className="crm-form-grid"><label className="crm-field"><span>Tipo</span><select name="document_type" defaultValue={contractId?'contract':'budget'}>{Object.entries(documentTypes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="crm-field"><span>Nome do documento</span><input name="name" required minLength={2} maxLength={180}/></label><label className="crm-field"><span>Valor (R$)</span><input name="budget_value" type="number" min="0" max="99999999999.99" step="0.01" required/></label><label className="crm-field"><span>Validade</span><input name="valid_until" type="date" required/></label><label className="crm-field"><span>Arquivo PDF</span><input name="file" type="file" accept="application/pdf,.pdf" required/><small>Somente PDF, até 10 MB.</small></label></div><label className="crm-field"><span>Observação</span><textarea name="notes" maxLength={4000} rows={3}/></label>{error&&<p role="alert" className="error-box">{error}</p>}<div className="crm-form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" disabled={busy}>{busy?'Enviando…':'Anexar PDF'}</button></div></form></Modal>}
 {modal==='edit'&&selected&&<Modal title="Editar dados do documento" onClose={()=>!busy&&setModal(null)}><form className="crm-form" onSubmit={submitEdit}><div className="crm-form-grid"><label className="crm-field"><span>Tipo</span><select name="document_type" defaultValue={selected.document_type}>{Object.entries(documentTypes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="crm-field"><span>Nome do documento</span><input name="name" required minLength={2} maxLength={180} defaultValue={selected.name}/></label><label className="crm-field"><span>Valor (R$)</span><input name="budget_value" type="number" min="0" max="99999999999.99" step="0.01" required defaultValue={selected.budget_value}/></label><label className="crm-field"><span>Validade</span><input name="valid_until" type="date" required defaultValue={selected.valid_until}/></label></div><label className="crm-field"><span>Observação</span><textarea name="notes" maxLength={4000} rows={4} defaultValue={selected.notes}/></label><p className="muted">O PDF original será preservado. Para outro arquivo, crie um novo documento.</p>{error&&<p role="alert" className="error-box">{error}</p>}<div className="crm-form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" disabled={busy}>Salvar alterações</button></div></form></Modal>}
 {modal==='signature'&&selected&&<Modal title="Registrar assinatura" onClose={()=>!busy&&setModal(null)}><form className="crm-form" onSubmit={submitSignature}><label className="crm-field"><span>Situação</span><select name="signature_status" defaultValue={selected.signature_status}><option value="unsigned">Sem assinatura</option><option value="signed">Assinado</option></select></label><label className="crm-field"><span>Assinado por</span><input name="signed_by" maxLength={180} defaultValue={selected.signed_by}/></label><label className="crm-field"><span>Data e hora da assinatura</span><input name="signed_at" type="datetime-local" defaultValue={selected.signed_at?new Date(selected.signed_at).toISOString().slice(0,16):new Date().toISOString().slice(0,16)}/></label><label className="crm-field"><span>Observações</span><textarea name="signature_notes" maxLength={2000} defaultValue={selected.signature_notes}/></label><p className="muted">Este registro documenta uma assinatura realizada externamente; não executa assinatura eletrônica.</p>{error&&<p className="error-box">{error}</p>}<div className="crm-form-actions"><button type="button" className="button secondary" onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" disabled={busy}>Salvar registro</button></div></form></Modal>}
 {modal==='email'&&selected&&<Modal title="Enviar orçamento por e-mail" onClose={()=>!busy&&setModal(null)}><form className="crm-form" onSubmit={sendEmail}><div className="email-document-summary"><FileClock size={20}/><div><strong>{selected.name}</strong><small>{selected.original_filename} · {size(selected.file_size)}</small></div></div><label className="crm-field"><span>E-mail do cliente</span><input name="recipient" type="email" required maxLength={254} defaultValue={selected.customer_email}/><small>Confirme ou corrija o destinatário antes do envio.</small></label><label className="crm-field"><span>Assunto</span><input name="subject" required maxLength={180} defaultValue={`Orçamento ${selected.name} · Peclat Solar`}/></label><label className="crm-field"><span>Mensagem</span><textarea name="message" required maxLength={10000} rows={8} defaultValue={`Olá, ${selected.customer_name}.\n\nSegue em anexo o orçamento ${selected.name}, preparado pela Peclat Solar. A proposta é válida até ${date(selected.valid_until)}.\n\nFicamos à disposição para esclarecer qualquer dúvida.\n\nAtenciosamente,\nEquipe Peclat Solar`}/></label><p className="muted">O PDF será enviado como anexo. Revise o destinatário, o assunto e a mensagem.</p>{error&&<p role="alert" className="error-box">{error}</p>}<div className="crm-form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" disabled={busy}><Mail size={16}/>{busy?'Enviando…':'Enviar orçamento'}</button></div></form></Modal>}
 {modal==='history'&&selected&&<Modal title={`Histórico · ${selected.name}`} onClose={()=>setModal(null)}>{detail.loading&&<p role="status">Carregando histórico…</p>}{detail.error&&<p role="alert" className="error-box">{detail.error}</p>}{detail.data?.emails.length?<><h3 className="document-history-heading">Envios por e-mail</h3><div className="document-email-history">{detail.data.emails.map(item=><article key={item.id}><Mail size={17}/><div><strong>{item.document_name}</strong><span>Para: {item.recipient}</span><small>{item.subject} · enviado por {item.actor_name}</small></div><time>{date(item.sent_at,true)}</time></article>)}</div></>:null}<h3 className="document-history-heading">Alterações do documento</h3><div className="document-history">{detail.data?.history.map(item=><article key={item.id}><div><strong>{item.action==='created'?'Documento criado':item.action==='updated'?'Dados atualizados':item.action==='signature_changed'?'Assinatura registrada':'Status alterado'}</strong><small>{item.actor_name}</small></div><div><span>{documentStatuses[item.snapshot.status]}</span><strong>{money(item.snapshot.budget_value)}</strong></div><time>{date(item.created_at,true)}</time></article>)}</div></Modal>}</div>;
}
