import type {PoolClient} from 'pg';
import {database,transaction} from '@/server/db';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {createMetaFlow,deprecateMetaFlow,fetchMetaFlows,metaConfiguration,MetaFlowError,publishMetaFlow,uploadMetaFlowJson,type MetaFetcher} from './meta';
import {flowCategories,flowCreateInput,flowMappingInput,flowMutationInput,flowUpdateInput,flowStatuses} from './flow-domain';
import {SOLAR_FLOW_DISPLAY_NAME,SOLAR_FLOW_JSON_VERSION,SOLAR_FLOW_TECHNICAL_NAME,solarBudgetDefaultMappings,solarBudgetFlowJson} from './solar-budget-flow';

type Db=Pick<PoolClient,'query'>;
type Integration={status:string;api_version:string;phone_number_id:string;business_account_id:string};
type FlowRow={id:string;organization_id:string;meta_flow_id:string|null;technical_name:string;display_name:string;category:string;status:string;json_version:string;data_api_version:string;flow_json:Record<string,unknown>;validation_errors:unknown[];health_status:Record<string,unknown>;preview_url:string;endpoint_uri:string;safe_error:string;outcome_uncertain:boolean;published_at:string|null;synced_at:string|null;version:number;created_at:string;updated_at:string;submissions?:number;leads_created?:number;leads_updated?:number};

function manage(actor:Actor){requirePermission(actor,'whatsapp.flows.manage');if(actor.role!=='admin')throw new AccessError(403,'Somente administradores podem gerenciar WhatsApp Flows.');}
function cleanStatus(value:string){return (flowStatuses as readonly string[]).includes(value)?value:'UNKNOWN';}
function cleanCategory(value:string|undefined){return value&&(flowCategories as readonly string[]).includes(value)?value:'OTHER';}
function safeName(value:string,id:string){const normalized=value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,180);return normalized.length>=3?normalized:`meta_flow_${id.replace(/\D/g,'').slice(-20)||'sincronizado'}`;}
async function integration(actor:Actor,db:Db=database()){const result=await db.query<Integration>('SELECT status,api_version,phone_number_id,business_account_id FROM whatsapp_integrations WHERE organization_id=$1',[actor.organizationId]);if(!result.rowCount||result.rows[0].status!=='connected')throw new AccessError(503,'A integração do WhatsApp não está conectada.');return result.rows[0];}
async function ensureSolarFlow(actor:Actor){return transaction(async db=>{
  await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`${actor.organizationId}:solar-flow-default`]);
  const existing=await db.query<{id:string}>('SELECT id FROM whatsapp_flows WHERE organization_id=$1 AND technical_name=$2',[actor.organizationId,SOLAR_FLOW_TECHNICAL_NAME]);if(existing.rowCount)return existing.rows[0].id;
  const created=await db.query<{id:string}>(`INSERT INTO whatsapp_flows(organization_id,technical_name,display_name,category,json_version,data_api_version,flow_json,created_by,updated_by) VALUES ($1,$2,$3,'LEAD_GENERATION',$4,'3.0',$5,$6,$6) RETURNING id`,[actor.organizationId,SOLAR_FLOW_TECHNICAL_NAME,SOLAR_FLOW_DISPLAY_NAME,SOLAR_FLOW_JSON_VERSION,JSON.stringify(solarBudgetFlowJson()),actor.userId]);
  for(const [flowField,crmField,label] of solarBudgetDefaultMappings)await db.query(`INSERT INTO whatsapp_flow_field_mappings(organization_id,flow_id,flow_field,crm_field,label) VALUES ($1,$2,$3,$4,$5)`,[actor.organizationId,created.rows[0].id,flowField,crmField,label]);
  await db.query(`INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.flow_draft_created',$3)`,[actor.organizationId,actor.userId,`Flow local ${SOLAR_FLOW_TECHNICAL_NAME} preparado.`]);return created.rows[0].id;
 });}
async function row(actor:Actor,id:string,db:Db=database(),lock=false){const result=await db.query<FlowRow>(`SELECT * FROM whatsapp_flows WHERE organization_id=$1 AND id=$2${lock?' FOR UPDATE':''}`,[actor.organizationId,id]);if(!result.rowCount)throw new AccessError(404,'Flow não encontrado.');return result.rows[0];}
export async function flowManagerOverview(actor:Actor){manage(actor);await ensureSolarFlow(actor);const result=await database().query<FlowRow>(`SELECT f.*,(SELECT count(*)::int FROM whatsapp_flow_submissions s WHERE s.organization_id=f.organization_id AND s.flow_id=f.id) submissions,(SELECT count(*)::int FROM whatsapp_flow_submissions s WHERE s.organization_id=f.organization_id AND s.flow_id=f.id AND s.processing_result='lead_created') leads_created,(SELECT count(*)::int FROM whatsapp_flow_submissions s WHERE s.organization_id=f.organization_id AND s.flow_id=f.id AND s.processing_result='lead_updated') leads_updated FROM whatsapp_flows f WHERE f.organization_id=$1 ORDER BY (f.technical_name=$2) DESC,f.updated_at DESC,f.id`,[actor.organizationId,SOLAR_FLOW_TECHNICAL_NAME]);return {items:result.rows.map(item=>({...item,submissions:Number(item.submissions),leads_created:Number(item.leads_created),leads_updated:Number(item.leads_updated)}))};}
export async function createFlowDraft(actor:Actor,input:unknown){manage(actor);const data=flowCreateInput.parse(input),definition=solarBudgetFlowJson();try{await transaction(async db=>{
 const created=await db.query<{id:string}>(`INSERT INTO whatsapp_flows(organization_id,technical_name,display_name,category,json_version,data_api_version,flow_json,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,'3.0',$6,$7,$7) RETURNING id`,[actor.organizationId,data.technical_name,data.display_name,data.category,SOLAR_FLOW_JSON_VERSION,JSON.stringify(definition),actor.userId]);
 for(const [field,target,label] of solarBudgetDefaultMappings)await db.query('INSERT INTO whatsapp_flow_field_mappings(organization_id,flow_id,flow_field,crm_field,label) VALUES ($1,$2,$3,$4,$5)',[actor.organizationId,created.rows[0].id,field,target,label]);
 await db.query("INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.flow_draft_created',$3)",[actor.organizationId,actor.userId,`Flow ${created.rows[0].id} criado localmente.`]);
 });}catch(error){if((error as {code?:string}).code==='23505')throw new AccessError(409,'Já existe um Flow com esse nome técnico.');throw error;}return flowManagerOverview(actor);}
export async function updateFlowDraft(actor:Actor,id:string,input:unknown){manage(actor);const data=flowUpdateInput.parse(input);await transaction(async db=>{const current=await row(actor,id,db,true);if(current.status!=='DRAFT'||current.meta_flow_id)throw new AccessError(409,'Somente rascunhos locais ainda não criados na Meta podem ser editados.');if(current.version!==data.version)throw new AccessError(409,'O Flow foi atualizado. Recarregue a página.');await db.query(`UPDATE whatsapp_flows SET technical_name=$3,display_name=$4,category=$5,updated_by=$6,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,data.technical_name,data.display_name,data.category,actor.userId]);await db.query(`INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.flow_updated',$3)`,[actor.organizationId,actor.userId,`Flow ${id} atualizado localmente.`]);});return flowManagerOverview(actor);}
export async function flowMappings(actor:Actor,id:string){manage(actor);await row(actor,id);const result=await database().query('SELECT flow_field,crm_field,label,enabled FROM whatsapp_flow_field_mappings WHERE organization_id=$1 AND flow_id=$2 ORDER BY id',[actor.organizationId,id]);return {items:result.rows};}
export async function saveFlowMappings(actor:Actor,id:string,input:unknown){manage(actor);const data=flowMappingInput.parse(input);await transaction(async db=>{const current=await row(actor,id,db,true);if(current.version!==data.version)throw new AccessError(409,'O Flow foi atualizado. Recarregue a página.');await db.query('DELETE FROM whatsapp_flow_field_mappings WHERE organization_id=$1 AND flow_id=$2',[actor.organizationId,id]);for(const item of data.mappings)await db.query(`INSERT INTO whatsapp_flow_field_mappings(organization_id,flow_id,flow_field,crm_field,label,enabled) VALUES ($1,$2,$3,$4,$5,$6)`,[actor.organizationId,id,item.flow_field,item.crm_field,item.label,item.enabled]);await db.query('UPDATE whatsapp_flows SET updated_by=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,actor.userId]);await db.query(`INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.flow_mapping_updated',$3)`,[actor.organizationId,actor.userId,`Mapeamento do Flow ${id} atualizado.`]);});return flowManagerOverview(actor);}
export async function synchronizeFlows(actor:Actor,fetcher?:MetaFetcher){manage(actor);const current=await integration(actor),items=await fetchMetaFlows(metaConfiguration(current),fetcher);await transaction(async db=>{await db.query(`UPDATE whatsapp_flows SET status='UNKNOWN',synced_at=now(),updated_at=now() WHERE organization_id=$1 AND meta_flow_id IS NOT NULL`,[actor.organizationId]);for(const item of items){const category=cleanCategory(item.categories[0]),existing=await db.query<{id:string}>('SELECT id FROM whatsapp_flows WHERE organization_id=$1 AND (meta_flow_id=$2 OR technical_name=$3) ORDER BY meta_flow_id=$2 DESC LIMIT 1',[actor.organizationId,item.id,safeName(item.name,item.id)]);if(existing.rowCount)await db.query(`UPDATE whatsapp_flows SET meta_flow_id=$3,display_name=CASE WHEN display_name='' THEN $4 ELSE display_name END,status=$5,category=$6,json_version=COALESCE(NULLIF($7,''),json_version),data_api_version=COALESCE(NULLIF($8,''),data_api_version),validation_errors=$9,preview_url=$10,health_status=$11,safe_error='',outcome_uncertain=false,synced_at=now(),published_at=CASE WHEN $5='PUBLISHED' THEN COALESCE(published_at,now()) ELSE published_at END,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,existing.rows[0].id,item.id,item.name,cleanStatus(item.status),category,item.jsonVersion,item.dataApiVersion,JSON.stringify(item.validationErrors),item.previewUrl,JSON.stringify(item.healthStatus)]);else await db.query(`INSERT INTO whatsapp_flows(organization_id,meta_flow_id,technical_name,display_name,category,status,json_version,data_api_version,validation_errors,preview_url,health_status,created_by,updated_by,synced_at,published_at) VALUES ($1,$2,$3,$4,$5,$6,COALESCE(NULLIF($7,''),'7.3'),COALESCE(NULLIF($8,''),'3.0'),$9,$10,$11,$12,$12,now(),CASE WHEN $6='PUBLISHED' THEN now() END)`,[actor.organizationId,item.id,safeName(item.name,item.id),item.name,category,cleanStatus(item.status),item.jsonVersion,item.dataApiVersion,JSON.stringify(item.validationErrors),item.previewUrl,JSON.stringify(item.healthStatus),actor.userId]);}await db.query(`INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.flows_synced',$3)`,[actor.organizationId,actor.userId,`${items.length} Flows consultados na Meta.`]);});return flowManagerOverview(actor);}
export async function createFlowOnMeta(actor:Actor,id:string,input:unknown,fetcher?:MetaFetcher){manage(actor);const data=flowMutationInput.parse(input),current=await transaction(async db=>{const found=await row(actor,id,db,true);if(found.version!==data.version)throw new AccessError(409,'O Flow foi atualizado. Recarregue a página.');if(found.meta_flow_id)return found;if(found.outcome_uncertain)throw new AccessError(409,'Há uma criação pendente de confirmação. Sincronize com a Meta antes de continuar.');await db.query("UPDATE whatsapp_flows SET outcome_uncertain=true,safe_error='Criação em andamento',updated_by=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[actor.organizationId,id,actor.userId]);return found;});if(current.meta_flow_id)return flowManagerOverview(actor);try{const config=metaConfiguration(await integration(actor)),created=await createMetaFlow(config,{name:current.technical_name,category:current.category,endpointUri:current.endpoint_uri||undefined},fetcher);await database().query("UPDATE whatsapp_flows SET meta_flow_id=$3,outcome_uncertain=false,safe_error='',synced_at=now(),version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[actor.organizationId,id,created.id]);}catch(error){if(error instanceof MetaFlowError)await database().query('UPDATE whatsapp_flows SET safe_error=$3,outcome_uncertain=$4,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,error.safeDetail,error.kind==='uncertain']);throw new AccessError(502,error instanceof MetaFlowError?error.safeDetail:'Não foi possível criar o Flow na Meta.');}return flowManagerOverview(actor);}
export async function validateFlowOnMeta(actor:Actor,id:string,input:unknown,fetcher?:MetaFetcher){manage(actor);const data=flowMutationInput.parse(input),current=await row(actor,id);if(current.version!==data.version)throw new AccessError(409,'O Flow foi atualizado. Recarregue a página.');if(!current.meta_flow_id)throw new AccessError(409,'Crie o Flow na Meta antes de validar.');if(current.status!=='DRAFT')throw new AccessError(409,'Somente Flows em rascunho podem receber uma nova definição.');try{const result=await uploadMetaFlowJson(metaConfiguration(await integration(actor)),current.meta_flow_id,current.flow_json,fetcher);await database().query(`UPDATE whatsapp_flows SET validation_errors=$3,safe_error=$4,outcome_uncertain=false,synced_at=now(),updated_by=$5,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,JSON.stringify(result.validationErrors),result.validationErrors.length?'A Meta encontrou erros de validação.':'',actor.userId]);}catch(error){if(error instanceof MetaFlowError)await database().query('UPDATE whatsapp_flows SET validation_errors=$3,safe_error=$4,outcome_uncertain=$5,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,JSON.stringify(error.validationErrors),error.safeDetail,error.kind==='uncertain']);throw new AccessError(502,error instanceof MetaFlowError?error.safeDetail:'Não foi possível validar o Flow na Meta.');}return flowManagerOverview(actor);}
export async function publishFlow(actor:Actor,id:string,input:unknown,fetcher?:MetaFetcher){manage(actor);const data=flowMutationInput.parse(input),current=await row(actor,id);if(current.version!==data.version)throw new AccessError(409,'O Flow foi atualizado. Recarregue a página.');if(!current.meta_flow_id||current.status!=='DRAFT'||current.validation_errors.length)throw new AccessError(409,'O Flow precisa estar criado e validado sem erros antes da publicação.');try{await publishMetaFlow(metaConfiguration(await integration(actor)),current.meta_flow_id,fetcher);await database().query(`UPDATE whatsapp_flows SET status='PUBLISHED',published_at=now(),synced_at=now(),safe_error='',outcome_uncertain=false,updated_by=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,actor.userId]);await database().query(`INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.flow_published',$3)`,[actor.organizationId,actor.userId,`Flow ${id} publicado.`]);}catch(error){if(error instanceof MetaFlowError)await database().query('UPDATE whatsapp_flows SET safe_error=$3,outcome_uncertain=$4,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,error.safeDetail,error.kind==='uncertain']);throw new AccessError(502,error instanceof MetaFlowError?error.safeDetail:'Não foi possível publicar o Flow.');}return flowManagerOverview(actor);}
export async function deprecateFlow(actor:Actor,id:string,input:unknown,fetcher?:MetaFetcher){manage(actor);const data=flowMutationInput.parse(input),current=await row(actor,id);if(current.version!==data.version)throw new AccessError(409,'O Flow foi atualizado. Recarregue a página.');if(!current.meta_flow_id||current.status!=='PUBLISHED')throw new AccessError(409,'Somente um Flow publicado pode ser desativado.');try{await deprecateMetaFlow(metaConfiguration(await integration(actor)),current.meta_flow_id,fetcher);await database().query(`UPDATE whatsapp_flows SET status='DEPRECATED',safe_error='',outcome_uncertain=false,updated_by=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,actor.userId]);await database().query(`INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.flow_deprecated',$3)`,[actor.organizationId,actor.userId,`Flow ${id} desativado.`]);}catch(error){if(error instanceof MetaFlowError)await database().query('UPDATE whatsapp_flows SET safe_error=$3,outcome_uncertain=$4,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id,error.safeDetail,error.kind==='uncertain']);throw new AccessError(502,error instanceof MetaFlowError?error.safeDetail:'Não foi possível desativar o Flow.');}return flowManagerOverview(actor);}
