import type {PoolClient} from 'pg';
import {database,transaction} from '@/server/db';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {commercialScope,commercialScopeParams} from '@/modules/commercial/scope';
import {crmAccess,getRecord,listRecords,saveRecordInTransaction} from '@/modules/crm/repository';
import {uuid} from '@/modules/crm/domain';
import {normalizeWhatsAppNumber,serviceWindow,whatsappConversationFilters,whatsappLeadInput,whatsappLinkInput,whatsappReadInput} from './domain';
import {emitAutomationEvent} from '@/modules/automations/events';
type Db=Pick<PoolClient,'query'>;
type Match={id:string;kind:'lead'|'customer'|'company';name:string};
export class WhatsAppLeadDuplicateError extends AccessError{constructor(public matches:Match[],public multiple:boolean){super(409,multiple?'Encontramos mais de um cadastro com este telefone. Selecione qual deseja vincular.':'Este telefone já pertence a um cadastro existente.');}}
function access(actor:Actor){requirePermission(actor,'whatsapp.use');}
function visibility(actor:Actor){return `(c.record_id IS NULL OR EXISTS(SELECT 1 FROM crm_records scoped_record WHERE scoped_record.id=c.record_id AND scoped_record.organization_id=c.organization_id AND ${commercialScope(actor,'scoped_record')}))`;}
const select=`c.id,c.external_wa_id,c.phone_e164,c.profile_name,c.last_message_preview,c.last_message_type,c.last_message_at,c.unread_count,c.status,c.record_id,c.link_status,c.link_source,c.automation_owner_id,c.automations_paused,c.automation_blocked,(SELECT u.name FROM users u WHERE u.id=c.automation_owner_id) automation_owner_name,c.version,c.created_at,c.updated_at,r.name record_name,r.kind record_kind`;
export async function listWhatsAppConversations(actor:Actor,input:unknown){access(actor);const filters=whatsappConversationFilters.parse(input),params=commercialScopeParams(actor),conditions=[visibility(actor),`c.organization_id=$1`];const add=(sql:string,value:unknown)=>{params.push(value);conditions.push(sql.replace('?',`$${params.length}`));};if(filters.unread==='unread')conditions.push('c.unread_count>0');if(filters.link==='linked')conditions.push('c.record_id IS NOT NULL');if(filters.link==='unlinked')conditions.push('c.record_id IS NULL');if(filters.q){const q=filters.q.replace(/[\\%_]/g,'\\$&');add(`lower(concat_ws(' ',c.profile_name,c.phone_e164,c.external_wa_id,r.name,c.last_message_preview)) LIKE lower(?) ESCAPE '\\'`,`%${q}%`);}const where=conditions.join(' AND '),offset=(filters.page-1)*filters.pageSize;params.push(filters.pageSize,offset);const [items,total]=await Promise.all([database().query(`SELECT ${select} FROM whatsapp_conversations c LEFT JOIN crm_records r ON r.organization_id=c.organization_id AND r.id=c.record_id WHERE ${where} ORDER BY c.last_message_at DESC NULLS LAST,c.id LIMIT $${params.length-1} OFFSET $${params.length}`,params),database().query(`SELECT count(*)::int total FROM whatsapp_conversations c LEFT JOIN crm_records r ON r.organization_id=c.organization_id AND r.id=c.record_id WHERE ${where}`,params.slice(0,-2))]);return {items:items.rows,total:Number(total.rows[0].total),page:filters.page,pageSize:filters.pageSize,canCreateLead:actor.permissions.includes('crm.all')||actor.permissions.includes('crm.own')};}
export async function assertWhatsAppConversation(actor:Actor,id:string,db:Db=database(),lock=false){access(actor);uuid.parse(id);const params=commercialScopeParams(actor);params.push(id);const result=await db.query(`SELECT ${select},c.last_inbound_at FROM whatsapp_conversations c LEFT JOIN crm_records r ON r.organization_id=c.organization_id AND r.id=c.record_id WHERE ${visibility(actor)} AND c.organization_id=$1 AND c.id=$${params.length}${lock?' FOR UPDATE OF c':''}`,params);if(!result.rowCount)throw new AccessError(404,'Conversa não encontrada.');return result.rows[0];}
type MessageCursor={before_timestamp:string;before_id:string};
export async function getWhatsAppConversation(actor:Actor,id:string,cursor?:MessageCursor){const current=await assertWhatsAppConversation(actor,id),limit=100,params:unknown[]=[actor.organizationId,id],before=cursor?`AND (m.meta_timestamp,m.id)<($3::timestamptz,$4::uuid)`:'';if(cursor)params.push(cursor.before_timestamp,cursor.before_id);params.push(limit+1);const messages=await database().query(`SELECT recent.id,recent.meta_message_id,recent.direction,recent.message_type,recent.text_body,recent.context_message_id,recent.media_id,recent.mime_type,recent.filename,recent.caption,recent.safe_metadata,recent.meta_timestamp,recent.received_at,recent.processing_status,recent.template_name,recent.template_language,recent.delivery_status,recent.sent_at,recent.delivered_at,recent.read_at,recent.failed_at,recent.outcome_uncertain,recent.failure_title,recent.failure_detail,u.name sender_name FROM (SELECT m.id,m.meta_message_id,m.direction,m.message_type,m.text_body,m.context_message_id,m.media_id,m.mime_type,m.filename,m.caption,m.safe_metadata,m.meta_timestamp,m.received_at,m.processing_status,m.template_name,m.template_language,m.delivery_status,m.sent_at,m.delivered_at,m.read_at,m.failed_at,m.outcome_uncertain,m.failure_title,m.failure_detail,m.sent_by FROM whatsapp_messages m WHERE m.organization_id=$1 AND m.conversation_id=$2 ${before} ORDER BY m.meta_timestamp DESC,m.id DESC LIMIT $${params.length}) recent LEFT JOIN users u ON u.id=recent.sent_by ORDER BY recent.meta_timestamp ASC,recent.id ASC`,params);const hasOlder=messages.rows.length>limit,items=hasOlder?messages.rows.slice(-limit):messages.rows,total=await database().query('SELECT count(*)::int total FROM whatsapp_messages WHERE organization_id=$1 AND conversation_id=$2',[actor.organizationId,id]),oldest=items[0];return {conversation:current,messages:items,window:serviceWindow(current.last_inbound_at?new Date(current.last_inbound_at):null),total:Number(total.rows[0].total),pageSize:limit,hasOlder,nextCursor:hasOlder&&oldest?{before_timestamp:new Date(oldest.meta_timestamp).toISOString(),before_id:oldest.id}:null};}
export async function markWhatsAppConversationRead(actor:Actor,id:string,input:unknown){const data=whatsappReadInput.parse(input);return transaction(async db=>{const current=await assertWhatsAppConversation(actor,id,db,true);if(Number(current.version)!==data.version)throw new AccessError(409,'Conversa atualizada. Recarregue a página.');await db.query('UPDATE whatsapp_conversations SET unread_count=0,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id]);if(Number(current.unread_count)>0)await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,'whatsapp.conversation_read',`Conversa ${id} marcada como lida.`]);return {ok:true};});}
export async function linkWhatsAppConversation(actor:Actor,id:string,input:unknown){const data=whatsappLinkInput.parse(input);return transaction(async db=>{const current=await assertWhatsAppConversation(actor,id,db,true);if(Number(current.version)!==data.version)throw new AccessError(409,'Conversa atualizada. Recarregue a página.');if(data.record_id)await getRecord(actor,data.record_id,db);const before=current.record_id as string|null;if(before===data.record_id)return {ok:true};await db.query(`UPDATE whatsapp_conversations SET record_id=$3,link_status=$4,link_source='manual',version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,data.record_id,data.record_id?'identified':'unidentified']);const action=data.record_id?(before?'whatsapp.conversation_relinked':'whatsapp.conversation_linked'):'whatsapp.conversation_unlinked';await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,action,`Conversa ${id}; vínculo anterior ${before??'nenhum'}; vínculo atual ${data.record_id??'nenhum'}.`]);return {ok:true};});}
async function matchingRecords(db:Db,actor:Actor,phone:string){
 const all=await db.query<Match>(`SELECT DISTINCT r.id,r.kind,r.name FROM crm_records r WHERE r.organization_id=$1 AND r.deleted_at IS NULL AND (r.phone=$2 OR r.whatsapp=$2 OR EXISTS(SELECT 1 FROM crm_record_contacts rc JOIN crm_contacts c ON c.organization_id=rc.organization_id AND c.id=rc.contact_id WHERE rc.organization_id=r.organization_id AND rc.record_id=r.id AND (c.phone=$2 OR c.whatsapp=$2))) ORDER BY r.id LIMIT 20`,[actor.organizationId,phone]);
 if(!all.rowCount)return {all:[],visible:[]};
 const params=commercialScopeParams(actor);params.push(phone);
 const visible=await db.query<Match>(`SELECT DISTINCT r.id,r.kind,r.name FROM crm_records r WHERE ${commercialScope(actor,'r',true)} AND r.deleted_at IS NULL AND (r.phone=$${params.length} OR r.whatsapp=$${params.length} OR EXISTS(SELECT 1 FROM crm_record_contacts rc JOIN crm_contacts c ON c.organization_id=rc.organization_id AND c.id=rc.contact_id WHERE rc.organization_id=r.organization_id AND rc.record_id=r.id AND (c.phone=$${params.length} OR c.whatsapp=$${params.length}))) ORDER BY r.id LIMIT 20`,params);
 return {all:all.rows,visible:visible.rows};
}
async function ensureWhatsAppTag(db:Db,actor:Actor){
 const existing=await db.query<{id:string}>("SELECT id FROM crm_tags WHERE organization_id=$1 AND lower(name)='whatsapp' LIMIT 1",[actor.organizationId]);
 if(existing.rowCount)return existing.rows[0].id;
 const count=await db.query<{total:number}>('SELECT count(*)::int total FROM crm_tags WHERE organization_id=$1',[actor.organizationId]);
 if(Number(count.rows[0].total)>=500)throw new AccessError(422,'O limite de Tags foi atingido. Remova uma Tag antes de criar o Lead.');
 const created=await db.query<{id:string}>("INSERT INTO crm_tags(organization_id,name,color) VALUES ($1,'WhatsApp','#219878') RETURNING id",[actor.organizationId]);
 return created.rows[0].id;
}
export async function createLeadFromWhatsApp(actor:Actor,id:string,input:unknown){
 access(actor);crmAccess(actor);const data=whatsappLeadInput.parse(input);
 return transaction(async db=>{
  await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[actor.organizationId]);
  const conversation=await assertWhatsAppConversation(actor,id,db,true);
  if(conversation.record_id){const record=await getRecord(actor,conversation.record_id,db);throw new WhatsAppLeadDuplicateError([{id:record.id,kind:record.kind,name:record.name}],false);}
  const normalized=normalizeWhatsAppNumber(conversation.phone_e164);if(!normalized.valid)throw new AccessError(422,'O telefone da conversa não é válido para criar um Lead.');
  const matches=await matchingRecords(db,actor,normalized.digits);if(matches.all.length)throw new WhatsAppLeadDuplicateError(matches.visible,matches.all.length>1);
  const whatsappTag=await ensureWhatsAppTag(db,actor),tagIds=[...new Set([...data.tag_ids,whatsappTag])];
  const lead=await saveRecordInTransaction(actor,'lead',{name:data.name,phone:normalized.digits,whatsapp:normalized.digits,email:data.email,observations:data.notes,source:'WhatsApp',tag_ids:tagIds},db);
  await db.query("UPDATE whatsapp_conversations SET record_id=$3,link_status='identified',link_source='manual',version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2",[actor.organizationId,id,lead.id]);
  await db.query('INSERT INTO crm_activities(organization_id,record_id,actor_id,action,detail) VALUES ($1,$2,$3,$4,$5)',[actor.organizationId,lead.id,actor.userId,'whatsapp.lead.created',`Lead criado a partir da conversa ${id}.`]);
  await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,'whatsapp.lead.created',`Lead ${lead.id}; conversa ${id}; tags ${tagIds.join(',')}.`]);
  await emitAutomationEvent(db,{organizationId:actor.organizationId,type:'whatsapp.lead_created',eventId:`whatsapp-lead:${id}:${lead.id}`,entityType:'record',entityId:lead.id,conversationId:id,recordId:lead.id,payload:{owner_id:lead.owner_id,source:'WhatsApp'}});
  return {lead};
 });
}
export async function searchWhatsAppLinkOptions(actor:Actor,q:string){access(actor);const query=q.trim();if(query.length<2)return [];const groups=await Promise.all((['lead','customer','company'] as const).map(kind=>listRecords(actor,kind,{q:query,pageSize:8,status:'all'})));return groups.flatMap(group=>group.records.map(record=>({id:record.id,name:record.name,kind:record.kind,phone:record.whatsapp||record.phone}))).slice(0,20);}
export async function whatsappConversationsForRecord(actor:Actor,recordId:string){access(actor);await getRecord(actor,recordId);const result=await database().query(`SELECT id,profile_name,phone_e164,last_message_preview,last_message_at,unread_count FROM whatsapp_conversations WHERE organization_id=$1 AND record_id=$2 ORDER BY last_message_at DESC NULLS LAST LIMIT 10`,[actor.organizationId,recordId]);return result.rows;}
