import type {PoolClient} from 'pg';
import {database,transaction} from '@/server/db';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {commercialScope,commercialScopeParams} from '@/modules/commercial/scope';
import {getRecord,listRecords} from '@/modules/crm/repository';
import {uuid} from '@/modules/crm/domain';
import {serviceWindow,whatsappConversationFilters,whatsappLinkInput,whatsappReadInput} from './domain';
type Db=Pick<PoolClient,'query'>;
function access(actor:Actor){requirePermission(actor,'whatsapp.use');}
function visibility(actor:Actor){return `(c.record_id IS NULL OR EXISTS(SELECT 1 FROM crm_records scoped_record WHERE scoped_record.id=c.record_id AND scoped_record.organization_id=c.organization_id AND ${commercialScope(actor,'scoped_record')}))`;}
const select=`c.id,c.external_wa_id,c.phone_e164,c.profile_name,c.last_message_preview,c.last_message_type,c.last_message_at,c.unread_count,c.status,c.record_id,c.link_status,c.link_source,c.version,c.created_at,c.updated_at,r.name record_name,r.kind record_kind`;
export async function listWhatsAppConversations(actor:Actor,input:unknown){access(actor);const filters=whatsappConversationFilters.parse(input),params=commercialScopeParams(actor),conditions=[visibility(actor),`c.organization_id=$1`];const add=(sql:string,value:unknown)=>{params.push(value);conditions.push(sql.replace('?',`$${params.length}`));};if(filters.unread==='unread')conditions.push('c.unread_count>0');if(filters.link==='linked')conditions.push('c.record_id IS NOT NULL');if(filters.link==='unlinked')conditions.push('c.record_id IS NULL');if(filters.q){const q=filters.q.replace(/[\\%_]/g,'\\$&');add(`lower(concat_ws(' ',c.profile_name,c.phone_e164,c.external_wa_id,r.name,c.last_message_preview)) LIKE lower(?) ESCAPE '\\'`,`%${q}%`);}const where=conditions.join(' AND '),offset=(filters.page-1)*filters.pageSize;params.push(filters.pageSize,offset);const [items,total]=await Promise.all([database().query(`SELECT ${select} FROM whatsapp_conversations c LEFT JOIN crm_records r ON r.organization_id=c.organization_id AND r.id=c.record_id WHERE ${where} ORDER BY c.last_message_at DESC NULLS LAST,c.id LIMIT $${params.length-1} OFFSET $${params.length}`,params),database().query(`SELECT count(*)::int total FROM whatsapp_conversations c LEFT JOIN crm_records r ON r.organization_id=c.organization_id AND r.id=c.record_id WHERE ${where}`,params.slice(0,-2))]);return {items:items.rows,total:Number(total.rows[0].total),page:filters.page,pageSize:filters.pageSize};}
export async function assertWhatsAppConversation(actor:Actor,id:string,db:Db=database(),lock=false){access(actor);uuid.parse(id);const params=commercialScopeParams(actor);params.push(id);const result=await db.query(`SELECT ${select},c.last_inbound_at FROM whatsapp_conversations c LEFT JOIN crm_records r ON r.organization_id=c.organization_id AND r.id=c.record_id WHERE ${visibility(actor)} AND c.organization_id=$1 AND c.id=$${params.length}${lock?' FOR UPDATE OF c':''}`,params);if(!result.rowCount)throw new AccessError(404,'Conversa não encontrada.');return result.rows[0];}
export async function getWhatsAppConversation(actor:Actor,id:string,page=1){const current=await assertWhatsAppConversation(actor,id),limit=100,offset=(page-1)*limit;const messages=await database().query(`SELECT m.id,m.meta_message_id,m.direction,m.message_type,m.text_body,m.context_message_id,m.media_id,m.mime_type,m.filename,m.caption,m.safe_metadata,m.meta_timestamp,m.received_at,m.processing_status,m.template_name,m.template_language,m.delivery_status,m.sent_at,m.delivered_at,m.read_at,m.failed_at,m.outcome_uncertain,m.failure_title,m.failure_detail,u.name sender_name FROM whatsapp_messages m LEFT JOIN users u ON u.id=m.sent_by WHERE m.organization_id=$1 AND m.conversation_id=$2 ORDER BY m.meta_timestamp ASC,m.id ASC LIMIT $3 OFFSET $4`,[actor.organizationId,id,limit,offset]);const total=await database().query('SELECT count(*)::int total FROM whatsapp_messages WHERE organization_id=$1 AND conversation_id=$2',[actor.organizationId,id]);return {conversation:current,messages:messages.rows,window:serviceWindow(current.last_inbound_at?new Date(current.last_inbound_at):null),total:Number(total.rows[0].total),page,pageSize:limit};}
export async function markWhatsAppConversationRead(actor:Actor,id:string,input:unknown){const data=whatsappReadInput.parse(input);return transaction(async db=>{const current=await assertWhatsAppConversation(actor,id,db,true);if(Number(current.version)!==data.version)throw new AccessError(409,'Conversa atualizada. Recarregue a página.');await db.query('UPDATE whatsapp_conversations SET unread_count=0,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2',[actor.organizationId,id]);if(Number(current.unread_count)>0)await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,'whatsapp.conversation_read',`Conversa ${id} marcada como lida.`]);return {ok:true};});}
export async function linkWhatsAppConversation(actor:Actor,id:string,input:unknown){const data=whatsappLinkInput.parse(input);return transaction(async db=>{const current=await assertWhatsAppConversation(actor,id,db,true);if(Number(current.version)!==data.version)throw new AccessError(409,'Conversa atualizada. Recarregue a página.');if(data.record_id)await getRecord(actor,data.record_id,db);const before=current.record_id as string|null;if(before===data.record_id)return {ok:true};await db.query(`UPDATE whatsapp_conversations SET record_id=$3,link_status=$4,link_source='manual',version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,data.record_id,data.record_id?'identified':'unidentified']);const action=data.record_id?(before?'whatsapp.conversation_relinked':'whatsapp.conversation_linked'):'whatsapp.conversation_unlinked';await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,action,`Conversa ${id}; vínculo anterior ${before??'nenhum'}; vínculo atual ${data.record_id??'nenhum'}.`]);return {ok:true};});}
export async function searchWhatsAppLinkOptions(actor:Actor,q:string){access(actor);const query=q.trim();if(query.length<2)return [];const groups=await Promise.all((['lead','customer','company'] as const).map(kind=>listRecords(actor,kind,{q:query,pageSize:8,status:'all'})));return groups.flatMap(group=>group.records.map(record=>({id:record.id,name:record.name,kind:record.kind,phone:record.whatsapp||record.phone}))).slice(0,20);}
export async function whatsappConversationsForRecord(actor:Actor,recordId:string){access(actor);await getRecord(actor,recordId);const result=await database().query(`SELECT id,profile_name,phone_e164,last_message_preview,last_message_at,unread_count FROM whatsapp_conversations WHERE organization_id=$1 AND record_id=$2 ORDER BY last_message_at DESC NULLS LAST LIMIT 10`,[actor.organizationId,recordId]);return result.rows;}
