import {database,transaction} from '@/server/db';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {normalizeWhatsAppNumber,whatsappConfigurationInput,type WhatsAppStatus} from './domain';

type Row={organization_id:string;status:WhatsAppStatus;account_name:string;phone_number_id:string;business_account_id:string;display_phone_number:string;api_version:string;version:number;created_at:string;updated_at:string};
const secretReadiness=()=>({access_token_configured:Boolean(process.env.WHATSAPP_ACCESS_TOKEN),verify_token_configured:Boolean(process.env.WHATSAPP_VERIFY_TOKEN),app_secret_configured:Boolean(process.env.WHATSAPP_APP_SECRET)});
function admin(actor:Actor){requirePermission(actor,'settings.read');if(actor.role!=='admin')throw new AccessError(403,'Somente administradores podem configurar o WhatsApp Business.');}
function complete(row:Pick<Row,'account_name'|'phone_number_id'|'business_account_id'|'display_phone_number'|'api_version'>){return Boolean(row.account_name&&row.phone_number_id&&row.business_account_id&&row.display_phone_number&&row.api_version);}
function publicStatus(row:Row|null){const secrets=secretReadiness();if(!row)return {status:'not_configured' as WhatsAppStatus,...secrets};let status=row.status;if(status==='connected'&&(!complete(row)||!secrets.access_token_configured||!secrets.verify_token_configured||!secrets.app_secret_configured))status='incomplete';return {status,...secrets};}
export async function whatsappAdminConfiguration(actor:Actor){admin(actor);const result=await database().query<Row>('SELECT organization_id,status,account_name,phone_number_id,business_account_id,display_phone_number,api_version,version,created_at,updated_at FROM whatsapp_integrations WHERE organization_id=$1',[actor.organizationId]);const row=result.rows[0]??null,status=publicStatus(row);return {configuration:row?{status:status.status,account_name:row.account_name,phone_number_id:row.phone_number_id,business_account_id:row.business_account_id,display_phone_number:row.display_phone_number,api_version:row.api_version,version:Number(row.version),created_at:row.created_at,updated_at:row.updated_at}:null,...status};}
export async function saveWhatsAppConfiguration(actor:Actor,input:unknown){admin(actor);const data=whatsappConfigurationInput.parse(input);await transaction(async db=>{const current=await db.query<Row>('SELECT * FROM whatsapp_integrations WHERE organization_id=$1 FOR UPDATE',[actor.organizationId]);const row=current.rows[0];if(row&&data.version!==Number(row.version))throw new AccessError(409,'A configuração foi atualizada. Recarregue a página.');if(!row&&data.version!==null)throw new AccessError(409,'A configuração foi atualizada. Recarregue a página.');const configured=Boolean(data.account_name||data.phone_number_id||data.business_account_id||data.display_phone_number||data.api_version),status:WhatsAppStatus=configured?'incomplete':'not_configured';if(row){await db.query(`UPDATE whatsapp_integrations SET status=$2,account_name=$3,phone_number_id=$4,business_account_id=$5,display_phone_number=$6,api_version=$7,updated_by=$8,version=version+1,updated_at=now() WHERE organization_id=$1`,[actor.organizationId,status,data.account_name,data.phone_number_id,data.business_account_id,data.display_phone_number,data.api_version,actor.userId]);}else{await db.query(`INSERT INTO whatsapp_integrations(organization_id,status,account_name,phone_number_id,business_account_id,display_phone_number,api_version,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8)`,[actor.organizationId,status,data.account_name,data.phone_number_id,data.business_account_id,data.display_phone_number,data.api_version,actor.userId]);}await db.query('INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,$3,$4)',[actor.organizationId,actor.userId,row?'whatsapp.configuration_updated':'whatsapp.configuration_created',`Status: ${status}; metadados seguros atualizados.`]);});return whatsappAdminConfiguration(actor);}
export async function whatsappActionAvailability(actor:Actor,number:string){if(!actor.permissions.includes('whatsapp.use'))return {available:false,number:null};const normalized=normalizeWhatsAppNumber(number);if(!normalized.valid)return {available:false,number:null};const result=await database().query<Row>('SELECT * FROM whatsapp_integrations WHERE organization_id=$1',[actor.organizationId]);const row=result.rows[0]??null,status=publicStatus(row).status;return {available:status==='connected',number:normalized.e164};}
