import type {PoolClient} from 'pg';
import {database,transaction} from '@/server/db';
import {AccessError,requirePermission,type Actor} from '@/modules/auth/policy';
import {createMetaTemplate,fetchMetaTemplates,metaConfiguration,MetaTemplateError,type MetaFetcher} from './meta';
import {syncWhatsAppTemplates,templateSupport} from './outbound';
import {templateBodyComponents,templateDraftCreateInput,templateDraftSubmitInput,templateDraftUpdateInput} from './template-manager-domain';

type Db=Pick<PoolClient,'query'>;
type DraftRow={id:string;organization_id:string;name:string;category:'MARKETING'|'UTILITY';language:string;body_text:string;example_values:string[];components:unknown[];submission_status:string;meta_template_id:string|null;rejection_reason:string;safe_error:string;outcome_uncertain:boolean;submitted_at:string|null;synced_at:string|null;version:number;created_by:string;updated_by:string;created_at:string;updated_at:string;created_by_name:string;updated_by_name:string;official_status?:string|null};
const officialStatuses=['APPROVED','PENDING','REJECTED','PAUSED','DISABLED','IN_APPEAL','PENDING_DELETION','DELETED','LIMIT_EXCEEDED'] as const;

function manage(actor:Actor){requirePermission(actor,'whatsapp.templates.manage');if(actor.role!=='admin')throw new AccessError(403,'Somente administradores podem gerenciar modelos oficiais.');}
function normalizeStatus(value:string){return (officialStatuses as readonly string[]).includes(value)?value:'UNKNOWN';}
async function integration(actor:Actor,db:Db=database()){const result=await db.query<{status:string;api_version:string;phone_number_id:string;business_account_id:string}>('SELECT status,api_version,phone_number_id,business_account_id FROM whatsapp_integrations WHERE organization_id=$1',[actor.organizationId]);if(!result.rowCount||result.rows[0].status!=='connected')throw new AccessError(503,'A integração do WhatsApp não está conectada.');return result.rows[0];}
async function scopedDraft(actor:Actor,id:string,db:Db=database(),lock=false){const result=await db.query<DraftRow>(`SELECT * FROM whatsapp_template_drafts WHERE organization_id=$1 AND id=$2${lock?' FOR UPDATE':''}`,[actor.organizationId,id]);if(!result.rowCount)throw new AccessError(404,'Rascunho não encontrado.');return result.rows[0];}
async function assertAvailableName(actor:Actor,name:string,language:string,excludeId:string|null,db:Db){const result=await db.query(`SELECT 1 FROM whatsapp_template_drafts WHERE organization_id=$1 AND name=$2 AND language=$3 AND ($4::uuid IS NULL OR id<>$4) UNION ALL SELECT 1 FROM whatsapp_templates WHERE organization_id=$1 AND name=$2 AND language=$3 LIMIT 1`,[actor.organizationId,name,language,excludeId]);if(result.rowCount)throw new AccessError(409,'Já existe um modelo com este nome e idioma na organização.');}

export async function templateManagerOverview(actor:Actor){manage(actor);await integration(actor);const result=await database().query<DraftRow>(`SELECT d.*,creator.name created_by_name,updater.name updated_by_name,t.status official_status FROM whatsapp_template_drafts d JOIN users creator ON creator.id=d.created_by JOIN users updater ON updater.id=d.updated_by LEFT JOIN whatsapp_templates t ON t.organization_id=d.organization_id AND t.meta_template_id=d.meta_template_id WHERE d.organization_id=$1 ORDER BY d.updated_at DESC,d.name`,[actor.organizationId]);return {items:result.rows.map(row=>({...row,version:Number(row.version)})),supported:{categories:['MARKETING','UTILITY'],languages:[{code:'pt_BR',label:'Português (Brasil)'}],components:['BODY_TEXT']}};}

export async function createTemplateDraft(actor:Actor,input:unknown){manage(actor);const data=templateDraftCreateInput.parse(input),components=templateBodyComponents(data.body_text,data.example_values);return transaction(async db=>{await assertAvailableName(actor,data.name,data.language,null,db);const result=await db.query<DraftRow>(`INSERT INTO whatsapp_template_drafts(organization_id,name,category,language,body_text,example_values,components,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING *`,[actor.organizationId,data.name,data.category,data.language,data.body_text,JSON.stringify(data.example_values),JSON.stringify(components),actor.userId]);await db.query("INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.template_draft_created',$3)",[actor.organizationId,actor.userId,`Modelo ${data.name}/${data.language}; rascunho local.`]);return result.rows[0];});}

export async function updateTemplateDraft(actor:Actor,id:string,input:unknown){manage(actor);const data=templateDraftUpdateInput.parse(input),components=templateBodyComponents(data.body_text,data.example_values);return transaction(async db=>{const current=await scopedDraft(actor,id,db,true);if(Number(current.version)!==data.version)throw new AccessError(409,'O rascunho foi atualizado. Recarregue a página.');if(!['DRAFT','REJECTED'].includes(current.submission_status)||current.meta_template_id)throw new AccessError(409,'Somente rascunhos locais ou submissões recusadas sem identificador oficial podem ser editados.');await assertAvailableName(actor,data.name,data.language,id,db);const result=await db.query<DraftRow>(`UPDATE whatsapp_template_drafts SET name=$3,category=$4,language=$5,body_text=$6,example_values=$7,components=$8,submission_status='DRAFT',rejection_reason='',safe_error='',outcome_uncertain=false,updated_by=$9,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2 RETURNING *`,[actor.organizationId,id,data.name,data.category,data.language,data.body_text,JSON.stringify(data.example_values),JSON.stringify(components),actor.userId]);await db.query("INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.template_draft_updated',$3)",[actor.organizationId,actor.userId,`Modelo ${data.name}/${data.language}; rascunho revisado.`]);return result.rows[0];});}

async function persistOfficial(actor:Actor,id:string,meta:{id:string;status:string;category:string},components:unknown[],db:Db){const status=normalizeStatus(meta.status),support=templateSupport({components});const draft=await scopedDraft(actor,id,db,true);await db.query(`INSERT INTO whatsapp_templates(organization_id,meta_template_id,name,language,category,status,components,supported,unsupported_reason) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(organization_id,meta_template_id) DO UPDATE SET name=EXCLUDED.name,language=EXCLUDED.language,category=EXCLUDED.category,status=EXCLUDED.status,components=EXCLUDED.components,supported=EXCLUDED.supported,unsupported_reason=EXCLUDED.unsupported_reason,synced_at=now(),updated_at=now()`,[actor.organizationId,meta.id,draft.name,draft.language,meta.category,status,JSON.stringify(support.components),support.supported,support.reason]);const result=await db.query<DraftRow>(`UPDATE whatsapp_template_drafts SET meta_template_id=$3,category=$4,submission_status=$5,components=$6,rejection_reason='',safe_error='',outcome_uncertain=false,submitted_at=COALESCE(submitted_at,now()),synced_at=now(),updated_by=$7,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2 RETURNING *`,[actor.organizationId,id,meta.id,meta.category,status,JSON.stringify(support.components),actor.userId]);await db.query("INSERT INTO audit_logs(organization_id,actor_id,action,detail) VALUES ($1,$2,'whatsapp.template_submitted',$3)",[actor.organizationId,actor.userId,`Modelo ${draft.name}/${draft.language}; status ${status}; identificador oficial registrado.`]);return result.rows[0];}

export async function submitTemplateDraft(actor:Actor,id:string,input:unknown,fetcher?:MetaFetcher){manage(actor);const data=templateDraftSubmitInput.parse(input);const reserved=await transaction(async db=>{const current=await scopedDraft(actor,id,db,true);if(Number(current.version)!==data.version)throw new AccessError(409,'O rascunho foi atualizado. Recarregue a página.');if(!['DRAFT','REJECTED'].includes(current.submission_status)||current.meta_template_id||current.outcome_uncertain)throw new AccessError(409,'Este modelo não está disponível para uma nova submissão. Sincronize o catálogo.');await assertAvailableName(actor,current.name,current.language,current.id,db);await db.query(`UPDATE whatsapp_template_drafts SET submission_status='SUBMITTING',safe_error='',rejection_reason='',updated_by=$3,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,actor.userId]);return {...current,version:Number(current.version)+1};});const config=metaConfiguration(await integration(actor));
 try{const meta=await createMetaTemplate(config,{name:reserved.name,language:reserved.language,category:reserved.category,components:reserved.components},fetcher);return transaction(db=>persistOfficial(actor,id,meta,reserved.components,db));}
 catch(error){if(error instanceof MetaTemplateError&&error.kind==='uncertain'){try{const found=(await fetchMetaTemplates(config,fetcher)).find(item=>item.name===reserved.name&&item.language===reserved.language);if(found)return transaction(db=>persistOfficial(actor,id,{id:found.id,status:found.status,category:found.category},found.components,db));}catch{/* O estado permanece incerto e exige sincronização explícita. */}await database().query(`UPDATE whatsapp_template_drafts SET submission_status='UNCERTAIN',safe_error=$3,outcome_uncertain=true,updated_by=$4,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,error.safeDetail,actor.userId]);throw new AccessError(502,'O resultado da submissão não pôde ser confirmado. Sincronize os modelos antes de qualquer nova tentativa.');}
  if(error instanceof MetaTemplateError){await database().query(`UPDATE whatsapp_template_drafts SET submission_status='REJECTED',safe_error=$3,rejection_reason=$3,outcome_uncertain=false,updated_by=$4,version=version+1,updated_at=now() WHERE organization_id=$1 AND id=$2`,[actor.organizationId,id,error.safeDetail,actor.userId]);throw new AccessError(400,'A Meta recusou a submissão. Revise o motivo exibido no rascunho.');}throw error;}
}

export async function synchronizeTemplateManager(actor:Actor,fetcher?:MetaFetcher){manage(actor);await syncWhatsAppTemplates(actor,fetcher);return templateManagerOverview(actor);}
