'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Plus,Search,Download,SlidersHorizontal,Users } from 'lucide-react';
import { labels,paths,priorities,sources,stages,statuses,temperatures,type CommercialRecord,type Kind,type Tag } from '@/modules/crm/domain';
import { useRemote } from './use-remote';
import { errorMessage } from './api';
import { CommercialControls, type CommercialListOptions } from './commercial-controls';
const endpoints:Record<Kind,string>={lead:'leads',customer:'customers',company:'companies'};
export function RecordList({kind,options}:{kind:Kind;options:CommercialListOptions&{tags:Tag[]}}){
 const [filters,setFilters]=useState<Record<string,string>>({page:'1',sort:'newest',status:'active',view:options.scope});const [exportError,setExportError]=useState('');const [exporting,setExporting]=useState(false);const [revision,setRevision]=useState(0);const [selected,setSelected]=useState<Record<string,number>>({});
 const params=new URLSearchParams(Object.entries(filters).filter(([,v])=>!!v));
 const {data,error,loading}=useRemote<{records:CommercialRecord[];total:number;page:number;pageSize:number;unassigned:number}>(`/api/${endpoints[kind]}?${params}`,revision);
 const change=(key:string,value:string)=>{setSelected({});setFilters(old=>({...old,page:'1',[key]:value}));};
 const filter=(key:string,label:string,values:Record<string,string>)=><label className="crm-field" key={key}><span>{label}</span><select value={filters[key]??''} onChange={e=>change(key,e.target.value)}><option value="">Todos</option>{Object.entries(values).map(([v,name])=><option value={v} key={v}>{name}</option>)}</select></label>;
 async function exportCsv(){setExporting(true);setExportError('');try{const response=await fetch(`/api/${endpoints[kind]}/export?${params}`);if(!response.ok)throw new Error((await response.json()).error);const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`peclat-${endpoints[kind]}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setExportError(errorMessage(e));}finally{setExporting(false);}}
 return <><div className="page-heading"><div><span className="eyebrow blue">RELACIONAMENTO COMERCIAL</span><h1>{labels[kind]}</h1><p>{kind==='lead'?'Cada conexão pode se tornar um novo projeto solar.':kind==='customer'?'O relacionamento continua depois da primeira conquista.':'Organize as empresas e as pessoas com quem você se conecta.'}</p></div><Link className="button primary" href={`/${paths[kind]}/novo`}><Plus size={18}/> {kind==='lead'?'Novo lead':kind==='customer'?'Novo cliente':'Nova empresa'}</Link></div>
 <section className="card crm-list"><div className="crm-toolbar"><label className="crm-search"><Search size={18}/><input aria-label={`Pesquisar ${labels[kind].toLowerCase()}`} value={filters.q??''} onChange={e=>change('q',e.target.value)} placeholder="Nome, telefone, e-mail ou documento" maxLength={120}/></label><button className="button secondary" onClick={exportCsv} disabled={exporting}><Download size={17}/>{exporting?'Exportando…':'Exportar CSV'}</button></div>
 <CommercialControls kind={kind} options={options} filters={filters} change={change} records={data?.records??[]} selected={selected} setSelected={setSelected} onUpdated={()=>setRevision(value=>value+1)} unassigned={data?.unassigned??0}/>
 <details className="crm-filters"><summary><SlidersHorizontal size={16}/> Filtros e ordenação</summary><div className="crm-form-grid">{filter('owner','Vendedor',Object.fromEntries(options.owners.map(o=>[o.id,o.name])))}{filter('person_type','Tipo',{PF:'Pessoa física',PJ:'Pessoa jurídica'})}{kind==='lead'&&<>{filter('source','Origem',Object.fromEntries(sources.map(s=>[s,s])))}{filter('stage','Estágio',stages)}{filter('temperature','Temperatura',temperatures)}{filter('priority','Prioridade',priorities)}</>}{['city','state'].map(key=><label className="crm-field" key={key}><span>{key==='city'?'Cidade':'Estado (UF)'}</span><input value={filters[key]??''} maxLength={key==='state'?2:100} onChange={e=>change(key,e.target.value)}/></label>)}{filter('tag','Tag',Object.fromEntries(options.tags.map(t=>[t.id,t.name])))}{['from','to'].map(key=><label className="crm-field" key={key}><span>{key==='from'?'Criados a partir de':'Criados até'}</span><input type="date" value={filters[key]??''} onChange={e=>change(key,e.target.value)}/></label>)}<label className="crm-field"><span>Status</span><select value={filters.status} onChange={e=>change('status',e.target.value)}>{Object.entries({...statuses,all:'Todos os status'}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="crm-field"><span>Ordenação</span><select value={filters.sort} onChange={e=>change('sort',e.target.value)}><option value="newest">Mais recentes</option><option value="oldest">Mais antigos</option><option value="name">Nome A–Z</option><option value="value">Maior valor potencial</option></select></label></div><button className="button secondary" onClick={()=>{setSelected({});setFilters({page:'1',sort:'newest',status:'active',view:options.scope});}}>Limpar filtros</button></details>
 {(error||exportError)&&<div className="error-box" role="alert">{error||exportError}{error&&<button className="button secondary" onClick={()=>setRevision(r=>r+1)}>Tentar novamente</button>}</div>}
 {loading&&<div className="crm-loading" role="status"><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/>Carregando cadastros…</div>}
 {data&&(data.total===0?<div className="empty-state"><Users size={36}/><h2>Nenhum cadastro encontrado</h2><p>Cadastre um novo registro ou ajuste os filtros de pesquisa.</p><Link className="button primary" href={`/${paths[kind]}/novo`}>Criar primeiro cadastro</Link></div>:<><div className="table-scroll"><table><thead><tr>{kind==='lead'&&options.scope!=='mine'&&<th><input type="checkbox" aria-label="Selecionar leads da página" checked={data.records.length>0&&data.records.every(r=>selected[r.id]===r.version)} onChange={e=>setSelected(e.target.checked?Object.fromEntries(data.records.map(r=>[r.id,r.version])):{})}/></th>}<th>Cadastro</th><th>Contato</th><th>{kind==='lead'?'Estágio':'Localização'}</th><th>Responsável</th><th>Status</th><th>Valor potencial</th></tr></thead><tbody>{data.records.map(r=><tr key={r.id}>{kind==='lead'&&options.scope!=='mine'&&<td><input type="checkbox" aria-label={`Selecionar ${r.name}`} checked={selected[r.id]===r.version} onChange={e=>setSelected(current=>{const next={...current};if(e.target.checked)next[r.id]=r.version;else delete next[r.id];return next;})}/></td>}<td><Link className="record-name" href={`/${paths[kind]}/${r.id}`}>{r.name}</Link><div className="record-tags">{r.tags.map(t=><span key={t.id} className="crm-tag"><i style={{background:t.color}}/>{t.name}</span>)}</div></td><td><span>{r.whatsapp||r.phone||'Não informado'}</span><small className="table-secondary">{r.email}</small></td><td>{kind==='lead'?stages[r.stage]:[r.city,r.state].filter(Boolean).join(' / ')||'Não informada'}{kind==='lead'&&<small className="table-secondary">{temperatures[r.temperature]} · {priorities[r.priority]}</small>}</td><td>{r.owner_name??'Sem responsável'}</td><td><span className="badge">{statuses[r.status]}</span></td><td>{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(r.potential_value)}</td></tr>)}</tbody></table></div><div className="crm-pagination"><span>{data.total} cadastro(s) · Página {data.page} de {Math.max(1,Math.ceil(data.total/data.pageSize))}</span><div><button className="button secondary" disabled={data.page<=1} onClick={()=>setFilters({...filters,page:String(data.page-1)})}>Anterior</button><button className="button secondary" disabled={data.page*data.pageSize>=data.total} onClick={()=>setFilters({...filters,page:String(data.page+1)})}>Próxima</button></div></div></>)}
 </section></>;
}
