'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { api,ApiError,errorMessage } from './api';
import { Modal } from './modal';
import { paths,priorities,sources,stages,temperatures,type CommercialRecord,type Kind,type Tag } from '@/modules/crm/domain';
const endpoint:Record<Kind,string>={lead:'leads',customer:'customers',company:'companies'};
type Options={owners:{id:string;name:string}[];tags:Tag[]};
type Props={kind:Kind;record?:CommercialRecord;options:Options;userId:string;onSaved?:(record:CommercialRecord)=>void};
export function RecordForm({kind,record,options,userId,onSaved}:Props){
 const router=useRouter();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [duplicate,setDuplicate]=useState<{matches:{id:string;kind:Kind;name:string}[];canOverride:boolean;payload:Record<string,unknown>}|null>(null);
 const [personType,setPersonType]=useState(record?.person_type??(kind==='company'?'PJ':'PF'));
 async function save(payload:Record<string,unknown>){setBusy(true);setError('');try{const saved=await api<CommercialRecord>(`/api/${endpoint[kind]}${record?'/'+record.id:''}`,record?'PUT':'POST',payload);setDuplicate(null);if(onSaved)onSaved(saved);else{router.push(`/${paths[kind]}/${saved.id}`);router.refresh();}}catch(e){if(e instanceof ApiError&&Array.isArray(e.data.matches))setDuplicate({matches:e.data.matches as {id:string;kind:Kind;name:string}[],canOverride:!!e.data.canOverride,payload});else setError(errorMessage(e));}finally{setBusy(false);}}
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const data:Record<string,unknown>=Object.fromEntries(form);data.tag_ids=form.getAll('tag_ids');data.person_type=personType;for(const key of ['battery_interest','financing_interest'])data[key]=form.get(key)==='on';data.average_consumption=form.get('average_consumption')||null;data.consumer_units=form.get('consumer_units')||1;data.potential_value=form.get('potential_value')||0;if(record)data.version=record.version;void save(data);}
 const input=(name:string,label:string,type='text',max=180,required=false)=><label className="crm-field" key={name}><span>{label}{required?' *':''}</span><input name={name} type={type} required={required} maxLength={max} defaultValue={String((record as unknown as Record<string,unknown>)?.[name]??'')} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined}/></label>;
 const select=(name:string,label:string,values:Record<string,string>,fallback:string)=><label className="crm-field" key={name}><span>{label}</span><select name={name} defaultValue={String((record as unknown as Record<string,unknown>)?.[name]??fallback)}>{Object.entries(values).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;
 return <><form className="crm-form" onSubmit={submit} aria-busy={busy}><p className="muted">Preencha o nome para começar. Os demais dados podem ser completados durante o atendimento.</p><fieldset disabled={busy}><legend>Identificação</legend><div className="crm-form-grid">{input('name',kind==='company'?'Razão social':'Nome','text',180,true)}<label className="crm-field"><span>Tipo de pessoa</span><select value={personType} disabled={kind==='company'} onChange={e=>setPersonType(e.target.value as 'PF'|'PJ')}><option value="PF">Pessoa física</option><option value="PJ">Pessoa jurídica</option></select></label>{input('document',personType==='PJ'?'CNPJ':'CPF','text',24)}{kind==='company'&&<>{input('trade_name','Nome fantasia')}{input('state_registration','Inscrição estadual','text',30)}{input('website','Site','url',300)}</>}{input('phone','Telefone','tel',30)}{input('whatsapp','WhatsApp','tel',30)}{input('email','E-mail','email',254)}</div></fieldset>
 <fieldset disabled={busy}><legend>Endereço</legend><div className="crm-form-grid">{input('postal_code','CEP','text',10)}{input('address','Endereço')}{input('number','Número','text',20)}{input('complement','Complemento','text',120)}{input('neighborhood','Bairro','text',100)}{input('city','Cidade','text',100)}{input('state','Estado (UF)','text',2)}</div></fieldset>
 <fieldset disabled={busy}><legend>Relacionamento comercial</legend><div className="crm-form-grid"><label className="crm-field"><span>Vendedor responsável</span><select name="owner_id" defaultValue={record?.owner_id??userId}>{options.owners.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label>{kind!=='company'&&<>{select('source','Origem',Object.fromEntries([...new Set([...sources,record?.source??'Manual'])].map(s=>[s,s])),'Manual')}{input('campaign','Campanha','text',120)}{select('priority','Prioridade',priorities,'normal')}{select('temperature','Temperatura',temperatures,'warm')}{select('stage','Estágio',stages,'new')}{input('potential_value','Valor potencial (R$)','number')}{input('expected_close','Previsão de fechamento','date')}</>}</div><div className="tag-selector"><span>Tags</span>{options.tags.length?options.tags.map(tag=><label key={tag.id}><input type="checkbox" name="tag_ids" value={tag.id} defaultChecked={record?.tags.some(t=>t.id===tag.id)}/>{tag.name}</label>):<p className="muted">O administrador pode configurar tags na área Tags.</p>}</div></fieldset>
 {kind!=='company'&&<fieldset disabled={busy}><legend>Perfil de energia solar</legend><div className="crm-form-grid">{input('average_consumption','Consumo médio mensal (kWh)','number')}{input('utility','Distribuidora','text',100)}{input('property_type','Tipo de imóvel','text',80)}{input('roof_type','Tipo de telhado','text',80)}<label className="crm-field"><span>Unidades consumidoras</span><input name="consumer_units" type="number" min="1" max="10000" step="1" defaultValue={record?.consumer_units??1}/></label></div><div className="crm-checks"><label><input type="checkbox" name="battery_interest" defaultChecked={record?.battery_interest}/> Interesse em bateria</label><label><input type="checkbox" name="financing_interest" defaultChecked={record?.financing_interest}/> Interesse em financiamento</label></div></fieldset>}
 <label className="crm-field"><span>Observações internas</span><textarea name="observations" rows={4} maxLength={4000} defaultValue={record?.observations}/></label>{error&&<p className="error-box" role="alert">{error}</p>}<div className="crm-form-actions"><Link className="button secondary" href={record?`/${paths[kind]}/${record.id}`:`/${paths[kind]}`}>Cancelar</Link><button className="button primary" disabled={busy}>{busy?'Salvando…':record?'Salvar alterações':'Criar cadastro'}</button></div></form>
 {duplicate&&<Modal title="Encontramos um cadastro semelhante" onClose={()=>setDuplicate(null)}><p>Confira os registros antes de continuar. Nenhum dado foi salvo.</p>{duplicate.matches.length?<ul className="duplicate-list">{duplicate.matches.map(match=><li key={match.id}><Link href={`/${paths[match.kind]}/${match.id}`}>{match.name} · Abrir cadastro</Link></li>)}</ul>:<p className="muted">O cadastro semelhante está fora do seu acesso. Consulte o gerente.</p>}{error&&<p role="alert" className="error-box">{error}</p>}<div className="crm-form-actions"><button className="button secondary" disabled={busy} onClick={()=>setDuplicate(null)}>Cancelar</button>{duplicate.canOverride&&<button className="button primary" disabled={busy} onClick={()=>save({...duplicate.payload,allow_duplicate:true})}>Continuar mesmo assim</button>}</div></Modal>}</>;
}
